import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "09_Dili_Gecmis_Zaman",
    title: "Dİ'Lİ GEÇMİŞ ZAMAN (PAST SIMPLE)",
    blocks: [
      { type: "rule", text: "Di'li geçmiş zaman; geçmişte başlayıp bitmiş, tamamlanmış eylemleri anlatmak için kullanılır." },
      { type: "rule", text: "Yapı: Özne + Fiil (2. hal / V2). Düzenli fiillerde bu -ED eki eklenerek yapılır." },
      { type: "pattern", text: "ÖZNE + V2 (bütün öznelerde aynı fiil hâli kullanılır)" },
      { type: "example", en: "I worked yesterday.", tr: "Dün çalıştım." },
      { type: "example", en: "She visited her family last week.", tr: "O geçen hafta ailesini ziyaret etti." },
      { type: "example", en: "We watched a movie last night.", tr: "Dün gece bir film izledik." },
      { type: "rule", text: "-ED eki kuralları: Fiil sessiz \"E\" ile bitiyorsa sadece -D eklenir (like-liked). Sessiz harf+Y ile bitiyorsa Y, I'ya dönüşür (study-studied). Tek heceli ve tek ünlüden sonra tek sessizle biten fiillerde son harf ikizlenir (stop-stopped, plan-planned)." },
      { type: "example", en: "He studied hard for the exam.", tr: "O sınav için sıkı çalıştı." },
      { type: "example", en: "The car stopped suddenly.", tr: "Araba aniden durdu." },
      { type: "rule", text: "Birçok fiil düzensizdir ve -ED almaz, kendine özgü bir 2. hali vardır: GO-WENT, SEE-SAW, BUY-BOUGHT, WRITE-WROTE, COME-CAME, TAKE-TOOK, KNOW-KNEW, GIVE-GAVE, MAKE-MADE, GET-GOT." },
      { type: "example", en: "I saw him at the station yesterday.", tr: "Onu dün istasyonda gördüm." },
      { type: "example", en: "We bought a new car last month.", tr: "Geçen ay yeni bir araba satın aldık." },
      { type: "example", en: "She gave me a nice gift.", tr: "O bana güzel bir hediye verdi." },
      { type: "rule", text: "Olumsuz yapı: Özne + DIDN'T + Fiil (yalın hal). DIDN'T kullanıldığında fiil asla 2. halde kullanılmaz, düzensiz fiiller bile yalın hâle döner." },
      { type: "pattern", text: "ÖZNE + DIDN'T + V1" },
      { type: "example", en: "I didn't go there yesterday.", tr: "Dün oraya gitmedim." },
      { type: "example", en: "She didn't call me last night.", tr: "O dün gece beni aramadı." },
      { type: "rule", text: "Soru yapısı: DID + Özne + Fiil (yalın hal)?" },
      { type: "pattern", text: "DID + ÖZNE + V1 ?" },
      { type: "example", en: "Did you go to Germany for the first time?", tr: "Almanya'ya ilk defa mı gittin?" },
      { type: "example", en: "Did he come here yesterday?", tr: "O dün buraya geldi mi?" },
      { type: "example", en: "Did they finish the project?", tr: "Onlar projeyi bitirdi mi?" },
      { type: "rule", text: "Di'li geçmiş zamanla sıkça kullanılan zaman zarfları: YESTERDAY (dün), LAST WEEK/MONTH/YEAR (geçen hafta/ay/yıl), ... AGO (önce), IN 2020 (2020'de)." },
      { type: "example", en: "They finished the project two days ago.", tr: "Projeyi iki gün önce bitirdiler." },
      { type: "example", en: "We moved to this city three years ago.", tr: "Bu şehre üç yıl önce taşındık." },
      { type: "rule", text: "\"VISIT\" fiili üzerinden tam çekim tablosunu inceleyelim." },
      { type: "pattern", text: "VISIT (OLUMLU / OLUMSUZ / SORU)" },
      { type: "example", en: "I visited my grandmother last Sunday.", tr: "Geçen pazar büyükannemi ziyaret ettim." },
      { type: "example", en: "You visited the museum yesterday.", tr: "Dün müzeyi ziyaret ettin." },
      { type: "example", en: "He visited us last week.", tr: "O geçen hafta bizi ziyaret etti." },
      { type: "example", en: "She didn't visit her friends last month.", tr: "O geçen ay arkadaşlarını ziyaret etmedi." },
      { type: "example", en: "We didn't visit that city.", tr: "O şehri ziyaret etmedik." },
      { type: "example", en: "Did they visit their parents?", tr: "Onlar ailelerini ziyaret etti mi?" },
      { type: "example", en: "Did you visit the exhibition?", tr: "Sergiyi ziyaret ettin mi?" },
      { type: "rule", text: "Düzensiz fiillerle daha fazla örnek cümle görelim." },
      { type: "example", en: "She wrote a long letter to her sister.", tr: "O kız kardeşine uzun bir mektup yazdı." },
      { type: "example", en: "We ate dinner at a nice restaurant.", tr: "Güzel bir restoranda akşam yemeği yedik." },
      { type: "example", en: "He took a lot of photos on his trip.", tr: "O gezisinde çok fotoğraf çekti." },
      { type: "example", en: "I forgot my umbrella at home.", tr: "Şemsiyemi evde unuttum." },
      { type: "example", en: "They left the office at six.", tr: "Onlar ofisten saat altıda ayrıldılar." },
      { type: "example", en: "She found her keys under the sofa.", tr: "O anahtarlarını kanepenin altında buldu." },
      { type: "rule", text: "Karışık soru-cevap alıştırmasıyla bu dersi pekiştirelim." },
      { type: "example", en: "What did you do last weekend? I stayed home.", tr: "Geçen hafta sonu ne yaptın? Evde kaldım." },
      { type: "example", en: "Where did they go on vacation? They went to Spain.", tr: "Onlar tatilde nereye gittiler? İspanya'ya gittiler." },
      { type: "example", en: "When did the movie start? It started at 8.", tr: "Film ne zaman başladı? Saat 8'de başladı." },
      { type: "example", en: "Why didn't you call me? I lost my phone.", tr: "Beni neden aramadın? Telefonumu kaybettim." },
      { type: "example", en: "How did you learn English? I learned it at school.", tr: "İngilizceyi nasıl öğrendin? Okulda öğrendim." },
      { type: "rule", text: "Daha fazla düzenli ve düzensiz fiil örneğiyle bu dersi genişletelim." },
      { type: "example", en: "We played chess all afternoon.", tr: "Bütün öğleden sonra satranç oynadık." },
      { type: "example", en: "She cleaned the whole house yesterday.", tr: "O dün bütün evi temizledi." },
      { type: "example", en: "He fixed the car by himself.", tr: "O arabayı kendi başına tamir etti." },
      { type: "example", en: "I read that book last summer.", tr: "O kitabı geçen yaz okudum." },
      { type: "example", en: "They built this house in 2010.", tr: "Onlar bu evi 2010'da inşa ettiler." },
      { type: "example", en: "We spent a lot of money on the trip.", tr: "Gezide çok para harcadık." },
      { type: "example", en: "She sold her old car last week.", tr: "O geçen hafta eski arabasını sattı." },
      { type: "example", en: "He broke his leg while skiing.", tr: "Kayak yaparken bacağını kırdı." },
      { type: "rule", text: "Zaman zarflarıyla daha fazla örnek cümle görelim." },
      { type: "example", en: "I met her three years ago.", tr: "Onunla üç yıl önce tanıştım." },
      { type: "example", en: "We graduated in 2018.", tr: "2018'de mezun olduk." },
      { type: "example", en: "He called me an hour ago.", tr: "Bir saat önce beni aradı." },
      { type: "example", en: "They arrived last night.", tr: "Dün gece vardılar." },
      { type: "example", en: "Did she pass the exam last month?", tr: "O geçen ay sınavı geçti mi?" },
      { type: "rule", text: "Son bir tekrar bölümüyle bu dersi tamamlayalım." },
      { type: "example", en: "We didn't expect such a big surprise.", tr: "Böyle büyük bir sürpriz beklemiyorduk." },
      { type: "example", en: "He apologized for being late.", tr: "Geç kaldığı için özür diledi." },
      { type: "example", en: "I checked my email before I left.", tr: "Ayrılmadan önce e-postamı kontrol ettim." },
      { type: "example", en: "She didn't recognize me at first.", tr: "O beni önce tanımadı." },
      { type: "example", en: "Did you enjoy the concert?", tr: "Konserden keyif aldın mı?" },
      { type: "rule", text: "Daha fazla düzenli fiil örneğiyle -ED ekini pekiştirelim." },
      { type: "example", en: "We waited for an hour at the station.", tr: "İstasyonda bir saat bekledik." },
      { type: "example", en: "She helped me with my homework.", tr: "O ödevimde bana yardım etti." },
      { type: "example", en: "They walked to school every day last year.", tr: "Geçen yıl her gün okula yürüdüler." },
      { type: "example", en: "He explained the rules clearly.", tr: "O kuralları açıkça anlattı." },
      { type: "example", en: "I decided to change my career.", tr: "Kariyerimi değiştirmeye karar verdim." },
      { type: "example", en: "We watched the sunset from the hill.", tr: "Gün batımını tepeden izledik." },
      { type: "example", en: "She answered all the questions correctly.", tr: "O bütün soruları doğru cevapladı." },
      { type: "example", en: "Did the price include breakfast?", tr: "Fiyata kahvaltı dahil miydi?" },
      { type: "example", en: "We didn't plan this trip carefully.", tr: "Bu geziyi dikkatli planlamadık." },
      { type: "example", en: "He returned the book to the library.", tr: "O kitabı kütüphaneye iade etti." },
      { type: "example", en: "We celebrated her birthday last Friday.", tr: "Geçen cuma onun doğum gününü kutladık." },
      { type: "example", en: "I missed the bus this morning.", tr: "Bu sabah otobüsü kaçırdım." },
      { type: "example", en: "She invited all her colleagues.", tr: "O bütün meslektaşlarını davet etti." },
      { type: "example", en: "We discussed the issue for hours.", tr: "Konuyu saatlerce tartıştık." },
      { type: "example", en: "He promised to fix it by Monday.", tr: "Pazartesiye kadar düzeltmeye söz verdi." },
      { type: "example", en: "I turned off all the lights before leaving.", tr: "Ayrılmadan önce bütün ışıkları kapattım." },
      { type: "example", en: "She practiced the piano every day last month.", tr: "Geçen ay her gün piyano çalıştı." },
      { type: "example", en: "We didn't recognize the address at first.", tr: "Adresi ilk başta tanımadık." },
    ],
  },
  {
    fileBase: "10_Was_Were",
    title: "WAS - WERE VE FARKLI SIFATLAR",
    blocks: [
      { type: "rule", text: "WAS/WERE, AM/IS/ARE fiilinin geçmiş zaman hâlidir." },
      { type: "pattern", text: "I / HE / SHE / IT + WAS        YOU / WE / THEY + WERE" },
      { type: "example", en: "I was tired.", tr: "Yorgundum." },
      { type: "example", en: "Where were you?", tr: "Neredeydin?" },
      { type: "example", en: "We were happy about the news.", tr: "Haber için mutluyduk." },
      { type: "rule", text: "AM/IS/ARE'ın yanında kullandığımız her kalıp (sıfatlar, yer bildiren ifadeler vb.) WAS/WERE ile de aynı şekilde kullanılabilir." },
      { type: "example", en: "Were they at home?", tr: "Onlar evde miydi?" },
      { type: "example", en: "She wasn't ready on time.", tr: "O zamanında hazır değildi." },
      { type: "pattern", text: "OUT OF THE OFFICE = ofis dışında / OUT OF THE CITY = şehir dışında / ABROAD = yurt dışında" },
      { type: "example", en: "He was abroad last month.", tr: "O geçen ay yurt dışındaydı." },
      { type: "example", en: "Were you out of the city last weekend?", tr: "Geçen hafta sonu şehir dışında mıydın?" },
      { type: "pattern", text: "CAREFUL = dikkatli / PATIENT = sabırlı" },
      { type: "example", en: "She was very patient with the children.", tr: "O çocuklara karşı çok sabırlıydı." },
      { type: "example", en: "Was he careful with the documents?", tr: "O belgelerle dikkatli miydi?" },
      { type: "rule", text: "BE BORN = doğmak. Bu kalıp genellikle sadece \"BORN\" kelimesiyle hatırlanır ama WAS/WERE BORN şeklinde kullanılmalıdır." },
      { type: "example", en: "Where were you born?", tr: "Nerede doğdun?" },
      { type: "example", en: "When was he born?", tr: "O ne zaman doğdu?" },
      { type: "example", en: "I was born in Istanbul.", tr: "Ben İstanbul'da doğdum." },
      { type: "pattern", text: "DEFEND = savunmak" },
      { type: "example", en: "He was right, but we didn't defend them.", tr: "O haklıydı, ama onları savunmadık." },
      { type: "rule", text: "MISS = kaçırmak. Bu fiil \"özlemek\" olarak da bilinir, ama günlük kullanımda çoğunlukla \"kaçırmak\" anlamındadır." },
      { type: "example", en: "We missed the last train.", tr: "Son treni kaçırdık." },
      { type: "example", en: "I mustn't miss the flight.", tr: "Uçağı kaçırmamalıyım." },
      { type: "example", en: "I miss my hometown.", tr: "Memleketimi özlüyorum." },
      { type: "pattern", text: "OPPORTUNITY = fırsat" },
      { type: "example", en: "You shouldn't miss that opportunity.", tr: "O fırsatı kaçırmamalısın." },
      { type: "pattern", text: "IGNORE = görmezden gelmek / EFFORT = çaba / CONTRIBUTION = katkı / COOPERATION = işbirliği" },
      { type: "example", en: "We cannot ignore their cooperation.", tr: "Onların işbirliğini görmezden gelemeyiz." },
      { type: "example", en: "I cannot ignore his effort.", tr: "Onun çabasını görmezden gelemem." },
      { type: "rule", text: "WAS/WERE'in tam çekim tablosunu görelim." },
      { type: "pattern", text: "BE (WAS/WERE) TAM ÇEKİM" },
      { type: "example", en: "I was at home yesterday.", tr: "Dün evdeydim." },
      { type: "example", en: "You were at home yesterday.", tr: "Dün evdeydin." },
      { type: "example", en: "He was at home yesterday.", tr: "O dün evdeydi." },
      { type: "example", en: "She was at home yesterday.", tr: "O (kadın) dün evdeydi." },
      { type: "example", en: "It was cold yesterday.", tr: "Dün hava soğuktu." },
      { type: "example", en: "We were at home yesterday.", tr: "Dün evdeydik." },
      { type: "example", en: "They were at home yesterday.", tr: "Dün evdeydiler." },
      { type: "rule", text: "Olumsuz ve soru hâlleriyle daha fazla örnek görelim." },
      { type: "example", en: "I wasn't at the party.", tr: "Partide değildim." },
      { type: "example", en: "She wasn't happy with the result.", tr: "O sonuçtan mutlu değildi." },
      { type: "example", en: "We weren't aware of the problem.", tr: "Problemin farkında değildik." },
      { type: "example", en: "Were you satisfied with the service?", tr: "Hizmetten memnun muydun?" },
      { type: "example", en: "Was the exam difficult?", tr: "Sınav zor muydu?" },
      { type: "rule", text: "Daha fazla günlük hayat cümlesiyle bu dersi pekiştirelim." },
      { type: "example", en: "The streets were empty at midnight.", tr: "Gece yarısı sokaklar boştu." },
      { type: "example", en: "He was so nervous before the interview.", tr: "Mülakattan önce çok gerginmişti." },
      { type: "example", en: "Was she surprised by the news?", tr: "O haberden şaşırdı mı?" },
      { type: "example", en: "We were exhausted after the trip.", tr: "Geziden sonra bitkinmiştik." },
      { type: "example", en: "I was proud of my students.", tr: "Öğrencilerimle gurur duydum." },
      { type: "rule", text: "WAS/WERE ile daha fazla günlük hayat cümlesi kuralım." },
      { type: "example", en: "It was a beautiful day.", tr: "Güzel bir gündü." },
      { type: "example", en: "The food was delicious.", tr: "Yemek lezzetliydi." },
      { type: "example", en: "The movie wasn't as good as I expected.", tr: "Film beklediğim kadar iyi değildi." },
      { type: "example", en: "Were the tickets expensive?", tr: "Biletler pahalı mıydı?" },
      { type: "example", en: "My grandparents were very kind people.", tr: "Büyükanne ve büyükbabam çok kibar insanlardı." },
      { type: "example", en: "The concert was amazing last night.", tr: "Konser dün gece harikaydı." },
      { type: "example", en: "Was it your first time here?", tr: "Burada ilk seferin miydi?" },
      { type: "example", en: "We were neighbors for ten years.", tr: "On yıl komşuyduk." },
      { type: "example", en: "She was late because of the traffic.", tr: "O trafik yüzünden geç kaldı." },
      { type: "example", en: "I was worried about the results.", tr: "Sonuçlar için endişeliydim." },
      { type: "rule", text: "Son bir tekrar bölümüyle bu dersi tamamlayalım." },
      { type: "example", en: "The hotel room was clean and comfortable.", tr: "Otel odası temiz ve rahattı." },
      { type: "example", en: "Were you nervous before the presentation?", tr: "Sunumdan önce gergin miydin?" },
      { type: "example", en: "The lecture was too long.", tr: "Ders çok uzundu." },
      { type: "example", en: "We weren't sure about the address.", tr: "Adresten emin değildik." },
      { type: "example", en: "Was the flight comfortable?", tr: "Uçuş rahat mıydı?" },
      { type: "rule", text: "Daha fazla örnekle WAS/WERE'i pekiştirelim." },
      { type: "example", en: "My childhood was very happy.", tr: "Çocukluğum çok mutluydu." },
      { type: "example", en: "The lesson wasn't interesting at all.", tr: "Ders hiç ilginç değildi." },
      { type: "example", en: "Where was he when the accident happened?", tr: "Kaza olduğunda o neredeydi?" },
      { type: "example", en: "We were shocked by the announcement.", tr: "Duyuru bizi şok etti." },
      { type: "example", en: "The instructions were confusing.", tr: "Talimatlar kafa karıştırıcıydı." },
      { type: "example", en: "Was your grandfather a doctor?", tr: "Büyükbaban bir doktor muydu?" },
      { type: "example", en: "They were very generous with their time.", tr: "Zamanları konusunda çok cömerttiler." },
      { type: "example", en: "I wasn't hungry after the big lunch.", tr: "Büyük öğle yemeğinden sonra aç değildim." },
      { type: "example", en: "The staff were friendly and helpful.", tr: "Personel arkadaş canlısı ve yardımseverdi." },
      { type: "example", en: "It wasn't my fault.", tr: "Bu benim hatam değildi." },
      { type: "example", en: "Were you born in this country?", tr: "Bu ülkede mi doğdun?" },
      { type: "example", en: "The weather was terrible during our vacation.", tr: "Tatilimiz boyunca hava berbattı." },
      { type: "example", en: "He wasn't very talkative that day.", tr: "O gün pek konuşkan değildi." },
      { type: "example", en: "We were the only ones there.", tr: "Orada sadece biz vardık." },
      { type: "example", en: "Was the customer satisfied?", tr: "Müşteri memnun kaldı mı?" },
      { type: "example", en: "I was speechless when I heard the news.", tr: "Haberi duyduğumda dilim tutuldu." },
    ],
  },
  {
    fileBase: "11_Emir_Kipi_ve_Renkler",
    title: "EMİR KİPİ, RENKLER VE AİLE ÜYELERİ",
    blocks: [
      { type: "rule", text: "İngilizcede emir kipi kurmak için fiil doğrudan yalın hâlde, özne kullanılmadan cümlenin başına getirilir." },
      { type: "pattern", text: "V1 !        DON'T + V1 !" },
      { type: "example", en: "Come here! / Don't come!", tr: "Buraya gel! / Gelme!" },
      { type: "example", en: "Believe me! Don't spend a lot of money!", tr: "Bana inan! Çok para harcama!" },
      { type: "example", en: "Visit us! Don't use this medicine!", tr: "Bizi ziyaret et! Bu ilacı kullanma!" },
      { type: "example", en: "Start today! Don't speak loudly!", tr: "Bugün başla! Yüksek sesle konuşma!" },
      { type: "pattern", text: "WASTE = boşa harcamak / RENT = kiralamak" },
      { type: "example", en: "I can't waste my money.", tr: "Param boşa harcayamam." },
      { type: "example", en: "He shouldn't waste his time.", tr: "O zamanını boşa harcamamalı." },
      { type: "pattern", text: "REGRET = pişman olmak" },
      { type: "example", en: "If you don't want to regret, don't waste your time.", tr: "Pişman olmak istemiyorsan zamanını boşa harcama." },
      { type: "pattern", text: "IN CASE OF = ... durumunda (fire-yangın, emergency-acil durum, danger-tehlike, earthquake-deprem)" },
      { type: "example", en: "In case of fire, don't use the elevator!", tr: "Yangın durumunda asansörü kullanma!" },
      { type: "pattern", text: "ELEVATOR = LIFT = asansör / STAIRS = merdiven" },
      { type: "example", en: "In case of fire, use the stairs!", tr: "Yangın durumunda merdivenleri kullanın!" },
      { type: "pattern", text: "CONVINCE = ikna etmek / DETERMINED = kararlı" },
      { type: "example", en: "Anybody cannot convince him, because he is so determined.", tr: "Kimse onu ikna edemez, çünkü o çok kararlı." },
      { type: "example", en: "I'll try everything to convince them.", tr: "Onları ikna etmek için her şeyi deneyeceğim." },
      { type: "pattern", text: "ATTEND = katılmak / MEETING, CLASS, ORGANIZATION = toplantı, ders, organizasyon" },
      { type: "example", en: "Attend the meeting on time!", tr: "Toplantıya vaktinde katıl!" },
      { type: "rule", text: "Renkler: YELLOW (sarı), RED (kırmızı), BLUE (mavi), GREEN (yeşil), WHITE (beyaz), BLACK (siyah), GREY (gri), ORANGE (turuncu), PINK (pembe), PURPLE (mor), BROWN (kahverengi)." },
      { type: "example", en: "I like the blue one, not the red one.", tr: "Maviyi severim, kırmızıyı değil." },
      { type: "rule", text: "Aile üyeleri: SON (oğul), DAUGHTER (kız evlat), MOTHER (anne), FATHER (baba), BROTHER (erkek kardeş), SISTER (kız kardeş), FAMILY (aile), PARENTS (ebeveynler), SIBLING (kardeş). Diğer aile üyeleri: GRANDMOTHER, GRANDFATHER, UNCLE, AUNT, COUSIN, NEPHEW, NIECE." },
      { type: "example", en: "My sister lives with our parents.", tr: "Kız kardeşim ebeveynlerimizle yaşıyor." },
      { type: "pattern", text: "CARE ABOUT = önemsemek, değer vermek / EDUCATION = eğitim" },
      { type: "example", en: "She always cares about her daughter's health.", tr: "O her zaman kızının sağlığını önemser." },
      { type: "example", en: "I always care about her education.", tr: "Onun eğitimini her zaman önemserim." },
      { type: "pattern", text: "WET = ıslak / DRY = kuru / FLOOR = zemin" },
      { type: "example", en: "The floor was wet, so I want a dry towel.", tr: "Zemin ıslaktı, bu yüzden kuru bir havlu istiyorum." },
      { type: "rule", text: "Bazı sıfatların GET ile fiil hâli: GET TIRED (yorulmak), GET ANGRY (kızmak), GET SAD (üzülmek), GET ILL (hastalanmak), GET EXCITED (heyecanlanmak), GET BORED (sıkılmak), GET OLD (yaşlanmak)." },
      { type: "example", en: "I don't want to get tired.", tr: "Yorulmak istemiyorum." },
      { type: "example", en: "He got so angry.", tr: "O çok kızdı." },
      { type: "example", en: "We will not get ill.", tr: "Hastalanmayacağız." },
      { type: "rule", text: "GET WELL / RECOVER = iyileşmek. SEE YOU SOON! / GET WELL SOON! gibi kalıplar günlük hayatta sık kullanılır." },
      { type: "pattern", text: "AWARE = farkında / ATTENTION = dikkat / PRECAUTION = tedbir / OBEY = uymak" },
      { type: "example", en: "We should be aware of everything and obey the safety instructions.", tr: "Her şeyin farkında olmalı ve güvenlik talimatlarına uymalıyız." },
      { type: "example", en: "You must pay attention to your budget.", tr: "Bütçene dikkat etmelisin." },
      { type: "rule", text: "Emir kipiyle daha fazla günlük hayat örneği görelim." },
      { type: "example", en: "Sit down and relax!", tr: "Otur ve rahatla!" },
      { type: "example", en: "Please close the door!", tr: "Lütfen kapıyı kapat!" },
      { type: "example", en: "Don't touch that, it's hot!", tr: "Ona dokunma, sıcak!" },
      { type: "example", en: "Turn left at the corner!", tr: "Köşede sola dön!" },
      { type: "example", en: "Be careful on the stairs!", tr: "Merdivenlerde dikkatli ol!" },
      { type: "example", en: "Don't forget your keys!", tr: "Anahtarlarını unutma!" },
      { type: "rule", text: "Renklerle daha fazla örnek cümle kuralım." },
      { type: "example", en: "She always wears black.", tr: "O her zaman siyah giyer." },
      { type: "example", en: "The sky is orange at sunset.", tr: "Gün batımında gökyüzü turuncu olur." },
      { type: "example", en: "Which color do you prefer, green or purple?", tr: "Hangi rengi tercih edersin, yeşil mi mor mu?" },
      { type: "rule", text: "Aile üyeleriyle daha fazla örnek cümle kuralım." },
      { type: "example", en: "My cousin lives in another city.", tr: "Kuzenim başka bir şehirde yaşıyor." },
      { type: "example", en: "Her grandmother is ninety years old.", tr: "Onun büyükannesi doksan yaşında." },
      { type: "example", en: "His uncle owns a small shop.", tr: "Onun amcasının küçük bir dükkanı var." },
      { type: "rule", text: "GET ile fiil hâline gelen sıfatlarla daha fazla örnek görelim." },
      { type: "example", en: "Don't get bored, we will finish soon.", tr: "Sıkılma, yakında bitireceğiz." },
      { type: "example", en: "She got excited about the news.", tr: "O haber için heyecanlandı." },
      { type: "example", en: "Did he get sad when you left?", tr: "Sen ayrıldığında o üzüldü mü?" },
      { type: "rule", text: "Bu dersteki bütün kalıplarla karışık bir alıştırma bölümü ekleyelim." },
      { type: "example", en: "Never give up on your dreams!", tr: "Hayallerinden asla vazgeçme!" },
      { type: "example", en: "Always tell the truth!", tr: "Her zaman gerçeği söyle!" },
      { type: "example", en: "Don't be afraid to ask questions!", tr: "Soru sormaktan korkma!" },
      { type: "example", en: "My niece has blue eyes.", tr: "Yeğenimin gözleri mavi." },
      { type: "example", en: "We should attend the ceremony together.", tr: "Törene birlikte katılmalıyız." },
      { type: "example", en: "He is aware of the risks.", tr: "O risklerin farkında." },
      { type: "example", en: "Take care of your family!", tr: "Ailenle ilgilen!" },
      { type: "example", en: "Don't waste this opportunity!", tr: "Bu fırsatı boşa harcama!" },
      { type: "rule", text: "Daha fazla emir kipi ve aile örneğiyle konuyu tamamlayalım." },
      { type: "example", en: "Wash your hands before dinner!", tr: "Akşam yemeğinden önce ellerini yıka!" },
      { type: "example", en: "Don't shout, I can hear you!", tr: "Bağırma, seni duyabiliyorum!" },
      { type: "example", en: "Finish your plate!", tr: "Tabağını bitir!" },
      { type: "example", en: "My father-in-law is very generous.", tr: "Kayınpederim çok cömert." },
      { type: "example", en: "Her nephew is studying medicine.", tr: "Onun yeğeni tıp okuyor." },
      { type: "example", en: "The leaves turn brown and orange in autumn.", tr: "Sonbaharda yapraklar kahverengi ve turuncuya döner." },
      { type: "example", en: "He got tired after the long meeting.", tr: "O uzun toplantıdan sonra yoruldu." },
      { type: "example", en: "Respect your elders!", tr: "Büyüklerine saygı göster!" },
      { type: "example", en: "My sister-in-law is a lawyer.", tr: "Görümcem/yengem bir avukat." },
      { type: "example", en: "Don't be rude to the staff!", tr: "Personele karşı kaba olma!" },
      { type: "example", en: "Believe in yourself!", tr: "Kendine inan!" },
      { type: "example", en: "My favorite color combination is black and gold.", tr: "En sevdiğim renk kombinasyonu siyah ve altın." },
      { type: "example", en: "Her son-in-law works abroad.", tr: "Onun damadı yurt dışında çalışıyor." },
      { type: "example", en: "Don't be jealous of others!", tr: "Başkalarını kıskanma!" },
      { type: "example", en: "He got angry when he heard the news.", tr: "Haberi duyduğunda sinirlendi." },
      { type: "example", en: "Speak clearly and slowly!", tr: "Açık ve yavaş konuş!" },
      { type: "example", en: "My relatives live all over the country.", tr: "Akrabalarım ülkenin her yerinde yaşıyor." },
      { type: "example", en: "Don't get excited too early!", tr: "Çok erken heyecanlanma!" },
    ],
  },
  {
    fileBase: "12_Gecmis_Zamanin_Simdiki_Hali",
    title: "GEÇMİŞ ZAMANIN ŞİMDİKİ HALİ (PAST CONTINUOUS)",
    blocks: [
      { type: "rule", text: "Bu tense, geçmişte belirli bir anda devam etmekte olan eylemleri anlatmak için kullanılır. \"Şu anda yapıyorum\" yapısının geçmişe taşınmış hâlidir." },
      { type: "rule", text: "Yapı: Özne + WAS/WERE + Fiil-ING." },
      { type: "pattern", text: "I / HE / SHE / IT + WAS + V-ing        YOU / WE / THEY + WERE + V-ing" },
      { type: "example", en: "I was working at 9 o'clock yesterday.", tr: "Dün saat 9'da çalışıyordum." },
      { type: "example", en: "They were sleeping when I called.", tr: "Ben aradığımda onlar uyuyordu." },
      { type: "example", en: "We were having dinner at 8 pm.", tr: "Akşam saat 8'de yemek yiyorduk." },
      { type: "rule", text: "Olumsuz yapı: Özne + WASN'T/WEREN'T + Fiil-ING." },
      { type: "example", en: "She wasn't listening to me.", tr: "O beni dinlemiyordu." },
      { type: "example", en: "We weren't waiting for you.", tr: "Seni beklemiyorduk." },
      { type: "rule", text: "Soru yapısı: WAS/WERE + Özne + Fiil-ING?" },
      { type: "example", en: "What were you doing at that time?", tr: "O saatte ne yapıyordun?" },
      { type: "example", en: "Was he working when you arrived?", tr: "Sen vardığında o çalışıyor muydu?" },
      { type: "rule", text: "Bu tense çoğu zaman WHILE (-iken, -ken) bağlacıyla birlikte, iki eylemin aynı anda geçmişte devam ettiğini anlatmak için kullanılır." },
      { type: "example", en: "While I was cooking, he was watching TV.", tr: "Ben yemek pişirirken, o televizyon izliyordu." },
      { type: "example", en: "While she was studying, they were playing outside.", tr: "O ders çalışırken, onlar dışarıda oynuyordu." },
      { type: "rule", text: "Ayrıca, geçmişte devam eden bir eylemin arasına giren ani bir olayı anlatmak için de kullanılır; bu durumda ani olay Di'li geçmiş zamanla (Past Simple) verilir." },
      { type: "example", en: "I was sleeping when the phone rang.", tr: "Telefon çaldığında uyuyordum." },
      { type: "example", en: "We were walking in the park when it started to rain.", tr: "Yağmur başladığında parkta yürüyorduk." },
      { type: "example", en: "He was driving when the accident happened.", tr: "Kaza olduğunda o araba kullanıyordu." },
      { type: "rule", text: "Bu tense'in kısaca hikâye anlatımında, geçmişteki bir sahneyi betimlemek için de sıkça kullanıldığı unutulmamalıdır." },
      { type: "example", en: "The sun was shining and the birds were singing.", tr: "Güneş parlıyordu ve kuşlar ötüyordu." },
      { type: "rule", text: "\"WORK\" fiili üzerinden Past Continuous tam çekim tablosunu görelim." },
      { type: "pattern", text: "WAS/WERE WORKING (TAM ÇEKİM)" },
      { type: "example", en: "I was working when you called.", tr: "Sen aradığında çalışıyordum." },
      { type: "example", en: "You were working late that night.", tr: "O gece geç saatlere kadar çalışıyordun." },
      { type: "example", en: "He was working on his laptop.", tr: "O dizüstü bilgisayarında çalışıyordu." },
      { type: "example", en: "She wasn't working at that time.", tr: "O saatte çalışmıyordu." },
      { type: "example", en: "We weren't working together back then.", tr: "O zamanlar birlikte çalışmıyorduk." },
      { type: "example", en: "Were they working on the weekend?", tr: "Onlar hafta sonu çalışıyor muydu?" },
      { type: "rule", text: "Daha fazla günlük hayat örneğiyle bu dersi pekiştirelim." },
      { type: "example", en: "I was reading a book when the lights went out.", tr: "Işıklar söndüğünde bir kitap okuyordum." },
      { type: "example", en: "She was crying when I saw her.", tr: "Onu gördüğümde ağlıyordu." },
      { type: "example", en: "We were talking about you.", tr: "Senin hakkında konuşuyorduk." },
      { type: "example", en: "What were they doing in the garden?", tr: "Onlar bahçede ne yapıyorlardı?" },
      { type: "example", en: "He was standing near the window.", tr: "O pencerenin yanında duruyordu." },
      { type: "rule", text: "WHILE ve WHEN bağlaçlarıyla daha fazla örnek görelim." },
      { type: "example", en: "While we were traveling, we met many interesting people.", tr: "Seyahat ederken birçok ilginç insanla tanıştık." },
      { type: "example", en: "While he was speaking, everyone was listening carefully.", tr: "O konuşurken herkes dikkatlice dinliyordu." },
      { type: "example", en: "I was cooking when the guests arrived.", tr: "Misafirler geldiğinde yemek pişiriyordum." },
      { type: "example", en: "She was doing her homework when I came in.", tr: "İçeri girdiğimde o ödevini yapıyordu." },
      { type: "rule", text: "Hikâye anlatımı tarzında birkaç örnek daha ekleyerek bu dersi tamamlayalım." },
      { type: "example", en: "It was raining heavily, and the wind was blowing hard.", tr: "Şiddetli yağmur yağıyordu ve rüzgar sert esiyordu." },
      { type: "example", en: "Everyone was waiting quietly in the room.", tr: "Herkes odada sessizce bekliyordu." },
      { type: "example", en: "The children were playing happily in the garden.", tr: "Çocuklar bahçede mutlu bir şekilde oynuyordu." },
      { type: "rule", text: "Son bir tekrar bölümüyle bu dersi tamamlayalım." },
      { type: "example", en: "I was thinking about you when you called.", tr: "Sen aradığında seni düşünüyordum." },
      { type: "example", en: "They were arguing about money.", tr: "Onlar para hakkında tartışıyordu." },
      { type: "example", en: "She was smiling the whole time.", tr: "O bütün zaman gülümsüyordu." },
      { type: "example", en: "We were discussing the new project.", tr: "Yeni proje hakkında konuşuyorduk." },
      { type: "example", en: "What was he wearing at the party?", tr: "O partide ne giyiyordu?" },
      { type: "rule", text: "Daha fazla örnek cümleyle bu tense'i iyice pekiştirelim." },
      { type: "example", en: "I was studying when the fire alarm went off.", tr: "Yangın alarmı çaldığında ders çalışıyordum." },
      { type: "example", en: "She was singing in the shower.", tr: "O duşta şarkı söylüyordu." },
      { type: "example", en: "We were watching a movie when the power went out.", tr: "Elektrik kesildiğinde bir film izliyorduk." },
      { type: "example", en: "He was jogging in the park this morning.", tr: "O bu sabah parkta koşu yapıyordu." },
      { type: "example", en: "They weren't paying attention during the lecture.", tr: "Onlar ders sırasında dikkat etmiyorlardı." },
      { type: "example", en: "Was she waiting for a long time?", tr: "O uzun süre mi bekliyordu?" },
      { type: "example", en: "I was checking my messages when you knocked.", tr: "Sen kapıyı çaldığında mesajlarımı kontrol ediyordum." },
      { type: "example", en: "The dog was barking loudly all night.", tr: "Köpek bütün gece yüksek sesle havlıyordu." },
      { type: "rule", text: "Bu dersteki bütün kalıpları içeren bir kapanış bölümü ekleyelim." },
      { type: "example", en: "While she was driving, she was listening to the radio.", tr: "O araba kullanırken radyo dinliyordu." },
      { type: "example", en: "We were still talking when the waiter came.", tr: "Garson geldiğinde hâlâ konuşuyorduk." },
      { type: "example", en: "What were you thinking about?", tr: "Ne hakkında düşünüyordun?" },
      { type: "rule", text: "Bu tense'i pekiştirmek için birkaç örnek daha ekleyelim." },
      { type: "example", en: "I was texting my friend during the class.", tr: "Ders sırasında arkadaşıma mesaj atıyordum." },
      { type: "example", en: "She was cleaning the kitchen when I got home.", tr: "Eve vardığımda o mutfağı temizliyordu." },
      { type: "example", en: "We were discussing the budget for two hours.", tr: "İki saat boyunca bütçeyi tartışıyorduk." },
      { type: "example", en: "He wasn't paying attention to the road.", tr: "O yola dikkat etmiyordu." },
      { type: "example", en: "Were the kids behaving well at school?", tr: "Çocuklar okulda iyi mi davranıyordu?" },
      { type: "example", en: "I was carrying too many bags at once.", tr: "Aynı anda çok fazla çanta taşıyordum." },
      { type: "example", en: "We were negotiating the price for an hour.", tr: "Bir saat boyunca fiyatı pazarlık ediyorduk." },
      { type: "example", en: "She was wearing a beautiful red dress.", tr: "O güzel kırmızı bir elbise giyiyordu." },
      { type: "example", en: "The team was preparing for the final match.", tr: "Takım final maçına hazırlanıyordu." },
      { type: "example", en: "Why weren't you answering my calls?", tr: "Neden aramalarıma cevap vermiyordun?" },
      { type: "example", en: "I was daydreaming during the lesson.", tr: "Ders sırasında hayal kuruyordum." },
      { type: "example", en: "They were celebrating their victory.", tr: "Onlar zaferlerini kutluyorlardı." },
      { type: "example", en: "Was he complaining about the food again?", tr: "Yine yemek hakkında mı şikayet ediyordu?" },
      { type: "example", en: "The manager was reviewing the applications.", tr: "Müdür başvuruları inceliyordu." },
      { type: "example", en: "I was hoping you would call.", tr: "Aramanı umuyordum." },
      { type: "example", en: "We were enjoying the sunny weather.", tr: "Güneşli havanın keyfini çıkarıyorduk." },
      { type: "example", en: "She was explaining the situation calmly.", tr: "O durumu sakince açıklıyordu." },
      { type: "example", en: "The children were fighting over a toy.", tr: "Çocuklar bir oyuncak için kavga ediyordu." },
      { type: "example", en: "I was counting the money when he walked in.", tr: "O içeri girdiğinde parayı sayıyordum." },
      { type: "example", en: "We were following the news closely.", tr: "Haberleri yakından takip ediyorduk." },
      { type: "rule", text: "Sık yapılan hatalar: Öğrenciler genellikle WAS/WERE ile birlikte fiili -ING yapmayı unutur veya WAS/WERE'i özneyle uyumsuz kullanır. \"He were working\" değil \"He was working\" doğrudur; \"They was sleeping\" değil \"They were sleeping\" doğrudur." },
      { type: "rule", text: "Bir diğer yaygın hata, Past Continuous ile Past Simple'ı karıştırmaktır. Past Continuous devam eden bir arka plan eylemini, Past Simple ise kısa ve tamamlanmış bir eylemi anlatır; genellikle birlikte kullanılırlar." },
      { type: "example", en: "I was watching TV when he knocked on the door.", tr: "O kapıyı çaldığında televizyon izliyordum." },
      { type: "example", en: "She was walking home when it began to snow.", tr: "Kar yağmaya başladığında eve doğru yürüyordu." },
      { type: "rule", text: "Şimdi bu tense'i pekiştirmek için karşılaştırmalı birkaç örnek daha görelim: iki eylem aynı anda mı devam ediyordu, yoksa biri diğerini mi kesti?" },
      { type: "example", en: "While I was washing the dishes, my phone was ringing.", tr: "Ben bulaşıkları yıkarken telefonum çalıyordu." },
      { type: "example", en: "While the teacher was explaining the lesson, some students were whispering.", tr: "Öğretmen dersi anlatırken bazı öğrenciler fısıldaşıyordu." },
      { type: "example", en: "I was getting dressed when the taxi arrived.", tr: "Taksi geldiğinde giyiniyordum." },
      { type: "example", en: "She was brushing her teeth when the doorbell rang.", tr: "Kapı zili çaldığında dişlerini fırçalıyordu." },
      { type: "rule", text: "Past Continuous, aynı zamanda geçmişte kibarca bir isteği ya da niyeti belirtmek için de kullanılabilir; bu kullanım özellikle resmi olmayan konuşmalarda görülür." },
      { type: "example", en: "I was wondering if you could help me.", tr: "Acaba bana yardım edebilir misin diye merak ediyordum." },
      { type: "example", en: "We were hoping to see you at the party.", tr: "Seni partide görmeyi umuyorduk." },
      { type: "rule", text: "Son olarak bu dersteki tüm yapıları içeren bir tekrar bölümüyle konuyu tamamlayalım." },
      { type: "example", en: "What were you doing when the earthquake happened?", tr: "Deprem olduğunda ne yapıyordun?" },
      { type: "example", en: "They were arguing loudly, so the neighbors were complaining.", tr: "Onlar yüksek sesle tartışıyordu, bu yüzden komşular şikayet ediyordu." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
