import { publishQuiz, prisma, QuizDef } from "./lib/quiz-lib";

const ZAMANLAR = "İngilizce - Zamanlar";
const KELIME = "İngilizce - Kelime ve Kalıplar";

const quizzes: QuizDef[] = [
  {
    title: "20 İş ve Günlük Yaşam Kalıpları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "\"Çalışkan\" kelimesinin İngilizcesi nedir?", optionA: "hardworking", optionB: "lazy", optionC: "busy", optionD: "available", correct: "A" },
      { prompt: "\"Tembel\" kelimesinin İngilizcesi nedir?", optionA: "hardworking", optionB: "lazy", optionC: "busy", optionD: "available", correct: "B" },
      { prompt: "\"Müsait\" kelimesinin İngilizcesi nedir?", optionA: "busy", optionB: "available", optionC: "lazy", optionD: "tired", correct: "B" },
      { prompt: "GET USED TO ne anlama gelir?", optionA: "Alışmak (süreç)", optionB: "Alışkın olmak (durum)", optionC: "Eskiden yapmak", optionD: "Hiç yapmamak", correct: "A" },
      { prompt: "BE USED TO ne anlama gelir?", optionA: "Alışmak (süreç)", optionB: "Alışkın olmak (durum)", optionC: "Eskiden yapmak", optionD: "Hiç yapmamak", correct: "B" },
      { prompt: "USED TO + V1 ne anlama gelir?", optionA: "Eskiden yapardı", optionB: "Şimdi yapıyor", optionC: "Alışkın olmak", optionD: "Asla yapmadı", correct: "A" },
      { prompt: "I ___ live in a small village. (eskiden)", optionA: "use to", optionB: "used to", optionC: "am used to", optionD: "get used to", correct: "B" },
      { prompt: "She is used to ___ long hours.", optionA: "work", optionB: "working", optionC: "worked", optionD: "works", correct: "B" },
      { prompt: "MEET A DEADLINE ne anlama gelir?", optionA: "Toplantı yapmak", optionB: "Son teslim tarihine yetişmek", optionC: "Randevu almak", optionD: "Zaman kaybetmek", correct: "B" },
      { prompt: "GET PROMOTED ne anlama gelir?", optionA: "İşten çıkarılmak", optionB: "Terfi almak", optionC: "İşe başlamak", optionD: "İstifa etmek", correct: "B" },
      { prompt: "SCHEDULE A MEETING ne anlama gelir?", optionA: "Toplantıyı iptal etmek", optionB: "Toplantı planlamak", optionC: "Toplantıya geç kalmak", optionD: "Toplantıdan kaçmak", correct: "B" },
      { prompt: "TAKE MINUTES ne anlama gelir?", optionA: "Ara vermek", optionB: "Tutanak tutmak", optionC: "Geç kalmak", optionD: "Erken gelmek", correct: "B" },
      { prompt: "APPLY FOR A JOB ne anlama gelir?", optionA: "İşten ayrılmak", optionB: "İşe başvurmak", optionC: "İşten kovulmak", optionD: "Terfi almak", correct: "B" },
      { prompt: "\"Özgeçmiş\" kelimesinin İngilizcesi nedir?", optionA: "CV/resume", optionB: "application", optionC: "interview", optionD: "qualification", correct: "A" },
      { prompt: "PRIORITIZE ne anlama gelir?", optionA: "Ertelemek", optionB: "Önceliklendirmek", optionC: "Unutmak", optionD: "Tamamlamak", correct: "B" },
      { prompt: "PROCRASTINATE ne anlama gelir?", optionA: "Ertelemek", optionB: "Hemen yapmak", optionC: "Önceliklendirmek", optionD: "Bitirmek", correct: "A" },
      { prompt: "RUN ERRANDS ne anlama gelir?", optionA: "Koşmak", optionB: "İşleri halletmek", optionC: "Kaçmak", optionD: "Dinlenmek", correct: "B" },
      { prompt: "TREAT YOURSELF ne anlama gelir?", optionA: "Kendine kötü davranmak", optionB: "Kendine iyi bakmak/ısmarlamak", optionC: "Kendini eleştirmek", optionD: "Kendini unutmak", correct: "B" },
      { prompt: "WORK-LIFE BALANCE ne anlama gelir?", optionA: "İş yükü", optionB: "İş-yaşam dengesi", optionC: "Maaş dengesi", optionD: "Kariyer planı", correct: "B" },
      { prompt: "TAKE A DAY OFF ne anlama gelir?", optionA: "İşe erken gitmek", optionB: "Bir gün izin almak", optionC: "Fazla mesai yapmak", optionD: "İşi bırakmak", correct: "B" },
    ],
  },
  {
    title: "12 Edilgen Çatı (Passive Voice) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "Passive Voice yapısı nedir?", optionA: "BE + V3", optionB: "HAVE + V3", optionC: "BE + V-ing", optionD: "V1", correct: "A" },
      { prompt: "The letter ___ written yesterday.", optionA: "is", optionB: "was", optionC: "does", optionD: "has", correct: "B" },
      { prompt: "Passive Voice'ta eylemi yapan kişi hangi edatla belirtilir?", optionA: "FOR", optionB: "BY", optionC: "WITH", optionD: "TO", correct: "B" },
      { prompt: "English ___ spoken in many countries.", optionA: "is", optionB: "are", optionC: "was", optionD: "were", correct: "A" },
      { prompt: "This bridge ___ built in 1990.", optionA: "is", optionB: "was", optionC: "are", optionD: "were", correct: "B" },
      { prompt: "Passive Voice'ta hangi durumda BY kullanılmaz?", optionA: "Eylemi yapan biliniyorsa", optionB: "Eylemi yapan önemli değilse", optionC: "Her zaman kullanılır", optionD: "Asla kullanılmaz", correct: "B" },
      { prompt: "This problem must ___ solved immediately.", optionA: "be", optionB: "is", optionC: "was", optionD: "been", correct: "A" },
      { prompt: "Modallerle Passive yapısı nedir?", optionA: "MODAL + BE + V3", optionB: "MODAL + V1", optionC: "MODAL + HAVE + V3", optionD: "MODAL + V-ing", correct: "A" },
      { prompt: "___ this room cleaned every day?", optionA: "Is", optionB: "Does", optionC: "Do", optionD: "Has", correct: "A" },
      { prompt: "GET, günlük konuşmada neyin yerine kullanılabilir?", optionA: "HAVE", optionB: "BE (Passive)", optionC: "WILL", optionD: "DO", correct: "B" },
      { prompt: "He got ___ in the accident.", optionA: "injure", optionB: "injured", optionC: "injuring", optionD: "injures", correct: "B" },
      { prompt: "It is said ___ he is very rich.", optionA: "that", optionB: "who", optionC: "which", optionD: "what", correct: "A" },
      { prompt: "Sürekli (continuous) zamanlarda Passive yapısı nedir?", optionA: "BE BEING + V3", optionB: "HAVE BEEN + V3", optionC: "HAD + V3", optionD: "WILL BE + V3", correct: "A" },
      { prompt: "The house is ___ painted.", optionA: "be being", optionB: "being", optionC: "been", optionD: "be", correct: "B" },
      { prompt: "Tamamlanmış (perfect) zamanlarda Passive yapısı nedir?", optionA: "HAVE/HAS BEEN + V3", optionB: "BE + V-ing", optionC: "HAD + V-ing", optionD: "WILL + V3", correct: "A" },
      { prompt: "All the tickets have already ___ sold.", optionA: "be", optionB: "been", optionC: "being", optionD: "was", correct: "B" },
      { prompt: "Aktif cümleyi Passive'e çevirirken nesne ne olur?", optionA: "Nesne kalır", optionB: "Nesne özne olur", optionC: "Nesne silinir", optionD: "Nesne edat olur", correct: "B" },
      { prompt: "This car was made ___ Germany.", optionA: "at", optionB: "in", optionC: "on", optionD: "by", correct: "B" },
      { prompt: "The window was broken ___ the kids.", optionA: "at", optionB: "in", optionC: "by", optionD: "with", correct: "C" },
      { prompt: "Sık yapılan hata: Passive'te hangi fiil unutulur?", optionA: "BE fiili", optionB: "V1", optionC: "DO fiili", optionD: "HAVE fiili", correct: "A" },
    ],
  },
  {
    title: "21 As Kalıpları ve Memnuniyet İfadeleri - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "AS SOON AS POSSIBLE ne anlama gelir?", optionA: "Asla", optionB: "Mümkün olan en kısa zamanda", optionC: "Bazen", optionD: "Her zaman", correct: "B" },
      { prompt: "AS LONG AS POSSIBLE ne anlama gelir?", optionA: "Olabildiğince kısa", optionB: "Olabildiğince uzun", optionC: "Asla", optionD: "Bazen", correct: "B" },
      { prompt: "AS...AS ne anlama gelir?", optionA: "-den daha", optionB: "-kadar (eşitlik)", optionC: "En çok", optionD: "En az", correct: "B" },
      { prompt: "This car is as expensive ___ the other one.", optionA: "than", optionB: "as", optionC: "so", optionD: "that", correct: "B" },
      { prompt: "BE USED TO ne anlama gelir?", optionA: "Alışmak süreci", optionB: "Alışkın olmak", optionC: "Kullanmak", optionD: "Kullanılmak", correct: "B" },
      { prompt: "BE IN A GOOD MOOD ne anlama gelir?", optionA: "Kötü modda olmak", optionB: "İyi modda olmak", optionC: "Modu olmamak", optionD: "Şaşırmış olmak", correct: "B" },
      { prompt: "DISAPPOINT ne anlama gelir?", optionA: "Sevindirmek", optionB: "Hayal kırıklığına uğratmak", optionC: "Şaşırtmak", optionD: "Rahatlatmak", correct: "B" },
      { prompt: "HAVE FUN ne anlama gelir?", optionA: "Üzülmek", optionB: "Eğlenmek", optionC: "Sıkılmak", optionD: "Yorulmak", correct: "B" },
      { prompt: "AS FAR AS I KNOW ne anlama gelir?", optionA: "Hiç bilmiyorum", optionB: "Bildiğim kadarıyla", optionC: "Kesinlikle", optionD: "Asla bilmem", correct: "B" },
      { prompt: "AS A MATTER OF FACT ne anlama gelir?", optionA: "Aslına bakarsan", optionB: "Hiçbir şekilde", optionC: "Belki", optionD: "Asla", correct: "A" },
      { prompt: "AS USUAL ne anlama gelir?", optionA: "Beklenmedik şekilde", optionB: "Her zamanki gibi", optionC: "Nadiren", optionD: "Asla", correct: "B" },
      { prompt: "AS EXPECTED ne anlama gelir?", optionA: "Beklenmedik şekilde", optionB: "Beklendiği gibi", optionC: "Asla", optionD: "Bazen", correct: "B" },
      { prompt: "FEEL LIKE + V-ing ne anlama gelir?", optionA: "Bir şey yapmak zorunda olmak", optionB: "Canı bir şey yapmak istemek", optionC: "Bir şeyi sevmemek", optionD: "Bir şeyi unutmak", correct: "B" },
      { prompt: "GET USED TO ile BE USED TO arasındaki fark nedir?", optionA: "Fark yok", optionB: "GET süreç, BE durum vurgular", optionC: "BE süreç, GET durum vurgular", optionD: "İkisi de aynı anlamda", correct: "B" },
      { prompt: "REASONABLE ne anlama gelir?", optionA: "Mantıksız", optionB: "Makul", optionC: "Anlamsız", optionD: "Kötü", correct: "B" },
      { prompt: "FIRE ne anlama gelir (iş bağlamında)?", optionA: "İşe almak", optionB: "Kovmak", optionC: "Terfi ettirmek", optionD: "Eğitmek", correct: "B" },
      { prompt: "HIRE ne anlama gelir?", optionA: "Kovmak", optionB: "İşe almak", optionC: "İstifa etmek", optionD: "Emekli olmak", correct: "B" },
      { prompt: "TRY ON ne anlama gelir?", optionA: "Denemek (kıyafet)", optionB: "Satın almak", optionC: "İade etmek", optionD: "Yıkamak", correct: "A" },
      { prompt: "COMPARE ne anlama gelir?", optionA: "Kıyaslamak", optionB: "Kopyalamak", optionC: "Tekrarlamak", optionD: "Karıştırmak", correct: "A" },
      { prompt: "SUCH AS ne anlama gelir?", optionA: "Gibi, örneğin", optionB: "Ama", optionC: "Veya", optionD: "Rağmen", correct: "A" },
    ],
  },
  {
    title: "22 Karma Kalıplar - 1 - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "IN A SENSE ne anlama gelir?", optionA: "Bir bakıma", optionB: "Hiçbir şekilde", optionC: "Kesinlikle", optionD: "Asla", correct: "A" },
      { prompt: "INSIST ON ne anlama gelir?", optionA: "Vazgeçmek", optionB: "Israr etmek", optionC: "Kabul etmek", optionD: "Reddetmek", correct: "B" },
      { prompt: "MAKE AN EFFORT ne anlama gelir?", optionA: "Çaba sarfetmek", optionB: "Vazgeçmek", optionC: "Dinlenmek", optionD: "Beklemek", correct: "A" },
      { prompt: "HOW LONG ne sorar?", optionA: "Mesafe", optionB: "Süre", optionC: "Miktar", optionD: "Sıklık", correct: "B" },
      { prompt: "HOW FAR ne sorar?", optionA: "Süre", optionB: "Mesafe", optionC: "Fiyat", optionD: "Sıklık", correct: "B" },
      { prompt: "AS A RESULT ne anlama gelir?", optionA: "Sonuç olarak", optionB: "Örneğin", optionC: "Ancak", optionD: "Rağmen", correct: "A" },
      { prompt: "AT FIRST ne anlama gelir?", optionA: "Sonunda", optionB: "İlk olarak", optionC: "Asla", optionD: "Her zaman", correct: "B" },
      { prompt: "HESITATE ne anlama gelir?", optionA: "Çekinmek, tereddüt etmek", optionB: "Karar vermek", optionC: "Acele etmek", optionD: "Kabul etmek", correct: "A" },
      { prompt: "ALTHOUGH ne anlama gelir?", optionA: "Çünkü", optionB: "-e rağmen", optionC: "Eğer", optionD: "O yüzden", correct: "B" },
      { prompt: "INCREASE ne anlama gelir?", optionA: "Azaltmak", optionB: "Arttırmak", optionC: "Durdurmak", optionD: "Değiştirmek", correct: "B" },
      { prompt: "DECREASE ne anlama gelir?", optionA: "Arttırmak", optionB: "Azaltmak", optionC: "Durdurmak", optionD: "Sabit tutmak", correct: "B" },
      { prompt: "NOWADAYS ne anlama gelir?", optionA: "Eskiden", optionB: "Bugünlerde", optionC: "Yakında", optionD: "Asla", correct: "B" },
      { prompt: "BE INTERESTED IN ne anlama gelir?", optionA: "İlgilenmek", optionB: "Korkmak", optionC: "Sıkılmak", optionD: "Şaşırmak", correct: "A" },
      { prompt: "FROM NOW ON ne anlama gelir?", optionA: "Geçmişte", optionB: "Bundan böyle", optionC: "Daha önce", optionD: "Asla", correct: "B" },
      { prompt: "CELEBRATE ne anlama gelir?", optionA: "Kutlamak", optionB: "Üzülmek", optionC: "Şikayet etmek", optionD: "Unutmak", correct: "A" },
      { prompt: "RECOMMEND ne anlama gelir?", optionA: "Reddetmek", optionB: "Tavsiye etmek", optionC: "Eleştirmek", optionD: "Görmezden gelmek", correct: "B" },
      { prompt: "REPRESENT ne anlama gelir?", optionA: "Temsil etmek", optionB: "Reddetmek", optionC: "Kabul etmek", optionD: "Unutmak", correct: "A" },
      { prompt: "APPROXIMATELY ne anlama gelir?", optionA: "Tam olarak", optionB: "Yaklaşık olarak", optionC: "Asla", optionD: "Kesinlikle", correct: "B" },
      { prompt: "FORECAST ne anlama gelir?", optionA: "Geçmiş", optionB: "Tahmin", optionC: "Sonuç", optionD: "Haber", correct: "B" },
      { prompt: "CONCLUSION ne anlama gelir?", optionA: "Başlangıç", optionB: "Sonuç", optionC: "Soru", optionD: "Öneri", correct: "B" },
    ],
  },
  {
    title: "23 Karma Kalıplar - 2 - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "PREDICT ne anlama gelir?", optionA: "Öngörmek", optionB: "Unutmak", optionC: "Reddetmek", optionD: "Kabul etmek", correct: "A" },
      { prompt: "TAKE A RISK ne anlama gelir?", optionA: "Risk almak", optionB: "Riskten kaçmak", optionC: "Güvenli olmak", optionD: "Beklemek", correct: "A" },
      { prompt: "BE PLEASED WITH ne anlama gelir?", optionA: "Memnun olmak", optionB: "Kızmak", optionC: "Şaşırmak", optionD: "Üzülmek", correct: "A" },
      { prompt: "BE PROUD OF ne anlama gelir?", optionA: "Utanmak", optionB: "Gurur duymak", optionC: "Korkmak", optionD: "Şaşırmak", correct: "B" },
      { prompt: "APPEAR ne anlama gelir?", optionA: "Kaybolmak", optionB: "Görünmek, ortaya çıkmak", optionC: "Gizlenmek", optionD: "Reddetmek", correct: "B" },
      { prompt: "DISAPPEAR ne anlama gelir?", optionA: "Görünmek", optionB: "Ortadan kaybolmak", optionC: "Gelmek", optionD: "Kalmak", correct: "B" },
      { prompt: "WHAT KIND OF ne sorar?", optionA: "Ne tür", optionB: "Ne zaman", optionC: "Nerede", optionD: "Neden", correct: "A" },
      { prompt: "PURPOSE ne anlama gelir?", optionA: "Amaç", optionB: "Sonuç", optionC: "Soru", optionD: "Cevap", correct: "A" },
      { prompt: "DURATION ne anlama gelir?", optionA: "Yer", optionB: "Süre", optionC: "Sebep", optionD: "Sonuç", correct: "B" },
      { prompt: "RESCUE ne anlama gelir?", optionA: "Kurtarmak", optionB: "Kaybetmek", optionC: "Aramak", optionD: "Bulmak", correct: "A" },
      { prompt: "BOTH...AND ne anlama gelir?", optionA: "Ya...ya da", optionB: "Hem...hem de", optionC: "Ne...ne de", optionD: "Sadece biri", correct: "B" },
      { prompt: "NEITHER...NOR ne anlama gelir?", optionA: "Hem...hem de", optionB: "Ya...ya da", optionC: "Ne...ne de", optionD: "Hepsi", correct: "C" },
      { prompt: "PROVIDE ne anlama gelir?", optionA: "Sağlamak", optionB: "Almak", optionC: "Reddetmek", optionD: "Kaybetmek", correct: "A" },
      { prompt: "DEPOSIT MONEY ne anlama gelir?", optionA: "Para çekmek", optionB: "Para yatırmak", optionC: "Para harcamak", optionD: "Para kaybetmek", correct: "B" },
      { prompt: "WITHDRAW ne anlama gelir?", optionA: "Para yatırmak", optionB: "Para çekmek", optionC: "Borç almak", optionD: "Ödeme yapmak", correct: "B" },
      { prompt: "GAIN PROFIT ne anlama gelir?", optionA: "Zarar etmek", optionB: "Kâr elde etmek", optionC: "Para kaybetmek", optionD: "Borçlanmak", correct: "B" },
      { prompt: "INNOCENT ne anlama gelir?", optionA: "Suçlu", optionB: "Masum", optionC: "Kızgın", optionD: "Şüpheli", correct: "B" },
      { prompt: "GUILTY ne anlama gelir?", optionA: "Masum", optionB: "Suçlu", optionC: "Dürüst", optionD: "Sadık", correct: "B" },
      { prompt: "CONFIRM ne anlama gelir?", optionA: "Reddetmek", optionB: "Onaylamak", optionC: "Unutmak", optionD: "Ertelemek", correct: "B" },
      { prompt: "GUARANTEE ne anlama gelir?", optionA: "Garanti etmek", optionB: "Reddetmek", optionC: "Şüphelenmek", optionD: "Unutmak", correct: "A" },
    ],
  },
];

async function main() {
  for (const quiz of quizzes) {
    await publishQuiz(quiz);
  }
}

main().finally(() => prisma.$disconnect());
