import { publishQuiz, prisma, QuizDef } from "./lib/quiz-lib";

const ZAMANLAR = "İngilizce - Zamanlar";
const KELIME = "İngilizce - Kelime ve Kalıplar";

const quizzes: QuizDef[] = [
  {
    title: "17 Whenever - Whatever - Wherever ve Belirsizlik Zamirleri - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "WHENEVER ne anlama gelir?", optionA: "Her ne zaman", optionB: "Her ne", optionC: "Her nerede", optionD: "Her kim", correct: "A" },
      { prompt: "WHATEVER ne anlama gelir?", optionA: "Her ne zaman", optionB: "Her ne", optionC: "Her nerede", optionD: "Her kim", correct: "B" },
      { prompt: "WHEREVER ne anlama gelir?", optionA: "Her ne zaman", optionB: "Her ne", optionC: "Her nerede", optionD: "Her kim", correct: "C" },
      { prompt: "WHOEVER ne anlama gelir?", optionA: "Her ne zaman", optionB: "Her ne", optionC: "Her nerede", optionD: "Her kim", correct: "D" },
      { prompt: "ANYTHING hangi cümlelerde kullanılır?", optionA: "Olumlu", optionB: "Olumsuz/soru", optionC: "Sadece emir", optionD: "Sadece soru", correct: "B" },
      { prompt: "NOTHING hangi fiil ile kullanılır?", optionA: "Olumlu fiil", optionB: "Olumsuz fiil", optionC: "Sadece soru fiili", optionD: "Emir", correct: "A" },
      { prompt: "I don't know anything. = I know ___.", optionA: "anything", optionB: "nothing", optionC: "something", optionD: "everything", correct: "B" },
      { prompt: "NO MATTER WHAT ne anlama gelir?", optionA: "Ne olursa olsun", optionB: "Hiçbir zaman", optionC: "Her zaman", optionD: "Bazen", correct: "A" },
      { prompt: "EVERYTHING hangi fiil formunu alır?", optionA: "Tekil", optionB: "Çoğul", optionC: "Fark etmez", optionD: "Hiçbiri", correct: "A" },
      { prompt: "EVERYBODY hangi fiil formunu alır?", optionA: "Tekil", optionB: "Çoğul", optionC: "Fark etmez", optionD: "Hiçbiri", correct: "A" },
      { prompt: "SOMETHING genellikle hangi tür cümlede kullanılır?", optionA: "Olumlu", optionB: "Olumsuz", optionC: "Emir", optionD: "Ünlem", correct: "A" },
      { prompt: "\"Whoever wins the race will get a prize.\" Bu cümlede WHOEVER ne anlama gelir?", optionA: "Her kim", optionB: "Hiç kimse", optionC: "Herkes", optionD: "Bazıları", correct: "A" },
      { prompt: "EACH OTHER ne anlama gelir?", optionA: "Kendisi", optionB: "Birbiri", optionC: "Herkes", optionD: "Hiç kimse", correct: "B" },
      { prompt: "ANOTHER hangi isimlerle kullanılır?", optionA: "Tekil sayılabilir", optionB: "Çoğul", optionC: "Sayılamaz", optionD: "Özel isim", correct: "A" },
      { prompt: "OTHER genellikle hangi isimlerle kullanılır?", optionA: "Tekil", optionB: "Çoğul/belirli", optionC: "Özel isim", optionD: "Hiçbiri", correct: "B" },
      { prompt: "\"Can I have another cup of coffee?\" Burada ANOTHER ne anlama gelir?", optionA: "Diğer", optionB: "Bir tane daha", optionC: "Hepsi", optionD: "Hiçbiri", correct: "B" },
      { prompt: "NONE OF hangi anlamda kullanılır?", optionA: "Hepsi", optionB: "Hiçbiri", optionC: "Bazısı", optionD: "Çoğu", correct: "B" },
      { prompt: "SOMEWHERE ELSE ne anlama gelir?", optionA: "Aynı yerde", optionB: "Başka bir yerde", optionC: "Hiçbir yerde", optionD: "Her yerde", correct: "B" },
      { prompt: "AS IF ne anlama gelir?", optionA: "-mış gibi", optionB: "-dığı için", optionC: "-meden önce", optionD: "-dığı sürece", correct: "A" },
      { prompt: "WHICHEVER ne anlama gelir?", optionA: "Her kim", optionB: "Hangisi olursa", optionC: "Her ne zaman", optionD: "Her nerede", correct: "B" },
    ],
  },
  {
    title: "10 Gelecek Zamanın Şimdiki Hali (Future Continuous) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "Future Continuous yapısı nedir?", optionA: "WILL BE + V-ing", optionB: "WILL + V1", optionC: "WILL HAVE + V3", optionD: "BE + V-ing", correct: "A" },
      { prompt: "This time tomorrow, I will be ___ to London.", optionA: "fly", optionB: "flying", optionC: "flew", optionD: "flies", correct: "B" },
      { prompt: "Future Continuous ne zaman kullanılır?", optionA: "Gelecekte belirli bir anda devam eden eylem için", optionB: "Geçmiş için", optionC: "Emir için", optionD: "Şimdiki alışkanlık için", correct: "A" },
      { prompt: "They will be waiting for us at the ___.", optionA: "airport", optionB: "airports", optionC: "airporting", optionD: "airported", correct: "A" },
      { prompt: "Future Continuous'un olumsuzu nasıl yapılır?", optionA: "WON'T BE + V-ing", optionB: "DON'T + V1", optionC: "ISN'T + V-ing", optionD: "HASN'T + V3", correct: "A" },
      { prompt: "___ you be working this weekend?", optionA: "Will", optionB: "Do", optionC: "Are", optionD: "Is", correct: "A" },
      { prompt: "Future Continuous, Future Simple'dan farklı olarak neyi vurgular?", optionA: "Ani kararı", optionB: "Süreci/devam eden eylemi", optionC: "Geçmişi", optionD: "Emri", correct: "B" },
      { prompt: "At this time next week, we will be sitting on the ___.", optionA: "beach", optionB: "beaches", optionC: "beaching", optionD: "beached", correct: "A" },
      { prompt: "Don't call me at 9, I will be having ___.", optionA: "dinner", optionB: "dinners", optionC: "dine", optionD: "dined", correct: "A" },
      { prompt: "Future Continuous en çok hangi ifadeyle kullanılır?", optionA: "YESTERDAY", optionB: "AT THIS TIME TOMORROW", optionC: "LAST WEEK", optionD: "AGO", correct: "B" },
      { prompt: "I will be traveling ___ this time next week.", optionA: "since", optionB: "for", optionC: "at", optionD: "ago", correct: "C" },
      { prompt: "Will you be ___ the car tonight?", optionA: "use", optionB: "using", optionC: "used", optionD: "uses", correct: "B" },
      { prompt: "Future Continuous, kibarca ne sormak için kullanılabilir?", optionA: "Geçmiş olayı", optionB: "Birinin planlarını", optionC: "Emri", optionD: "Şikayeti", correct: "B" },
      { prompt: "She will be teaching a class then, so she won't be ___.", optionA: "free", optionB: "work", optionC: "working", optionD: "works", correct: "A" },
      { prompt: "We will be discussing the budget ___ tomorrow's meeting.", optionA: "during", optionB: "while", optionC: "since", optionD: "for", correct: "A" },
      { prompt: "The captain will be turning ___ the seatbelt sign shortly.", optionA: "off", optionB: "on", optionC: "up", optionD: "down", correct: "A" },
      { prompt: "Future Continuous'un soru yapısı nedir?", optionA: "WILL + Özne + BE + V-ing", optionB: "BE + Özne + V-ing", optionC: "DO + Özne + V1", optionD: "HAVE + Özne + V3", correct: "A" },
      { prompt: "This time next year, I will be ___ abroad.", optionA: "live", optionB: "living", optionC: "lived", optionD: "lives", correct: "B" },
      { prompt: "We will be meeting clients ___ the afternoon.", optionA: "all", optionB: "since", optionC: "ago", optionD: "for", correct: "A" },
      { prompt: "I'll be seeing him tomorrow, so I'll give him the ___.", optionA: "message", optionB: "messages", optionC: "messaging", optionD: "messaged", correct: "A" },
    ],
  },
  {
    title: "18 Seyahat ve Bilgi Alışverişi Kalıpları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "\"Kalkışlar\" kelimesinin İngilizcesi nedir?", optionA: "arrivals", optionB: "departures", optionC: "boarding", optionD: "gate", correct: "B" },
      { prompt: "\"Varışlar\" kelimesinin İngilizcesi nedir?", optionA: "arrivals", optionB: "departures", optionC: "boarding", optionD: "gate", correct: "A" },
      { prompt: "Can I get ___? (bilgi almak)", optionA: "information", optionB: "informations", optionC: "an information", optionD: "some informations", correct: "A" },
      { prompt: "INFORMATION hangi tür isimdir?", optionA: "Sayılabilir", optionB: "Sayılamaz", optionC: "Özel isim", optionD: "Çoğul", correct: "B" },
      { prompt: "I'd like to ___ a room. (rezerve etmek)", optionA: "book", optionB: "books", optionC: "booking", optionD: "booked", correct: "A" },
      { prompt: "What time is ___? (çıkış)", optionA: "check-in", optionB: "check-out", optionC: "booking", optionD: "reservation", correct: "B" },
      { prompt: "Turn left at the traffic ___.", optionA: "light", optionB: "lights", optionC: "lighting", optionD: "lighted", correct: "B" },
      { prompt: "\"Tek yön bilet\" kelimesinin İngilizcesi nedir?", optionA: "round-trip ticket", optionB: "one-way ticket", optionC: "return ticket", optionD: "group ticket", correct: "B" },
      { prompt: "Our flight has been ___ by two hours.", optionA: "cancel", optionB: "delayed", optionC: "arrived", optionD: "boarded", correct: "B" },
      { prompt: "\"Döviz kuru\" kelimesinin İngilizcesi nedir?", optionA: "currency", optionB: "exchange rate", optionC: "exchange office", optionD: "cash", correct: "B" },
      { prompt: "I need to report my lost ___. (bagaj)", optionA: "luggage", optionB: "luggages", optionC: "baggages", optionD: "bag", correct: "A" },
      { prompt: "Can I make a ___ about this service? (şikayet)", optionA: "complaint", optionB: "complain", optionC: "complained", optionD: "complaining", correct: "A" },
      { prompt: "You need to go through passport ___ first.", optionA: "check", optionB: "control", optionC: "office", optionD: "desk", correct: "B" },
      { prompt: "Do you have anything to ___? (gümrükte beyan etmek)", optionA: "declare", optionB: "declaration", optionC: "declared", optionD: "declaring", correct: "A" },
      { prompt: "Is there a tourist ___ office near the square?", optionA: "information", optionB: "informations", optionC: "inform", optionD: "informed", correct: "A" },
      { prompt: "I'd like to rent a ___ for a week.", optionA: "car", optionB: "cars", optionC: "carring", optionD: "cared", correct: "A" },
      { prompt: "Do I need an international driving ___?", optionA: "license", optionB: "licenses", optionC: "licensing", optionD: "licensed", correct: "A" },
      { prompt: "Where's the nearest bus ___?", optionA: "stop", optionB: "stops", optionC: "stopping", optionD: "stopped", correct: "A" },
      { prompt: "Could you recommend a local ___? (yemek)", optionA: "dish", optionB: "dishes", optionC: "dishing", optionD: "dished", correct: "A" },
      { prompt: "I'm allergic ___ nuts.", optionA: "at", optionB: "to", optionC: "with", optionD: "for", correct: "B" },
    ],
  },
  {
    title: "19 Duygular ve Kişilik Sıfatları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "\"Mutluluk\" kelimesinin İngilizcesi nedir?", optionA: "happiness", optionB: "sadness", optionC: "tiredness", optionD: "kindness", correct: "A" },
      { prompt: "\"İnatçı\" kelimesinin İngilizcesi nedir?", optionA: "ambitious", optionB: "stubborn", optionC: "generous", optionD: "honest", correct: "B" },
      { prompt: "\"Hırslı\" kelimesinin İngilizcesi nedir?", optionA: "ambitious", optionB: "stubborn", optionC: "lazy", optionD: "shy", correct: "A" },
      { prompt: "ENCOURAGE ne anlama gelir?", optionA: "Cesaretlendirmek", optionB: "Cesaretini kırmak", optionC: "Korkutmak", optionD: "Üzmek", correct: "A" },
      { prompt: "DISCOURAGE ne anlama gelir?", optionA: "Cesaretlendirmek", optionB: "Cesaretini kırmak", optionC: "Sevindirmek", optionD: "Övmek", correct: "B" },
      { prompt: "INTERESTED ile INTERESTING arasındaki fark nedir?", optionA: "Fark yok", optionB: "INTERESTED kişinin hissi, INTERESTING dış etken", optionC: "INTERESTED dış etken, INTERESTING kişinin hissi", optionD: "İkisi de aynı anlamda", correct: "B" },
      { prompt: "I am ___ in this subject.", optionA: "interesting", optionB: "interested", optionC: "interest", optionD: "interests", correct: "B" },
      { prompt: "This book is very ___.", optionA: "interesting", optionB: "interested", optionC: "interest", optionD: "interests", correct: "A" },
      { prompt: "\"Şaşırmış\" kelimesinin İngilizcesi nedir (kişi)?", optionA: "surprising", optionB: "surprised", optionC: "surprise", optionD: "surprises", correct: "B" },
      { prompt: "\"Şaşırtıcı\" kelimesinin İngilizcesi nedir (durum)?", optionA: "surprising", optionB: "surprised", optionC: "surprise", optionD: "surprises", correct: "A" },
      { prompt: "\"Kıskanç\" kelimesinin İngilizcesi nedir?", optionA: "jealous", optionB: "proud", optionC: "ashamed", optionD: "grateful", correct: "A" },
      { prompt: "\"Gururlu\" kelimesinin İngilizcesi nedir?", optionA: "jealous", optionB: "proud", optionC: "ashamed", optionD: "embarrassed", correct: "B" },
      { prompt: "\"Utanç duyan\" kelimesinin İngilizcesi nedir?", optionA: "jealous", optionB: "proud", optionC: "ashamed", optionD: "grateful", correct: "C" },
      { prompt: "\"Minnettar\" kelimesinin İngilizcesi nedir?", optionA: "jealous", optionB: "proud", optionC: "ashamed", optionD: "grateful", correct: "D" },
      { prompt: "\"Kaba\" kelimesinin İngilizcesi nedir?", optionA: "rude", optionB: "arrogant", optionC: "honest", optionD: "careless", correct: "A" },
      { prompt: "\"Kibirli\" kelimesinin İngilizcesi nedir?", optionA: "rude", optionB: "arrogant", optionC: "honest", optionD: "reliable", correct: "B" },
      { prompt: "GET ANGRY ne anlama gelir?", optionA: "Kızmak (değişim)", optionB: "Kızgın olmak (durum)", optionC: "Sakinleşmek", optionD: "Üzülmek", correct: "A" },
      { prompt: "BURST INTO TEARS ne anlama gelir?", optionA: "Gülmeye başlamak", optionB: "Gözyaşlarına boğulmak", optionC: "Kızmak", optionD: "Şaşırmak", correct: "B" },
      { prompt: "BE GOOD AT ne anlama gelir?", optionA: "-de iyi olmak", optionB: "-den korkmak", optionC: "-e düşkün olmak", optionD: "-e alışkın olmak", correct: "A" },
      { prompt: "BE AFRAID OF ne anlama gelir?", optionA: "-de iyi olmak", optionB: "-den korkmak", optionC: "-e düşkün olmak", optionD: "-e güvenmek", correct: "B" },
    ],
  },
  {
    title: "11 Gelecek Zamandaki Geçmiş (Future Perfect) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "Future Perfect yapısı nedir?", optionA: "WILL HAVE + V3", optionB: "WILL BE + V-ing", optionC: "HAVE + V3", optionD: "HAD + V3", correct: "A" },
      { prompt: "Future Perfect ne zaman kullanılır?", optionA: "Gelecekte belirli bir zamana kadar tamamlanmış olacak eylemler için", optionB: "Şu anki eylem için", optionC: "Geçmişteki eylem için", optionD: "Emir için", correct: "A" },
      { prompt: "By next year, I will have ___ my studies.", optionA: "finish", optionB: "finished", optionC: "finishing", optionD: "finishes", correct: "B" },
      { prompt: "Future Perfect en çok hangi edatla kullanılır?", optionA: "SINCE", optionB: "BY", optionC: "AGO", optionD: "DURING", correct: "B" },
      { prompt: "Future Perfect'in olumsuzu nasıl yapılır?", optionA: "WON'T HAVE + V3", optionB: "WON'T BE + V-ing", optionC: "HAVEN'T + V3", optionD: "DIDN'T + V1", correct: "A" },
      { prompt: "___ you have completed the report by tomorrow?", optionA: "Will", optionB: "Do", optionC: "Are", optionD: "Have", correct: "A" },
      { prompt: "By the time you wake up, I will have made ___.", optionA: "breakfast", optionB: "breakfasts", optionC: "breakfasting", optionD: "breakfasted", correct: "A" },
      { prompt: "Future Perfect, Future Simple'dan farklı olarak neyi vurgular?", optionA: "Anlık kararı", optionB: "Belirli bir zamana kadar tamamlanmışlığı", optionC: "Süreci", optionD: "Geçmişi", correct: "B" },
      { prompt: "The workers will have completed the building by next ___.", optionA: "spring", optionB: "springs", optionC: "springing", optionD: "sprung", correct: "A" },
      { prompt: "Future Perfect'in kısaltması nedir?", optionA: "'LL HAVE", optionB: "'LL BE", optionC: "'VE", optionD: "'D", correct: "A" },
      { prompt: "By the time she is thirty, she will have earned her ___.", optionA: "doctorate", optionB: "doctorates", optionC: "doctor", optionD: "doctoral", correct: "A" },
      { prompt: "How long ___ you have worked here by the end of this year?", optionA: "will", optionB: "do", optionC: "are", optionD: "have", correct: "A" },
      { prompt: "She will have heard the news by ___, I'm sure.", optionA: "now", optionB: "yesterday", optionC: "ago", optionD: "last week", correct: "A" },
      { prompt: "Future Perfect genellikle hangi bağlamda kullanılır?", optionA: "Günlük sohbet", optionB: "İş/proje planlaması, teslim tarihleri", optionC: "Emir cümleleri", optionD: "Ünlem cümleleri", correct: "B" },
      { prompt: "By the end of this year, I will have ___ twenty books.", optionA: "read", optionB: "reads", optionC: "reading", optionD: "readed", correct: "A" },
      { prompt: "We will have spent almost a year ___ this project.", optionA: "plan", optionB: "planning", optionC: "planned", optionD: "plans", correct: "B" },
      { prompt: "Future Perfect'in soru yapısı nedir?", optionA: "WILL + Özne + HAVE + V3", optionB: "HAVE + Özne + V3", optionC: "WILL + Özne + BE + V-ing", optionD: "DID + Özne + V1", correct: "A" },
      { prompt: "By December, I will have worked here for exactly five ___.", optionA: "year", optionB: "years", optionC: "yearly", optionD: "yearing", correct: "B" },
      { prompt: "They will have saved a lot by cutting unnecessary ___.", optionA: "expense", optionB: "expenses", optionC: "expensive", optionD: "expensing", correct: "B" },
      { prompt: "By the time this project is finished, we will have spent a year ___ it.", optionA: "build", optionB: "building", optionC: "built", optionD: "builds", correct: "B" },
    ],
  },
];

async function main() {
  for (const quiz of quizzes) {
    await publishQuiz(quiz);
  }
}

main().finally(() => prisma.$disconnect());
