import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "36_Karma_Kaliplar_3",
    title: "KARMA KALIPLAR - 3",
    blocks: [
      { type: "pattern", text: "CHEER UP = neşelenmek / FOR A WHILE = bir süre" },
      { type: "example", en: "They need to cheer him up.", tr: "Onun onu neşelendirmesi lazım." },
      { type: "example", en: "We will not be here for a while.", tr: "Bir süre burada olmayacağız." },
      { type: "pattern", text: "TOUCH = dokunmak / KEEP IN TOUCH = iletişimde olmak / PUT IN TOUCH WITH = görüştürmek" },
      { type: "example", en: "Let's keep in touch!", tr: "İrtibatta olalım!" },
      { type: "example", en: "Can you put me in touch with your boss?", tr: "Beni patronunuzla görüştürebilir misiniz?" },
      { type: "rule", text: "BE GOOD AT / BE BAD AT = bir şeyde iyi/kötü olmak. Bu kalıptan sonra fiil -ING alır." },
      { type: "example", en: "He is good at driving.", tr: "O araba kullanmada iyi." },
      { type: "example", en: "I'm not good at singing.", tr: "Şarkı söylemede iyi değilim." },
      { type: "example", en: "They are bad at convincing people.", tr: "Onlar insanları ikna etmede kötü." },
      { type: "pattern", text: "DO SPORT = spor yapmak" },
      { type: "example", en: "How often do you do sport?", tr: "Ne sıklıkta spor yaparsın?" },
      { type: "pattern", text: "GIVE/PLACE AN ORDER = sipariş vermek / OUT OF ORDER = bozuk, arızalı" },
      { type: "example", en: "We're ready to order.", tr: "Sipariş vermeye hazırız." },
      { type: "example", en: "The elevator is out of order, please use the stairs!", tr: "Asansör bozuk, lütfen merdivenleri kullanın!" },
      { type: "pattern", text: "BREAK-BROKE-BROKEN = kırmak, çiğnemek / mola" },
      { type: "example", en: "They broke the rules.", tr: "Onlar kuralları çiğnediler." },
      { type: "example", en: "Who broke the vase?", tr: "Vazoyu kim kırdı?" },
      { type: "rule", text: "LET = izin vermek. LET'S kalıbıyla (Let us) karıştırılmamalıdır." },
      { type: "example", en: "Let me go!", tr: "Gideyim!" },
      { type: "example", en: "Don't let him smoke!", tr: "Onun sigara içmesine izin verme!" },
      { type: "example", en: "If something goes wrong, let me know!", tr: "Yolunda olmayan bir şey olursa bileyim!" },
      { type: "pattern", text: "DEPEND ON = bağlı olmak / IT IS UP TO YOU = sana bağlı, sana kalmış" },
      { type: "example", en: "Price depends on the quality.", tr: "Fiyat kaliteye bağlıdır." },
      { type: "example", en: "Does that depend on us?", tr: "Bu bize mi bağlı?" },
      { type: "pattern", text: "BE WRONG / BE MISTAKEN = yanılmak" },
      { type: "example", en: "Am I wrong?", tr: "Yanılıyor muyum?" },
      { type: "pattern", text: "CALM DOWN = sakinleşmek / KEEP CALM! = sakin kal! / QUIET = sessiz / SILENT = suskun" },
      { type: "example", en: "I should calm down before driving.", tr: "Araba kullanmadan önce sakinleşmeliyim." },
      { type: "example", en: "Be quiet!", tr: "Sessiz ol!" },
      { type: "pattern", text: "RESEMBLE = TAKE AFTER = benzemek" },
      { type: "example", en: "He takes after his father, they are both stubborn.", tr: "O babasına benziyor, ikisi de inatçı." },
      { type: "example", en: "My daughter resembles me.", tr: "Kızım bana benziyor." },
      { type: "pattern", text: "GET A JOB = işe girmek / FALL-FELL-FALLEN = düşmek" },
      { type: "example", en: "He wants to get a new job.", tr: "O yeni bir işe girmek istiyor." },
      { type: "example", en: "The girl suddenly fell down.", tr: "Kız aniden düştü." },
      { type: "pattern", text: "FALL ASLEEP = uyuyakalmak / COUCH = kanepe / FALL IN LOVE + WITH = aşık olmak" },
      { type: "example", en: "He has suddenly fallen asleep on the couch.", tr: "Aniden kanepede uyuyakaldı." },
      { type: "example", en: "I will almost fall in love with her.", tr: "Neredeyse ona aşık olacağım." },
      { type: "pattern", text: "HARM = zarar vermek / HARMFUL = zararlı / HARMLESS = zararsız" },
      { type: "example", en: "I don't want you to harm him.", tr: "Ona zarar vermeni istemiyorum." },
      { type: "example", en: "Smoking is a very harmful habit.", tr: "Sigara içmek çok zararlı bir alışkanlık." },
      { type: "pattern", text: "BE ABOUT TO = -mek üzere / SET OUT = HIT THE ROAD = yola çıkmak / OVERCOME = HANDLE = üstesinden gelmek" },
      { type: "example", en: "We're about to finish this job.", tr: "Bu işi bitirmek üzereyiz." },
      { type: "example", en: "They are about to hit the road.", tr: "Yola çıkmak üzereler." },
      { type: "pattern", text: "REALIZE = farkına varmak, gerçekleştirmek / CARRY OUT = gerçekleştirmek" },
      { type: "example", en: "I have to carry out one of my dreams.", tr: "Hayallerimden birini gerçekleştirmem lazım." },
      { type: "pattern", text: "PROMOTE = terfi ettirmek / BE PROMOTED = GET PROMOTION = terfi etmek" },
      { type: "example", en: "His boss decided to promote him for his contributions.", tr: "Katkılarından dolayı patronu onu terfi ettirmeye karar verdi." },
      { type: "example", en: "Did you get your promotion last year?", tr: "Geçen yıl mı terfi ettin?" },
      { type: "pattern", text: "SET UP = kurmak / ESTABLISH = kurmak, tesis etmek" },
      { type: "example", en: "They set up a new company last year.", tr: "Geçen yıl yeni bir şirket kurdular." },
      { type: "example", en: "The organization was established in 1975.", tr: "Kuruluş 1975'te tesis edildi." },
      { type: "pattern", text: "GIVE UP = vazgeçmek / GO ON = devam etmek / KEEP ON = -meye devam etmek" },
      { type: "example", en: "Don't give up on your dreams.", tr: "Hayallerinden vazgeçme." },
      { type: "example", en: "He kept on talking even though nobody was listening.", tr: "Kimse dinlemese de konuşmaya devam etti." },
      { type: "pattern", text: "LOOK FOR = aramak / LOOK AFTER = bakmak / LOOK INTO = araştırmak, incelemek" },
      { type: "example", en: "We are looking for a new house.", tr: "Yeni bir ev arıyoruz." },
      { type: "example", en: "The police are looking into the case.", tr: "Polis davayı araştırıyor." },
      { type: "pattern", text: "PUT OFF = ertelemek / PUT UP WITH = katlanmak, tahammül etmek" },
      { type: "example", en: "We had to put off the trip because of the weather.", tr: "Hava yüzünden geziyi ertelemek zorunda kaldık." },
      { type: "example", en: "I can't put up with this noise anymore.", tr: "Bu gürültüye artık katlanamıyorum." },
      { type: "pattern", text: "BRING UP = büyütmek (çocuk), gündeme getirmek / TAKE UP = başlamak (hobi vb.)" },
      { type: "example", en: "She was brought up by her grandparents.", tr: "O büyükanne ve büyükbabası tarafından büyütüldü." },
      { type: "example", en: "He recently took up painting.", tr: "O son zamanlarda resim yapmaya başladı." },
      { type: "pattern", text: "COME UP WITH = bulmak (fikir, çözüm) / FIGURE OUT = çözmek, anlamak" },
      { type: "example", en: "She came up with a brilliant idea.", tr: "O harika bir fikir buldu." },
      { type: "example", en: "We finally figured out the problem.", tr: "Sonunda sorunu çözdük." },
      { type: "rule", text: "Son olarak bu dersteki phrasal verb'leri ve kalıpları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Even though he was promoted, he didn't give up looking for a better opportunity, and eventually, he came up with his own business idea.", tr: "Terfi almasına rağmen daha iyi bir fırsat aramaktan vazgeçmedi ve sonunda kendi iş fikrini buldu." },
      { type: "pattern", text: "TURN UP = ortaya çıkmak, gelmek / SHOW UP = gelmek, boy göstermek" },
      { type: "example", en: "He didn't show up to the meeting.", tr: "Toplantıya gelmedi." },
      { type: "example", en: "Something urgent turned up, so I had to leave.", tr: "Acil bir şey çıktı, o yüzden ayrılmak zorunda kaldım." },
      { type: "pattern", text: "CHECK OUT = kontrol etmek, çıkış yapmak / CHECK IN = giriş yapmak" },
      { type: "example", en: "You should check out this new restaurant.", tr: "Bu yeni restoranı kontrol etmelisin (denemelisin)." },
      { type: "pattern", text: "GO OVER = gözden geçirmek / GO THROUGH = incelemek, yaşamak (zorluk)" },
      { type: "example", en: "Let's go over the details one more time.", tr: "Detayları bir kez daha gözden geçirelim." },
      { type: "example", en: "She has gone through a lot this year.", tr: "O bu yıl çok şey yaşadı." },
      { type: "pattern", text: "PICK UP = almak, toplamak / DROP OFF = bırakmak (araçla)" },
      { type: "example", en: "Can you pick me up from the airport?", tr: "Beni havalimanından alabilir misin?" },
      { type: "example", en: "I'll drop you off at the station.", tr: "Seni istasyona bırakırım." },
      { type: "rule", text: "Son olarak bu dersteki phrasal verb'leri pekiştiren birkaç örnek daha görelim." },
      { type: "example", en: "He showed up late, checked in quickly, and then went over the schedule with the team.", tr: "Geç geldi, hızlıca giriş yaptı ve sonra ekiple programı gözden geçirdi." },
      { type: "pattern", text: "WORK OUT = çözmek, spor yapmak, iyi gitmek" },
      { type: "example", en: "I hope everything works out for you.", tr: "Umarım her şey senin için yolunda gider." },
      { type: "example", en: "She works out at the gym every morning.", tr: "O her sabah spor salonunda antrenman yapıyor." },
      { type: "pattern", text: "CUT DOWN ON = azaltmak / CUT BACK ON = kısmak, azaltmak" },
      { type: "example", en: "You should cut down on sugar.", tr: "Şeker tüketimini azaltmalısın." },
      { type: "pattern", text: "TAKE OFF = havalanmak, çıkarmak (kıyafet) / PUT ON = giymek" },
      { type: "example", en: "Take off your shoes before entering.", tr: "İçeri girmeden önce ayakkabılarını çıkar." },
      { type: "pattern", text: "END UP = sonunda ... ile bitmek" },
      { type: "example", en: "If you keep spending like that, you'll end up in debt.", tr: "Böyle harcamaya devam edersen, sonunda borca gireceksin." },
    ],
  },
  {
    fileBase: "37_Karma_Kaliplar_4",
    title: "KARMA KALIPLAR - 4",
    blocks: [
      { type: "pattern", text: "BLAME = suçlamak / THEFT = hırsızlık" },
      { type: "example", en: "He blamed us for theft.", tr: "O bizi hırsızlıkla suçladı." },
      { type: "pattern", text: "PRODUCE = üretmek / PRODUCT = ürün / PRODUCER = üretici / PRODUCTION = üretim" },
      { type: "example", en: "What kind of clothes do they produce?", tr: "Ne çeşit kıyafetler üretiyorlar?" },
      { type: "example", en: "They haven't delivered my product yet.", tr: "Ürünümü henüz teslim etmediler." },
      { type: "example", en: "Is production finished?", tr: "Üretim bitti mi?" },
      { type: "pattern", text: "CONSUME = tüketmek / CONSUMER = tüketici / CONSUMPTION = tüketim / EXCESSIVE = aşırı" },
      { type: "example", en: "What kind of foods do you consume?", tr: "Ne tür yiyecekler tüketirsin?" },
      { type: "example", en: "Don't they know consumer rights?", tr: "Tüketici haklarını bilmiyorlar mı?" },
      { type: "example", en: "Aren't you aware of excessive consumption?", tr: "Aşırı tüketimin farkında değil misin?" },
      { type: "pattern", text: "RESOURCE = kaynak / DUE TO = nedeniyle, sebebiyle / PREVENT = engellemek / AUTHORITY = yetkili, uzman" },
      { type: "example", en: "Resources are decreasing day by day due to excessive consumption.", tr: "Aşırı tüketim yüzünden kaynaklar gün geçtikçe azalıyor." },
      { type: "example", en: "Authorities tried everything to prevent accidents in this area.", tr: "Yetkililer bu bölgede kazaları önlemek için her şeyi denedi." },
      { type: "pattern", text: "GRATEFUL = THANKFUL = minnettar / UNGRATEFUL = nankör" },
      { type: "example", en: "I am grateful for your help.", tr: "Yardımınız için minnettarım." },
      { type: "example", en: "Never be ungrateful!", tr: "Asla nankör olma!" },
      { type: "pattern", text: "PRACTICE = pratik yapmak, pratik / AVOID = kaçınmak / DRUG USE, ALCOHOL USE = uyuşturucu/alkol kullanımı" },
      { type: "example", en: "I will go to London to practice.", tr: "Pratik yapmak için Londra'ya gideceğim." },
      { type: "example", en: "You should avoid drug use.", tr: "Uyuşturucu kullanımından kaçınmalısın." },
      { type: "pattern", text: "QUIT SMOKING / GIVE UP SMOKING = sigarayı bırakmak" },
      { type: "pattern", text: "TEMPORARY = geçici / PERMANENT = kalıcı / TEMPORARILY = geçici olarak" },
      { type: "example", en: "I think he can quit smoking temporarily.", tr: "Bence o sigarayı geçici olarak bırakabilir." },
      { type: "example", en: "We must try to find permanent solutions.", tr: "Kalıcı çözümler bulmaya çalışmalıyız." },
      { type: "pattern", text: "PROVIDING THAT = koşulu ile, şartıyla" },
      { type: "example", en: "You can take my car, providing that you bring it back on time.", tr: "Zamanında geri getirmen şartıyla arabamı alabilirsin." },
      { type: "pattern", text: "OBSESSION = takıntı / BE OBSESSED WITH = takıntılı olmak" },
      { type: "example", en: "You should get rid of some of your obsessions to be successful.", tr: "Başarılı olmak için bazı takıntılarından kurtulmalısın." },
      { type: "example", en: "She's obsessed with cleaning.", tr: "O temizlik takıntılı." },
      { type: "pattern", text: "INTERRUPT = sözünü kesmek" },
      { type: "example", en: "I don't want to interrupt you, but I have to say something.", tr: "Sözünü kesmek istemem ama bir şey söylemeliyim." },
      { type: "pattern", text: "EXHAUSTED = bitkin, aşırı yorgun" },
      { type: "pattern", text: "WORRIED / ANXIOUS = endişeli / IMPATIENT = sabırsız" },
      { type: "example", en: "Don't be anxious! We will handle all.", tr: "Endişeli olma! Her şeyi halledeceğiz." },
      { type: "example", en: "I haven't seen a man as impatient as you.", tr: "Senin kadar sabırsız adam görmedim." },
      { type: "pattern", text: "WILLING / EAGER = istekli / UNWILLING / RELUCTANT = isteksiz" },
      { type: "pattern", text: "HARDWORKING / DILIGENT = çalışkan / DILIGENCE = çalışkanlık / PERSEVERANCE = azim, sebat" },
      { type: "example", en: "This process requires more perseverance.", tr: "Bu süreç daha fazla azim gerektiriyor." },
      { type: "pattern", text: "CANDIDATE / APPLICANT = aday / SCHOLARSHIP = burs" },
      { type: "pattern", text: "APPOINT = görevlendirmek, atamak" },
      { type: "example", en: "We will appoint him as an accountant.", tr: "Biz onu muhasebeci olarak atayacağız." },
      { type: "example", en: "He was appointed as general manager.", tr: "O genel müdür olarak atandı." },
      { type: "pattern", text: "IMMEDIATELY / RIGHT NOW / RIGHT AWAY = hemen, derhal / INTERFERE WITH = karışmak, müdahale etmek" },
      { type: "example", en: "You're right in a sense, but I cannot interfere with this job.", tr: "Bir bakıma haklısın ama ben bu işe karışamam." },
      { type: "pattern", text: "ADAPT = uyum sağlamak / ADAPTATION = uyum" },
      { type: "example", en: "It took her a while to adapt to the new environment.", tr: "Yeni ortama uyum sağlaması biraz zaman aldı." },
      { type: "pattern", text: "COPE WITH = başa çıkmak / MANAGE = idare etmek, başarmak" },
      { type: "example", en: "How do you cope with stress?", tr: "Stresle nasıl başa çıkıyorsun?" },
      { type: "example", en: "We managed to finish on time.", tr: "Zamanında bitirmeyi başardık." },
      { type: "pattern", text: "OVERWHELMED = bunalmış / OVERWHELMING = bunaltıcı, ezici" },
      { type: "example", en: "I feel overwhelmed with all this work.", tr: "Bütün bu işle bunalmış hissediyorum." },
      { type: "pattern", text: "RELIEF = rahatlama / RELIEVED = rahatlamış" },
      { type: "example", en: "I felt a huge relief when I heard the good news.", tr: "İyi haberi duyduğumda büyük bir rahatlama hissettim." },
      { type: "example", en: "She was relieved that the exam was over.", tr: "Sınavın bitmiş olması onu rahatlattı." },
      { type: "pattern", text: "ANXIETY = kaygı / TENSE = gergin / TENSION = gerginlik" },
      { type: "example", en: "The atmosphere in the room was full of tension.", tr: "Odadaki atmosfer gerginlikle doluydu." },
      { type: "pattern", text: "COMFORT = rahatlık, teselli etmek / COMFORTABLE = rahat / UNCOMFORTABLE = rahatsız" },
      { type: "example", en: "I tried to comfort her after the bad news.", tr: "Kötü haberden sonra onu teselli etmeye çalıştım." },
      { type: "example", en: "This chair isn't very comfortable.", tr: "Bu sandalye pek rahat değil." },
      { type: "rule", text: "Son olarak bu dersteki karma kalıpları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "It took him a long time to cope with the anxiety and adapt to his new responsibilities, but eventually he felt relieved.", tr: "Kaygıyla başa çıkması ve yeni sorumluluklarına uyum sağlaması uzun zaman aldı ama sonunda rahatladı." },
      { type: "pattern", text: "REGARDLESS OF = fark etmeksizin, -e bakmaksızın" },
      { type: "example", en: "Regardless of the cost, we need to fix this immediately.", tr: "Maliyete bakmaksızın bunu hemen düzeltmemiz gerekiyor." },
      { type: "pattern", text: "AS OPPOSED TO = -in aksine" },
      { type: "example", en: "He prefers working alone, as opposed to in a team.", tr: "O bir ekipte çalışmanın aksine yalnız çalışmayı tercih ediyor." },
      { type: "pattern", text: "GIVEN THAT = göz önüne alındığında, madem ki" },
      { type: "example", en: "Given that we have limited time, let's focus on the essentials.", tr: "Sınırlı zamanımız olduğu göz önüne alındığında, temel şeylere odaklanalım." },
      { type: "pattern", text: "AS LONG AS = -diği sürece / SO LONG AS = -diği sürece" },
      { type: "example", en: "As long as you're happy, that's all that matters.", tr: "Mutlu olduğun sürece, önemli olan bu." },
      { type: "rule", text: "Bu bağlaçları pekiştiren bir kapanış cümlesi görelim." },
      { type: "example", en: "Regardless of what others think, as long as you believe in yourself, you can achieve anything, given that you're willing to work hard.", tr: "Başkalarının ne düşündüğüne bakmaksızın, kendine inandığın sürece, çok çalışmaya istekli olman şartıyla her şeyi başarabilirsin." },
      { type: "pattern", text: "ON CONDITION THAT = -mesi şartıyla / OTHERWISE = aksi takdirde" },
      { type: "example", en: "I'll lend you the money on condition that you pay it back next week.", tr: "Gelecek hafta geri ödemen şartıyla sana parayı ödünç vereceğim." },
      { type: "pattern", text: "IN CASE = -ihtimaline karşı, ...se diye" },
      { type: "example", en: "Take an umbrella in case it rains.", tr: "Yağmur yağar diye şemsiye al." },
      { type: "pattern", text: "EVEN IF = -se bile / EVEN THOUGH = -mesine rağmen" },
      { type: "example", en: "Even if it rains, we'll still go.", tr: "Yağmur yağsa bile yine de gideceğiz." },
      { type: "pattern", text: "SUPPOSING (THAT) = varsayalım ki, diyelim ki" },
      { type: "example", en: "Supposing that we miss the flight, what should we do?", tr: "Diyelim ki uçağı kaçırdık, ne yapmalıyız?" },
      { type: "rule", text: "Son olarak bu dersteki şart bağlaçlarını içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Even if things don't go as planned, as long as we stay calm and take everything into account, we'll find a solution.", tr: "İşler planlandığı gibi gitmese bile, sakin kaldığımız ve her şeyi hesaba kattığımız sürece bir çözüm bulacağız." },
      { type: "pattern", text: "OTHERWISE = aksi takdirde, yoksa" },
      { type: "example", en: "Hurry up, otherwise we'll be late.", tr: "Acele et, yoksa geç kalacağız." },
      { type: "pattern", text: "ASSUMING THAT = varsayarsak, eğer öyleyse" },
      { type: "example", en: "Assuming that everyone agrees, we can start tomorrow.", tr: "Herkes kabul ediyorsa varsayarsak, yarın başlayabiliriz." },
      { type: "rule", text: "Son olarak bu dersteki bütün şart ve durum bağlaçlarını içeren uzun bir kapanış cümlesi görelim." },
      { type: "example", en: "Supposing that the weather stays good, and assuming everyone shows up on time, the trip should go smoothly; otherwise, we might have to postpone it.", tr: "Hava iyi giderse ve herkes zamanında gelirse gezinin sorunsuz gitmesi lazım; aksi takdirde ertelemek zorunda kalabiliriz." },
      { type: "pattern", text: "ON THE CONDITION THAT = ...şartı ile / SHOULD (IF şeklinde) = eğer ...irse (resmi kullanım)" },
      { type: "example", en: "Should you need any help, don't hesitate to call.", tr: "Yardıma ihtiyacın olursa, aramaktan çekinme." },
    ],
  },
  {
    fileBase: "38_Karma_Kaliplar_5",
    title: "KARMA KALIPLAR - 5",
    blocks: [
      { type: "pattern", text: "OWN = sahip olmak, kendi / OWNER = sahip / FOUNDER = kurucu" },
      { type: "example", en: "My father owns this factory.", tr: "Bu fabrika babamın." },
      { type: "example", en: "Who is the owner of this house?", tr: "Bu evin sahibi kimdir?" },
      { type: "example", en: "Are you founder of this company?", tr: "Bu şirketin kurucusu sen misin?" },
      { type: "pattern", text: "LOYAL = FAITHFUL = sadık / LOYALTY = sadakat / SLAVE = köle / SLAVERY = kölelik" },
      { type: "example", en: "If he leaves this job, he will be free from slavery.", tr: "Eğer bu işten çıkarsa kölelikten kurtulacak." },
      { type: "pattern", text: "DEDICATE = adamak / DEDICATION = özveri, adama" },
      { type: "example", en: "He dedicates his life to cats.", tr: "O hayatını kedilere adadı." },
      { type: "example", en: "You need more dedication to handle this.", tr: "Bunu halletmek için daha fazla özveriye ihtiyacınız var." },
      { type: "pattern", text: "BEYOND = ötesinde" },
      { type: "example", en: "The village you are going to is beyond that mountain.", tr: "Gideceğiniz köy şu dağın ötesindedir." },
      { type: "example", en: "Our reality is beyond their dreams.", tr: "Bizim gerçeklerimiz onların hayallerinin ötesinde." },
      { type: "pattern", text: "ANNOUNCE = duyurmak, açıklamak" },
      { type: "example", en: "The decision has just been announced.", tr: "Karar az önce açıklandı." },
      { type: "pattern", text: "DETAIN = göz altına almak / ARREST = tutuklamak / BE INVOLVED = dahil olmak / DEMONSTRATION = gösteri" },
      { type: "example", en: "Is there anyone who knows why this man was arrested?", tr: "Bu adamın niye tutuklandığını bilen var mı?" },
      { type: "example", en: "They have been detained because they were involved in demonstrations.", tr: "Gösterilere dahil oldukları için gözaltına alındılar." },
      { type: "pattern", text: "RETAIN = kaybetmemek, tutmak" },
      { type: "example", en: "I did everything to retain her.", tr: "Onu kaybetmemek için her şeyi yaptım." },
      { type: "pattern", text: "BENEFIT = fayda, faydalanmak / BENEFICIAL = HELPFUL = USEFUL = yararlı" },
      { type: "example", en: "You should benefit from his experience.", tr: "Onun deneyiminden yararlanmalısın." },
      { type: "example", en: "The project that we gave up would not be beneficial for us.", tr: "Vazgeçtiğimiz projenin bize yararı olmayacaktı." },
      { type: "pattern", text: "TAKE ADVANTAGE OF = faydalanmak, istismar etmek / GOODWILL = iyi niyet" },
      { type: "example", en: "We shouldn't have taken advantage of her goodwill.", tr: "Onun iyi niyetinden yararlanmamalıydık." },
      { type: "pattern", text: "PRINCIPLE = ilke / IN PRINCIPLE = prensipte / PLEASANT = keyifli, hoş" },
      { type: "example", en: "We agree in principle.", tr: "Prensipte anlaştık." },
      { type: "example", en: "It was very pleasant for us.", tr: "Bizim için çok keyifliydi." },
      { type: "pattern", text: "BREATHE = nefes almak / BREATH = nefes / OUT OF BREATH = nefes nefese" },
      { type: "example", en: "Take a deep breath and relax!", tr: "Derin bir nefes al ve rahatla!" },
      { type: "example", en: "Why are you out of breath?", tr: "Neden nefes nefesesin?" },
      { type: "pattern", text: "CONSIDER = göz önünde bulundurmak / PROS AND CONS = artılar eksiler" },
      { type: "example", en: "We must consider the pros and cons.", tr: "Artıları ve eksileri göz önünde bulundurmalıyız." },
      { type: "pattern", text: "HABIT = alışkanlık / MAKE A HABIT OF = alışkanlık haline getirmek / FULFILL = yerine getirmek / TASK/DUTY/MISSION = görev" },
      { type: "example", en: "They have made a habit of being late.", tr: "Onlar gecikmeyi alışkanlık haline getirdiler." },
      { type: "example", en: "I will fulfill all my duties.", tr: "Tüm görevlerimi yerine getireceğim." },
      { type: "pattern", text: "TAKE A WALK / GO FOR A WALK = yürüyüşe çıkmak / ON BEHALF OF = adına / CONFIDENT = kendinden emin" },
      { type: "example", en: "I'm calling you on behalf of my boss.", tr: "Sizi patronum adına arıyorum." },
      { type: "rule", text: "WHETHER / IF = ... olup olmadığı(nı)." },
      { type: "example", en: "I don't know whether she is at home.", tr: "Onun evde olup olmadığını bilmiyorum." },
      { type: "example", en: "I am not sure if they are right.", tr: "Onların haklı olup olmadığına emin değilim." },
      { type: "pattern", text: "USE UP = tüketmek, tamamını bitirmek / CAUTIOUS = tedbirli, dikkatli" },
      { type: "example", en: "They used up the sugar in the house.", tr: "Onlar evdeki şekeri tükettiler." },
      { type: "example", en: "We have to be more cautious not to regret.", tr: "Pişman olmamak için daha tedbirli olmalıyız." },
      { type: "pattern", text: "GENEROSITY = cömertlik / KINDNESS = nezaket, iyilik" },
      { type: "example", en: "Thank you for your kindness.", tr: "Nezaketiniz için teşekkür ederim." },
      { type: "pattern", text: "SACRIFICE = fedakarlık, fedakarlık yapmak" },
      { type: "example", en: "Parents make a lot of sacrifices for their children.", tr: "Ebeveynler çocukları için birçok fedakarlık yapar." },
      { type: "pattern", text: "COMMIT = üstlenmek, kendini adamak / COMMITMENT = bağlılık, kendini adama" },
      { type: "example", en: "She is fully committed to this project.", tr: "O bu projeye tamamen kendini adamış durumda." },
      { type: "pattern", text: "ACHIEVEMENT = başarı / ACCOMPLISH = başarmak, tamamlamak" },
      { type: "example", en: "This is a great achievement for the whole team.", tr: "Bu bütün ekip için büyük bir başarı." },
      { type: "example", en: "We accomplished everything we set out to do.", tr: "Yapmaya niyetlendiğimiz her şeyi başardık." },
      { type: "pattern", text: "STRUGGLE = mücadele etmek, mücadele / OVERCOME = üstesinden gelmek" },
      { type: "example", en: "She struggled a lot before achieving success.", tr: "Başarıya ulaşmadan önce çok mücadele etti." },
      { type: "example", en: "We managed to overcome all the obstacles.", tr: "Bütün engellerin üstesinden gelmeyi başardık." },
      { type: "rule", text: "Son olarak bu dersteki karma kalıpları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Despite all the sacrifices, their commitment and perseverance finally paid off, and they accomplished their goal.", tr: "Bütün fedakarlıklara rağmen, bağlılıkları ve azimleri sonunda karşılığını verdi ve hedeflerine ulaştılar." },
      { type: "pattern", text: "IN FAVOR OF = lehine, tarafında" },
      { type: "example", en: "Most people voted in favor of the new law.", tr: "Çoğu insan yeni yasanın lehine oy verdi." },
      { type: "pattern", text: "OPPOSE = karşı çıkmak / OPPOSITION = muhalefet, karşı çıkma" },
      { type: "example", en: "Some members opposed the decision.", tr: "Bazı üyeler karara karşı çıktı." },
      { type: "pattern", text: "COMPROMISE = uzlaşma, uzlaşmak / NEGOTIATE = müzakere etmek" },
      { type: "example", en: "Both sides had to compromise to reach a deal.", tr: "Her iki taraf da bir anlaşmaya varmak için uzlaşmak zorunda kaldı." },
      { type: "pattern", text: "MUTUAL = karşılıklı / MUTUALLY = karşılıklı olarak" },
      { type: "example", en: "They reached a mutually beneficial agreement.", tr: "Karşılıklı olarak faydalı bir anlaşmaya vardılar." },
      { type: "pattern", text: "PERSPECTIVE = bakış açısı / VIEWPOINT = görüş açısı" },
      { type: "example", en: "From my perspective, this is the best solution.", tr: "Benim bakış açımdan, bu en iyi çözüm." },
      { type: "rule", text: "Son olarak bu dersteki karma kalıpları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Although they had different perspectives, both sides were willing to compromise, and eventually reached a mutually beneficial agreement.", tr: "Farklı bakış açılarına sahip olsalar da her iki taraf da uzlaşmaya istekliydi ve sonunda karşılıklı olarak faydalı bir anlaşmaya vardılar." },
      { type: "pattern", text: "CONSENSUS = fikir birliği / UNANIMOUS = oybirliğiyle" },
      { type: "example", en: "The committee reached a consensus after a long debate.", tr: "Komite uzun bir tartışmadan sonra fikir birliğine vardı." },
      { type: "pattern", text: "DISPUTE = anlaşmazlık / DISAGREEMENT = fikir ayrılığı" },
      { type: "example", en: "There was a dispute over the contract terms.", tr: "Sözleşme şartları üzerine bir anlaşmazlık vardı." },
      { type: "pattern", text: "SETTLE A DISPUTE = anlaşmazlığı çözmek / MEDIATE = arabuluculuk yapmak" },
      { type: "example", en: "A lawyer helped settle the dispute.", tr: "Bir avukat anlaşmazlığı çözmeye yardım etti." },
      { type: "pattern", text: "STANDPOINT = bakış açısı / FROM A BUSINESS STANDPOINT = iş açısından" },
      { type: "example", en: "From a business standpoint, this decision makes sense.", tr: "İş açısından, bu karar mantıklı." },
      { type: "rule", text: "Son olarak bu dersteki müzakere ve fikir kalıplarını içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "From a business standpoint, mediating the dispute and reaching a consensus was far more beneficial than continuing the disagreement.", tr: "İş açısından, anlaşmazlıkta arabuluculuk yapmak ve fikir birliğine varmak, fikir ayrılığını sürdürmekten çok daha faydalıydı." },
      { type: "pattern", text: "OBJECTION = itiraz / RAISE AN OBJECTION = itirazda bulunmak" },
      { type: "example", en: "Nobody raised an objection to the plan.", tr: "Kimse plana itirazda bulunmadı." },
      { type: "pattern", text: "ENDORSE = onaylamak, desteklemek / BACK UP = desteklemek" },
      { type: "example", en: "The board endorsed the new strategy.", tr: "Yönetim kurulu yeni stratejiyi onayladı." },
      { type: "pattern", text: "WITHDRAW = geri çekmek / RETRACT = geri almak (sözü)" },
      { type: "example", en: "He withdrew his complaint after the apology.", tr: "Özürden sonra şikayetini geri çekti." },
      { type: "pattern", text: "ARBITRATION = tahkim / SETTLEMENT = uzlaşma, çözüm" },
      { type: "example", en: "The case was resolved through arbitration.", tr: "Dava tahkim yoluyla çözüldü." },
      { type: "rule", text: "Son olarak bu dersteki müzakere kalıplarını içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "After raising several objections, the two parties finally reached a settlement through arbitration, and both sides endorsed the final agreement.", tr: "Birkaç itirazda bulunduktan sonra, iki taraf sonunda tahkim yoluyla bir uzlaşmaya vardı ve her iki taraf da son anlaşmayı onayladı." },
    ],
  },
  {
    fileBase: "39_Karma_Kaliplar_6",
    title: "KARMA KALIPLAR - 6",
    blocks: [
      { type: "pattern", text: "RUN INTO = tesadüfen karşılaşmak, rastgelmek" },
      { type: "example", en: "We ran into each other at the entrance of the museum.", tr: "Müzenin girişinde tesadüfen karşılaştık." },
      { type: "pattern", text: "SOLD-OUT = tükenmiş, bitmiş / TURN DOWN = reddetmek, sesi kısmak" },
      { type: "example", en: "Unfortunately, all the tickets are sold-out.", tr: "Maalesef tüm biletler tükendi." },
      { type: "example", en: "Turn the music down!", tr: "Müziğin sesini kıs!" },
      { type: "rule", text: "MAY'in iki kullanımı vardır. MAY-1: CAN gibidir ama izin, ihtimal, olabilirlik anlamı taşır (CAN ise daha çok yetenek anlamındadır)." },
      { type: "example", en: "It is cloudy, so it may rain.", tr: "Bulutlu, bu yüzden yağmur yağabilir." },
      { type: "example", en: "If we have more time, we may start today.", tr: "Daha fazla zamanımız olursa bugün başlayabiliriz." },
      { type: "rule", text: "MAY-2: Kibar sorularda kullanılır; COULD'a göre farkı, genellikle I/WE özneleriyle kullanılmasıdır." },
      { type: "example", en: "May I come in?", tr: "Girebilir miyim?" },
      { type: "example", en: "Excuse me! May I get information?", tr: "Affedersiniz! Bilgi alabilir miyim?" },
      { type: "example", en: "May I have some orange juice?", tr: "Biraz portakal suyu alabilir miyim?" },
      { type: "pattern", text: "VIOLATE = ihlal etmek / BAN = PROHIBITION = yasak (isim)" },
      { type: "example", en: "I don't want to violate any rules.", tr: "Herhangi bir kuralı ihlal etmek istemiyorum." },
      { type: "example", en: "The bans were violated.", tr: "Yasaklar ihlal edildi." },
      { type: "example", en: "The bans were lifted!", tr: "Yasaklar kalktı!" },
      { type: "pattern", text: "FORBID-FORBADE-FORBIDDEN = yasaklamak / PROHIBITED GOODS = yasaklanmış ürünler" },
      { type: "example", en: "His mother forbade him to go out.", tr: "Annesi onun dışarı çıkmasını yasakladı." },
      { type: "example", en: "It is forbidden to smoke.", tr: "Sigara içmek yasaktır." },
      { type: "pattern", text: "SUSTAINABLE = sürdürülebilir" },
      { type: "example", en: "We have given up, because this process isn't sustainable.", tr: "Bu süreç sürdürülebilir olmadığından vazgeçtik." },
      { type: "pattern", text: "ROOMMATE = oda arkadaşı / COLLEAGUE = CO-WORKER = iş arkadaşı" },
      { type: "example", en: "Do you have a lot of colleagues?", tr: "Çok iş arkadaşın var mı?" },
      { type: "example", en: "Where is your roommate from?", tr: "Oda arkadaşın nereli?" },
      { type: "pattern", text: "THRIFTY = tutumlu / POCKET = cep" },
      { type: "example", en: "I can say that we have to be more thrifty.", tr: "Daha tutumlu olmamız gerektiğini söyleyebilirim." },
      { type: "example", en: "How much do you have in your pocket?", tr: "Cebinde ne kadar var?" },
      { type: "pattern", text: "PUBLISH = yayınlamak, basmak / MAGAZINE = dergi" },
      { type: "example", en: "This magazine is published twice a year.", tr: "Bu dergi yılda iki kere yayınlanır." },
      { type: "example", en: "Who decided to publish this book?", tr: "Kim bu kitabı yayınlamaya karar verdi?" },
      { type: "pattern", text: "VARIETY / DIVERSITY = çeşitlilik / RANGE OF FOODS = yiyecek çeşidi" },
      { type: "pattern", text: "DISCRIMINATION = ayrım / DISCRIMINATE BETWEEN = ayrım yapmak" },
      { type: "example", en: "I can't discriminate between them, they are both precious to me.", tr: "Onlar arasında ayrım yapamam, ikisi de benim için kıymetli." },
      { type: "pattern", text: "ABUSE = suistimal etmek, kötüye kullanmak" },
      { type: "example", en: "You shouldn't abuse her goodwill.", tr: "Onun iyi niyetini suistimal etmemelisin." },
      { type: "pattern", text: "SEE OFF = uğurlamak, yolcu etmek" },
      { type: "example", en: "Everyone is at the airport to see him off.", tr: "Herkes onu uğurlamak için havalimanında." },
      { type: "pattern", text: "COINCIDENCE = tesadüf / COINCIDENTAL = tesadüfi / COINCIDENTALLY = tesadüfen" },
      { type: "example", en: "This can't be a coincidence.", tr: "Bu bir tesadüf olamaz." },
      { type: "example", en: "I cannot accept the coincidental success.", tr: "Tesadüfi başarıyı kabul edemem." },
      { type: "pattern", text: "VARIOUS = çeşitli, farklı / PROPERLY = adam akıllı, doğru düzgün" },
      { type: "example", en: "We received various offers, but we turned down all of them.", tr: "Çeşitli teklifler aldık ama hepsini geri çevirdik." },
      { type: "example", en: "He couldn't properly express himself.", tr: "O kendisini adam akıllı ifade edemedi." },
      { type: "pattern", text: "GET ALONG WITH = iyi geçinmek / GET OVER = atlatmak (hastalık, üzüntü)" },
      { type: "example", en: "Do you get along with your neighbors?", tr: "Komşularınla iyi geçinir misin?" },
      { type: "example", en: "It took her weeks to get over the flu.", tr: "Gribi atlatması haftalar sürdü." },
      { type: "pattern", text: "CARRY ON = devam etmek / GIVE IN = teslim olmak, pes etmek" },
      { type: "example", en: "Please carry on with your work.", tr: "Lütfen işinize devam edin." },
      { type: "example", en: "She never gives in, no matter how hard it gets.", tr: "Ne kadar zorlaşırsa zorlaşsın asla pes etmez." },
      { type: "pattern", text: "STAND OUT = öne çıkmak / STAND FOR = temsil etmek, anlamına gelmek" },
      { type: "example", en: "Her work really stands out among the others.", tr: "Onun çalışması diğerleri arasında gerçekten öne çıkıyor." },
      { type: "example", en: "What does this abbreviation stand for?", tr: "Bu kısaltma neyin kısaltması?" },
      { type: "pattern", text: "BRING ABOUT = neden olmak, meydana getirmek / RESULT IN = sonuçlanmak" },
      { type: "example", en: "The new policy brought about many changes.", tr: "Yeni politika birçok değişikliğe neden oldu." },
      { type: "example", en: "The negotiations resulted in a new agreement.", tr: "Müzakereler yeni bir anlaşmayla sonuçlandı." },
      { type: "pattern", text: "SET ASIDE = bir kenara koymak, ayırmak (zaman/para)" },
      { type: "example", en: "We should set aside some money for emergencies.", tr: "Acil durumlar için biraz para ayırmalıyız." },
      { type: "rule", text: "Son olarak bu dersteki phrasal verb'leri ve karma kalıpları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Although the new regulations brought about a lot of confusion at first, the team managed to get along, carry on with their work, and eventually overcome the challenges.", tr: "Yeni düzenlemeler başta çok kafa karışıklığına neden olsa da, ekip iyi geçinmeyi, işlerine devam etmeyi ve sonunda zorlukların üstesinden gelmeyi başardı." },
      { type: "pattern", text: "TAKE INTO ACCOUNT = hesaba katmak / ACCOUNT FOR = açıklamak, sebep olmak" },
      { type: "example", en: "We need to take into account the extra costs.", tr: "Ek maliyetleri hesaba katmamız gerekiyor." },
      { type: "example", en: "How do you account for this difference?", tr: "Bu farkı nasıl açıklıyorsun?" },
      { type: "pattern", text: "RULE OUT = elemek, göz ardı etmek / TAKE INTO CONSIDERATION = göz önünde bulundurmak" },
      { type: "example", en: "We can't rule out the possibility of a delay.", tr: "Bir gecikme olasılığını göz ardı edemeyiz." },
      { type: "pattern", text: "MAKE UP FOR = telafi etmek / COMPENSATE = tazmin etmek, telafi etmek" },
      { type: "example", en: "He tried to make up for his mistake.", tr: "Hatasını telafi etmeye çalıştı." },
      { type: "example", en: "The company compensated us for the delay.", tr: "Şirket gecikme için bizi tazmin etti." },
      { type: "pattern", text: "LIVE UP TO = beklentileri karşılamak / FALL SHORT OF = yetersiz kalmak, ulaşamamak" },
      { type: "example", en: "The movie didn't live up to my expectations.", tr: "Film beklentilerimi karşılamadı." },
      { type: "example", en: "The results fell short of our target.", tr: "Sonuçlar hedefimize ulaşamadı." },
      { type: "rule", text: "Son olarak bu dersteki karma kalıpları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Taking into account all the factors, and despite falling short of some targets, the team tried to make up for it by working overtime.", tr: "Bütün faktörleri hesaba katarak, bazı hedeflere ulaşamamalarına rağmen, ekip fazla mesai yaparak bunu telafi etmeye çalıştı." },
      { type: "pattern", text: "PRIORITIZE = önceliklendirmek / TOP PRIORITY = en yüksek öncelik" },
      { type: "example", en: "Safety should always be our top priority.", tr: "Güvenlik her zaman en yüksek önceliğimiz olmalı." },
      { type: "pattern", text: "STREAMLINE = basitleştirmek, sadeleştirmek / OPTIMIZE = optimize etmek" },
      { type: "example", en: "We need to streamline this process.", tr: "Bu süreci basitleştirmemiz gerekiyor." },
      { type: "pattern", text: "IMPLEMENT = uygulamaya koymak / IMPLEMENTATION = uygulama" },
      { type: "example", en: "The new policy will be implemented next month.", tr: "Yeni politika gelecek ay uygulamaya konacak." },
      { type: "pattern", text: "OUTLINE = ana hatlarını çizmek / SUMMARIZE = özetlemek" },
      { type: "example", en: "Can you outline the main points of the proposal?", tr: "Teklifin ana noktalarını özetleyebilir misin?" },
      { type: "rule", text: "Son olarak bu dersteki iş kalıplarını içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Before implementing the new system, we should streamline the process and outline all the necessary steps.", tr: "Yeni sistemi uygulamaya koymadan önce, süreci basitleştirmeli ve gerekli bütün adımların ana hatlarını çizmeliyiz." },
      { type: "pattern", text: "ALLOCATE = tahsis etmek, ayırmak / DISTRIBUTE = dağıtmak" },
      { type: "example", en: "We need to allocate more resources to this department.", tr: "Bu departmana daha fazla kaynak tahsis etmemiz gerekiyor." },
      { type: "pattern", text: "MONITOR = izlemek, denetlemek / EVALUATE = değerlendirmek" },
      { type: "example", en: "We monitor progress on a weekly basis.", tr: "İlerlemeyi haftalık olarak izliyoruz." },
      { type: "pattern", text: "DELEGATE TASKS = görevleri devretmek / SUPERVISE = denetlemek" },
      { type: "example", en: "A good manager knows how to delegate tasks.", tr: "İyi bir müdür görevleri nasıl devredeceğini bilir." },
      { type: "pattern", text: "FEASIBLE = uygulanabilir / VIABLE = uygulanabilir, geçerli" },
      { type: "example", en: "Is this plan feasible within our budget?", tr: "Bu plan bütçemiz dahilinde uygulanabilir mi?" },
      { type: "rule", text: "Son olarak bu dersteki iş yönetimi kalıplarını içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "A feasible plan requires allocating resources wisely, monitoring progress closely, and delegating tasks to the right people.", tr: "Uygulanabilir bir plan, kaynakları akıllıca tahsis etmeyi, ilerlemeyi yakından izlemeyi ve görevleri doğru kişilere devretmeyi gerektirir." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
