import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "13_Karsilastirma_Kaliplari",
    title: "KARŞILAŞTIRMA KALIPLARI (COMPARATIVE - SUPERLATIVE)",
    blocks: [
      { type: "rule", text: "Tek heceli sıfatlarda karşılaştırma için sıfata -ER, en üstünlük için THE + sıfat-EST eklenir." },
      { type: "pattern", text: "BIG - BIGGER - THE BIGGEST        SMALL - SMALLER - THE SMALLEST" },
      { type: "pattern", text: "LONG - LONGER - THE LONGEST        SHORT - SHORTER - THE SHORTEST" },
      { type: "pattern", text: "OLD - OLDER - THE OLDEST        YOUNG - YOUNGER - THE YOUNGEST" },
      { type: "pattern", text: "TALL - TALLER - THE TALLEST        STRONG - STRONGER - THE STRONGEST" },
      { type: "pattern", text: "WEAK - WEAKER - THE WEAKEST        FAT - FATTER - THE FATTEST" },
      { type: "pattern", text: "THIN - THINNER - THE THINNEST        CHEAP - CHEAPER - THE CHEAPEST" },
      { type: "example", en: "This bag is bigger than that one.", tr: "Bu çanta ondan daha büyük." },
      { type: "example", en: "He is the tallest boy in his class.", tr: "O sınıfındaki en uzun çocuk." },
      { type: "rule", text: "Çok heceli (uzun) sıfatlarda -ER/-EST eklenmez; bunun yerine MORE ve THE MOST kullanılır." },
      { type: "pattern", text: "EXPENSIVE - MORE EXPENSIVE - THE MOST EXPENSIVE" },
      { type: "pattern", text: "BEAUTIFUL - MORE BEAUTIFUL - THE MOST BEAUTIFUL" },
      { type: "pattern", text: "HANDSOME - MORE HANDSOME - THE MOST HANDSOME" },
      { type: "pattern", text: "SUCCESSFUL - MORE SUCCESSFUL - THE MOST SUCCESSFUL" },
      { type: "rule", text: "Bazı sıfatlar düzensizdir ve kendine özgü bir karşılaştırma hâli vardır." },
      { type: "pattern", text: "GOOD - BETTER - THE BEST        BAD - WORSE - THE WORST" },
      { type: "pattern", text: "CLOSE - CLOSER - THE CLOSEST        FAR - FARTHER(FURTHER) - THE FARTHEST(FURTHEST)" },
      { type: "rule", text: "İki şeyi karşılaştırırken THAN (-den/-dan) kullanılır." },
      { type: "example", en: "This car is more expensive than the other one.", tr: "Bu araba diğerinden daha pahalı." },
      { type: "example", en: "I am taller than him.", tr: "Ben ondan daha uzunum." },
      { type: "example", en: "This restaurant is closer than the pharmacy.", tr: "Bu restoran eczaneden daha yakın." },
      { type: "example", en: "This river is longer than the other one.", tr: "Bu nehir diğerinden daha uzun." },
      { type: "rule", text: "En üstünlük (superlative) hâlinde THE mutlaka kullanılır." },
      { type: "example", en: "She is the most successful student in this class.", tr: "O bu sınıftaki en başarılı öğrenci." },
      { type: "example", en: "He is the most patient man I know.", tr: "O tanıdığım en sabırlı adam." },
      { type: "example", en: "This room is the biggest in the house.", tr: "Bu oda evdeki en büyük oda." },
      { type: "rule", text: "OTHER / THE OTHER ONE gibi kalıplar da karşılaştırmalarda sıkça kullanılır." },
      { type: "example", en: "I like this one more than the other one.", tr: "Bunu diğerinden daha çok severim." },
      { type: "rule", text: "İyelik zamirleri: MINE (benimki), YOURS (seninki), HIS (onunki-erkek), HERS (onunki-kız), OURS (bizimki), YOURS (sizinki), THEIRS (onlarınki)." },
      { type: "example", en: "This bag is cheaper than mine.", tr: "Bu çanta benimkinden daha ucuz." },
      { type: "example", en: "Our team is better than theirs.", tr: "Bizim takımımız onlarınkinden daha iyi." },
      { type: "example", en: "Her son is younger than yours.", tr: "Onun oğlu seninkinden daha genç." },
      { type: "example", en: "My friend is more handsome than hers.", tr: "Benim arkadaşım onunkinden daha yakışıklı." },
      { type: "rule", text: "Eşitlik karşılaştırması için AS + sıfat + AS (kadar) kullanılır. Olumsuzda NOT AS/SO + sıfat + AS kullanılır." },
      { type: "pattern", text: "AS + sıfat + AS = ... kadar        NOT AS/SO + sıfat + AS = ... kadar değil" },
      { type: "example", en: "She is as tall as her brother.", tr: "O kardeşi kadar uzun." },
      { type: "example", en: "This book isn't as interesting as the other one.", tr: "Bu kitap diğeri kadar ilginç değil." },
      { type: "example", en: "He is as strong as a bull.", tr: "O boğa kadar güçlü." },
      { type: "example", en: "This test isn't as difficult as the last one.", tr: "Bu sınav sonuncusu kadar zor değil." },
      { type: "rule", text: "Kısaltmalar için THE SAME AS (aynısı) kalıbı da eşitlik anlatımında kullanılabilir." },
      { type: "example", en: "Her dress is the same as mine.", tr: "Onun elbisesi benimkiyle aynı." },
      { type: "rule", text: "Fazlalık/azlık karşılaştırması için sıfatın önüne LESS, en azlık için THE LEAST getirilir; bu, MORE/THE MOST'un tam tersidir." },
      { type: "pattern", text: "LESS + sıfat + THAN = ...den daha az        THE LEAST + sıfat = en az ..." },
      { type: "example", en: "This exercise is less difficult than the previous one.", tr: "Bu alıştırma öncekinden daha az zor." },
      { type: "example", en: "This is the least expensive option.", tr: "Bu en az pahalı seçenek." },
      { type: "rule", text: "Çift karşılaştırma (double comparative) yapısı, bir şeyin sürekli artan/azalan bir durumunu anlatır: sıfat-ER and sıfat-ER, veya MORE and MORE + sıfat." },
      { type: "pattern", text: "-ER and -ER / MORE and MORE = giderek daha ..." },
      { type: "example", en: "The weather is getting colder and colder.", tr: "Hava giderek soğuyor." },
      { type: "example", en: "This subject is becoming more and more difficult.", tr: "Bu konu giderek daha zor hâle geliyor." },
      { type: "rule", text: "Orantılı karşılaştırma (proportional comparative) için THE + karşılaştırma, THE + karşılaştırma kalıbı kullanılır: bir şey arttıkça diğeri de artar/azalır." },
      { type: "pattern", text: "THE + comparative, THE + comparative = ne kadar ... o kadar ..." },
      { type: "example", en: "The more you practice, the better you get.", tr: "Ne kadar çok pratik yaparsan, o kadar iyi olursun." },
      { type: "example", en: "The sooner we leave, the earlier we arrive.", tr: "Ne kadar erken ayrılırsak, o kadar erken varırız." },
      { type: "rule", text: "Sık yapılan hatalardan biri, çok heceli sıfatlarda hem -ER hem MORE'u birlikte kullanmaktır; bu yanlıştır. Sadece biri kullanılmalıdır." },
      { type: "example", en: "This is more beautiful than that. (doğru) — NOT: more beautifuller", tr: "Bu ondan daha güzel. — Yanlış kullanım: more beautifuller" },
      { type: "rule", text: "Şimdi bu kalıpları günlük hayattan daha fazla örnekle pekiştirelim." },
      { type: "example", en: "This laptop is lighter than my old one.", tr: "Bu dizüstü bilgisayar eskisinden daha hafif." },
      { type: "example", en: "Istanbul is more crowded than Ankara.", tr: "İstanbul, Ankara'dan daha kalabalık." },
      { type: "example", en: "He is the most intelligent student in the school.", tr: "O okuldaki en zeki öğrenci." },
      { type: "example", en: "This is the worst movie I've ever seen.", tr: "Bu şimdiye kadar izlediğim en kötü film." },
      { type: "example", en: "My new job is better than my old one.", tr: "Yeni işim eskisinden daha iyi." },
      { type: "example", en: "This is the best restaurant in town.", tr: "Bu şehirdeki en iyi restoran." },
      { type: "example", en: "Traffic is worse in the morning than in the evening.", tr: "Trafik sabahları akşamdan daha kötü." },
      { type: "example", en: "She works harder than everyone else in the office.", tr: "O ofisteki herkesten daha çok çalışıyor." },
      { type: "rule", text: "Son olarak, karşılaştırma kalıplarını pekiştiren bir özet tablo görelim." },
      { type: "pattern", text: "Kısa sıfat: -ER / THE -EST   |   Uzun sıfat: MORE / THE MOST   |   Düzensiz: kendine özgü   |   Eşitlik: AS...AS   |   Azlık: LESS / THE LEAST" },
      { type: "rule", text: "İki heceli bazı sıfatlar hem -ER/-EST hem de MORE/THE MOST alabilir; bu tür sıfatlar genellikle -Y, -LE, -OW, -ER ile biter." },
      { type: "pattern", text: "HAPPY - HAPPIER - THE HAPPIEST        SIMPLE - SIMPLER - THE SIMPLEST" },
      { type: "pattern", text: "NARROW - NARROWER - THE NARROWEST        CLEVER - CLEVERER - THE CLEVEREST" },
      { type: "example", en: "She looks happier than yesterday.", tr: "O dünkünden daha mutlu görünüyor." },
      { type: "example", en: "This explanation is simpler than the previous one.", tr: "Bu açıklama öncekinden daha basit." },
      { type: "rule", text: "-Y ile biten sıfatlarda -ER/-EST eklenirken Y harfi I'ya döner: EASY-EASIER, BUSY-BUSIER, HEALTHY-HEALTHIER." },
      { type: "example", en: "This job is busier than my last one.", tr: "Bu iş bir öncekinden daha yoğun." },
      { type: "example", en: "Fruit is healthier than fast food.", tr: "Meyve fast food'dan daha sağlıklı." },
      { type: "rule", text: "Tek heceli, tek ünlü + tek ünsüzle biten sıfatlarda son ünsüz ikiye katlanır: BIG-BIGGER, HOT-HOTTER, THIN-THINNER, FAT-FATTER." },
      { type: "example", en: "It's hotter today than yesterday.", tr: "Bugün dünkünden daha sıcak." },
      { type: "example", en: "This soup is thinner than I expected.", tr: "Bu çorba beklediğimden daha sulu." },
      { type: "rule", text: "Karşılaştırma kalıpları özellikle alışveriş, seyahat ve günlük tercihler hakkında konuşurken çok işlevseldir." },
      { type: "example", en: "This hotel is more comfortable than the one we stayed at last year.", tr: "Bu otel geçen yıl kaldığımızdan daha rahat." },
      { type: "example", en: "The blue shirt is cheaper than the white one.", tr: "Mavi gömlek beyazdan daha ucuz." },
      { type: "example", en: "Which one is more convenient for you, morning or evening?", tr: "Sabah mı akşam mı senin için daha uygun?" },
      { type: "example", en: "This route is shorter than the other one.", tr: "Bu güzergah diğerinden daha kısa." },
      { type: "rule", text: "MUCH ve A LOT, karşılaştırma sıfatlarının önüne gelerek farkın büyüklüğünü vurgular: MUCH BIGGER (çok daha büyük), A LOT CHEAPER (çok daha ucuz)." },
      { type: "example", en: "This phone is much better than my old one.", tr: "Bu telefon eskisinden çok daha iyi." },
      { type: "example", en: "Today's traffic is a lot worse than usual.", tr: "Bugünkü trafik her zamankinden çok daha kötü." },
      { type: "rule", text: "A BIT ve SLIGHTLY ise küçük bir farkı vurgulamak için kullanılır: A BIT MORE EXPENSIVE (biraz daha pahalı)." },
      { type: "example", en: "This one is a bit more expensive, but it's better quality.", tr: "Bu biraz daha pahalı ama kalitesi daha iyi." },
      { type: "example", en: "She is slightly taller than me.", tr: "O benden biraz daha uzun." },
    ],
  },
  {
    fileBase: "14_Aylar_ve_Gunluk_Kaliplar",
    title: "AYLAR VE GÜNLÜK KALIPLAR",
    blocks: [
      { type: "rule", text: "Aylar: JANUARY, FEBRUARY, MARCH, APRIL, MAY, JUNE, JULY, AUGUST, SEPTEMBER, OCTOBER, NOVEMBER, DECEMBER. Aylarda \"IN\" edatı kullanılır." },
      { type: "example", en: "My birthday is in June.", tr: "Doğum günüm Haziran'da." },
      { type: "example", en: "We usually go on holiday in August.", tr: "Genellikle Ağustos'ta tatile gideriz." },
      { type: "rule", text: "Bazı sıfatların MAKE ile fiil hâli (birine bir duygu yaşatmak): MAKE TIRED (yormak), MAKE ANGRY (kızdırmak), MAKE SAD (üzmek), MAKE EXCITED (heyecanlandırmak), MAKE BORED (sıkmak), MAKE WET (ıslatmak)." },
      { type: "example", en: "Don't make me bored!", tr: "Beni sıkma!" },
      { type: "example", en: "The rain made people wet.", tr: "Yağmur insanları ıslattı." },
      { type: "example", en: "We don't want to make him sad.", tr: "Onu üzmek istemiyoruz." },
      { type: "pattern", text: "EARN MONEY / MAKE MONEY = para kazanmak" },
      { type: "example", en: "You should make more money.", tr: "Daha fazla para kazanmalısın." },
      { type: "pattern", text: "SAVE (MONEY) = para biriktirmek / SAVINGS = birikim" },
      { type: "example", en: "His savings aren't enough for this house.", tr: "Onun birikimi bu ev için yeterli değil." },
      { type: "example", en: "If you want to buy this car, you must save more money.", tr: "Bu arabayı almak istiyorsan daha fazla para biriktirmelisin." },
      { type: "rule", text: "Günlük selamlaşma kalıpları: HELLO / HI (merhaba), WELCOME (hoş geldin), HOW ARE YOU? (nasılsın?), THANK YOU / THANKS (teşekkürler), YOU'RE WELCOME! / NOT AT ALL! (rica ederim!), GOODBYE (hoşça kal), TAKE CARE! (kendine iyi bak!), SEE YOU LATER/SOON! (görüşürüz!)." },
      { type: "example", en: "See you next week!", tr: "Gelecek hafta görüşürüz!" },
      { type: "example", en: "Thank you for your help! You're welcome!", tr: "Yardımın için teşekkürler! Rica ederim!" },
      { type: "pattern", text: "CATCH = yakalamak, yetişmek" },
      { type: "example", en: "You should catch the first train.", tr: "İlk trene yetişmelisin." },
      { type: "example", en: "We have to catch them before they leave.", tr: "Onlar ayrılmadan önce onlara yetişmeliyiz." },
      { type: "pattern", text: "CATCH A COLD = üşütmek, nezle olmak" },
      { type: "example", en: "If you don't want to catch a cold, you need some precautions.", tr: "Üşütmek istemiyorsan bazı tedbirler almalısın." },
      { type: "rule", text: "Ulaşım araçları: BUS, TRAIN, PLANE, CAR, BIKE, TRAM, METRO/SUBWAY/TUBE. Ulaşım araçlarıyla \"BY\" edatı kullanılır." },
      { type: "example", en: "We will go there by bus.", tr: "Oraya otobüsle gideceğiz." },
      { type: "example", en: "You can come here by bike.", tr: "Buraya bisikletle gelebilirsin." },
      { type: "pattern", text: "ARRIVE = varmak / EASY = kolay / EASILY = kolayca" },
      { type: "example", en: "How can we arrive there?", tr: "Oraya nasıl varabiliriz?" },
      { type: "example", en: "You can easily arrive there by subway.", tr: "Oraya metroyla kolayca ulaşabilirsin." },
      { type: "pattern", text: "WARN = uyarmak / WARNING = uyarı / HEAR = duymak" },
      { type: "example", en: "Didn't you hear the warning?", tr: "Uyarıyı duymadın mı?" },
      { type: "rule", text: "TIME (kez, kere) - MANY TIMES = defalarca, birçok kez." },
      { type: "example", en: "We warned them many times, but they don't care about it.", tr: "Onları defalarca uyardık ama umursamıyorlar." },
      { type: "rule", text: "Haftanın günleri: MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY. Günlerde de \"ON\" edatı kullanılır." },
      { type: "example", en: "I have an exam on Monday.", tr: "Pazartesi günü sınavım var." },
      { type: "example", en: "We usually meet on Fridays.", tr: "Genellikle Cuma günleri buluşuruz." },
      { type: "rule", text: "Mevsimler: SPRING (ilkbahar), SUMMER (yaz), AUTUMN/FALL (sonbahar), WINTER (kış). Mevsimlerde \"IN\" edatı kullanılır." },
      { type: "example", en: "Flowers bloom in spring.", tr: "Çiçekler ilkbaharda açar." },
      { type: "example", en: "It snows a lot in winter here.", tr: "Burada kışın çok kar yağar." },
      { type: "rule", text: "Saat bildirimi: IT'S + saat + O'CLOCK (tam saat), HALF PAST (buçuk), QUARTER PAST (çeyrek geçe), QUARTER TO (çeyrek kala)." },
      { type: "example", en: "It's five o'clock.", tr: "Saat beş." },
      { type: "example", en: "It's half past seven.", tr: "Saat yedi buçuk." },
      { type: "example", en: "It's a quarter to nine.", tr: "Saate dokuza çeyrek var." },
      { type: "rule", text: "Günlük rutin fiilleri: WAKE UP (uyanmak), GET UP (kalkmak), HAVE BREAKFAST (kahvaltı yapmak), GO TO WORK (işe gitmek), COME HOME (eve gelmek), GO TO BED (yatmak)." },
      { type: "example", en: "I wake up at seven every morning.", tr: "Her sabah saat yedide uyanırım." },
      { type: "example", en: "She goes to bed early on weekdays.", tr: "O hafta içi erken yatar." },
      { type: "rule", text: "Sıklık zarfları: ALWAYS (her zaman), USUALLY (genellikle), OFTEN (sık sık), SOMETIMES (bazen), RARELY/SELDOM (nadiren), NEVER (asla)." },
      { type: "example", en: "I rarely eat fast food.", tr: "Nadiren fast food yerim." },
      { type: "example", en: "He is never late for work.", tr: "O işe hiçbir zaman geç kalmaz." },
      { type: "rule", text: "Hava durumu ifadeleri: IT'S SUNNY (güneşli), IT'S RAINING (yağmurlu), IT'S CLOUDY (bulutlu), IT'S WINDY (rüzgarlı), IT'S SNOWING (karlı)." },
      { type: "example", en: "It's very sunny today, so take your sunglasses.", tr: "Bugün çok güneşli, o yüzden güneş gözlüğünü al." },
      { type: "example", en: "Don't forget your umbrella, it's raining outside.", tr: "Şemsiyeni unutma, dışarıda yağmur yağıyor." },
      { type: "rule", text: "Alışveriş ve para ile ilgili günlük kalıplar: HOW MUCH IS IT? (ne kadar?), IT COSTS... (fiyatı ...), ON SALE (indirimde), EXPENSIVE/CHEAP (pahalı/ucuz)." },
      { type: "example", en: "How much is this jacket?", tr: "Bu ceket ne kadar?" },
      { type: "example", en: "This shirt is on sale this week.", tr: "Bu gömlek bu hafta indirimde." },
      { type: "rule", text: "Son olarak bu dersteki bütün kalıpları içeren günlük bir diyalog örneği görelim." },
      { type: "example", en: "What time do you usually wake up? — I usually wake up at seven and have breakfast before going to work.", tr: "Genellikle saat kaçta uyanırsın? — Genellikle saat yedide uyanır ve işe gitmeden önce kahvaltı yaparım." },
      { type: "example", en: "See you on Saturday then! — Sure, take care until then!", tr: "O zaman Cumartesi görüşürüz! — Tabii, o zamana kadar kendine iyi bak!" },
      { type: "rule", text: "Tarih söyleme: DATE (tarih) belirtirken sıra sayıları (ordinal numbers) kullanılır: 1ST (FIRST), 2ND (SECOND), 3RD (THIRD), 4TH (FOURTH)... Tarihlerde \"ON\" edatı kullanılır." },
      { type: "example", en: "My birthday is on the fifteenth of March.", tr: "Doğum günüm 15 Mart'ta." },
      { type: "example", en: "The meeting is on the third of May.", tr: "Toplantı 3 Mayıs'ta." },
      { type: "rule", text: "Ev işleri ile ilgili günlük fiiller: CLEAN THE HOUSE (evi temizlemek), DO THE LAUNDRY (çamaşır yıkamak), COOK DINNER (akşam yemeği pişirmek), WASH THE DISHES (bulaşık yıkamak), TAKE OUT THE TRASH (çöpü atmak)." },
      { type: "example", en: "I do the laundry every Sunday.", tr: "Her Pazar çamaşır yıkarım." },
      { type: "example", en: "Can you take out the trash before you leave?", tr: "Çıkmadan önce çöpü atabilir misin?" },
      { type: "rule", text: "İş ve okul ile ilgili günlük kalıplar: BE ON TIME (zamanında olmak), BE LATE FOR (geç kalmak), HAND IN (teslim etmek), TAKE A BREAK (mola vermek)." },
      { type: "example", en: "Please don't be late for the meeting.", tr: "Lütfen toplantıya geç kalma." },
      { type: "example", en: "We need to hand in the report by Friday.", tr: "Raporu Cuma'ya kadar teslim etmemiz gerekiyor." },
      { type: "example", en: "Let's take a short break and continue later.", tr: "Kısa bir mola verip sonra devam edelim." },
      { type: "rule", text: "Duygu ve durum bildiren günlük sıfatlar: TIRED (yorgun), HUNGRY (aç), THIRSTY (susamış), BORED (sıkılmış), EXCITED (heyecanlı), NERVOUS (gergin)." },
      { type: "example", en: "I'm so hungry, let's eat something.", tr: "Çok açım, bir şeyler yiyelim." },
      { type: "example", en: "She was really nervous before the interview.", tr: "O mülakattan önce gerçekten gergindi." },
      { type: "rule", text: "Randevu ve planlama ile ilgili kalıplar: MAKE AN APPOINTMENT (randevu almak), CANCEL (iptal etmek), POSTPONE (ertelemek), BE FREE (müsait olmak)." },
      { type: "example", en: "I need to make an appointment with the dentist.", tr: "Diş hekimiyle randevu almam gerekiyor." },
      { type: "example", en: "We had to postpone the meeting until next week.", tr: "Toplantıyı gelecek haftaya ertelemek zorunda kaldık." },
      { type: "example", en: "Are you free this weekend?", tr: "Bu hafta sonu müsait misin?" },
      { type: "rule", text: "Toplu taşıma ve trafik ile ilgili günlük kalıplar: MISS THE BUS (otobüsü kaçırmak), BE STUCK IN TRAFFIC (trafikte kalmak), GET OFF/ON (inmek/binmek)." },
      { type: "example", en: "I missed the bus this morning, so I was late.", tr: "Bu sabah otobüsü kaçırdım, o yüzden geç kaldım." },
      { type: "example", en: "We were stuck in traffic for almost an hour.", tr: "Neredeyse bir saat trafikte kaldık." },
      { type: "example", en: "You should get off at the next stop.", tr: "Bir sonraki durakta inmelisin." },
      { type: "rule", text: "Yemek ve restoran ile ilgili günlük kalıplar: BOOK A TABLE (masa ayırtmak), ORDER (sipariş vermek), THE BILL, PLEASE (hesap lütfen)." },
      { type: "example", en: "I'd like to book a table for two, please.", tr: "İki kişilik masa ayırtmak istiyorum lütfen." },
      { type: "example", en: "Have you ordered yet?", tr: "Sipariş verdin mi?" },
      { type: "example", en: "Could we have the bill, please?", tr: "Hesabı alabilir miyiz lütfen?" },
    ],
  },
  {
    fileBase: "15_Present_Perfect",
    title: "YAKIN GEÇMİŞ ZAMAN (PRESENT PERFECT)",
    blocks: [
      { type: "rule", text: "Present Perfect; geçmişte gerçekleşmiş ama tam zamanı önemli olmayan eylemleri, ya da geçmişte başlayıp hâlâ etkisi süren durumları anlatmak için kullanılır." },
      { type: "rule", text: "Yapı: Özne + HAVE/HAS + Fiil (3. hal / V3)." },
      { type: "pattern", text: "I / YOU / WE / THEY + HAVE + V3        HE / SHE / IT + HAS + V3" },
      { type: "example", en: "I have finished my homework.", tr: "Ödevimi bitirdim." },
      { type: "example", en: "She has already left.", tr: "O çoktan ayrıldı." },
      { type: "example", en: "We have visited that museum twice.", tr: "O müzeyi iki kez ziyaret ettik." },
      { type: "rule", text: "Olumsuz yapı: Özne + HAVEN'T/HASN'T + V3." },
      { type: "example", en: "We haven't seen him yet.", tr: "Onu henüz görmedik." },
      { type: "example", en: "He hasn't called me today.", tr: "O bugün beni aramadı." },
      { type: "rule", text: "Soru yapısı: HAVE/HAS + Özne + V3?" },
      { type: "example", en: "Have you ever been to London?", tr: "Hiç Londra'ya gittin mi?" },
      { type: "example", en: "Has she finished the report?", tr: "O raporu bitirdi mi?" },
      { type: "rule", text: "Bu tense'le sıkça kullanılan zarflar: ALREADY (çoktan, zaten), JUST (henüz, az önce), YET (henüz - olumsuz/soru cümlelerinde), EVER (hiç), NEVER (hiçbir zaman)." },
      { type: "example", en: "I have never been there before.", tr: "Daha önce hiç orada bulunmadım." },
      { type: "example", en: "Have you finished the report yet?", tr: "Raporu henüz bitirdin mi?" },
      { type: "example", en: "He has just arrived.", tr: "O az önce vardı." },
      { type: "rule", text: "FOR (bir süre boyunca, ör: for two years) ve SINCE (bir noktadan beri, ör: since 2020) Present Perfect ile birlikte sıkça kullanılır." },
      { type: "example", en: "They have lived here for ten years.", tr: "Onlar burada on yıldır yaşıyorlar." },
      { type: "example", en: "I have known him since 2015.", tr: "Onu 2015'ten beri tanıyorum." },
      { type: "example", en: "She has worked here since she graduated.", tr: "O mezun olduğundan beri burada çalışıyor." },
      { type: "rule", text: "V3 (past participle) hâli düzenli fiillerde -ED, düzensiz fiillerde kendine özgüdür: GO-GONE, SEE-SEEN, WRITE-WRITTEN, DO-DONE, EAT-EATEN, BUY-BOUGHT." },
      { type: "example", en: "Has she done her homework?", tr: "O ödevini yaptı mı?" },
      { type: "example", en: "We have eaten there before.", tr: "Daha önce orada yemek yedik." },
      { type: "rule", text: "Present Perfect ile Past Simple arasındaki temel fark: Past Simple net bir geçmiş zamanı belirtir (yesterday, last week), Present Perfect ise zamanı belirtmez veya günümüze bağlı bir sonucu vurgular." },
      { type: "example", en: "I saw him yesterday. (Past Simple) / I have seen him before. (Present Perfect)", tr: "Onu dün gördüm. / Onu daha önce gördüm." },
      { type: "rule", text: "Sık kullanılan düzensiz fiillerin V3 (past participle) hâllerini bir liste hâlinde görelim." },
      { type: "pattern", text: "BE-BEEN, HAVE-HAD, TAKE-TAKEN, GIVE-GIVEN, COME-COME, MAKE-MADE, KNOW-KNOWN, FORGET-FORGOTTEN" },
      { type: "example", en: "Have you ever been to Paris?", tr: "Hiç Paris'e gittin mi?" },
      { type: "example", en: "I have already made my decision.", tr: "Kararımı çoktan verdim." },
      { type: "example", en: "She has forgotten her password again.", tr: "O yine şifresini unuttu." },
      { type: "rule", text: "ALREADY genellikle olumlu cümlelerde HAVE/HAS ile fiil arasında, YET ise olumsuz ve soru cümlelerinin sonunda kullanılır." },
      { type: "example", en: "I have already told you the answer.", tr: "Sana cevabı çoktan söyledim." },
      { type: "example", en: "We haven't decided yet.", tr: "Henüz karar vermedik." },
      { type: "example", en: "Has the bus arrived yet?", tr: "Otobüs henüz geldi mi?" },
      { type: "rule", text: "JUST, bir eylemin çok yakın zamanda tamamlandığını vurgular ve genellikle HAVE/HAS'ten hemen sonra kullanılır." },
      { type: "example", en: "I have just finished my dinner.", tr: "Az önce yemeğimi bitirdim." },
      { type: "example", en: "They have just moved to a new house.", tr: "Onlar az önce yeni bir eve taşındılar." },
      { type: "rule", text: "EVER (hiç), genellikle soru cümlelerinde, NEVER (hiçbir zaman) ise olumlu yapıda olumsuz anlam katarak kullanılır." },
      { type: "example", en: "Have you ever tried Turkish coffee?", tr: "Hiç Türk kahvesi denedin mi?" },
      { type: "example", en: "I have never seen such a beautiful view.", tr: "Hiç bu kadar güzel bir manzara görmedim." },
      { type: "rule", text: "HAVE/HAS kısaltmaları günlük konuşmada çok sık kullanılır: I'VE, YOU'VE, WE'VE, THEY'VE, HE'S, SHE'S, IT'S." },
      { type: "example", en: "I've never been so tired in my life.", tr: "Hayatımda hiç bu kadar yorgun olmamıştım." },
      { type: "example", en: "She's just called to say she's on her way.", tr: "O az önce yolda olduğunu söylemek için aradı." },
      { type: "rule", text: "Present Perfect ile hayat deneyimlerini anlatmak çok yaygındır; bu kullanımda zaman genellikle belirtilmez." },
      { type: "example", en: "I have traveled to many different countries.", tr: "Birçok farklı ülkeye seyahat ettim." },
      { type: "example", en: "He has worked in three different companies.", tr: "O üç farklı şirkette çalıştı." },
      { type: "example", en: "We have never lived abroad.", tr: "Hiç yurt dışında yaşamadık." },
      { type: "rule", text: "Sık yapılan bir hata, Present Perfect ile net bir geçmiş zaman ifadesini (yesterday, last year, in 2010) birlikte kullanmaktır; bu yanlıştır, bu durumda Past Simple kullanılmalıdır." },
      { type: "example", en: "I have seen him yesterday. (YANLIŞ) — I saw him yesterday. (DOĞRU)", tr: "Onu dün gördüm — doğru kullanım Past Simple ile yapılmalıdır." },
      { type: "rule", text: "Son olarak bu tense'i pekiştiren daha fazla örnek görelim." },
      { type: "example", en: "Have you finished your project yet?", tr: "Projeni henüz bitirdin mi?" },
      { type: "example", en: "We have already paid the bill.", tr: "Faturayı çoktan ödedik." },
      { type: "example", en: "She hasn't replied to my message yet.", tr: "O henüz mesajıma cevap vermedi." },
      { type: "example", en: "I have lost my keys somewhere in the house.", tr: "Anahtarlarımı evin bir yerinde kaybettim." },
      { type: "rule", text: "Present Perfect, aynı zamanda HOW LONG (ne kadar süredir) sorusuna cevap verirken FOR/SINCE ile birlikte çok sık kullanılır." },
      { type: "example", en: "How long have you lived in this city?", tr: "Bu şehirde ne kadar süredir yaşıyorsun?" },
      { type: "example", en: "How long has she worked here?", tr: "O burada ne kadar süredir çalışıyor?" },
      { type: "rule", text: "THIS IS THE FIRST/SECOND TIME kalıbı da Present Perfect ile birlikte kullanılır: bir eylemin kaçıncı kez yapıldığını vurgular." },
      { type: "pattern", text: "THIS IS THE FIRST TIME + Özne + HAVE/HAS + V3" },
      { type: "example", en: "This is the first time I have visited this city.", tr: "Bu şehri ziyaret etmem ilk kez." },
      { type: "example", en: "This is the third time she has called today.", tr: "Bugün araması üçüncü kez." },
      { type: "rule", text: "SO FAR (şimdiye kadar) ve UP TO NOW (şimdiye dek) ifadeleri de Present Perfect ile birlikte sıkça kullanılır." },
      { type: "example", en: "We have finished three chapters so far.", tr: "Şimdiye kadar üç bölüm bitirdik." },
      { type: "example", en: "Up to now, nothing has changed.", tr: "Şimdiye dek hiçbir şey değişmedi." },
      { type: "rule", text: "Present Perfect ile RECENTLY (son zamanlarda) ve LATELY (son zamanlarda) zarfları da kullanılabilir." },
      { type: "example", en: "I haven't seen him recently.", tr: "Son zamanlarda onu görmedim." },
      { type: "example", en: "Have you been to the gym lately?", tr: "Son zamanlarda spor salonuna gittin mi?" },
      { type: "rule", text: "Şimdi bu tense'i pekiştiren karma bir tekrar bölümüyle dersi tamamlayalım." },
      { type: "example", en: "We have known each other for fifteen years.", tr: "Birbirimizi on beş yıldır tanıyoruz." },
      { type: "example", en: "Has the price of oil increased this month?", tr: "Bu ay petrol fiyatı arttı mı?" },
      { type: "example", en: "I have never eaten sushi before.", tr: "Daha önce hiç suşi yemedim." },
      { type: "example", en: "She has just woken up.", tr: "O az önce uyandı." },
      { type: "rule", text: "Present Perfect, bir eylemin tekrarlanma sayısını belirtirken de kullanılır: ONCE (bir kez), TWICE (iki kez), THREE TIMES (üç kez) gibi ifadelerle birlikte." },
      { type: "example", en: "I have watched this movie three times.", tr: "Bu filmi üç kez izledim." },
      { type: "example", en: "She has visited Paris twice this year.", tr: "O bu yıl Paris'i iki kez ziyaret etti." },
      { type: "rule", text: "Present Perfect ile BEFORE (daha önce) zarfı da sık kullanılır ve genellikle cümlenin sonuna gelir." },
      { type: "example", en: "Have you met her before?", tr: "Onunla daha önce tanıştın mı?" },
      { type: "example", en: "I haven't tried this dish before.", tr: "Bu yemeği daha önce hiç denemedim." },
      { type: "rule", text: "Son olarak Present Perfect ile bir işin sonucu ve şimdiki durumu arasındaki bağı gösteren örnekler görelim." },
      { type: "example", en: "I have broken my phone, so I need a new one.", tr: "Telefonumu kırdım, bu yüzden yeni birine ihtiyacım var." },
      { type: "example", en: "She has cut her hair; it looks great now.", tr: "O saçını kestirdi; şimdi harika görünüyor." },
      { type: "example", en: "We have run out of milk, can you buy some?", tr: "Sütümüz bitti, biraz alabilir misin?" },
    ],
  },
  {
    fileBase: "16_Could_Kaliplari",
    title: "COULD KALIPLARI VE ANLAŞMA-MEMNUNİYET İFADELERİ",
    blocks: [
      { type: "rule", text: "COULD'un iki ayrı kullanımı vardır. COULD-1: CAN'in geçmiş zaman hâlidir, geçmişteki yetenek/imkânı anlatır." },
      { type: "pattern", text: "COULD-1 = geçmişte yapabilmek" },
      { type: "example", en: "We couldn't finish it on time.", tr: "Onu zamanında bitiremedik." },
      { type: "example", en: "Unfortunately, they couldn't catch the train.", tr: "Maalesef treni yakalayamadılar." },
      { type: "example", en: "I could swim when I was five.", tr: "Beş yaşımdayken yüzebiliyordum." },
      { type: "rule", text: "COULD-2: Kibar sorular sormak için kullanılır, geçmiş zamanla ilgisi yoktur." },
      { type: "pattern", text: "COULD-2 = kibarca rica etmek" },
      { type: "example", en: "Could you open the window?", tr: "Pencereyi açabilir misiniz?" },
      { type: "example", en: "Could you please pay the bill, because I forgot my wallet?", tr: "Hesabı ödeyebilir misiniz, cüzdanımı unuttum?" },
      { type: "example", en: "Could you show me the way?", tr: "Bana yolu gösterebilir misiniz?" },
      { type: "rule", text: "COULD'un bu iki kullanımının aynı konuşmada art arda kullanılması karışıklığa yol açabileceğinden dikkat edilmelidir." },
      { type: "pattern", text: "REACH = ulaşmak / REACH AN AGREEMENT = anlaşmaya varmak" },
      { type: "example", en: "Can I easily reach you?", tr: "Sana kolayca ulaşabilir miyim?" },
      { type: "example", en: "They couldn't reach an agreement yet.", tr: "Onlar henüz bir anlaşmaya varamadılar." },
      { type: "pattern", text: "SATISFIED = memnun, hoşnut / BE SATISFIED + WITH = ... den memnun olmak" },
      { type: "pattern", text: "SERVICE = hizmet / ACCOMMODATION = konaklama" },
      { type: "example", en: "Are you satisfied with the service?", tr: "Hizmetten memnun musunuz?" },
      { type: "example", en: "We aren't satisfied with the hotel, because the rooms are too small.", tr: "Otelden memnun değiliz, çünkü odalar çok küçük." },
      { type: "example", en: "I am satisfied with your work.", tr: "Çalışmandan memnunum." },
      { type: "rule", text: "COULD-1'in olumsuz sorusu da geçmişteki bir yetenek/imkânsızlığı sorgulamak için kullanılır." },
      { type: "example", en: "Couldn't you find a solution?", tr: "Bir çözüm bulamadın mı?" },
      { type: "example", en: "Could they speak English when they were children?", tr: "Onlar çocukken İngilizce konuşabiliyorlar mıydı?" },
      { type: "rule", text: "COULD-2, CAN'e göre daha kibar ve resmi bir rica şeklidir; özellikle yabancılarla veya iş ortamında CAN yerine COULD tercih edilir." },
      { type: "example", en: "Could I ask you a question?", tr: "Size bir soru sorabilir miyim?" },
      { type: "example", en: "Could we start the meeting now?", tr: "Toplantıya şimdi başlayabilir miyiz?" },
      { type: "rule", text: "COULD ayrıca gelecekteki zayıf bir olasılığı belirtmek için de kullanılabilir; bu kullanım MAY/MIGHT'a yakındır." },
      { type: "example", en: "It could rain later today.", tr: "Bugün ilerleyen saatlerde yağmur yağabilir." },
      { type: "pattern", text: "ACCOMMODATION = konaklama / SERVICE = hizmet" },
      { type: "example", en: "How was the accommodation during your trip?", tr: "Gezin sırasında konaklama nasıldı?" },
      { type: "example", en: "The hotel service wasn't satisfying at all.", tr: "Otel hizmeti hiç tatmin edici değildi." },
      { type: "rule", text: "REACH AN AGREEMENT kalıbı iş görüşmelerinde ve müzakerelerde çok sık kullanılır." },
      { type: "example", en: "Did both sides reach an agreement?", tr: "Her iki taraf da bir anlaşmaya vardı mı?" },
      { type: "example", en: "We are trying to reach an agreement with them.", tr: "Onlarla bir anlaşmaya varmaya çalışıyoruz." },
      { type: "rule", text: "COULD, CAN ve WOULD ile karşılaştırıldığında: CAN şimdiki yetenek/izin, COULD geçmiş yetenek veya kibar rica, WOULD ise kibar istek ya da hayali durumlar için kullanılır." },
      { type: "pattern", text: "CAN = şimdiki zaman yetenek/izin   |   COULD = geçmiş yetenek / kibar rica   |   WOULD = kibar istek / hayali durum" },
      { type: "example", en: "Would you like some coffee?", tr: "Kahve ister misiniz?" },
      { type: "example", en: "Could you pass me the salt, please?", tr: "Tuzu uzatır mısınız lütfen?" },
      { type: "rule", text: "COULD HAVE + V3 kalıbı, geçmişte yapılabilecek ama yapılmamış bir eylemi anlatır; pişmanlık ya da olasılık ifade eder." },
      { type: "pattern", text: "COULD HAVE + V3 = ...yapabilirdi (ama yapmadı)" },
      { type: "example", en: "You could have told me earlier!", tr: "Bana daha önce söyleyebilirdin!" },
      { type: "example", en: "We could have won the match if we had tried harder.", tr: "Daha çok çabalasaydık maçı kazanabilirdik." },
      { type: "rule", text: "Memnuniyet ve şikayet ifadelerini pekiştiren daha fazla kalıp: BE PLEASED WITH (memnun olmak), COMPLAIN ABOUT (şikayet etmek), BE DISAPPOINTED WITH (hayal kırıklığına uğramak)." },
      { type: "example", en: "I am pleased with the results.", tr: "Sonuçlardan memnunum." },
      { type: "example", en: "He complained about the noise all night.", tr: "O bütün gece gürültüden şikayet etti." },
      { type: "example", en: "We were disappointed with the customer service.", tr: "Müşteri hizmetlerinden hayal kırıklığına uğradık." },
      { type: "rule", text: "Anlaşma ve müzakere ile ilgili ek kalıplar: NEGOTIATE (müzakere etmek), COMPROMISE (uzlaşmak), COME TO A DECISION (bir karara varmak)." },
      { type: "example", en: "Could we negotiate the price a little?", tr: "Fiyatı biraz müzakere edebilir miyiz?" },
      { type: "example", en: "They finally came to a decision after a long discussion.", tr: "Uzun bir tartışmadan sonra sonunda bir karara vardılar." },
      { type: "example", en: "We had to compromise on the delivery date.", tr: "Teslimat tarihi konusunda uzlaşmak zorunda kaldık." },
      { type: "rule", text: "COULD YOU MIND...? gibi bazı kalıplar yanlış kullanılır; doğrusu WOULD YOU MIND + V-ing? şeklindedir." },
      { type: "example", en: "Would you mind closing the door?", tr: "Kapıyı kapatır mısınız (sakıncası var mı)?" },
      { type: "example", en: "Would you mind waiting a few minutes?", tr: "Birkaç dakika bekler misiniz (sakıncası var mı)?" },
      { type: "rule", text: "Son olarak bu dersteki bütün kalıpları içeren bir tekrar bölümü görelim." },
      { type: "example", en: "Could you help me carry these bags?", tr: "Bu çantaları taşımama yardım edebilir misin?" },
      { type: "example", en: "I couldn't sleep well because I wasn't satisfied with the hotel room.", tr: "İyi uyuyamadım çünkü otel odasından memnun değildim." },
      { type: "example", en: "We could have reached an agreement if they had been more flexible.", tr: "Onlar daha esnek olsaydı bir anlaşmaya varabilirdik." },
      { type: "rule", text: "COULDN'T HAVE + V3 kalıbı, geçmişte bir eylemin imkansız olduğunu vurgular." },
      { type: "pattern", text: "COULDN'T HAVE + V3 = ...yapamazdı" },
      { type: "example", en: "I couldn't have finished it without your help.", tr: "Senin yardımın olmadan onu bitiremezdim." },
      { type: "example", en: "She couldn't have known about the surprise.", tr: "O sürprizden haberdar olamazdı." },
      { type: "rule", text: "İş ve toplantı ortamında sıkça kullanılan ek kalıplar: SET UP A MEETING (toplantı ayarlamak), FOLLOW UP (takip etmek), DEAL WITH (halletmek)." },
      { type: "example", en: "Could you set up a meeting for next week?", tr: "Gelecek hafta için bir toplantı ayarlayabilir misin?" },
      { type: "example", en: "I'll follow up with the client tomorrow.", tr: "Yarın müşteriyle takip edeceğim." },
      { type: "example", en: "We need to deal with this problem immediately.", tr: "Bu sorunu hemen halletmemiz gerekiyor." },
      { type: "rule", text: "Otel ve tatil deneyimleriyle ilgili memnuniyet/şikayet kalıplarını pekiştirelim." },
      { type: "example", en: "The accommodation was excellent, and the staff were very satisfied to help us.", tr: "Konaklama mükemmeldi ve personel bize yardım etmekten çok memnundu." },
      { type: "example", en: "Could you recommend a good place to stay?", tr: "Kalınacak iyi bir yer önerebilir misin?" },
      { type: "example", en: "We weren't satisfied with the room service at all.", tr: "Oda servisinden hiç memnun kalmadık." },
      { type: "rule", text: "Kibar rica cümlelerini pekiştiren daha fazla günlük örnek görelim." },
      { type: "example", en: "Could you turn down the music, please?", tr: "Müziği kısabilir misiniz lütfen?" },
      { type: "example", en: "Could I borrow your pen for a second?", tr: "Bir saniyeliğine kalemini ödünç alabilir miyim?" },
      { type: "example", en: "Could you repeat that, please? I didn't understand.", tr: "Bunu tekrar edebilir misiniz lütfen? Anlamadım." },
      { type: "rule", text: "Son olarak bu dersteki bütün yapıları içeren bir kapanış bölümü ekleyelim." },
      { type: "example", en: "Could you please explain how we could reach a fair agreement?", tr: "Adil bir anlaşmaya nasıl varabileceğimizi açıklayabilir misiniz lütfen?" },
      { type: "example", en: "We couldn't have been more satisfied with the service.", tr: "Hizmetten daha fazla memnun olamazdık." },
      { type: "rule", text: "MAY I / MIGHT I kalıpları da COULD I gibi kibar izin isteme cümlelerinde kullanılabilir, ancak COULD günlük konuşmada daha yaygındır." },
      { type: "example", en: "May I come in?", tr: "İçeri girebilir miyim?" },
      { type: "example", en: "Might I suggest a different approach?", tr: "Farklı bir yaklaşım önerebilir miyim?" },
      { type: "rule", text: "Şikayet ve memnuniyet ifadelerini restoran, otel ve müşteri hizmetleri bağlamında pekiştirelim." },
      { type: "example", en: "I'd like to complain about the delay.", tr: "Gecikme hakkında şikayette bulunmak istiyorum." },
      { type: "example", en: "We are very satisfied with how you handled the situation.", tr: "Durumu ele alış şeklinizden çok memnunuz." },
      { type: "rule", text: "Bu dersteki tüm kalıpları içeren son bir günlük diyalog örneğiyle konuyu tamamlayalım." },
      { type: "example", en: "Could you help me reach an agreement with the supplier? — Sure, I'll try, but I can't promise we'll be fully satisfied.", tr: "Tedarikçiyle bir anlaşmaya varmama yardım edebilir misin? — Tabii, deneyeceğim ama tamamen memnun kalacağımızı garanti edemem." },
      { type: "example", en: "Could we have reached a better deal? — Maybe, but we couldn't have known that at the time.", tr: "Daha iyi bir anlaşma yapabilir miydik? — Belki, ama o zaman bunu bilemezdik." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
