import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "21_Yer_Edatlari_ve_Hava",
    title: "YER EDATLARI, THERE IS/ARE VE HAVA DURUMU",
    blocks: [
      { type: "rule", text: "Yer edatları: ON (üstünde), UNDER (altında), IN FRONT OF (önünde), BEHIND (arkasında), NEXT TO (yanında), ACROSS (karşısında), BETWEEN...AND (...ile ... arasında), ON THE CORNER OF (köşesinde)." },
      { type: "example", en: "My phone is on the table.", tr: "Telefonum masanın üstünde." },
      { type: "example", en: "The post office is between the pharmacy and the bookstore.", tr: "Postane eczane ile kitapçı arasında." },
      { type: "example", en: "Is he sitting next to you?", tr: "O senin yanında mı oturuyor?" },
      { type: "pattern", text: "ACROSS THE ROAD = yolun karşısında" },
      { type: "example", en: "He is waiting for you across the road.", tr: "O seni yolun karşısında bekliyor." },
      { type: "rule", text: "THERE IS (tekil/sayılamayan) ve THERE ARE (çoğul) \"var\" anlamına gelir." },
      { type: "pattern", text: "THERE IS + tekil isim        THERE ARE + çoğul isim" },
      { type: "example", en: "There is a man in front of the door.", tr: "Kapının önünde bir adam var." },
      { type: "example", en: "There are a few cats under the table.", tr: "Masanın altında birkaç kedi var." },
      { type: "example", en: "There are some people across the building.", tr: "Binanın karşısında birkaç kişi var." },
      { type: "rule", text: "Olumsuz hâli: THERE ISN'T / THERE AREN'T, ya da THERE IS NO / THERE ARE NO." },
      { type: "example", en: "There isn't any money. = There is no money.", tr: "Hiç para yok." },
      { type: "example", en: "There isn't enough time.", tr: "Yeterince zaman yok." },
      { type: "example", en: "Is there an ATM in the mall?", tr: "Alışveriş merkezinde bir ATM var mı?" },
      { type: "rule", text: "Hava durumu için IT IS kalıbı kullanılır ve genellikle şimdiki zamanla (present continuous) ifade edilir." },
      { type: "pattern", text: "RAIN = yağmur, yağmur yağmak / SNOW = kar, kar yağmak" },
      { type: "example", en: "It is raining right now.", tr: "Şu anda yağmur yağıyor." },
      { type: "example", en: "It is snowing outside.", tr: "Dışarıda kar yağıyor." },
      { type: "example", en: "Did it rain a lot yesterday?", tr: "Dün çok yağmur yağdı mı?" },
      { type: "rule", text: "Hava durumu sıfatları: CLOUDY (bulutlu), WINDY (rüzgarlı), SUNNY (güneşli), FOGGY (sisli), HOT (sıcak), WARM (ılık), COLD (soğuk), COOL (serin)." },
      { type: "example", en: "It is cloudy today, it may rain.", tr: "Bugün bulutlu, yağmur yağabilir." },
      { type: "example", en: "It was so windy last night.", tr: "Dün gece çok rüzgarlıydı." },
      { type: "example", en: "The sun is shining, it is a sunny day.", tr: "Güneş parlıyor, güneşli bir gün." },
      { type: "rule", text: "HOW IS THE WEATHER? / WHAT IS THE WEATHER LIKE? = Hava nasıl?" },
      { type: "example", en: "It will be so hot tomorrow.", tr: "Yarın hava çok sıcak olacak." },
      { type: "example", en: "It is too foggy today, so there is no sight.", tr: "Bugün çok sisli, bu yüzden görüş yok." },
      { type: "rule", text: "Daha fazla yer edatı: NEAR (yakınında), FAR FROM (uzağında), OPPOSITE (karşısında), AMONG (arasında - üçten fazla), THROUGH (içinden), ALONG (boyunca), AROUND (etrafında)." },
      { type: "example", en: "The bank is near the hospital.", tr: "Banka hastanenin yakınında." },
      { type: "example", en: "My house is far from the city center.", tr: "Evim şehir merkezinden uzakta." },
      { type: "example", en: "The cinema is opposite the shopping mall.", tr: "Sinema alışveriş merkezinin karşısında." },
      { type: "example", en: "He was standing among the crowd.", tr: "O kalabalığın arasında duruyordu." },
      { type: "example", en: "We walked through the park.", tr: "Parkın içinden yürüdük." },
      { type: "example", en: "There are many shops along this street.", tr: "Bu cadde boyunca birçok dükkan var." },
      { type: "rule", text: "Yol tarifi verirken kullanılan kalıplar: GO STRAIGHT ON (düz devam et), TURN LEFT/RIGHT (sağa/sola dön), AT THE CORNER (köşede), AT THE TRAFFIC LIGHTS (trafik ışıklarında)." },
      { type: "example", en: "Go straight on and turn left at the corner.", tr: "Düz devam et ve köşede sola dön." },
      { type: "example", en: "Turn right at the traffic lights, and the museum is on your left.", tr: "Trafik ışıklarında sağa dön, müze solunda olacak." },
      { type: "rule", text: "THERE IS/ARE geçmiş zamanda THERE WAS/WERE, gelecek zamanda THERE WILL BE olur." },
      { type: "pattern", text: "THERE WAS + tekil        THERE WERE + çoğul        THERE WILL BE + tekil/çoğul" },
      { type: "example", en: "There was a big tree in front of the house.", tr: "Evin önünde büyük bir ağaç vardı." },
      { type: "example", en: "There were many people at the concert.", tr: "Konserde birçok insan vardı." },
      { type: "example", en: "There will be a meeting tomorrow.", tr: "Yarın bir toplantı olacak." },
      { type: "rule", text: "Hava durumuyla ilgili daha fazla ifade: IT'S FREEZING (donuyor), IT'S POURING (bardaktan boşanırcasına yağıyor), IT'S BOILING (kavuruyor), THERE'S A STORM (fırtına var)." },
      { type: "example", en: "It's freezing outside, wear a coat.", tr: "Dışarısı dondurucu soğuk, palto giy." },
      { type: "example", en: "It's pouring, we can't go out now.", tr: "Bardaktan boşanırcasına yağıyor, şimdi dışarı çıkamayız." },
      { type: "example", en: "There's a storm coming, so stay inside.", tr: "Fırtına geliyor, o yüzden içeride kal." },
      { type: "rule", text: "Sık yapılan bir hata: yer edatlarında IN, ON, AT'i karıştırmaktır. IN (bir alanın içinde), ON (bir yüzeyin üstünde), AT (belirli bir nokta) kullanılır." },
      { type: "example", en: "The keys are in the drawer.", tr: "Anahtarlar çekmecenin içinde." },
      { type: "example", en: "The picture is on the wall.", tr: "Resim duvarın üstünde." },
      { type: "example", en: "She is waiting at the bus stop.", tr: "O otobüs durağında bekliyor." },
      { type: "rule", text: "Son olarak bu dersteki yer edatlarını ve hava durumunu birlikte pekiştiren birkaç örnek görelim." },
      { type: "example", en: "There is a cafe between the bank and the bookstore, but it's closed because of the storm.", tr: "Banka ile kitapçı arasında bir kafe var ama fırtına yüzünden kapalı." },
      { type: "example", en: "What's the weather like near the coast today?", tr: "Bugün kıyı yakınında hava nasıl?" },
      { type: "example", en: "We were sitting under a tree when it suddenly started to rain.", tr: "Bir ağacın altında otururken aniden yağmur yağmaya başladı." },
      { type: "rule", text: "Ev içindeki yer edatlarını pekiştiren daha fazla örnek: INSIDE (içinde), OUTSIDE (dışında), AT THE TOP OF (üstünde/tepesinde), AT THE BOTTOM OF (altında/dibinde)." },
      { type: "example", en: "The cat is hiding inside the box.", tr: "Kedi kutunun içinde saklanıyor." },
      { type: "example", en: "There is a garden outside the house.", tr: "Evin dışında bir bahçe var." },
      { type: "example", en: "The book is at the top of the shelf.", tr: "Kitap rafın üstünde." },
      { type: "example", en: "Write your name at the bottom of the page.", tr: "Adını sayfanın altına yaz." },
      { type: "rule", text: "Şehir ve seyahatle ilgili yer edatları: AT THE AIRPORT, AT THE STATION, IN THE CITY CENTER, ON THE HIGHWAY." },
      { type: "example", en: "We'll meet at the airport at six.", tr: "Havaalanında saat altıda buluşacağız." },
      { type: "example", en: "There's a lot of traffic on the highway today.", tr: "Bugün otoyolda çok trafik var." },
      { type: "rule", text: "HERE ve THERE zarfları da yer belirtirken sık kullanılır: HERE (burada, buraya), THERE (orada, oraya)." },
      { type: "example", en: "Come here for a second.", tr: "Bir saniye buraya gel." },
      { type: "example", en: "Put the box over there.", tr: "Kutuyu şuraya koy." },
      { type: "rule", text: "Mevsimlik hava durumu tahminleri: IT'S GOING TO RAIN/SNOW (yağmur/kar yağacak) — gelecek zaman tahmini için kullanılır." },
      { type: "example", en: "Look at those clouds, it's going to rain.", tr: "Şu bulutlara bak, yağmur yağacak." },
      { type: "example", en: "The forecast says it's going to snow this weekend.", tr: "Hava durumuna göre bu hafta sonu kar yağacak." },
      { type: "rule", text: "Doğa olaylarıyla ilgili kelimeler: THUNDER (gök gürültüsü), LIGHTNING (şimşek), RAINBOW (gökkuşağı), TEMPERATURE (sıcaklık), DEGREE (derece)." },
      { type: "example", en: "We heard thunder in the distance.", tr: "Uzaktan gök gürültüsü duyduk." },
      { type: "example", en: "There's a beautiful rainbow after the rain.", tr: "Yağmurdan sonra güzel bir gökkuşağı var." },
      { type: "example", en: "The temperature dropped to five degrees last night.", tr: "Dün gece sıcaklık beş dereceye düştü." },
      { type: "rule", text: "Yer ve hava durumunu birleştiren günlük bir diyalog örneği görelim." },
      { type: "example", en: "Where is the nearest pharmacy? — It's on the corner, opposite the bakery, but it's raining, so take an umbrella.", tr: "En yakın eczane nerede? — Köşede, fırının karşısında, ama yağmur yağıyor, şemsiye al." },
      { type: "example", en: "Is there a park near your house? — Yes, there's a big park behind the school, it's lovely when it's sunny.", tr: "Evinin yakınında bir park var mı? — Evet, okulun arkasında büyük bir park var, güneşliyken çok güzel oluyor." },
      { type: "rule", text: "UNDERGROUND / ABOVE THE GROUND (yerin altında/üstünde), UPSTAIRS / DOWNSTAIRS (üst katta/alt katta) ifadeleri de bina içi konumları anlatır." },
      { type: "example", en: "The bedrooms are upstairs.", tr: "Yatak odaları üst katta." },
      { type: "example", en: "The kitchen is downstairs, next to the living room.", tr: "Mutfak alt katta, oturma odasının yanında." },
      { type: "rule", text: "Hava durumuyla ilgili sıklık ve derece zarflarını pekiştirelim: SLIGHTLY (hafifçe), EXTREMELY (aşırı derecede), A BIT (biraz)." },
      { type: "example", en: "It's slightly colder today than yesterday.", tr: "Bugün dünden biraz daha soğuk." },
      { type: "example", en: "It's extremely hot this summer.", tr: "Bu yaz aşırı sıcak." },
    ],
  },
  {
    fileBase: "22_Sira_Sayilari_ve_Zaman",
    title: "SIRA SAYILARI VE ZAMAN İFADELERİ",
    blocks: [
      { type: "rule", text: "Sıra sayıları: FIRST, SECOND, THIRD, FOURTH, FIFTH, SIXTH, SEVENTH, EIGHTH, NINTH, TENTH." },
      { type: "pattern", text: "FOR THE FIRST TIME = ilk defa / FOR THE THIRD TIME = üçüncü defa" },
      { type: "example", en: "Did he go to Germany for the first time?", tr: "O Almanya'ya ilk defa mı gitti?" },
      { type: "pattern", text: "TOO / AS WELL = -de, dahi" },
      { type: "example", en: "Did you miss the second train as well?", tr: "İkinci treni de mi kaçırdın?" },
      { type: "pattern", text: "MEET = buluşmak, tanışmak / GLAD = memnun, sevinçli / NICE TO MEET YOU! = tanıştığımıza memnun oldum!" },
      { type: "example", en: "Where did you meet for the first time?", tr: "İlk defa nerede tanıştınız?" },
      { type: "example", en: "I'm glad that you came.", tr: "Geldiğine memnunum." },
      { type: "example", en: "I'm glad to see you.", tr: "Seni gördüğüme sevindim." },
      { type: "pattern", text: "LOSE = kaybetmek / BE LOST, GET LOST = kaybolmak" },
      { type: "example", en: "Unfortunately, they are lost, so everyone is looking for them.", tr: "Maalesef onlar kayboldu, bu yüzden herkes onları arıyor." },
      { type: "example", en: "I will never lose her.", tr: "Onu asla kaybetmeyeceğim." },
      { type: "rule", text: "STILL (hâlâ, olumlu/soru cümlelerinde) ve YET (henüz, olumsuz/soru cümlelerinde) arasındaki fark önemlidir." },
      { type: "example", en: "Are you still working?", tr: "Hâlâ çalışıyor musun?" },
      { type: "example", en: "We are still looking for her.", tr: "Onu hâlâ arıyoruz." },
      { type: "example", en: "He didn't call me yet.", tr: "Henüz beni aramadı." },
      { type: "pattern", text: "WAKE UP = uyanmak / uyandırmak / AT WHAT TIME = WHAT TIME = saat kaçta" },
      { type: "example", en: "At what time does he usually wake up?", tr: "Genellikle saat kaçta uyanır?" },
      { type: "example", en: "Please wake me up, if you get up earlier than me!", tr: "Lütfen benden erken kalkarsan beni uyandır!" },
      { type: "pattern", text: "DOUBT = şüphe / DEBT = borç" },
      { type: "example", en: "He has no debt, and I have no doubt about it.", tr: "Onun borcu yok, ve bundan şüphem yok." },
      { type: "example", en: "We had a lot of debts, but we paid all of them.", tr: "Çok borcumuz vardı ama hepsini ödedik." },
      { type: "rule", text: "WHEN (-dığında, -diğinde) bağlacı iki olayın birbirine bağlı olduğunu anlatır." },
      { type: "example", en: "He will call us when he arrives.", tr: "Vardığında bizi arayacak." },
      { type: "example", en: "I will inform you when I finish.", tr: "Bitirdiğimde sana haber vereceğim." },
      { type: "example", en: "She called me when she got home.", tr: "Eve vardığında beni aradı." },
      { type: "pattern", text: "LEAVE = ayrılmak, bırakmak / CHOOSE-CHOSE-CHOSEN = seçmek / REQUEST = istek, rica" },
      { type: "example", en: "Please, leave a message!", tr: "Lütfen mesaj bırakın!" },
      { type: "example", en: "Unfortunately, we chose the wrong direction.", tr: "Maalesef yanlış yönü seçtik." },
      { type: "example", en: "Do you have any request?", tr: "Bir isteğin var mı?" },
      { type: "rule", text: "Sıra sayıları tarih söylemede de kullanılır: THE FIRST OF JANUARY, THE TWENTY-THIRD OF MAY gibi." },
      { type: "example", en: "Her birthday is on the twenty-first of April.", tr: "Onun doğum günü 21 Nisan'da." },
      { type: "example", en: "The meeting is on the eleventh of this month.", tr: "Toplantı bu ayın on birinde." },
      { type: "rule", text: "Sıra sayıları bina katlarını ve sıralamayı belirtirken de kullanılır: THE FIRST FLOOR, THE SECOND CHAPTER, THE THIRD PLACE." },
      { type: "example", en: "Our office is on the fifth floor.", tr: "Ofisimiz beşinci katta." },
      { type: "example", en: "She came in third place in the race.", tr: "Yarışta üçüncü oldu." },
      { type: "rule", text: "Zaman ifadeleri: AGO (önce, geçmiş zamanla), IN (kaç zaman sonra, gelecek zamanla), LATER (daha sonra), SOON (yakında)." },
      { type: "pattern", text: "SÜRE + AGO = ... önce        IN + SÜRE = ... sonra (gelecek)" },
      { type: "example", en: "I moved to this city two years ago.", tr: "Bu şehre iki yıl önce taşındım." },
      { type: "example", en: "The train will arrive in ten minutes.", tr: "Tren on dakika sonra gelecek." },
      { type: "example", en: "See you soon!", tr: "Yakında görüşürüz!" },
      { type: "rule", text: "BY THE TIME (o zamana kadar) kalıbı, bir eylemin başka bir eylemden önce tamamlandığını vurgulamak için kullanılır." },
      { type: "example", en: "By the time you arrive, I will have finished cooking.", tr: "Sen vardığında ben yemek pişirmeyi bitirmiş olacağım." },
      { type: "rule", text: "ALREADY, JUST, YET zarflarının zaman ifadelerindeki kullanımını pekiştirelim." },
      { type: "example", en: "Have you finished the report yet?", tr: "Raporu henüz bitirdin mi?" },
      { type: "example", en: "I have just seen him at the station.", tr: "Onu az önce istasyonda gördüm." },
      { type: "rule", text: "ONCE (bir zamanlar / bir kez), TWICE (iki kez), FOR THE LAST TIME (son kez) gibi zaman zarfları da sıkça kullanılır." },
      { type: "example", en: "I have visited that city once.", tr: "O şehri bir kez ziyaret ettim." },
      { type: "example", en: "This is the last time I'm telling you this.", tr: "Bunu sana son kez söylüyorum." },
      { type: "rule", text: "Son olarak sıra sayıları ve zaman ifadelerini birlikte pekiştiren birkaç örnek görelim." },
      { type: "example", en: "This is the second time he has been late this week.", tr: "Bu hafta geç kalması ikinci kez oluyor." },
      { type: "example", en: "We arrived three hours ago, and the meeting starts in one hour.", tr: "Üç saat önce vardık ve toplantı bir saat sonra başlıyor." },
      { type: "example", en: "By the time we finish, it will be midnight.", tr: "Bitirdiğimizde gece yarısı olacak." },
      { type: "rule", text: "Sıra sayılarının yazımında dikkat edilmesi gereken kurallar: 1st (first), 2nd (second), 3rd (third), 4. ve sonrası -TH ekiyle biter (4th, 5th, 20th), ama 21st, 22nd, 23rd gibi istisnalar vardır." },
      { type: "example", en: "This is his 21st birthday.", tr: "Bu onun 21. doğum günü." },
      { type: "example", en: "We celebrated our 25th anniversary last year.", tr: "Geçen yıl 25. yıl dönümümüzü kutladık." },
      { type: "rule", text: "EARLY (erken) ve LATE (geç) zarflarını pekiştiren örnekler görelim; bunlar hem sıfat hem zarf olarak kullanılabilir." },
      { type: "example", en: "We arrived early for the meeting.", tr: "Toplantı için erken vardık." },
      { type: "example", en: "Sorry I'm late, the traffic was terrible.", tr: "Üzgünüm geç kaldım, trafik berbattı." },
      { type: "rule", text: "DURING (süresince) ve WHILE (-iken) arasındaki fark: DURING bir isimle, WHILE bir cümleyle (özne+fiil) kullanılır." },
      { type: "pattern", text: "DURING + isim        WHILE + özne + fiil" },
      { type: "example", en: "I fell asleep during the movie.", tr: "Film sırasında uyuyakaldım." },
      { type: "example", en: "I fell asleep while I was watching the movie.", tr: "Filmi izlerken uyuyakaldım." },
      { type: "rule", text: "UNTIL/TILL (...e kadar) ve BY (en geç ...e kadar) arasındaki fark önemlidir: UNTIL bir eylemin ne zamana kadar sürdüğünü, BY ise bir eylemin en geç ne zaman tamamlanacağını belirtir." },
      { type: "example", en: "I will wait until you arrive.", tr: "Sen gelene kadar bekleyeceğim." },
      { type: "example", en: "Please finish this report by Friday.", tr: "Lütfen bu raporu en geç Cuma'ya kadar bitir." },
      { type: "rule", text: "Haftanın, ayın ve yılın bölümlerini anlatan zaman ifadeleri: AT THE BEGINNING OF (başında), AT THE END OF (sonunda), IN THE MIDDLE OF (ortasında)." },
      { type: "example", en: "We're going on holiday at the end of July.", tr: "Temmuz'un sonunda tatile gidiyoruz." },
      { type: "example", en: "He joined the company in the middle of last year.", tr: "O geçen yılın ortasında şirkete katıldı." },
      { type: "rule", text: "NOWADAYS (günümüzde) ve THESE DAYS (bu günlerde) ifadeleri, günümüzdeki bir alışkanlık ya da durumdan bahsederken kullanılır." },
      { type: "example", en: "Nowadays, most people work from home.", tr: "Günümüzde çoğu insan evden çalışıyor." },
      { type: "example", en: "I've been very busy these days.", tr: "Bu günlerde çok meşgulüm." },
      { type: "rule", text: "Son olarak sıra sayıları, zaman zarfları ve edatları birlikte pekiştiren birkaç örnek görelim." },
      { type: "example", en: "This is the third time I've called you during the meeting.", tr: "Toplantı sırasında seni araması üçüncü kez oluyor." },
      { type: "example", en: "By the end of the month, we'll have finished the first phase of the project.", tr: "Ay sonuna kadar projenin ilk aşamasını bitirmiş olacağız." },
      { type: "example", en: "She joined us for the first time at the beginning of this year.", tr: "O bize bu yılın başında ilk kez katıldı." },
      { type: "rule", text: "FROM...TO / FROM...UNTIL kalıpları bir zaman aralığını belirtmek için kullanılır." },
      { type: "example", en: "The shop is open from nine to six.", tr: "Dükkan dokuzdan altıya kadar açık." },
      { type: "example", en: "We worked from morning until night.", tr: "Sabahtan geceye kadar çalıştık." },
      { type: "rule", text: "EVERY OTHER DAY (gün aşırı), ONCE A WEEK (haftada bir), TWICE A MONTH (ayda iki kez) gibi sıklık ifadeleri de zaman anlatımında sık kullanılır." },
      { type: "example", en: "I go to the gym three times a week.", tr: "Haftada üç kez spor salonuna gidiyorum." },
      { type: "example", en: "We visit our grandparents every other weekend.", tr: "Büyükanne ve büyükbabamızı hafta aşırı ziyaret ediyoruz." },
      { type: "rule", text: "NEXT ve LAST kelimeleri zaman ifadelerinde bir gün/hafta/ay/yıl öncesini veya sonrasını belirtir: NEXT WEEK, LAST MONTH, NEXT YEAR." },
      { type: "example", en: "We are moving to a new house next month.", tr: "Gelecek ay yeni bir eve taşınıyoruz." },
      { type: "example", en: "I saw her last week at the market.", tr: "Onu geçen hafta pazarda gördüm." },
      { type: "rule", text: "THE DAY BEFORE YESTERDAY (evvelsi gün) ve THE DAY AFTER TOMORROW (öbür gün) gibi daha spesifik zaman ifadelerini de bilmek faydalıdır." },
      { type: "example", en: "I met him the day before yesterday.", tr: "Onunla evvelsi gün karşılaştım." },
      { type: "example", en: "The package will arrive the day after tomorrow.", tr: "Paket öbür gün gelecek." },
    ],
  },
  {
    fileBase: "23_Past_Perfect",
    title: "GEÇMİŞTEN ÖNCEKİ GEÇMİŞ ZAMAN (PAST PERFECT)",
    blocks: [
      { type: "rule", text: "Past Perfect; geçmişte gerçekleşen iki olaydan daha önce yaşanmış olanı belirtmek için kullanılır. Yani \"geçmişin geçmişi\"dir." },
      { type: "rule", text: "Yapı: Özne + HAD + Fiil (3. hal / V3). HAD bütün öznelerde aynı kalır." },
      { type: "pattern", text: "ÖZNE + HAD + V3" },
      { type: "example", en: "The train had already left when we arrived.", tr: "Biz vardığımızda tren çoktan gitmişti." },
      { type: "example", en: "She had finished her homework before dinner.", tr: "O, akşam yemeğinden önce ödevini bitirmişti." },
      { type: "example", en: "They had already sold the house before we called.", tr: "Biz aramadan önce evi çoktan satmışlardı." },
      { type: "rule", text: "Olumsuz yapı: Özne + HADN'T + V3." },
      { type: "example", en: "I hadn't seen him before that day.", tr: "O günden önce onu görmemiştim." },
      { type: "example", en: "We hadn't finished the report before the deadline.", tr: "Son teslim tarihinden önce raporu bitirmemiştik." },
      { type: "rule", text: "Soru yapısı: HAD + Özne + V3?" },
      { type: "example", en: "Had they left before you called?", tr: "Sen aradığında onlar gitmiş miydi?" },
      { type: "example", en: "Had she eaten before the meeting?", tr: "Toplantıdan önce o yemek yemiş miydi?" },
      { type: "rule", text: "Past Perfect genellikle BEFORE (önce) ve AFTER (sonra) bağlaçlarıyla, iki geçmiş olay arasındaki sırayı netleştirmek için kullanılır." },
      { type: "example", en: "He had already eaten before I arrived.", tr: "Ben varmadan önce o çoktan yemek yemişti." },
      { type: "example", en: "After she had finished her work, she went home.", tr: "İşini bitirdikten sonra eve gitti." },
      { type: "rule", text: "Eğer iki olay arasındaki sıra BEFORE/AFTER ile zaten açıksa, günlük konuşmada Past Simple de kullanılabilir; ama Past Perfect anlamı daha net kılar." },
      { type: "example", en: "By the time we got there, the movie had already started.", tr: "Biz oraya vardığımızda film çoktan başlamıştı." },
      { type: "rule", text: "Past Perfect'in V3 hâli, Present Perfect'te kullanılan aynı 3. hal fiillerdir (go-gone, see-seen, write-written vb.), sadece yardımcı fiil HAVE/HAS yerine HAD olur." },
      { type: "example", en: "I realized that I had forgotten my wallet.", tr: "Cüzdanımı unuttuğumu fark ettim." },
      { type: "rule", text: "Kısaltma: konuşma dilinde HAD genellikle 'D olarak kısaltılır." },
      { type: "example", en: "I'd never seen such a beautiful view before.", tr: "Daha önce hiç böyle güzel bir manzara görmemiştim." },
      { type: "rule", text: "Past Perfect, dolaylı anlatımda (reported speech) bir konuşmacının geçmişte söylediği bir cümleyi aktarırken de kullanılır." },
      { type: "example", en: "He said that he had already paid the bill.", tr: "Faturayı çoktan ödediğini söyledi." },
      { type: "example", en: "She told me that she had never been abroad.", tr: "Bana hiç yurt dışına çıkmadığını söyledi." },
      { type: "rule", text: "Soru-cevap alıştırması: Past Perfect ile kurulmuş birkaç örnek daha inceleyelim." },
      { type: "example", en: "Why hadn't they informed us before?", tr: "Onlar bizi neden daha önce bilgilendirmemişti?" },
      { type: "example", en: "Everything had changed by the time we returned.", tr: "Biz döndüğümüzde her şey değişmişti." },
      { type: "example", en: "The lights had already gone out when we entered the room.", tr: "Biz odaya girdiğimizde ışıklar çoktan sönmüştü." },
      { type: "rule", text: "Past Perfect, NO SOONER...THAN ve HARDLY/SCARCELY...WHEN gibi devrik (inverted) yapılarda da kullanılır; bu yapılar bir olayın hemen ardından başka bir olayın gerçekleştiğini vurgular." },
      { type: "pattern", text: "NO SOONER + HAD + ÖZNE + V3 + THAN + Past Simple = ...ar ...maz" },
      { type: "example", en: "No sooner had we arrived than it started to rain.", tr: "Biz varır varmaz yağmur yağmaya başladı." },
      { type: "example", en: "Hardly had she sat down when the phone rang.", tr: "O oturur oturmaz telefon çaldı." },
      { type: "rule", text: "Past Perfect, IF ile kurulan üçüncü tip şart cümlelerinde (Third Conditional) geçmişteki gerçekleşmemiş bir durumu anlatmak için kullanılır." },
      { type: "pattern", text: "IF + ÖZNE + HAD + V3, ÖZNE + WOULD HAVE + V3" },
      { type: "example", en: "If I had known about the meeting, I would have attended.", tr: "Toplantıdan haberim olsaydı katılırdım." },
      { type: "example", en: "If she had studied harder, she would have passed the exam.", tr: "Daha çok çalışsaydı sınavı geçerdi." },
      { type: "rule", text: "WISH + HAD + V3 kalıbı, geçmişte yapılmayan bir şey için pişmanlık ifade eder." },
      { type: "pattern", text: "WISH + ÖZNE + HAD + V3 = keşke ...saydım" },
      { type: "example", en: "I wish I had told her the truth.", tr: "Keşke ona gerçeği söyleseydim." },
      { type: "example", en: "He wishes he hadn't sold his old car.", tr: "Keşke eski arabasını satmasaydı." },
      { type: "rule", text: "Past Perfect, bir hikâyenin akışında geçmişteki olayları doğru sırayla anlatmak için çok kullanışlıdır." },
      { type: "example", en: "By the time the police arrived, the thief had already escaped.", tr: "Polis vardığında hırsız çoktan kaçmıştı." },
      { type: "example", en: "She realized she had left her passport at home.", tr: "Pasaportunu evde bıraktığını fark etti." },
      { type: "example", en: "We had never met before that party.", tr: "O partiden önce hiç tanışmamıştık." },
      { type: "rule", text: "Past Perfect ile Past Simple'ı aynı cümlede kullanarak zaman sırasını netleştiren daha fazla örnek görelim." },
      { type: "example", en: "When I got to the airport, the plane had already taken off.", tr: "Havaalanına vardığımda uçak çoktan kalkmıştı." },
      { type: "example", en: "After we had eaten dinner, we watched a movie together.", tr: "Akşam yemeğini yedikten sonra birlikte film izledik." },
      { type: "example", en: "She had already left the office when I called.", tr: "Ben aradığımda o ofisten çoktan ayrılmıştı." },
      { type: "rule", text: "Son olarak Past Perfect'in bütün kullanımlarını içeren karma bir tekrar bölümü görelim." },
      { type: "example", en: "I couldn't recognize the city because it had changed so much.", tr: "Şehri tanıyamadım çünkü çok değişmişti." },
      { type: "example", en: "By the time we had finished packing, it was already midnight.", tr: "Toplanmayı bitirdiğimizde saat çoktan gece yarısıydı." },
      { type: "example", en: "He told me he had never eaten sushi before that dinner.", tr: "Bana o akşam yemeğinden önce hiç suşi yemediğini söyledi." },
      { type: "rule", text: "Past Perfect'in düzenli fiillerle çekimini tam bir örnek üzerinden görelim: FINISH (bitirmek) fiili." },
      { type: "pattern", text: "TAM ÇEKİM: FINISH (BİTİRMEK) — PAST PERFECT" },
      { type: "example", en: "I had finished my work before he called.", tr: "O aramadan önce işimi bitirmiştim." },
      { type: "example", en: "You had finished your work before he called.", tr: "Sen o aramadan önce işini bitirmiştin." },
      { type: "example", en: "She had finished her work before he called.", tr: "O, o aramadan önce işini bitirmişti." },
      { type: "example", en: "We had finished our work before he called.", tr: "Biz o aramadan önce işimizi bitirmiştik." },
      { type: "example", en: "They had finished their work before he called.", tr: "Onlar o aramadan önce işlerini bitirmişti." },
      { type: "rule", text: "Şimdi de olumsuz ve soru hâllerini görelim." },
      { type: "example", en: "I hadn't finished my work before he called.", tr: "O aramadan önce işimi bitirmemiştim." },
      { type: "example", en: "Had you finished your work before he called?", tr: "O aramadan önce işini bitirmiş miydin?" },
      { type: "rule", text: "Past Perfect, bir eylemin gerçekleşmesinin ne kadar sürdüğünü belirtmek için Past Perfect Continuous ile karşılaştırılabilir; ancak Past Perfect sonuca, Past Perfect Continuous ise sürece odaklanır." },
      { type: "example", en: "I had cleaned the house before the guests arrived. (sonuç)", tr: "Misafirler gelmeden önce evi temizlemiştim (bitmiş hâli önemli)." },
      { type: "rule", text: "Past Perfect, seyahat ve deneyim anlatırken de sıkça kullanılır: bir yere gitmeden önce daha önce orada bulunup bulunmadığını anlatmak için." },
      { type: "example", en: "I had never been to Italy before that trip.", tr: "O geziden önce hiç İtalya'da bulunmamıştım." },
      { type: "example", en: "Had you ever tried Japanese food before you moved there?", tr: "Oraya taşınmadan önce hiç Japon yemeği denemiş miydin?" },
      { type: "rule", text: "Sık yapılan bir hata, iki geçmiş olay arasında net bir öncelik sırası yokken gereksiz yere Past Perfect kullanmaktır; sıra net değilse Past Simple yeterlidir." },
      { type: "example", en: "I ate breakfast and then went to work. (basit sıra, Past Perfect gerekmez)", tr: "Kahvaltı ettim ve sonra işe gittim." },
      { type: "rule", text: "Son olarak bu dersteki bütün yapıları içeren bir kapanış paragrafı görelim." },
      { type: "example", en: "By the time she turned thirty, she had already achieved everything she had dreamed of.", tr: "O otuz yaşına geldiğinde hayalini kurduğu her şeyi çoktan başarmıştı." },
      { type: "example", en: "We hadn't expected such a warm welcome when we arrived at the village.", tr: "Köye vardığımızda bu kadar sıcak bir karşılama beklemiyorduk." },
      { type: "rule", text: "Past Perfect, bir mazeret ya da açıklama sunarken de kullanışlıdır: bir şeyin neden olmadığını geçmişteki bir sebeple açıklamak için." },
      { type: "example", en: "I couldn't call you because I had lost my phone.", tr: "Seni arayamadım çünkü telefonumu kaybetmiştim." },
      { type: "example", en: "She didn't recognize him because he had changed so much.", tr: "Onu tanıyamadı çünkü o çok değişmişti." },
      { type: "rule", text: "Past Perfect'in ALREADY/JUST ile kullanımını pekiştiren birkaç örnek daha görelim." },
      { type: "example", en: "By six o'clock, we had already had dinner.", tr: "Saat altıya kadar akşam yemeğini çoktan yemiştik." },
      { type: "example", en: "He had just left when the phone rang.", tr: "Telefon çaldığında o daha yeni ayrılmıştı." },
      { type: "rule", text: "Past Perfect'in kullanıldığı bir mini hikaye örneğiyle dersi kapatalım." },
      { type: "example", en: "When she opened the fridge, she realized that someone had eaten all the cake she had baked the night before.", tr: "Buzdolabını açtığında, önceki gece pişirdiği pastanın tamamını birinin yediğini fark etti." },
      { type: "example", en: "The waiter brought the wrong dish because he hadn't listened carefully to our order.", tr: "Garson yanlış yemeği getirdi çünkü siparişimizi dikkatlice dinlememişti." },
      { type: "example", en: "We finally found the restaurant, even though we had gotten lost twice on the way.", tr: "Yolda iki kez kaybolmuş olsak da sonunda restoranı bulduk." },
      { type: "rule", text: "Past Perfect ile kurulmuş soru-cevap alıştırmalarını çoğaltalım; bu, hem yapıyı hem de düzensiz fiilleri pekiştirir." },
      { type: "example", en: "Had you eaten before the party started? — Yes, I had already eaten at home.", tr: "Parti başlamadan önce yemek yemiş miydin? — Evet, evde çoktan yemiştim." },
      { type: "example", en: "Had they finished the project by the deadline? — No, they hadn't finished it in time.", tr: "Son teslim tarihine kadar projeyi bitirmişler miydi? — Hayır, zamanında bitirmemişlerdi." },
      { type: "rule", text: "Past Perfect, bir yerin ya da durumun beklenmedik şekilde değiştiğini anlatırken de sıkça kullanılır." },
      { type: "example", en: "The prices had risen so much that we couldn't afford the trip anymore.", tr: "Fiyatlar o kadar artmıştı ki artık geziyi karşılayamıyorduk." },
      { type: "example", en: "The company had grown rapidly over the past five years.", tr: "Şirket son beş yılda hızla büyümüştü." },
      { type: "rule", text: "Son olarak Past Perfect'i pekiştiren uzun bir hikaye paragrafı görelim." },
      { type: "example", en: "By the time the ambulance arrived, the doctors had already stabilized the patient, and everyone had calmed down a little.", tr: "Ambulans vardığında, doktorlar hastayı çoktan stabilize etmişti ve herkes biraz sakinleşmişti." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
