import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "05_Am_Is_Are",
    title: "AM - IS - ARE VE DUYGU SIFATLARI",
    blocks: [
      { type: "rule", text: "AM / IS / ARE, Türkçedeki \"-im, -sin, -dir\" gibi eklerin karşılığıdır ve \"olmak\" fiilinin geniş zaman hâlidir." },
      { type: "pattern", text: "I + AM        HE / SHE / IT + IS        YOU / WE / THEY + ARE" },
      { type: "example", en: "I am ready.", tr: "Ben hazırım." },
      { type: "example", en: "She is at work.", tr: "O işte." },
      { type: "example", en: "We are students.", tr: "Biz öğrenciyiz." },
      { type: "example", en: "They are friends.", tr: "Onlar arkadaş." },
      { type: "rule", text: "Olumsuz yapı: AM NOT / ISN'T / AREN'T. Soru yapısında AM/IS/ARE cümlenin başına gelir." },
      { type: "example", en: "Where are you?", tr: "Neredesin?" },
      { type: "example", en: "I am at home, not at work.", tr: "Evdeyim, işte değilim." },
      { type: "example", en: "Is he in Istanbul?", tr: "O İstanbul'da mı?" },
      { type: "example", en: "We aren't at the office today.", tr: "Bugün ofiste değiliz." },
      { type: "rule", text: "AM/IS/ARE ile birlikte kullanılan durum sıfatları: READY (hazır), SURE (emin), RIGHT (haklı), ILL (hasta), TIRED (yorgun), HUNGRY (aç), THIRSTY (susamış), FULL (tok/dolu)." },
      { type: "example", en: "Are you sure?", tr: "Emin misin?" },
      { type: "example", en: "I am hungry, but I am not thirsty.", tr: "Açım ama susamadım." },
      { type: "example", en: "He is ill today, so he isn't at school.", tr: "O bugün hasta, bu yüzden okulda değil." },
      { type: "example", en: "You are right, I am wrong.", tr: "Sen haklısın, ben yanılıyorum." },
      { type: "rule", text: "Duygu sıfatları: ANGRY (kızgın), HAPPY (mutlu), SAD (üzgün), BORED (sıkılmış), EXCITED (heyecanlı)." },
      { type: "example", en: "Why are you angry?", tr: "Neden kızgınsın?" },
      { type: "example", en: "We are so excited about the trip.", tr: "Gezi için çok heyecanlıyız." },
      { type: "example", en: "She is sad because of the news.", tr: "O haber yüzünden üzgün." },
      { type: "example", en: "Are the children bored?", tr: "Çocuklar sıkıldı mı?" },
      { type: "rule", text: "Haftanın günleri: MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY." },
      { type: "rule", text: "Günlerin başında \"ON\" edatı kullanılır." },
      { type: "example", en: "I am busy on Monday.", tr: "Pazartesi meşgulüm." },
      { type: "example", en: "Are you free on Sunday?", tr: "Pazar günü müsait misin?" },
      { type: "example", en: "We aren't at home on Fridays.", tr: "Cuma günleri evde değiliz." },
      { type: "rule", text: "AM/IS/ARE'ın tam çekim tablosunu READY sıfatıyla tekrar edelim." },
      { type: "pattern", text: "BE READY (OLUMLU / OLUMSUZ / SORU)" },
      { type: "example", en: "I am ready for the exam.", tr: "Sınava hazırım." },
      { type: "example", en: "You are ready for the exam.", tr: "Sınava hazırsın." },
      { type: "example", en: "He is ready for the exam.", tr: "O sınava hazır." },
      { type: "example", en: "She isn't ready for the interview.", tr: "O mülakata hazır değil." },
      { type: "example", en: "We aren't ready yet.", tr: "Henüz hazır değiliz." },
      { type: "example", en: "Are they ready to leave?", tr: "Onlar ayrılmaya hazır mı?" },
      { type: "example", en: "Is it ready?", tr: "O (nesne) hazır mı?" },
      { type: "rule", text: "Daha fazla durum ve duygu sıfatı ile örnek cümleler kuralım." },
      { type: "example", en: "I am not sure about this decision.", tr: "Bu karardan emin değilim." },
      { type: "example", en: "He is full, he doesn't want more food.", tr: "O tok, daha fazla yemek istemiyor." },
      { type: "example", en: "Is she thirsty?", tr: "O susadı mı?" },
      { type: "example", en: "We are so happy for you.", tr: "Senin için çok mutluyuz." },
      { type: "example", en: "Why is he so sad these days?", tr: "O son zamanlarda neden bu kadar üzgün?" },
      { type: "example", en: "The kids are bored at home.", tr: "Çocuklar evde sıkılıyor." },
      { type: "rule", text: "Haftanın günleriyle daha fazla örnek cümle görelim." },
      { type: "example", en: "The meeting is on Wednesday.", tr: "Toplantı çarşamba günü." },
      { type: "example", en: "Is the shop open on Tuesday?", tr: "Dükkan salı günü açık mı?" },
      { type: "example", en: "I'm not working on Thursday.", tr: "Perşembe çalışmıyorum." },
      { type: "rule", text: "WHERE ARE YOU FROM? (Nerelisin?) kalıbı ile bazı örnekler görelim." },
      { type: "example", en: "Where are you from? I'm from Turkey.", tr: "Nerelisin? Türkiye'denim." },
      { type: "example", en: "Where is she from?", tr: "O nereli?" },
      { type: "rule", text: "AM/IS/ARE ile kurulan daha fazla örnek cümleyle bu dersi pekiştirelim." },
      { type: "example", en: "This bag is very heavy.", tr: "Bu çanta çok ağır." },
      { type: "example", en: "These shoes are too small for me.", tr: "Bu ayakkabılar bana çok küçük." },
      { type: "example", en: "Is the coffee too hot?", tr: "Kahve çok mu sıcak?" },
      { type: "example", en: "The children are quiet now.", tr: "Çocuklar şimdi sessiz." },
      { type: "example", en: "I'm not afraid of the dark.", tr: "Karanlıktan korkmuyorum." },
      { type: "example", en: "Are you afraid of spiders?", tr: "Örümceklerden korkar mısın?" },
      { type: "example", en: "This exercise is difficult.", tr: "Bu alıştırma zor." },
      { type: "example", en: "The instructions aren't clear.", tr: "Talimatlar net değil." },
      { type: "rule", text: "IS THERE / ARE THERE kalıbı ile AM/IS/ARE'ı pekiştirelim (bu yapı ileride ayrıca işlenecektir)." },
      { type: "example", en: "Is there a bank near here?", tr: "Buraya yakın bir banka var mı?" },
      { type: "example", en: "Are there any messages for me?", tr: "Benim için herhangi bir mesaj var mı?" },
      { type: "rule", text: "Rengin, boyutun ve şeklin anlatıldığı basit AM/IS/ARE cümleleriyle konuyu tamamlayalım." },
      { type: "example", en: "The walls are white.", tr: "Duvarlar beyaz." },
      { type: "example", en: "My car is black and quite old.", tr: "Arabam siyah ve oldukça eski." },
      { type: "rule", text: "Duygu ve durum sıfatlarını konuşma pratiği için soru-cevap şeklinde tekrar edelim." },
      { type: "example", en: "Are you hungry? Yes, a little.", tr: "Aç mısın? Evet, biraz." },
      { type: "example", en: "Is he tired? Yes, he worked all day.", tr: "O yorgun mu? Evet, bütün gün çalıştı." },
      { type: "example", en: "Are you excited about the trip? Yes, very much!", tr: "Gezi için heyecanlı mısın? Evet, çok!" },
      { type: "example", en: "Is she angry with you? I don't think so.", tr: "O sana kızgın mı? Sanmıyorum." },
      { type: "rule", text: "Cansız nesnelerin özelliklerini anlatan birkaç örnek daha görelim." },
      { type: "example", en: "This coffee is too bitter.", tr: "Bu kahve çok acı." },
      { type: "example", en: "The room is a bit dark.", tr: "Oda biraz karanlık." },
      { type: "example", en: "These questions are not that hard.", tr: "Bu sorular o kadar da zor değil." },
      { type: "rule", text: "AM/IS/ARE ile meslek ve milliyet bildiren örnek cümleler kuralım." },
      { type: "example", en: "He is an engineer.", tr: "O bir mühendis." },
      { type: "example", en: "Are you Turkish or German?", tr: "Sen Türk müsün yoksa Alman mısın?" },
      { type: "example", en: "She is a very talented singer.", tr: "O çok yetenekli bir şarkıcı." },
      { type: "example", en: "We are not from this city.", tr: "Biz bu şehirden değiliz." },
      { type: "example", en: "Is he a good teacher?", tr: "O iyi bir öğretmen mi?" },
      { type: "example", en: "My parents are both retired.", tr: "Anne babam ikisi de emekli." },
      { type: "rule", text: "Bu dersteki bütün kalıpları özetleyen son bir alıştırma bölümü ekleyelim." },
      { type: "example", en: "Is the milk still fresh?", tr: "Süt hâlâ taze mi?" },
      { type: "example", en: "We are proud of our team.", tr: "Takımımızla gurur duyuyoruz." },
      { type: "example", en: "The exam is on Friday, not Thursday.", tr: "Sınav perşembe değil cuma günü." },
      { type: "example", en: "Am I late for the class?", tr: "Derse geç mi kaldım?" },
      { type: "example", en: "The children are polite and friendly.", tr: "Çocuklar kibar ve arkadaş canlısı." },
      { type: "example", en: "Is your phone charged?", tr: "Telefonun şarj oldu mu?" },
      { type: "example", en: "We aren't ready to make a decision yet.", tr: "Henüz karar vermeye hazır değiliz." },
      { type: "example", en: "Are the results official yet?", tr: "Sonuçlar resmi mi henüz?" },
      { type: "example", en: "This soup isn't hot enough.", tr: "Bu çorba yeterince sıcak değil." },
    ],
  },
  {
    fileBase: "06_Simdiki_Zaman",
    title: "ŞİMDİKİ ZAMAN (PRESENT CONTINUOUS)",
    blocks: [
      { type: "rule", text: "Şimdiki zaman; konuşma anında olmakta olan eylemleri ve geçici durumları anlatmak için kullanılır." },
      { type: "rule", text: "Yapı: Özne + AM/IS/ARE + Fiil-ING." },
      { type: "pattern", text: "I + AM + V-ing        HE / SHE / IT + IS + V-ing        YOU / WE / THEY + ARE + V-ing" },
      { type: "example", en: "I am working now.", tr: "Şu anda çalışıyorum." },
      { type: "example", en: "She is sleeping.", tr: "O uyuyor." },
      { type: "example", en: "We are having dinner.", tr: "Akşam yemeği yiyoruz." },
      { type: "rule", text: "-ING eki kuralları: Fiil sessiz harfle bitip önünde tek ünlü varsa son harf ikizlenir (run-running, stop-stopping). Fiil sessiz \"E\" ile bitiyorsa E düşer (write-writing, make-making). Fiil \"IE\" ile bitiyorsa \"YING\" olur (lie-lying, die-dying)." },
      { type: "example", en: "He is writing a letter.", tr: "O bir mektup yazıyor." },
      { type: "example", en: "They are running to the bus stop.", tr: "Onlar otobüs durağına doğru koşuyorlar." },
      { type: "example", en: "She is making a cake.", tr: "O bir kek yapıyor." },
      { type: "rule", text: "Olumsuz yapı: Özne + AM NOT / ISN'T / AREN'T + Fiil-ING." },
      { type: "example", en: "They aren't listening to us.", tr: "Onlar bizi dinlemiyor." },
      { type: "example", en: "I'm not joking.", tr: "Şaka yapmıyorum." },
      { type: "rule", text: "Soru yapısı: AM/IS/ARE + Özne + Fiil-ING?" },
      { type: "example", en: "Are you coming with us?", tr: "Bizimle geliyor musun?" },
      { type: "example", en: "What is he doing?", tr: "O ne yapıyor?" },
      { type: "example", en: "Why are they shouting?", tr: "Onlar neden bağırıyor?" },
      { type: "rule", text: "Şimdiki zaman sıkça NOW (şimdi), AT THE MOMENT (şu anda), RIGHT NOW (hemen şimdi) gibi zarflarla birlikte kullanılır." },
      { type: "example", en: "It is raining right now.", tr: "Şu anda yağmur yağıyor." },
      { type: "example", en: "What are you doing at the moment?", tr: "Şu anda ne yapıyorsun?" },
      { type: "rule", text: "Şimdiki zaman ayrıca yakın gelecekte planlanmış eylemleri anlatmak için de kullanılabilir." },
      { type: "example", en: "We are meeting them tomorrow.", tr: "Yarın onlarla buluşuyoruz." },
      { type: "example", en: "I am flying to London next week.", tr: "Gelecek hafta Londra'ya uçuyorum." },
      { type: "rule", text: "LIKE, KNOW, BELIEVE, UNDERSTAND, WANT gibi duygu/düşünce bildiren fiiller normalde şimdiki zamanda kullanılmaz, geniş zamanla kullanılır." },
      { type: "example", en: "I understand you. (Değil: I am understanding you.)", tr: "Seni anlıyorum." },
      { type: "example", en: "She likes this song. (Değil: She is liking this song.)", tr: "O bu şarkıyı seviyor." },
      { type: "rule", text: "\"PLAY\" fiili üzerinden tam çekim tablosunu inceleyelim." },
      { type: "pattern", text: "PLAY (OLUMLU / OLUMSUZ / SORU)" },
      { type: "example", en: "I am playing football right now.", tr: "Şu anda futbol oynuyorum." },
      { type: "example", en: "You are playing well today.", tr: "Bugün iyi oynuyorsun." },
      { type: "example", en: "He is playing the guitar.", tr: "O gitar çalıyor." },
      { type: "example", en: "She isn't playing with her friends.", tr: "O arkadaşlarıyla oynamıyor." },
      { type: "example", en: "We aren't playing today.", tr: "Bugün oynamıyoruz." },
      { type: "example", en: "Are they playing outside?", tr: "Onlar dışarıda mı oynuyor?" },
      { type: "example", en: "Is it working properly?", tr: "O (nesne) düzgün çalışıyor mu?" },
      { type: "rule", text: "Daha fazla günlük hayat örneğiyle şimdiki zamanı pekiştirelim." },
      { type: "example", en: "The children are watching cartoons.", tr: "Çocuklar çizgi film izliyor." },
      { type: "example", en: "My mother is cooking dinner.", tr: "Annem akşam yemeği pişiriyor." },
      { type: "example", en: "Why is he crying?", tr: "O neden ağlıyor?" },
      { type: "example", en: "They are building a new house.", tr: "Onlar yeni bir ev inşa ediyorlar." },
      { type: "example", en: "I am reading a very interesting book.", tr: "Çok ilginç bir kitap okuyorum." },
      { type: "example", en: "She is trying to fix her computer.", tr: "O bilgisayarını tamir etmeye çalışıyor." },
      { type: "rule", text: "Şimdiki zaman genellikle değişen ya da gelişmekte olan durumları da anlatır (GETTING + sıfat)." },
      { type: "example", en: "The weather is getting colder.", tr: "Hava soğuyor." },
      { type: "example", en: "Prices are getting higher every year.", tr: "Fiyatlar her yıl yükseliyor." },
      { type: "example", en: "He is getting better at English.", tr: "O İngilizcede gelişiyor." },
      { type: "rule", text: "Şimdiki zamanla daha fazla soru-cevap alıştırması yapalım." },
      { type: "example", en: "What are you doing tonight? I'm staying home.", tr: "Bu gece ne yapıyorsun? Evde kalıyorum." },
      { type: "example", en: "Who is he talking to? He is talking to his boss.", tr: "O kiminle konuşuyor? Patronuyla konuşuyor." },
      { type: "example", en: "Why is she smiling? She is happy about her results.", tr: "O neden gülümsüyor? Sonuçlarından mutlu." },
      { type: "example", en: "Are you feeling okay?", tr: "İyi hissediyor musun?" },
      { type: "example", en: "I'm not feeling well today.", tr: "Bugün kendimi iyi hissetmiyorum." },
      { type: "rule", text: "Bu dersteki fiillerle karışık alıştırma cümleleri kuralım." },
      { type: "example", en: "The baby is sleeping, please be quiet.", tr: "Bebek uyuyor, lütfen sessiz olun." },
      { type: "example", en: "We are waiting for the bus.", tr: "Otobüsü bekliyoruz." },
      { type: "example", en: "He is currently living in Berlin.", tr: "O şu anda Berlin'de yaşıyor." },
      { type: "example", en: "They are planning a surprise party.", tr: "Onlar sürpriz bir parti planlıyorlar." },
      { type: "rule", text: "Şimdiki zamanı içeren birkaç kısa diyalog cümlesiyle bu dersi tamamlayalım." },
      { type: "example", en: "Hold on, I'm coming!", tr: "Bekle, geliyorum!" },
      { type: "example", en: "Look, it's snowing!", tr: "Bak, kar yağıyor!" },
      { type: "example", en: "She's getting married next month.", tr: "O gelecek ay evleniyor." },
      { type: "example", en: "I'm thinking about changing my job.", tr: "İşimi değiştirmeyi düşünüyorum." },
      { type: "example", en: "Are you still waiting for the results?", tr: "Hâlâ sonuçları mı bekliyorsun?" },
      { type: "example", en: "The situation is improving slowly.", tr: "Durum yavaş yavaş iyileşiyor." },
      { type: "rule", text: "Şimdiki zamanla kurulmuş daha fazla örnek cümleyle konuyu pekiştirelim." },
      { type: "example", en: "He is talking on the phone right now.", tr: "O şu anda telefonda konuşuyor." },
      { type: "example", en: "We are learning a lot in this course.", tr: "Bu kursta çok şey öğreniyoruz." },
      { type: "example", en: "The company is opening a new branch.", tr: "Şirket yeni bir şube açıyor." },
      { type: "example", en: "I'm not working this week.", tr: "Bu hafta çalışmıyorum." },
      { type: "example", en: "Is your brother studying abroad?", tr: "Kardeşin yurt dışında mı okuyor?" },
      { type: "example", en: "They are fixing the road outside.", tr: "Dışarıda yolu tamir ediyorlar." },
      { type: "example", en: "Why is the printer not working?", tr: "Yazıcı neden çalışmıyor?" },
      { type: "rule", text: "Şimdiki zamanla ilgili son bir tekrar bölümü ekleyelim." },
      { type: "example", en: "Are you still working on the same project?", tr: "Hâlâ aynı proje üzerinde mi çalışıyorsun?" },
      { type: "example", en: "The kids are growing up so fast.", tr: "Çocuklar çok hızlı büyüyor." },
      { type: "example", en: "I'm considering moving to a new city.", tr: "Yeni bir şehre taşınmayı düşünüyorum." },
      { type: "example", en: "Something smells great in the kitchen.", tr: "Mutfakta harika bir şey kokuyor." },
      { type: "example", en: "He isn't answering his phone.", tr: "O telefonuna cevap vermiyor." },
      { type: "example", en: "We are running out of time.", tr: "Zamanımız azalıyor." },
      { type: "example", en: "The dog is barking at the mailman.", tr: "Köpek postacıya havlıyor." },
      { type: "example", en: "Is anyone using this chair?", tr: "Bu sandalyeyi kullanan var mı?" },
      { type: "rule", text: "Şimdiki zamanla ilgili birkaç ek örnek daha ekleyerek bu dersi tamamlayalım." },
      { type: "example", en: "The company is losing money this year.", tr: "Şirket bu yıl para kaybediyor." },
      { type: "example", en: "I am considering two job offers.", tr: "İki iş teklifini değerlendiriyorum." },
      { type: "example", en: "She is wearing a red dress today.", tr: "O bugün kırmızı bir elbise giyiyor." },
      { type: "example", en: "We are celebrating our anniversary tonight.", tr: "Bu gece yıl dönümümüzü kutluyoruz." },
      { type: "example", en: "The traffic is getting worse every day.", tr: "Trafik her gün daha da kötüleşiyor." },
    ],
  },
  {
    fileBase: "07_Gunluk_Fiiller_ve_Edatlar",
    title: "GÜNLÜK FİİLLER VE EDATLAR",
    blocks: [
      { type: "pattern", text: "TELL = anlatmak, söylemek / INFORM = bilgilendirmek" },
      { type: "example", en: "Tell me the truth.", tr: "Bana gerçeği söyle." },
      { type: "example", en: "Please inform us as soon as possible.", tr: "Lütfen bize en kısa zamanda haber verin." },
      { type: "pattern", text: "TAKE = almak / GIVE = vermek / TAKE A PHOTO = fotoğraf çekmek" },
      { type: "example", en: "Can you take a photo of us?", tr: "Bizim fotoğrafımızı çeker misin?" },
      { type: "example", en: "She gave me her number.", tr: "O bana numarasını verdi." },
      { type: "pattern", text: "REST = dinlenmek (fiil) / dinlenme (isim)" },
      { type: "example", en: "I need some rest, so I will rest today.", tr: "Biraz dinlenmeye ihtiyacım var, bu yüzden bugün dinleneceğim." },
      { type: "rule", text: "HAVE (sahip olmak) olumsuz yapılırken iki şekilde kurulabilir: DON'T HAVE ya da HAVE NO." },
      { type: "example", en: "I don't have a car. = I have no car.", tr: "Arabam yok." },
      { type: "example", en: "He doesn't have time. = He has no time.", tr: "Onun zamanı yok." },
      { type: "example", en: "We don't have any problem. = We have no problem.", tr: "Hiçbir sorunumuz yok." },
      { type: "pattern", text: "DISTURB = rahatsız etmek / LISTEN + TO = dinlemek / CALL = aramak, telefon etmek" },
      { type: "example", en: "Don't disturb him, he is listening to music.", tr: "Onu rahatsız etme, müzik dinliyor." },
      { type: "example", en: "I will call you later.", tr: "Seni sonra ararım." },
      { type: "pattern", text: "TRUST = güvenmek" },
      { type: "example", en: "Can I trust you?", tr: "Sana güvenebilir miyim?" },
      { type: "example", en: "I don't trust him anymore.", tr: "Artık ona güvenmiyorum." },
      { type: "pattern", text: "PAY = ödemek / PAY IN CASH, PAY BY CREDIT CARD = nakit/kredi kartıyla ödemek" },
      { type: "example", en: "Will you pay in cash or by credit card?", tr: "Nakit mi yoksa kredi kartıyla mı ödeyeceksin?" },
      { type: "example", en: "Who will pay the bill?", tr: "Hesabı kim ödeyecek?" },
      { type: "pattern", text: "SEND = göndermek / RECEIVE = almak, teslim almak / DOCUMENT, PAYMENT = belge, ödeme" },
      { type: "example", en: "I will send the document, and you will receive the payment.", tr: "Belgeyi göndereceğim, sen de ödemeyi alacaksın." },
      { type: "example", en: "Did you receive my email?", tr: "E-postamı aldın mı?" },
      { type: "pattern", text: "BRING = getirmek / CANCEL = iptal etmek" },
      { type: "example", en: "Can you bring the bill?", tr: "Hesabı getirir misin?" },
      { type: "example", en: "They cancelled the meeting.", tr: "Toplantıyı iptal ettiler." },
      { type: "pattern", text: "SPEND = harcamak, geçirmek / DESERVE = hak etmek" },
      { type: "example", en: "How do you spend your time?", tr: "Zamanını nasıl geçiriyorsun?" },
      { type: "example", en: "He doesn't deserve this salary.", tr: "O bu maaşı hak etmiyor." },
      { type: "rule", text: "Nesne zamirleriyle kullanılan edatlar: FOR (için), WITH (ile), BECAUSE OF (yüzünden), INSTEAD OF (yerine) + ME/YOU/HIM/HER/US/YOU/THEM." },
      { type: "example", en: "This gift is for you.", tr: "Bu hediye senin için." },
      { type: "example", en: "I will go with him instead of her.", tr: "Onun yerine onunla gideceğim." },
      { type: "example", en: "We are late because of them.", tr: "Onlar yüzünden geç kaldık." },
      { type: "rule", text: "Bu fiillerle daha fazla günlük hayat cümlesi kuralım." },
      { type: "example", en: "Tell them I'm not available.", tr: "Onlara müsait olmadığımı söyle." },
      { type: "example", en: "Can you take the kids to school?", tr: "Çocukları okula götürebilir misin?" },
      { type: "example", en: "I trust my instincts.", tr: "İçgüdülerime güvenirim." },
      { type: "example", en: "She pays for everything with her card.", tr: "O her şeyi kartıyla ödüyor." },
      { type: "example", en: "We sent the invitations last week.", tr: "Davetiyeleri geçen hafta gönderdik." },
      { type: "example", en: "Please bring an umbrella, it might rain.", tr: "Lütfen şemsiye getir, yağmur yağabilir." },
      { type: "example", en: "How much time do you spend on your phone?", tr: "Telefonunda ne kadar zaman geçiriyorsun?" },
      { type: "example", en: "This trophy is for the winning team.", tr: "Bu kupa kazanan takım için." },
      { type: "example", en: "I did it with my friends, not alone.", tr: "Bunu yalnız değil, arkadaşlarımla yaptım." },
      { type: "example", en: "We chose the blue one instead of the red one.", tr: "Kırmızı yerine maviyi seçtik." },
      { type: "example", en: "Don't disturb me while I'm working.", tr: "Ben çalışırken beni rahatsız etme." },
      { type: "example", en: "Can I pay by card?", tr: "Kartla ödeyebilir miyim?" },
      { type: "rule", text: "TAKE ve GIVE fiillerinin daha fazla kullanımını görelim." },
      { type: "example", en: "It takes ten minutes to get there.", tr: "Oraya varmak on dakika sürer." },
      { type: "example", en: "He gave a great speech.", tr: "O harika bir konuşma yaptı." },
      { type: "example", en: "Give me a second, please.", tr: "Bana bir saniye ver lütfen." },
      { type: "rule", text: "Bu dersteki fiillerle daha fazla iş hayatı örneği görelim." },
      { type: "example", en: "We received the payment yesterday.", tr: "Ödemeyi dün aldık." },
      { type: "example", en: "The company cancelled the contract.", tr: "Şirket sözleşmeyi iptal etti." },
      { type: "example", en: "How much did you spend on the trip?", tr: "Gezide ne kadar para harcadın?" },
      { type: "example", en: "He deserves a promotion.", tr: "O bir terfiyi hak ediyor." },
      { type: "example", en: "I called them three times, but nobody answered.", tr: "Onları üç kez aradım ama kimse cevap vermedi." },
      { type: "rule", text: "Bu dersteki fiillerle günlük kısa diyaloglar kuralım." },
      { type: "example", en: "Could you tell him I called?", tr: "Ona aradığımı söyler misin?" },
      { type: "example", en: "I need to rest for a while.", tr: "Bir süre dinlenmem lazım." },
      { type: "example", en: "Don't trust everything you see online.", tr: "İnternette gördüğün her şeye güvenme." },
      { type: "example", en: "Can you send me the file today?", tr: "Bugün dosyayı bana gönderebilir misin?" },
      { type: "example", en: "They brought gifts for everyone.", tr: "Onlar herkes için hediye getirdiler." },
      { type: "rule", text: "Bu fiillerle daha fazla örnek cümle ile konuyu tamamlayalım." },
      { type: "example", en: "She takes the same bus every morning.", tr: "O her sabah aynı otobüse biner." },
      { type: "example", en: "We gave them our full support.", tr: "Onlara tam desteğimizi verdik." },
      { type: "example", en: "I trust him completely.", tr: "Ona tamamen güveniyorum." },
      { type: "example", en: "They pay their employees well.", tr: "Onlar çalışanlarına iyi ödeme yapıyor." },
      { type: "example", en: "Did she send the report yet?", tr: "O raporu henüz gönderdi mi?" },
      { type: "example", en: "Please bring your ID card.", tr: "Lütfen kimlik kartınızı getirin." },
      { type: "rule", text: "Bu dersteki fiillerle son bir tekrar bölümü ekleyelim." },
      { type: "example", en: "I don't have any cash on me.", tr: "Üzerimde hiç nakit yok." },
      { type: "example", en: "She takes good care of her plants.", tr: "O bitkilerine iyi bakar." },
      { type: "example", en: "We rested for an hour after lunch.", tr: "Öğle yemeğinden sonra bir saat dinlendik." },
      { type: "example", en: "Can you trust your first impression?", tr: "İlk izlenimine güvenebilir misin?" },
      { type: "example", en: "They deserve a proper explanation.", tr: "Onlar düzgün bir açıklamayı hak ediyor." },
      { type: "example", en: "I won't spend more than fifty dollars.", tr: "Elli dolardan fazla harcamayacağım." },
      { type: "example", en: "He gave up his seat for an elderly man.", tr: "O koltuğunu yaşlı bir adam için verdi." },
      { type: "example", en: "We trust each other completely.", tr: "Birbirimize tamamen güveniyoruz." },
      { type: "rule", text: "Bu fiillerle birkaç ek örnek daha ekleyerek dersi tamamlayalım." },
      { type: "example", en: "The teacher gives homework every day.", tr: "Öğretmen her gün ödev verir." },
      { type: "example", en: "I called the restaurant to book a table.", tr: "Masa ayırtmak için restoranı aradım." },
      { type: "example", en: "They didn't take responsibility for the mistake.", tr: "Hatanın sorumluluğunu almadılar." },
      { type: "example", en: "Can you tell the difference between them?", tr: "Aralarındaki farkı söyleyebilir misin?" },
      { type: "example", en: "She spends most of her time reading.", tr: "O zamanının çoğunu okuyarak geçirir." },
    ],
  },
  {
    fileBase: "08_Sorular_ve_Zamirler",
    title: "SORULAR VE DÖNÜŞLÜ ZAMİRLER",
    blocks: [
      { type: "pattern", text: "JOIN = katılmak / DECIDE = karar vermek / DECISION = karar" },
      { type: "example", en: "Join us!", tr: "Bize katıl!" },
      { type: "example", en: "I don't know his decision.", tr: "Onun kararını bilmiyorum." },
      { type: "pattern", text: "GUESS = sanmak, tahmin etmek" },
      { type: "example", en: "I guess he didn't call us.", tr: "Sanırım bizi aramadı." },
      { type: "rule", text: "HOW MUCH sayılamayan isimlerle, HOW MANY sayılabilen (çoğul) isimlerle kullanılır." },
      { type: "example", en: "How much money do you have?", tr: "Ne kadar paran var?" },
      { type: "example", en: "How many cars do they have?", tr: "Kaç arabaları var?" },
      { type: "example", en: "How many children do you have?", tr: "Kaç çocuğun var?" },
      { type: "rule", text: "Dönüşlü zamirler: MYSELF, YOURSELF, HIMSELF, HERSELF, OURSELVES, YOURSELVES, THEMSELVES." },
      { type: "example", en: "I'll improve myself.", tr: "Kendimi geliştireceğim." },
      { type: "example", en: "He should improve himself.", tr: "O kendini geliştirmeli." },
      { type: "example", en: "They did it themselves.", tr: "Onu kendileri yaptılar." },
      { type: "pattern", text: "BEHAVE = davranmak / BEHAVIOR = davranış" },
      { type: "example", en: "We didn't deserve this behavior.", tr: "Bu davranışı hak etmedik." },
      { type: "rule", text: "AGREE WITH = birine katılmak. AGREE (tek başına) = aynen, katılıyorum anlamında kullanılır." },
      { type: "example", en: "Unfortunately, he doesn't agree with us.", tr: "Maalesef o bize katılmıyor." },
      { type: "example", en: "I agree, let's postpone the trip.", tr: "Aynen, geziyi erteleyelim." },
      { type: "pattern", text: "FORGET = unutmak / REMEMBER = hatırlamak" },
      { type: "example", en: "Do you remember me?", tr: "Beni hatırlıyor musun?" },
      { type: "example", en: "Don't forget to call me.", tr: "Beni aramayı unutma." },
      { type: "rule", text: "RIGHT (hak) isim olarak kullanıldığında \"HUMAN RIGHTS\" (insan hakları) gibi kalıplar oluşturur." },
      { type: "example", en: "You have no right to do like this.", tr: "Bunu yapmaya hakkın yok." },
      { type: "pattern", text: "CRITICIZE = eleştirmek" },
      { type: "example", en: "He has no right to criticize us.", tr: "Onun bizi eleştirmeye hakkı yok." },
      { type: "rule", text: "İyelik 'S ile OF kalıbı aynı anlama gelir: (this girl's bike) = (the bike of this girl)." },
      { type: "example", en: "That man's car is expensive. = The car of that man is expensive.", tr: "O adamın arabası pahalı." },
      { type: "example", en: "This is my friend's house.", tr: "Bu arkadaşımın evi." },
      { type: "pattern", text: "LOOK (+AT) = bakmak / LOOK FOR = aramak, bulmaya çalışmak" },
      { type: "example", en: "I didn't find my passport.", tr: "Pasaportumu bulamadım." },
      { type: "example", en: "Look at that building!", tr: "Şu binaya bak!" },
      { type: "rule", text: "VERY / SO / TOO sıfat ve zarfları niteler. SO MUCH / SO MANY ve A LOT OF isimleri niteler (A LOT OF hem sayılabilen hem sayılamayan isimlerle kullanılır)." },
      { type: "example", en: "I am not ready enough.", tr: "Yeterince hazır değilim." },
      { type: "example", en: "We didn't study enough.", tr: "Yeterince çalışmadık." },
      { type: "example", en: "Can I have a cup of coffee?", tr: "Bir fincan kahve alabilir miyim?" },
      { type: "rule", text: "BE LATE = geç kalmak." },
      { type: "example", en: "I shouldn't be late.", tr: "Geç kalmamalıyım." },
      { type: "rule", text: "Mevsimler: SPRING (ilkbahar), SUMMER (yaz), AUTUMN/FALL (sonbahar), WINTER (kış). Mevsimlerde \"IN\" edatı kullanılır." },
      { type: "example", en: "It is usually hot in summer.", tr: "Yazın genellikle hava sıcak olur." },
      { type: "example", en: "We go skiing in winter.", tr: "Kışın kayak yapmaya gideriz." },
      { type: "rule", text: "Dönüşlü zamirlerle ve bu dersteki diğer kalıplarla daha fazla örnek görelim." },
      { type: "example", en: "She talks to herself sometimes.", tr: "O bazen kendi kendine konuşur." },
      { type: "example", en: "We enjoyed ourselves at the party.", tr: "Partide kendimizi eğlendirdik." },
      { type: "example", en: "Did you make this cake yourself?", tr: "Bu keki kendin mi yaptın?" },
      { type: "example", en: "How much does this cost?", tr: "Bu ne kadar tutuyor?" },
      { type: "example", en: "How many languages does she speak?", tr: "O kaç dil konuşuyor?" },
      { type: "example", en: "I don't agree with his opinion.", tr: "Onun görüşüne katılmıyorum." },
      { type: "example", en: "Do you remember her name?", tr: "Onun ismini hatırlıyor musun?" },
      { type: "example", en: "This is John's car, not mine.", tr: "Bu John'un arabası, benim değil." },
      { type: "example", en: "What are you looking for?", tr: "Ne arıyorsun?" },
      { type: "example", en: "I'm looking at the menu.", tr: "Menüye bakıyorum." },
      { type: "example", en: "This soup is too salty for me.", tr: "Bu çorba benim için çok tuzlu." },
      { type: "example", en: "There are so many people here.", tr: "Burada çok fazla insan var." },
      { type: "example", en: "We have a lot of homework today.", tr: "Bugün çok fazla ödevimiz var." },
      { type: "example", en: "Don't be late for the interview.", tr: "Mülakata geç kalma." },
      { type: "example", en: "My favorite season is spring.", tr: "En sevdiğim mevsim ilkbahar." },
      { type: "rule", text: "Karışık soru-cevap alıştırmalarıyla bu dersi tamamlayalım." },
      { type: "example", en: "Whose bag is this? It's my sister's.", tr: "Bu kimin çantası? Kız kardeşimin." },
      { type: "example", en: "How much sugar do you want in your tea?", tr: "Çayında ne kadar şeker istersin?" },
      { type: "example", en: "Can you look after yourself while I'm away?", tr: "Ben yokken kendine bakabilir misin?" },
      { type: "rule", text: "Bu dersteki kalıplarla daha fazla karışık örnek cümle görelim." },
      { type: "example", en: "He behaves like a child sometimes.", tr: "O bazen çocuk gibi davranır." },
      { type: "example", en: "I completely agree with your plan.", tr: "Planına tamamen katılıyorum." },
      { type: "example", en: "Try to remember where you left it.", tr: "Nereye bıraktığını hatırlamaya çalış." },
      { type: "example", en: "Everyone has the right to be heard.", tr: "Herkesin duyulma hakkı var." },
      { type: "example", en: "Don't criticize people you don't know.", tr: "Tanımadığın insanları eleştirme." },
      { type: "example", en: "This is my brother's phone number.", tr: "Bu kardeşimin telefon numarası." },
      { type: "example", en: "I'm looking for my keys everywhere.", tr: "Anahtarlarımı her yerde arıyorum." },
      { type: "example", en: "She is too tired to continue.", tr: "O devam edemeyecek kadar yorgun." },
      { type: "example", en: "We were so late for the flight.", tr: "Uçak için çok geç kalmıştık." },
      { type: "example", en: "Autumn is my favorite season because of the colors.", tr: "Renkleri yüzünden en sevdiğim mevsim sonbahardır." },
      { type: "rule", text: "Son olarak bu dersteki bütün kalıpları içeren kısa bir tekrar bölümü ekleyelim." },
      { type: "example", en: "How much does it cost to fix this?", tr: "Bunu tamir ettirmek ne kadar tutar?" },
      { type: "example", en: "He introduced himself to the new team.", tr: "O kendini yeni takıma tanıttı." },
      { type: "example", en: "I can't remember his last name.", tr: "Onun soyadını hatırlayamıyorum." },
      { type: "example", en: "This is not my decision to make.", tr: "Bu benim vereceğim bir karar değil." },
      { type: "example", en: "We looked for the restaurant for an hour.", tr: "Restoranı bir saat boyunca aradık." },
      { type: "example", en: "He decided to join the army.", tr: "O orduya katılmaya karar verdi." },
      { type: "example", en: "I guess we should leave now.", tr: "Sanırım şimdi ayrılmalıyız." },
      { type: "example", en: "Behave yourself at the dinner table.", tr: "Yemek masasında düzgün davran." },
      { type: "example", en: "Whose idea was this?", tr: "Bu kimin fikriydi?" },
      { type: "example", en: "There isn't enough space in this room.", tr: "Bu odada yeterli alan yok." },
      { type: "rule", text: "Son bir tekrar bölümüyle bu dersi tamamlayalım." },
      { type: "example", en: "I need to remind myself to call her.", tr: "Onu aramam gerektiğini kendime hatırlatmalıyım." },
      { type: "example", en: "How many times have you visited Paris?", tr: "Paris'i kaç kere ziyaret ettin?" },
      { type: "example", en: "He always looks for the best deal.", tr: "O her zaman en iyi fırsatı arar." },
      { type: "example", en: "Do you have enough evidence?", tr: "Yeterince kanıtın var mı?" },
      { type: "example", en: "This isn't the right season for skiing.", tr: "Bu kayak için doğru mevsim değil." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
