import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "24_Past_Perfect_Continuous",
    title: "GEÇMİŞTEN ÖNCEKİ GEÇMİŞİN ŞİMDİKİ HALİ (PAST PERFECT CONTINUOUS)",
    blocks: [
      { type: "rule", text: "Bu tense; geçmişte bir noktaya kadar bir süredir devam etmekte olan eylemleri anlatmak için kullanılır. Past Perfect'in süreklilik vurgulayan hâlidir." },
      { type: "rule", text: "Yapı: Özne + HAD BEEN + Fiil-ING. HAD BEEN bütün öznelerde aynı kalır." },
      { type: "pattern", text: "ÖZNE + HAD BEEN + V-ing" },
      { type: "example", en: "He had been working there for ten years before he retired.", tr: "O emekli olmadan önce orada on yıldır çalışıyordu." },
      { type: "example", en: "They had been waiting for two hours when the bus finally came.", tr: "Otobüs sonunda geldiğinde onlar iki saattir bekliyorlardı." },
      { type: "example", en: "We had been driving for six hours before we stopped.", tr: "Durmadan önce altı saattir araba sürüyorduk." },
      { type: "rule", text: "Olumsuz yapı: Özne + HADN'T BEEN + Fiil-ING." },
      { type: "example", en: "She hadn't been sleeping well before the exam.", tr: "Sınavdan önce iyi uyuyamıyordu." },
      { type: "example", en: "He hadn't been feeling well for a few days.", tr: "Birkaç gündür kendini iyi hissetmiyordu." },
      { type: "rule", text: "Soru yapısı: HAD + Özne + BEEN + Fiil-ING?" },
      { type: "example", en: "How long had you been living there before you moved?", tr: "Taşınmadan önce orada ne kadardır yaşıyordun?" },
      { type: "example", en: "Had they been arguing before you arrived?", tr: "Sen varmadan önce onlar tartışıyor muydu?" },
      { type: "rule", text: "Bu tense genellikle FOR (süre) ve BEFORE (önce) ile birlikte, geçmişteki bir olaydan hemen önce ne kadar süredir bir şeyin devam ettiğini anlatır." },
      { type: "example", en: "I had been studying for three hours before I took a break.", tr: "Mola vermeden önce üç saattir ders çalışıyordum." },
      { type: "rule", text: "Past Perfect (HAD + V3) sonucu, Past Perfect Continuous (HAD BEEN + V-ing) ise süreci vurgular; tıpkı Present Perfect ile Present Perfect Continuous arasındaki farkın geçmişe taşınmış hâli gibidir." },
      { type: "example", en: "Her clothes were wet because she had been swimming.", tr: "Kıyafetleri ıslaktı çünkü yüzüyordu." },
      { type: "rule", text: "Bu tense genellikle bir sonucun sebebini geçmişe dönük olarak açıklamak için kullanılır: birisi yorgun, üzgün ya da belirli bir durumdaydı çünkü bir süredir bir şey yapıyordu." },
      { type: "example", en: "His hands were dirty because he had been working in the garden.", tr: "Elleri kirliydi çünkü bahçede çalışıyordu." },
      { type: "example", en: "She was out of breath because she had been running.", tr: "Nefes nefeseydi çünkü koşuyordu." },
      { type: "rule", text: "Olumsuz ve soru hâllerini birkaç örnekle daha pekiştirelim." },
      { type: "example", en: "We hadn't been talking for long before he interrupted us.", tr: "O sözümüzü kesmeden önce uzun süredir konuşmuyorduk." },
      { type: "example", en: "What had you been doing before the accident happened?", tr: "Kaza olmadan önce ne yapıyordun?" },
      { type: "example", en: "Had she been crying before you arrived?", tr: "Sen varmadan önce o ağlıyor muydu?" },
      { type: "rule", text: "Past Perfect Continuous ile Past Continuous karıştırılmamalıdır. Past Continuous (WAS/WERE + V-ing) geçmişteki belirli bir anda devam eden eylemi anlatır; Past Perfect Continuous ise geçmişteki bir noktaya KADAR süregelen eylemi anlatır." },
      { type: "example", en: "At 8 pm, I was cooking dinner. (o anda) / By 8 pm, I had been cooking dinner for an hour. (o ana kadar geçen süre)", tr: "Saat 8'de yemek pişiriyordum. / Saat 8'e kadar bir saattir yemek pişiriyordum." },
      { type: "rule", text: "SINCE, geçmişte belli bir başlangıç noktasını göstermek için Past Perfect Continuous ile birlikte kullanılır." },
      { type: "example", en: "He had been working there since 2015 when the company closed.", tr: "Şirket kapandığında o orada 2015'ten beri çalışıyordu." },
      { type: "example", en: "She had been living in Paris since she was a child.", tr: "O çocukluğundan beri Paris'te yaşıyordu." },
      { type: "rule", text: "BY THE TIME (...dığı zamana kadar) kalıbı, bir eylemin başka bir geçmiş olaydan önce ne kadar sürdüğünü vurgulamak için sıkça kullanılır." },
      { type: "example", en: "By the time the police arrived, they had been fighting for twenty minutes.", tr: "Polis geldiğinde onlar yirmi dakikadır kavga ediyordu." },
      { type: "example", en: "By the time I woke up, it had been raining for hours.", tr: "Ben uyandığımda saatlerdir yağmur yağıyordu." },
      { type: "rule", text: "ALL DAY, ALL NIGHT, ALL MORNING gibi süre ifadeleri de bu tense ile sıkça birlikte kullanılır." },
      { type: "example", en: "She had been crying all night before he finally called her.", tr: "O sonunda onu aramadan önce bütün gece ağlıyordu." },
      { type: "example", en: "We had been driving all day, so we were exhausted.", tr: "Bütün gün araba sürüyorduk, bu yüzden bitkindik." },
      { type: "rule", text: "Bilgi, düşünce ve duygu bildiren durum fiilleri (KNOW, BELIEVE, LOVE, WANT, UNDERSTAND gibi) normalde -ING almadığı için bu fiillerle Past Perfect Continuous yerine Past Perfect kullanılır." },
      { type: "example", en: "I had known her for years before we became friends. (NOT: had been knowing)", tr: "Arkadaş olmadan önce onu yıllardır tanıyordum." },
      { type: "example", en: "He had wanted that job for a long time before he got it.", tr: "O işi alana kadar uzun zamandır o işi istiyordu." },
      { type: "rule", text: "\"WAIT\" fiili üzerinden tam çekim tablosunu inceleyelim. HAD BEEN bütün öznelerde değişmez." },
      { type: "pattern", text: "TAM ÇEKİM: WAIT (BEKLEMEK)" },
      { type: "example", en: "I had been waiting for an hour.", tr: "Bir saattir bekliyordum." },
      { type: "example", en: "You had been waiting for an hour.", tr: "Bir saattir bekliyordun." },
      { type: "example", en: "He had been waiting for an hour.", tr: "O bir saattir bekliyordu." },
      { type: "example", en: "We had been waiting for an hour.", tr: "Bir saattir bekliyorduk." },
      { type: "example", en: "They had been waiting for an hour.", tr: "Bir saattir bekliyorlardı." },
      { type: "rule", text: "Aynı fiilin olumsuz çekimi." },
      { type: "example", en: "I hadn't been waiting long when she arrived.", tr: "O geldiğinde ben uzun süredir beklemiyordum." },
      { type: "example", en: "They hadn't been waiting there before.", tr: "Onlar daha önce orada beklemiyorlardı." },
      { type: "rule", text: "Aynı fiilin soru çekimi." },
      { type: "example", en: "Had you been waiting long?", tr: "Uzun süredir mi bekliyordun?" },
      { type: "example", en: "Had they been waiting outside?", tr: "Onlar dışarıda mı bekliyorlardı?" },
      { type: "rule", text: "Bu tense'in en yaygın kullanımı, geçmişteki bir durumun SEBEBİNİ açıklamaktır: birinin hâli/görünüşü, bir süredir yaptığı bir eylemin sonucudur." },
      { type: "example", en: "His eyes were red because he had been reading all night.", tr: "Gözleri kızarmıştı çünkü bütün gece kitap okuyordu." },
      { type: "example", en: "The ground was wet because it had been raining.", tr: "Zemin ıslaktı çünkü yağmur yağıyordu." },
      { type: "example", en: "She was exhausted because she had been dancing for hours.", tr: "Bitkindi çünkü saatlerdir dans ediyordu." },
      { type: "rule", text: "Sık yapılan bir hata; HAD BEEN yerine sadece BEEN kullanmak ya da HAD'i unutmaktır. \"He been working\" yanlıştır, doğrusu \"He had been working\" olmalıdır." },
      { type: "example", en: "She had been studying hard before the exam. (DOĞRU) — NOT: She been studying hard.", tr: "Sınavdan önce sıkı çalışıyordu. — Yanlış kullanım: She been studying hard." },
      { type: "rule", text: "HOW LONG (ne kadar süredir) sorusu, geçmişteki bir olaydan önceki süreyi sormak için Past Perfect Continuous ile sıkça kullanılır." },
      { type: "example", en: "How long had they been dating before they got married?", tr: "Evlenmeden önce ne kadar süredir çıkıyorlardı?" },
      { type: "example", en: "How long had she been teaching before she retired?", tr: "Emekli olmadan önce ne kadar süredir öğretmenlik yapıyordu?" },
      { type: "rule", text: "Şimdi bu tense'i pekiştiren günlük bir diyalog örneği görelim." },
      { type: "example", en: "Why were you so tired yesterday? — I had been packing boxes all day before the move.", tr: "Dün neden bu kadar yorgundun? — Taşınmadan önce bütün gün kutu paketliyordum." },
      { type: "example", en: "Had you been living there for a long time before you sold the house? — Yes, we had been living there for almost twenty years.", tr: "Evi satmadan önce orada uzun süredir mi yaşıyordunuz? — Evet, neredeyse yirmi yıldır orada yaşıyorduk." },
      { type: "rule", text: "Son olarak, bu tense'i pekiştiren karışık tekrar cümleleri görelim." },
      { type: "example", en: "The children were sleepy because they had been playing outside all afternoon.", tr: "Çocuklar uykuluydu çünkü bütün öğleden sonra dışarıda oynuyorlardı." },
      { type: "example", en: "He had been smoking for twenty years before he quit.", tr: "Bırakmadan önce yirmi yıldır sigara içiyordu." },
      { type: "example", en: "We had been planning the trip for months before we finally left.", tr: "Sonunda yola çıkmadan önce aylardır o geziyi planlıyorduk." },
      { type: "example", en: "Had she been feeling ill before she went to the doctor?", tr: "Doktora gitmeden önce kendini hasta mı hissediyordu?" },
      { type: "example", en: "I hadn't been sleeping well, so I felt dizzy all week.", tr: "İyi uyuyamıyordum, bu yüzden bütün hafta baş dönmesi yaşadım." },
      { type: "rule", text: "Past Perfect Continuous, iki geçmiş eylemi karşılaştırırken de kullanılır: biri bir süredir devam ediyordu, diğeri ise onu kesti veya değiştirdi." },
      { type: "example", en: "I had been reading for two hours when the power went out.", tr: "Elektrik kesildiğinde iki saattir kitap okuyordum." },
      { type: "example", en: "She had been cooking when the phone rang.", tr: "Telefon çaldığında yemek pişiriyordu." },
      { type: "rule", text: "NEVER BEFORE gibi vurgulu ifadeler de bu tense ile birlikte, önceki deneyimin süresini vurgulamak için kullanılabilir." },
      { type: "example", en: "He had never been working so hard before that project.", tr: "O projeden önce hiç bu kadar çok çalışmamıştı." },
      { type: "rule", text: "FOR AGES, FOR A WHILE gibi belirsiz süre ifadeleri de günlük konuşmada bu tense ile sık kullanılır." },
      { type: "example", en: "We had been talking for a while before we realized the time.", tr: "Saatin farkına varmadan önce bir süredir konuşuyorduk." },
      { type: "example", en: "I had been waiting for ages before the doctor called my name.", tr: "Doktor adımı seslenmeden önce uzun zamandır bekliyordum." },
      { type: "rule", text: "\"UNTIL/TILL\" bağlacı da bu tense ile birlikte, bir eylemin ne zamana kadar sürdüğünü belirtmek için kullanılabilir." },
      { type: "example", en: "She had been working there until the factory shut down.", tr: "Fabrika kapanana kadar orada çalışıyordu." },
      { type: "rule", text: "Soru cümlelerinde WHY, WHAT, HOW gibi soru sözcükleriyle de bu tense sıkça kullanılır." },
      { type: "example", en: "Why had they been shouting before the neighbors complained?", tr: "Komşular şikayet etmeden önce onlar neden bağırıyordu?" },
      { type: "example", en: "What had you been doing all that time?", tr: "Bütün o süre boyunca ne yapıyordun?" },
      { type: "rule", text: "Bu tense ile ayrıca bir kişinin bir şeyi bir süre sonra bırakmasını da anlatabiliriz: bir süredir devam eden bir eylem sona ermiştir." },
      { type: "example", en: "He had been smoking for ten years before he finally gave up.", tr: "Sonunda bırakmadan önce on yıldır sigara içiyordu." },
      { type: "example", en: "They had been arguing for months before they decided to separate.", tr: "Ayrılmaya karar vermeden önce aylardır tartışıyorlardı." },
      { type: "rule", text: "Bu bölümü, dersteki bütün kalıpları içeren karışık bir tekrar bölümüyle tamamlayalım." },
      { type: "example", en: "The streets were flooded because it had been raining for days.", tr: "Sokaklar sular altındaydı çünkü günlerdir yağmur yağıyordu." },
      { type: "example", en: "Had she been crying for a long time before you found her?", tr: "Sen onu bulmadan önce o uzun süredir mi ağlıyordu?" },
      { type: "example", en: "We hadn't been expecting such a big crowd.", tr: "Böyle büyük bir kalabalık beklemiyorduk." },
      { type: "example", en: "I had been trying to reach him for days before he finally answered.", tr: "O sonunda cevap vermeden önce günlerdir ona ulaşmaya çalışıyordum." },
    ],
  },
  {
    fileBase: "25_Before_After_Kaliplari",
    title: "BEFORE - AFTER VE SORUMLULUK KALIPLARI",
    blocks: [
      { type: "rule", text: "BEFORE ve AFTER'dan sonra iki cümlenin öznesi aynıysa ikinci fiil -ING alarak kısaltılabilir." },
      { type: "example", en: "I will call you before I finish. = I will call you before finishing.", tr: "Bitirmeden önce seni ararım." },
      { type: "example", en: "She will cook the meal after she arrives home. = ...after arriving home.", tr: "Eve vardıktan sonra yemeği pişirecek." },
      { type: "example", en: "He saw me after he opened the door. = ...after opening the door.", tr: "Kapıyı açtıktan sonra beni gördü." },
      { type: "rule", text: "İki cümledeki özneler farklı kişilerse, -ING kısaltması yapılamaz; her iki cümlenin de tam hâli kullanılmalıdır." },
      { type: "example", en: "I will visit you after you finish this work.", tr: "Sen bu işi bitirdikten sonra seni ziyaret edeceğim." },
      { type: "example", en: "We said everything before they explained.", tr: "Onlar açıklamadan önce biz her şeyi söyledik." },
      { type: "pattern", text: "CURIOUS = meraklı / BE CURIOUS ABOUT = merak etmek / WONDER = merak etmek" },
      { type: "example", en: "Are you curious about her?", tr: "Onu merak ediyor musun?" },
      { type: "example", en: "Why are you wondering everything?", tr: "Neden her şeyi merak ediyorsun?" },
      { type: "pattern", text: "TALK + TO = ile konuşmak / CALCULATE = hesaplamak / COUNT = saymak / GOODS = mallar" },
      { type: "example", en: "Why didn't he talk to us?", tr: "O neden bizimle konuşmadı?" },
      { type: "example", en: "Did you calculate my total debt?", tr: "Toplam borcumu hesapladın mı?" },
      { type: "example", en: "Did you count all the goods?", tr: "Bütün malları saydın mı?" },
      { type: "pattern", text: "REQUIRE = gerektirmek / PATIENCE = sabır / COURAGE = cesaret / PROCESS = süreç" },
      { type: "example", en: "This job requires more patience.", tr: "Bu iş daha fazla sabır gerektiriyor." },
      { type: "example", en: "This project requires more money.", tr: "Bu proje daha fazla para gerektiriyor." },
      { type: "pattern", text: "REQUIREMENTS / NEEDS = gereksinimler, ihtiyaçlar" },
      { type: "example", en: "Isn't he aware of your requirements?", tr: "O senin gereksinimlerinin farkında değil mi?" },
      { type: "pattern", text: "PRETTY = oldukça, çok / güzel, zarif" },
      { type: "example", en: "I'm pretty sure.", tr: "Adım gibi eminim." },
      { type: "pattern", text: "RESPONSIBLE = sorumlu / BE RESPONSIBLE + FOR = sorumlu olmak" },
      { type: "pattern", text: "ACCOUNT = hesap / ACCOUNTING = muhasebe / PURCHASE = satın alma / MARKETING = pazarlama" },
      { type: "example", en: "Who is responsible for accounting?", tr: "Muhasebeden kim sorumlu?" },
      { type: "example", en: "I'm responsible for marketing.", tr: "Pazarlamadan ben sorumluyum." },
      { type: "rule", text: "EXCITING (heyecan verici, dış dünyayı niteler) ile EXCITED (heyecanlı, kişinin duygusunu niteler) farklı kullanılır; aynı fark BORING/BORED için de geçerlidir." },
      { type: "example", en: "The elections were so exciting.", tr: "Seçimler çok heyecanlıydı." },
      { type: "example", en: "The match was very boring, so I am not glad.", tr: "Maç çok sıkıcıydı, bu yüzden memnun değilim." },
      { type: "pattern", text: "DEAL WITH = uğraşmak, başa çıkmak" },
      { type: "example", en: "I have no time to deal with the nonsense.", tr: "Saçmalıkla uğraşmaya vaktim yok." },
      { type: "example", en: "I cannot deal with her.", tr: "Onunla başa çıkamıyorum." },
      { type: "rule", text: "BEFORE ve AFTER isimlerle de kullanılabilir: BEFORE THE MEETING, AFTER THE LESSON gibi." },
      { type: "example", en: "Let's talk before the meeting starts.", tr: "Toplantı başlamadan önce konuşalım." },
      { type: "example", en: "We usually go for a walk after dinner.", tr: "Genellikle akşam yemeğinden sonra yürüyüşe çıkarız." },
      { type: "rule", text: "BEFORE/AFTER + V-ing yapısı, resmi yazışmalarda ve talimatlarda çok sık kullanılır." },
      { type: "example", en: "Please read the instructions carefully before starting.", tr: "Lütfen başlamadan önce talimatları dikkatlice okuyun." },
      { type: "example", en: "Wash your hands after touching the door handle.", tr: "Kapı koluna dokunduktan sonra ellerini yıka." },
      { type: "rule", text: "SOON AFTER (kısa bir süre sonra) ve SHORTLY BEFORE (kısa bir süre önce) kalıpları da zaman ilişkisini kısaltarak anlatır." },
      { type: "example", en: "Soon after we arrived, it started to rain.", tr: "Biz vardıktan kısa bir süre sonra yağmur yağmaya başladı." },
      { type: "example", en: "Shortly before the show, the singer got sick.", tr: "Gösteriden kısa bir süre önce şarkıcı hastalandı." },
      { type: "rule", text: "Sorumluluk ile ilgili ek kalıplar: TAKE RESPONSIBILITY FOR (sorumluluk almak), IN CHARGE OF (sorumlu, başında), BLAME (suçlamak)." },
      { type: "example", en: "Who is in charge of this department?", tr: "Bu departmandan kim sorumlu?" },
      { type: "example", en: "He took responsibility for the mistake.", tr: "O hata için sorumluluk aldı." },
      { type: "example", en: "Don't blame me for something I didn't do.", tr: "Yapmadığım bir şey için beni suçlama." },
      { type: "rule", text: "Son olarak BEFORE/AFTER ve sorumluluk kalıplarını birlikte pekiştiren örnekler görelim." },
      { type: "example", en: "Before taking responsibility for the project, make sure you understand all the requirements.", tr: "Proje için sorumluluk almadan önce bütün gereksinimleri anladığından emin ol." },
      { type: "example", en: "After discussing it with the team, we decided who would be in charge.", tr: "Ekiple tartıştıktan sonra kimin sorumlu olacağına karar verdik." },
      { type: "rule", text: "BEFORE LONG (çok geçmeden) ve UP UNTIL NOW (şimdiye kadar) gibi ek zaman ifadeleri de BEFORE/AFTER ailesindendir." },
      { type: "example", en: "Before long, everyone had heard the news.", tr: "Çok geçmeden herkes haberi duymuştu." },
      { type: "example", en: "Up until now, we haven't had any problems.", tr: "Şimdiye kadar hiçbir sorunumuz olmadı." },
      { type: "rule", text: "AS SOON AS (...er ...mez) kalıbı BEFORE/AFTER gibi iki eylem arasındaki zaman ilişkisini anlatır, ancak eylemlerin hemen ardı sıra gerçekleştiğini vurgular." },
      { type: "pattern", text: "AS SOON AS + ÖZNE + FİİL, ÖZNE + FİİL" },
      { type: "example", en: "As soon as I get home, I'll call you.", tr: "Eve varır varmaz seni arayacağım." },
      { type: "example", en: "She left as soon as the meeting ended.", tr: "Toplantı biter bitmez ayrıldı." },
      { type: "rule", text: "Sorumluluk devretme ile ilgili kalıplar: DELEGATE (devretmek), RELY ON (güvenmek, dayanmak), COUNT ON (güvenmek)." },
      { type: "example", en: "The manager delegated the task to his assistant.", tr: "Müdür görevi asistanına devretti." },
      { type: "example", en: "You can always rely on her.", tr: "Ona her zaman güvenebilirsin." },
      { type: "example", en: "I'm counting on you to finish this on time.", tr: "Bunu zamanında bitirmen için sana güveniyorum." },
      { type: "rule", text: "FAULT (kusur, hata) ve MISTAKE (hata) arasındaki fark: FAULT genellikle kimin sorumlu olduğunu, MISTAKE ise yapılan hatanın kendisini vurgular." },
      { type: "example", en: "It's not my fault that the project failed.", tr: "Projenin başarısız olması benim hatam değil." },
      { type: "example", en: "Everyone makes mistakes sometimes.", tr: "Herkes bazen hata yapar." },
      { type: "rule", text: "Son olarak BEFORE, AFTER, AS SOON AS ve sorumluluk kalıplarını birlikte pekiştiren bir kapanış bölümü görelim." },
      { type: "example", en: "As soon as she took charge of the project, she delegated tasks to each team member.", tr: "Projenin başına geçer geçmez, görevleri her bir ekip üyesine devretti." },
      { type: "example", en: "Before blaming anyone, we should find out whose fault it really was.", tr: "Kimseyi suçlamadan önce gerçekten kimin hatası olduğunu bulmalıyız." },
      { type: "rule", text: "PRIOR TO (öncesinde) ve FOLLOWING (izleyen, ardından) kalıpları BEFORE/AFTER'ın daha resmi eşdeğerleridir ve genellikle yazılı/iş İngilizcesinde kullanılır." },
      { type: "example", en: "Prior to the meeting, please review the documents.", tr: "Toplantı öncesinde lütfen belgeleri gözden geçirin." },
      { type: "example", en: "Following the announcement, the stock price dropped.", tr: "Duyurunun ardından hisse fiyatı düştü." },
      { type: "rule", text: "OWE (borçlu olmak) ve APOLOGIZE (özür dilemek) sorumluluk ile ilgili sık kullanılan fiillerdir." },
      { type: "example", en: "I owe you an apology for what happened.", tr: "Olanlar için sana bir özür borçluyum." },
      { type: "example", en: "He apologized for being late.", tr: "Geç kaldığı için özür diledi." },
      { type: "rule", text: "Son olarak bu dersteki tüm kalıpları içeren uzun bir örnek cümleyle konuyu tamamlayalım." },
      { type: "example", en: "Prior to taking charge of the department, she had made sure that everyone understood who was responsible for what.", tr: "Departmanın başına geçmeden önce, herkesin kimin neden sorumlu olduğunu anladığından emin olmuştu." },
      { type: "rule", text: "TAKE OVER (devralmak) ve HAND OVER (devretmek) sorumluluk değişimini anlatan sık kullanılan phrasal verb'lerdir." },
      { type: "example", en: "She will take over the project next month.", tr: "O gelecek ay projeyi devralacak." },
      { type: "example", en: "He handed over his duties before retiring.", tr: "Emekli olmadan önce görevlerini devretti." },
      { type: "rule", text: "IN THE MEANTIME (bu arada, o esnada), bir olayla başka bir olay arasındaki süreyi doldurmak için kullanılır." },
      { type: "example", en: "The food will be ready in ten minutes; in the meantime, let's set the table.", tr: "Yemek on dakikaya hazır olacak; bu arada masayı hazırlayalım." },
      { type: "example", en: "In the meantime, please wait in the lobby.", tr: "Bu arada lütfen lobide bekleyin." },
      { type: "rule", text: "MEANWHILE (bu esnada) IN THE MEANTIME ile aynı anlamda kullanılır ve genellikle cümle başında yer alır." },
      { type: "example", en: "I'll cook dinner. Meanwhile, you can set the table.", tr: "Ben yemeği pişireceğim. Bu esnada sen masayı hazırlayabilirsin." },
      { type: "rule", text: "UNTIL/BY THEN (o zamana kadar) ifadesi de BEFORE/AFTER ailesiyle birlikte, bahsedilen bir zamana kadar geçen süreci anlatır." },
      { type: "example", en: "The meeting is at 3 pm; by then, I need to finish this report.", tr: "Toplantı saat 3'te; o zamana kadar bu raporu bitirmem gerekiyor." },
      { type: "rule", text: "Son olarak bu dersteki bütün zaman ve sorumluluk kalıplarını içeren uzun bir kapanış cümlesi görelim." },
      { type: "example", en: "Before handing over the project, make sure everyone knows what to do in the meantime, and follow up regularly afterward.", tr: "Projeyi devretmeden önce, o esnada herkesin ne yapması gerektiğinden emin ol ve sonrasında düzenli olarak takip et." },
    ],
  },
  {
    fileBase: "26_Whenever_Whatever_Wherever",
    title: "WHENEVER - WHATEVER - WHEREVER VE BELİRSİZLİK ZAMİRLERİ",
    blocks: [
      { type: "pattern", text: "WHENEVER = her ne zaman" },
      { type: "example", en: "He can call us whenever he wants.", tr: "Ne zaman isterse bizi arayabilir." },
      { type: "example", en: "You can come here whenever you want. My door is always open to you.", tr: "İstediğin zaman buraya gelebilirsin. Kapım sana her zaman açık." },
      { type: "pattern", text: "WHATEVER = her ne" },
      { type: "example", en: "She can buy whatever she wants, that is her money.", tr: "İstediği her şeyi satın alabilir, o onun parası." },
      { type: "example", en: "You can tell them whatever they need. I don't care!", tr: "Onlara ihtiyaç duydukları her şeyi söyleyebilirsin. Umurumda değil!" },
      { type: "pattern", text: "WHEREVER = her nereye, her nerede / SAFE = güvenli" },
      { type: "example", en: "They can stay wherever they want, it is so safe here.", tr: "Nerede isterlerse kalabilirler, burası çok güvenli." },
      { type: "rule", text: "ANYTHING ve NOTHING aynı anlamı verir; ANYTHING olumsuz cümlede, NOTHING ise olumlu fiille kullanılır." },
      { type: "example", en: "I don't know anything. = I know nothing.", tr: "Hiçbir şey bilmiyorum." },
      { type: "example", en: "We didn't want to do anything. = We wanted to do nothing.", tr: "Hiçbir şey yapmak istemedik." },
      { type: "rule", text: "Aynı kural ANYBODY / NOBODY ve ANYWHERE / NOWHERE için de geçerlidir." },
      { type: "example", en: "I don't want to see anybody. = I want to see nobody.", tr: "Kimseyi görmek istemiyorum." },
      { type: "example", en: "We didn't go anywhere for vacation. = We went nowhere for vacation.", tr: "Tatil için hiçbir yere gitmedik." },
      { type: "pattern", text: "POSSIBLE = mümkün / IMPOSSIBLE = imkansız" },
      { type: "example", en: "It is impossible to go there, because it is too foggy.", tr: "Oraya gitmek imkansız, çünkü çok sisli." },
      { type: "pattern", text: "MEANINGFUL = anlamlı / MEANINGLESS = anlamsız / DISCUSS = tartışmak / DISCUSSION = tartışma" },
      { type: "example", en: "It is meaningless to discuss.", tr: "Tartışmak anlamsız." },
      { type: "example", en: "The discussion is over.", tr: "Tartışma bitti." },
      { type: "pattern", text: "IMPORTANT = önemli / URGENT = acil / URGENTLY = acilen" },
      { type: "example", en: "It is important to convince them.", tr: "Onları ikna etmek önemli." },
      { type: "example", en: "I have to urgently see them.", tr: "Onları acilen görmem lazım." },
      { type: "pattern", text: "OPINION = görüş / IN MY OPINION = bana göre, kanımca / WILLING = istekli" },
      { type: "example", en: "In my opinion, they aren't willing to come here.", tr: "Bana göre, buraya gelmeye istekli değiller." },
      { type: "pattern", text: "COUPLE = çift / A COUPLE OF = birkaç" },
      { type: "example", en: "We need a couple of different opinions.", tr: "Birkaç farklı görüşe ihtiyacımız var." },
      { type: "pattern", text: "PROVE = kanıtlamak / PROOF = kanıt / THING = şey / PUT = koymak" },
      { type: "example", en: "Do you have any proof to convince me?", tr: "Beni ikna edecek bir kanıtın var mı?" },
      { type: "example", en: "Where did they put their things?", tr: "Onlar eşyalarını nereye koydu?" },
      { type: "rule", text: "WHOEVER (her kim) ve WHICHEVER (hangisi olursa) de aynı aile içindeki belirsizlik bağlaçlarıdır." },
      { type: "pattern", text: "WHOEVER = her kim        WHICHEVER = hangisi olursa" },
      { type: "example", en: "Whoever calls, tell them I'm busy.", tr: "Kim ararsa arasın, meşgul olduğumu söyle." },
      { type: "example", en: "You can choose whichever color you like.", tr: "Hangi rengi istersen seçebilirsin." },
      { type: "rule", text: "NO MATTER WHAT / NO MATTER WHERE / NO MATTER WHO kalıpları da WHATEVER/WHEREVER/WHOEVER ile aynı anlamı verir, daha vurgulu bir ifadedir." },
      { type: "example", en: "No matter what happens, I'll always support you.", tr: "Ne olursa olsun, seni her zaman destekleyeceğim." },
      { type: "example", en: "No matter where you go, I'll find you.", tr: "Nereye gidersen git, seni bulacağım." },
      { type: "rule", text: "SOMETHING, SOMEBODY/SOMEONE, SOMEWHERE genellikle olumlu cümlelerde, ANYTHING, ANYBODY/ANYONE, ANYWHERE ise olumsuz ve soru cümlelerinde kullanılır." },
      { type: "example", en: "I need to tell you something important.", tr: "Sana önemli bir şey söylemem gerekiyor." },
      { type: "example", en: "Is there anybody home?", tr: "Evde biri var mı?" },
      { type: "example", en: "We couldn't find it anywhere.", tr: "Onu hiçbir yerde bulamadık." },
      { type: "rule", text: "EVERYTHING, EVERYBODY/EVERYONE, EVERYWHERE ise \"her şey, herkes, her yer\" anlamına gelir ve tekil fiil alır." },
      { type: "example", en: "Everything is ready for the party.", tr: "Parti için her şey hazır." },
      { type: "example", en: "Everybody was surprised by the news.", tr: "Herkes haberlere şaşırdı." },
      { type: "rule", text: "Bu belirsizlik zamirlerini ve WH- kalıplarını pekiştiren bir tekrar bölümü görelim." },
      { type: "example", en: "You can sit wherever you like, whenever you're ready.", tr: "İstediğin yere oturabilirsin, hazır olduğunda." },
      { type: "example", en: "No matter what she says, I won't change my mind.", tr: "O ne derse desin, fikrimi değiştirmeyeceğim." },
      { type: "example", en: "Whoever wins the competition will receive a prize.", tr: "Yarışmayı her kim kazanırsa bir ödül alacak." },
      { type: "rule", text: "SOME, ANY ve NO ön ekleriyle kurulan belirsizlik zamirlerinin tam listesini bir tabloda görelim." },
      { type: "pattern", text: "SOME- : SOMETHING, SOMEBODY/SOMEONE, SOMEWHERE   |   ANY- : ANYTHING, ANYBODY/ANYONE, ANYWHERE   |   NO- : NOTHING, NOBODY, NOWHERE" },
      { type: "example", en: "There must be somebody in the house, the lights are on.", tr: "Evde biri olmalı, ışıklar yanıyor." },
      { type: "example", en: "I looked everywhere but couldn't find my keys anywhere.", tr: "Her yere baktım ama anahtarlarımı hiçbir yerde bulamadım." },
      { type: "rule", text: "ANY- ile başlayan zamirler ayrıca olumlu cümlelerde \"fark etmez, herhangi biri\" anlamında da kullanılabilir." },
      { type: "example", en: "You can ask anybody in this office for help.", tr: "Bu ofisteki herhangi birinden yardım isteyebilirsin." },
      { type: "example", en: "Take anything you like from the table.", tr: "Masadan istediğin herhangi bir şeyi al." },
      { type: "rule", text: "WHATEVER, WHENEVER, WHEREVER, WHOEVER kalıpları aynı zamanda \"önemli değil\" anlamında kayıtsızlık ifade etmek için de kullanılabilir." },
      { type: "example", en: "\"Where should we eat?\" \"Whatever, I don't mind.\"", tr: "\"Nerede yiyelim?\" \"Fark etmez, önemli değil.\"" },
      { type: "rule", text: "Bu kalıplar özgürlük, tercih ve sınırsızlık anlatan cümlelerde çok sık karşımıza çıkar." },
      { type: "example", en: "You are free to leave whenever you want.", tr: "İstediğin zaman gitmekte özgürsün." },
      { type: "example", en: "This ticket allows you to travel wherever you like within the country.", tr: "Bu bilet ülke içinde istediğin yere seyahat etmene izin veriyor." },
      { type: "rule", text: "Son olarak bu dersteki bütün belirsizlik zamirlerini ve WH-EVER kalıplarını içeren karma bir tekrar bölümü görelim." },
      { type: "example", en: "Whatever you decide, make sure you tell everyone as soon as possible.", tr: "Ne karar verirsen ver, herkese en kısa sürede söylediğinden emin ol." },
      { type: "example", en: "Nobody knew where he had gone, and nothing he left behind gave any clues.", tr: "Kimse nereye gittiğini bilmiyordu ve geride bıraktığı hiçbir şey ipucu vermiyordu." },
      { type: "rule", text: "EACH OTHER ve ONE ANOTHER (birbiri) karşılıklı eylemleri anlatırken kullanılır; ikisi de aynı anlama gelir." },
      { type: "example", en: "They have known each other since childhood.", tr: "Birbirlerini çocukluktan beri tanıyorlar." },
      { type: "example", en: "The students helped one another with their homework.", tr: "Öğrenciler ödevlerinde birbirlerine yardım ettiler." },
      { type: "rule", text: "ALL, NONE, MOST gibi genelleme zamirleri de belirsizlik ailesine yakındır ve OF ile kullanıldığında belirli bir grubu işaret eder." },
      { type: "example", en: "None of them wanted to go first.", tr: "Hiçbiri ilk gitmek istemedi." },
      { type: "example", en: "Most of what he said made sense.", tr: "Söylediklerinin çoğu mantıklıydı." },
      { type: "rule", text: "OTHER ve ANOTHER arasındaki fark: ANOTHER tekil ve sayılabilir isimlerle \"bir başka\", OTHER ise çoğul ya da belirli isimlerle \"diğer\" anlamında kullanılır." },
      { type: "example", en: "Can I have another cup of coffee?", tr: "Bir fincan kahve daha alabilir miyim?" },
      { type: "example", en: "Where are the other students?", tr: "Diğer öğrenciler nerede?" },
      { type: "rule", text: "Son olarak bu dersteki bütün belirsizlik ve karşılıklılık zamirlerini içeren birkaç örnek daha görelim." },
      { type: "example", en: "Whatever happens, we should always support each other.", tr: "Ne olursa olsun, her zaman birbirimizi desteklemeliyiz." },
      { type: "example", en: "None of us knew what to do, so we asked someone for help.", tr: "Hiçbirimiz ne yapacağını bilmiyordu, o yüzden birinden yardım istedik." },
      { type: "rule", text: "SOMEHOW (bir şekilde) ve SOMEWHAT (biraz, bir dereceye kadar) da bu belirsizlik ailesine yakın zarflardır." },
      { type: "example", en: "We managed to finish it somehow.", tr: "Bir şekilde onu bitirmeyi başardık." },
      { type: "example", en: "The situation is somewhat complicated.", tr: "Durum biraz karmaşık." },
      { type: "rule", text: "Bu belirsizlik ifadelerini gerçek hayattaki karar anlarında pekiştiren birkaç örnek daha görelim." },
      { type: "example", en: "Whichever path you choose, work hard and stay determined.", tr: "Hangi yolu seçersen seç, çok çalış ve kararlı kal." },
      { type: "example", en: "Whoever is in charge should make a decision soon.", tr: "Her kim sorumluysa yakında bir karar vermeli." },
      { type: "rule", text: "ELSE kelimesi bu belirsizlik zamirleriyle birlikte \"başka\" anlamı katmak için kullanılır: SOMETHING ELSE, SOMEONE ELSE, ANYWHERE ELSE." },
      { type: "example", en: "Is there anything else I should know?", tr: "Bilmem gereken başka bir şey var mı?" },
      { type: "example", en: "Let's go somewhere else for dinner.", tr: "Akşam yemeği için başka bir yere gidelim." },
      { type: "rule", text: "Son olarak bu dersteki bütün belirsizlik zamirlerini birleştiren uzun bir örnek görelim." },
      { type: "example", en: "Whatever you need, whenever you need it, wherever you are, you can always count on someone in this team.", tr: "Neye ihtiyacın olursa olsun, ne zaman ihtiyacın olursa olsun, nerede olursan ol, bu takımda her zaman birine güvenebilirsin." },
    ],
  },
  {
    fileBase: "27_Future_Continuous",
    title: "GELECEK ZAMANIN ŞİMDİKİ HALİ (FUTURE CONTINUOUS)",
    blocks: [
      { type: "rule", text: "Bu tense; gelecekte belirli bir anda devam ediyor olacak eylemleri anlatmak için kullanılır." },
      { type: "rule", text: "Yapı: Özne + WILL BE + Fiil-ING. WILL BE bütün öznelerde aynı kalır." },
      { type: "pattern", text: "ÖZNE + WILL BE + V-ing" },
      { type: "example", en: "This time tomorrow, I will be flying to London.", tr: "Yarın bu saatlerde Londra'ya uçuyor olacağım." },
      { type: "example", en: "They will be waiting for us at the airport.", tr: "Onlar bizi havaalanında bekliyor olacaklar." },
      { type: "example", en: "She will be studying at 8 pm tonight.", tr: "O bu gece saat 8'de ders çalışıyor olacak." },
      { type: "rule", text: "Olumsuz yapı: Özne + WON'T BE + Fiil-ING." },
      { type: "example", en: "I won't be sleeping at that time.", tr: "O saatte uyuyor olmayacağım." },
      { type: "example", en: "We won't be traveling next month.", tr: "Gelecek ay seyahat ediyor olmayacağız." },
      { type: "rule", text: "Soru yapısı: WILL + Özne + BE + Fiil-ING?" },
      { type: "example", en: "Will you be working this weekend?", tr: "Bu hafta sonu çalışıyor olacak mısın?" },
      { type: "example", en: "What will you be doing at noon tomorrow?", tr: "Yarın öğlen ne yapıyor olacaksın?" },
      { type: "rule", text: "Future Continuous ayrıca kibarca birinin planlarını sormak için de kullanılır." },
      { type: "example", en: "Will you be using the car tonight?", tr: "Bu gece arabayı kullanıyor olacak mısın?" },
      { type: "rule", text: "Bu tense genellikle AT THIS TIME TOMORROW, THIS TIME NEXT WEEK gibi belirli bir gelecek zaman noktasıyla kullanılır." },
      { type: "example", en: "At this time next week, we will be sitting on the beach.", tr: "Gelecek hafta bu saatlerde sahilde oturuyor olacağız." },
      { type: "example", en: "This time next year, I will be living abroad.", tr: "Gelecek yıl bu zamanlar yurt dışında yaşıyor olacağım." },
      { type: "rule", text: "Future Continuous, aynı zamanda başka bir gelecek olayla aynı anda gerçekleşecek bir eylemi anlatmak için de kullanılır." },
      { type: "example", en: "When you arrive, we will be waiting for you at the station.", tr: "Sen vardığında, seni istasyonda bekliyor olacağız." },
      { type: "example", en: "While you are sleeping, I will be working.", tr: "Sen uyurken, ben çalışıyor olacağım." },
      { type: "rule", text: "Bu tense ile Future Simple (WILL + V1) arasındaki fark önemlidir: WILL genellikle anlık bir kararı, WILL BE + V-ing ise gelecekte devam eden bir süreci anlatır." },
      { type: "example", en: "I will call you tonight. (anlık karar) / I will be calling clients all afternoon. (süreç)", tr: "Bu gece seni arayacağım. / Bütün öğleden sonra müşterileri arıyor olacağım." },
      { type: "example", en: "Don't call me at 9, I will be having dinner.", tr: "Saat 9'da beni arama, akşam yemeği yiyor olacağım." },
      { type: "rule", text: "Future Continuous, kibarca bir şeyin normal seyrinde gerçekleşeceğini belirtmek için de kullanılır; bu, WILL'den daha az kesin ve daha doğal bir gelecek anlamı taşır." },
      { type: "example", en: "I'll be seeing him at the office tomorrow, so I'll give him the message.", tr: "Yarın ofiste onu görüyor olacağım, o yüzden mesajı ona vereceğim." },
      { type: "rule", text: "\"TRAVEL\" fiili üzerinden tam çekim tablosunu görelim." },
      { type: "pattern", text: "TAM ÇEKİM: TRAVEL (SEYAHAT ETMEK)" },
      { type: "example", en: "I will be traveling this time next week.", tr: "Gelecek hafta bu saatlerde seyahat ediyor olacağım." },
      { type: "example", en: "You will be traveling this time next week.", tr: "Gelecek hafta bu saatlerde seyahat ediyor olacaksın." },
      { type: "example", en: "She will be traveling this time next week.", tr: "O gelecek hafta bu saatlerde seyahat ediyor olacak." },
      { type: "example", en: "We will be traveling this time next week.", tr: "Biz gelecek hafta bu saatlerde seyahat ediyor olacağız." },
      { type: "rule", text: "Olumsuz ve soru çekimlerini de görelim." },
      { type: "example", en: "They won't be traveling with us next week.", tr: "Onlar gelecek hafta bizimle seyahat ediyor olmayacak." },
      { type: "example", en: "Will you be traveling alone this time?", tr: "Bu kez tek başına mı seyahat ediyor olacaksın?" },
      { type: "rule", text: "Future Continuous, bir eylemin gelecekte kesintisiz devam edeceğini vurgulamak için ALL DAY, ALL NIGHT gibi ifadelerle de kullanılabilir." },
      { type: "example", en: "We will be driving all day tomorrow.", tr: "Yarın bütün gün araba sürüyor olacağız." },
      { type: "example", en: "She will be working all weekend on this project.", tr: "O bu hafta sonu bütün zaman bu proje üzerinde çalışıyor olacak." },
      { type: "rule", text: "Sık yapılan bir hata, Future Continuous ile Future Simple'ı karıştırmaktır; bir süreci anlatmak isterken sadece WILL + V1 kullanmak anlamı eksik bırakabilir." },
      { type: "example", en: "At 10 pm, I will be sleeping. (süreç) — NOT: At 10 pm, I will sleep. (anlık, daha az doğal)", tr: "Saat 22:00'de uyuyor olacağım." },
      { type: "rule", text: "Son olarak bu tense'i pekiştiren günlük bir diyalog örneği görelim." },
      { type: "example", en: "What will you be doing this time tomorrow? — I'll be attending a conference in Izmir.", tr: "Yarın bu saatlerde ne yapıyor olacaksın? — İzmir'de bir konferansa katılıyor olacağım." },
      { type: "example", en: "Will you be free next Monday afternoon? — No, I'll be teaching a class then.", tr: "Gelecek Pazartesi öğleden sonra müsait olacak mısın? — Hayır, o zaman ders veriyor olacağım." },
      { type: "example", en: "This time next year, we will be celebrating our tenth anniversary.", tr: "Gelecek yıl bu zamanlar onuncu yıl dönümümüzü kutluyor olacağız." },
      { type: "rule", text: "Future Continuous, gelecekteki planlanmış ve rutin bir eylemi anlatırken de kullanılır; bu kullanım özellikle programlar, seyahat planları için idealdir." },
      { type: "example", en: "The train will be arriving at platform three shortly.", tr: "Tren kısa süre içinde üçüncü perona varacak." },
      { type: "example", en: "We will be boarding the plane in twenty minutes.", tr: "Yirmi dakika içinde uçağa biniyor olacağız." },
      { type: "rule", text: "Future Continuous olumsuz sorusu, birinin bir şeyi yapıp yapmayacağını nazikçe kontrol etmek için kullanılabilir." },
      { type: "example", en: "Won't you be needing this later?", tr: "Bunu daha sonra ihtiyacın olmayacak mı?" },
      { type: "rule", text: "Bu tense, gelecekteki bir olayın kaçınılmaz bir şekilde gerçekleşeceğini vurgulamak için de kullanılır (WILL'in doğal sonucu olarak)." },
      { type: "example", en: "As usual, prices will be rising again next year.", tr: "Her zamanki gibi fiyatlar gelecek yıl yine artıyor olacak." },
      { type: "rule", text: "Future Continuous ile Present Continuous (gelecek plan anlamında) arasındaki fark: Present Continuous kesinleşmiş bir planı, Future Continuous ise gelecekteki bir süreci ya da doğal akışı anlatır." },
      { type: "example", en: "I am meeting her at 5 pm. (kesin plan) / I will be meeting clients all afternoon. (genel süreç)", tr: "Onunla saat 5'te buluşuyorum. / Bütün öğleden sonra müşterilerle görüşüyor olacağım." },
      { type: "rule", text: "Son olarak bu dersteki bütün kullanımları içeren karma bir tekrar bölümü görelim." },
      { type: "example", en: "By this time next week, I will be relaxing on a beach somewhere warm.", tr: "Gelecek hafta bu saatlerde sıcak bir yerde sahilde dinleniyor olacağım." },
      { type: "example", en: "We will be discussing the budget during tomorrow's meeting.", tr: "Yarınki toplantı sırasında bütçeyi tartışıyor olacağız." },
      { type: "example", en: "She won't be joining us for dinner tonight because she will be working late.", tr: "Bu gece bize akşam yemeğinde katılmayacak çünkü geç saatlere kadar çalışıyor olacak." },
      { type: "rule", text: "Future Continuous'un olumsuz sorusu, birinden kibarca bir şey yapıp yapmayacağını teyit etmek için de kullanılabilir." },
      { type: "example", en: "Won't you be coming to the party tonight?", tr: "Bu gece partiye gelmiyor olmayacak mısın?" },
      { type: "rule", text: "Bu tense, uçuş ve tren anonslarında, resmi programlarda çok sık karşımıza çıkar." },
      { type: "example", en: "The captain will be turning off the seatbelt sign shortly.", tr: "Kaptan kısa süre içinde emniyet kemeri işaretini kapatacak." },
      { type: "example", en: "We will be serving breakfast between 7 and 9 am.", tr: "Kahvaltıyı sabah 7 ile 9 arasında servis ediyor olacağız." },
      { type: "rule", text: "Future Continuous, gelecekteki bir eylemin başka bir eylemi kesintiye uğratmayacağını nazikçe belirtmek için de kullanılır." },
      { type: "example", en: "Don't worry, I won't be disturbing you while you're working.", tr: "Merak etme, sen çalışırken seni rahatsız ediyor olmayacağım." },
      { type: "rule", text: "Bu tense'in soru kalıbı, birinin gelecekteki müsaitliğini kibarca öğrenmek için iş hayatında çok kullanışlıdır." },
      { type: "example", en: "Will you be available for a call tomorrow morning?", tr: "Yarın sabah bir görüşme için müsait olacak mısın?" },
      { type: "example", en: "Will she be presenting the report herself?", tr: "Raporu kendisi mi sunuyor olacak?" },
      { type: "rule", text: "Son olarak Future Continuous'u pekiştiren uzun bir kapanış paragrafı görelim." },
      { type: "example", en: "This time next month, I will be settling into my new apartment, and hopefully, I will be enjoying a much quieter neighborhood.", tr: "Gelecek ay bu zamanlar yeni dairemde yerleşmiş olacağım ve umarım çok daha sakin bir mahallenin tadını çıkarıyor olacağım." },
      { type: "example", en: "In ten years, technology will be changing our lives even more than it does today.", tr: "On yıl içinde teknoloji hayatlarımızı bugünkünden bile daha çok değiştiriyor olacak." },
      { type: "example", en: "I will be thinking of you while you're taking your exam.", tr: "Sen sınavına girerken seni düşünüyor olacağım." },
      { type: "example", en: "Next Sunday, my whole family will be gathering at my grandmother's house.", tr: "Gelecek Pazar bütün ailem büyükannemin evinde toplanıyor olacak." },
      { type: "rule", text: "Future Continuous ile ilgili son bir soru-cevap alıştırması görelim, bu tense'in doğal konuşmadaki yerini pekiştirelim." },
      { type: "example", en: "Will you be staying at the same hotel next time? — Yes, we'll probably be staying there again, we loved it.", tr: "Bir dahaki sefere aynı otelde mi kalıyor olacaksın? — Evet, muhtemelen yine orada kalıyor olacağız, çok sevdik." },
      { type: "example", en: "What will you be wearing to the wedding? — I'll be wearing the blue dress I bought last week.", tr: "Düğüne ne giyiyor olacaksın? — Geçen hafta aldığım mavi elbiseyi giyiyor olacağım." },
      { type: "rule", text: "Future Continuous, gelecekte iki eylemin aynı anda yaşanacağını karşılaştırmalı olarak anlatırken de kullanılabilir." },
      { type: "example", en: "While you'll be relaxing on the beach, I'll be sitting in an office all day.", tr: "Sen sahilde dinlenirken, ben bütün gün ofiste oturuyor olacağım." },
      { type: "example", en: "By the time you wake up, I will already be working, and you will still be sleeping.", tr: "Sen uyandığında ben çoktan çalışıyor olacağım ve sen hâlâ uyuyor olacaksın." },
      { type: "rule", text: "Future Continuous, gelecekteki bir organizasyonun veya etkinliğin akışını anlatırken de kullanılır: konferanslar, düğünler, festivaller gibi." },
      { type: "example", en: "Throughout the conference, experts will be sharing their latest research.", tr: "Konferans boyunca uzmanlar en son araştırmalarını paylaşıyor olacak." },
      { type: "example", en: "During the festival, local bands will be performing every evening.", tr: "Festival süresince yerel gruplar her akşam performans sergiliyor olacak." },
      { type: "rule", text: "Bu tense'i pekiştiren bir soru-cevap alıştırması daha görelim." },
      { type: "example", en: "Will your parents be visiting you this Christmas? — Yes, they'll be staying with us for a whole week.", tr: "Ailen bu Noel seni ziyaret ediyor olacak mı? — Evet, bizimle bütün bir hafta kalıyor olacaklar." },
      { type: "example", en: "Will the shop still be open at 9 pm? — No, it will be closing at 8.", tr: "Dükkan saat 9'da hâlâ açık olacak mı? — Hayır, saat 8'de kapanıyor olacak." },
      { type: "rule", text: "Son olarak Future Continuous'un günlük hayatta kullanıldığı bir kapanış paragrafı görelim." },
      { type: "example", en: "Ten years from now, I hope I will be living my dream life, working on projects I love, and traveling the world whenever I want.", tr: "Bundan on yıl sonra, umarım hayalimdeki hayatı yaşıyor, sevdiğim projeler üzerinde çalışıyor ve istediğim zaman dünyayı geziyor olacağım." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
