import { publishQuiz, prisma, QuizDef } from "./lib/quiz-lib";

const ZAMANLAR = "İngilizce - Zamanlar";
const KELIME = "İngilizce - Kelime ve Kalıplar";

const quizzes: QuizDef[] = [
  {
    title: "7 Emir Kipi, Renkler ve Aile Üyeleri - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "Emir kipinde fiil hangi halde kullanılır?", optionA: "V1 (yalın)", optionB: "V2", optionC: "V-ing", optionD: "V3", correct: "A" },
      { prompt: "___ the door! (Kapıyı kapat!)", optionA: "Close", optionB: "Closes", optionC: "Closing", optionD: "Closed", correct: "A" },
      { prompt: "Emir kipinin olumsuzu nasıl yapılır?", optionA: "NOT + V1", optionB: "DON'T + V1", optionC: "ISN'T + V1", optionD: "NO + V1", correct: "B" },
      { prompt: "___ talk during the exam! (konuşma)", optionA: "Not", optionB: "Don't", optionC: "Doesn't", optionD: "No", correct: "B" },
      { prompt: "\"Kırmızı\" kelimesinin İngilizcesi nedir?", optionA: "blue", optionB: "red", optionC: "green", optionD: "yellow", correct: "B" },
      { prompt: "\"Sarı\" kelimesinin İngilizcesi nedir?", optionA: "yellow", optionB: "purple", optionC: "orange", optionD: "pink", correct: "A" },
      { prompt: "\"Mor\" kelimesinin İngilizcesi nedir?", optionA: "brown", optionB: "purple", optionC: "grey", optionD: "black", correct: "B" },
      { prompt: "\"Amca/Dayı\" kelimesinin İngilizcesi nedir?", optionA: "aunt", optionB: "uncle", optionC: "cousin", optionD: "nephew", correct: "B" },
      { prompt: "\"Teyze/Hala\" kelimesinin İngilizcesi nedir?", optionA: "aunt", optionB: "uncle", optionC: "niece", optionD: "grandmother", correct: "A" },
      { prompt: "\"Kuzen\" kelimesinin İngilizcesi nedir?", optionA: "nephew", optionB: "niece", optionC: "cousin", optionD: "sibling", correct: "C" },
      { prompt: "\"Torun\" kelimesinin İngilizcesi nedir?", optionA: "grandchild", optionB: "grandparent", optionC: "sibling", optionD: "cousin", correct: "A" },
      { prompt: "___ sit down, please! (rica ile)", optionA: "Please", optionB: "Don't", optionC: "Never", optionD: "No", correct: "A" },
      { prompt: "\"Kardeş\" (cinsiyet belirtmeden) kelimesinin İngilizcesi nedir?", optionA: "brother", optionB: "sister", optionC: "sibling", optionD: "cousin", correct: "C" },
      { prompt: "Let's ___ a break! (mola verelim)", optionA: "take", optionB: "takes", optionC: "taking", optionD: "took", correct: "A" },
      { prompt: "\"Turuncu\" kelimesinin İngilizcesi nedir?", optionA: "orange", optionB: "yellow", optionC: "brown", optionD: "pink", correct: "A" },
      { prompt: "Never ___ up! (asla vazgeçme)", optionA: "give", optionB: "gives", optionC: "giving", optionD: "gave", correct: "A" },
      { prompt: "\"Yeğen\" (erkek) kelimesinin İngilizcesi nedir?", optionA: "niece", optionB: "nephew", optionC: "cousin", optionD: "uncle", correct: "B" },
      { prompt: "___ careful! (dikkatli ol)", optionA: "Be", optionB: "Is", optionC: "Are", optionD: "Am", correct: "A" },
      { prompt: "\"Gri\" kelimesinin İngilizcesi nedir?", optionA: "black", optionB: "white", optionC: "grey", optionD: "brown", correct: "C" },
      { prompt: "___ afraid! (korkma)", optionA: "Don't be", optionB: "Doesn't be", optionC: "Not be", optionD: "No be", correct: "A" },
    ],
  },
  {
    title: "5 Geçmiş Zamanın Şimdiki Hali (Past Continuous) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "I ___ working at 9 o'clock yesterday.", optionA: "was", optionB: "were", optionC: "am", optionD: "is", correct: "A" },
      { prompt: "They ___ sleeping when I called.", optionA: "was", optionB: "were", optionC: "is", optionD: "are", correct: "B" },
      { prompt: "Past Continuous yapısı nedir?", optionA: "WAS/WERE + V-ing", optionB: "WAS/WERE + V3", optionC: "DID + V1", optionD: "HAVE + V3", correct: "A" },
      { prompt: "While I ___ cooking, he was watching TV.", optionA: "was", optionB: "were", optionC: "am", optionD: "is", correct: "A" },
      { prompt: "What ___ you doing at that time?", optionA: "was", optionB: "were", optionC: "did", optionD: "do", correct: "B" },
      { prompt: "She wasn't ___ to me.", optionA: "listen", optionB: "listens", optionC: "listening", optionD: "listened", correct: "C" },
      { prompt: "___ he working when you arrived?", optionA: "Was", optionB: "Were", optionC: "Did", optionD: "Does", correct: "A" },
      { prompt: "I was sleeping when the phone ___.", optionA: "ring", optionB: "rang", optionC: "rings", optionD: "ringing", correct: "B" },
      { prompt: "We were walking when it ___ to rain.", optionA: "start", optionB: "started", optionC: "starts", optionD: "starting", correct: "B" },
      { prompt: "They weren't ___ for us.", optionA: "wait", optionB: "waits", optionC: "waited", optionD: "waiting", correct: "D" },
      { prompt: "Past Continuous en çok hangi bağlaçla kullanılır?", optionA: "SO", optionB: "WHILE", optionC: "BECAUSE", optionD: "ALTHOUGH", correct: "B" },
      { prompt: "I ___ TV when you called.", optionA: "was watching", optionB: "were watching", optionC: "watch", optionD: "watched", correct: "A" },
      { prompt: "The sun was shining and the birds ___ singing.", optionA: "was", optionB: "were", optionC: "is", optionD: "are", correct: "B" },
      { prompt: "___ you sleeping at midnight?", optionA: "Was", optionB: "Were", optionC: "Did", optionD: "Do", correct: "B" },
      { prompt: "He was driving when the accident ___.", optionA: "happen", optionB: "happened", optionC: "happens", optionD: "happening", correct: "B" },
      { prompt: "Past Continuous olumsuz yapısı nedir?", optionA: "WASN'T/WEREN'T + V-ing", optionB: "DIDN'T + V1", optionC: "ISN'T + V-ing", optionD: "HAVEN'T + V3", correct: "A" },
      { prompt: "I was reading when the lights ___ out.", optionA: "go", optionB: "went", optionC: "goes", optionD: "going", correct: "B" },
      { prompt: "She was crying when I ___ her.", optionA: "see", optionB: "saw", optionC: "sees", optionD: "seeing", correct: "B" },
      { prompt: "We ___ talking about you.", optionA: "was", optionB: "were", optionC: "is", optionD: "are", correct: "B" },
      { prompt: "It was raining ___ the wind was blowing hard.", optionA: "and", optionB: "but", optionC: "or", optionD: "so", correct: "A" },
    ],
  },
  {
    title: "8 Karşılaştırma Kalıpları (Comparative - Superlative) - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "This bag is ___ than that one. (BIG)", optionA: "big", optionB: "bigger", optionC: "biggest", optionD: "more big", correct: "B" },
      { prompt: "He is the ___ boy in his class. (TALL)", optionA: "tall", optionB: "taller", optionC: "tallest", optionD: "most tall", correct: "C" },
      { prompt: "Çok heceli sıfatlarda karşılaştırma nasıl yapılır?", optionA: "-ER eklenir", optionB: "MORE kullanılır", optionC: "-EST eklenir", optionD: "THE eklenir", correct: "B" },
      { prompt: "This car is ___ expensive than the other one.", optionA: "more", optionB: "most", optionC: "much", optionD: "many", correct: "A" },
      { prompt: "\"GOOD\" kelimesinin karşılaştırma hali nedir?", optionA: "gooder", optionB: "better", optionC: "best", optionD: "more good", correct: "B" },
      { prompt: "\"BAD\" kelimesinin karşılaştırma hali nedir?", optionA: "badder", optionB: "worse", optionC: "worst", optionD: "more bad", correct: "B" },
      { prompt: "She is the most successful student ___ this class.", optionA: "of", optionB: "at", optionC: "in", optionD: "on", correct: "C" },
      { prompt: "Eşitlik bildirmek için hangi kalıp kullanılır?", optionA: "AS...AS", optionB: "MORE...THAN", optionC: "THE MOST", optionD: "LESS...THAN", correct: "A" },
      { prompt: "He is ___ tall as his brother. (eşitlik)", optionA: "so", optionB: "as", optionC: "more", optionD: "most", correct: "B" },
      { prompt: "This test isn't ___ difficult as the last one.", optionA: "so", optionB: "as", optionC: "more", optionD: "most", correct: "B" },
      { prompt: "-Y ile biten sıfatlarda -ER eklenirken Y ne olur?", optionA: "Y kalır", optionB: "Y düşer", optionC: "Y, I'ya döner", optionD: "Y ikiye katlanır", correct: "C" },
      { prompt: "\"HAPPY\" kelimesinin karşılaştırma hali nedir?", optionA: "happyer", optionB: "happier", optionC: "more happy", optionD: "happiest", correct: "B" },
      { prompt: "\"BIG\" kelimesinin karşılaştırma halinde son harf ne olur?", optionA: "değişmez", optionB: "ikiye katlanır", optionC: "düşer", optionD: "Y'ye döner", correct: "B" },
      { prompt: "This is the ___ restaurant in town. (GOOD)", optionA: "gooder", optionB: "better", optionC: "best", optionD: "goodest", correct: "C" },
      { prompt: "She works ___ than everyone else. (HARD)", optionA: "harder", optionB: "more hard", optionC: "hardest", optionD: "most hard", correct: "A" },
      { prompt: "En üstünlük (superlative) yapısında hangi kelime mutlaka kullanılır?", optionA: "A", optionB: "AN", optionC: "THE", optionD: "SOME", correct: "C" },
      { prompt: "This is much ___ than my old phone. (GOOD)", optionA: "gooder", optionB: "better", optionC: "best", optionD: "well", correct: "B" },
      { prompt: "Traffic is ___ in the morning than in the evening. (BAD)", optionA: "worse", optionB: "worst", optionC: "badder", optionD: "more bad", correct: "A" },
      { prompt: "\"FAR\" kelimesinin karşılaştırma hali nedir?", optionA: "farer", optionB: "farther", optionC: "farrer", optionD: "more far", correct: "B" },
      { prompt: "This is the least expensive ___. (seçenek)", optionA: "option", optionB: "options", optionC: "optioning", optionD: "optioned", correct: "A" },
    ],
  },
  {
    title: "9 Aylar ve Günlük Kalıplar - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "Aylardan önce hangi edat kullanılır?", optionA: "ON", optionB: "AT", optionC: "IN", optionD: "TO", correct: "C" },
      { prompt: "Günlerden önce hangi edat kullanılır?", optionA: "ON", optionB: "AT", optionC: "IN", optionD: "TO", correct: "A" },
      { prompt: "Saatlerden önce hangi edat kullanılır?", optionA: "ON", optionB: "AT", optionC: "IN", optionD: "TO", correct: "B" },
      { prompt: "My birthday is ___ June.", optionA: "on", optionB: "at", optionC: "in", optionD: "to", correct: "C" },
      { prompt: "I have an exam ___ Monday.", optionA: "on", optionB: "at", optionC: "in", optionD: "to", correct: "A" },
      { prompt: "The meeting is ___ 5 o'clock.", optionA: "on", optionB: "at", optionC: "in", optionD: "to", correct: "B" },
      { prompt: "Mevsimlerden önce hangi edat kullanılır?", optionA: "ON", optionB: "AT", optionC: "IN", optionD: "TO", correct: "C" },
      { prompt: "Flowers bloom ___ spring.", optionA: "on", optionB: "at", optionC: "in", optionD: "to", correct: "C" },
      { prompt: "\"It's half past seven\" ne demektir?", optionA: "Saat yedi", optionB: "Saat yedi buçuk", optionC: "Yediye çeyrek var", optionD: "Saat sekiz", correct: "B" },
      { prompt: "\"It's a quarter to nine\" ne demektir?", optionA: "Saat dokuz", optionB: "Dokuza çeyrek var", optionC: "Saat dokuz buçuk", optionD: "Sekize çeyrek geçe", correct: "B" },
      { prompt: "I usually ___ up at seven. (uyanmak)", optionA: "wake", optionB: "wakes", optionC: "waking", optionD: "woke", correct: "A" },
      { prompt: "\"Genellikle\" kelimesinin İngilizcesi nedir?", optionA: "always", optionB: "usually", optionC: "never", optionD: "rarely", correct: "B" },
      { prompt: "\"Nadiren\" kelimesinin İngilizcesi nedir?", optionA: "always", optionB: "often", optionC: "rarely", optionD: "usually", correct: "C" },
      { prompt: "It's very sunny today, take your ___.", optionA: "umbrella", optionB: "sunglasses", optionC: "coat", optionD: "scarf", correct: "B" },
      { prompt: "Don't forget your ___, it's raining.", optionA: "umbrella", optionB: "sunglasses", optionC: "hat", optionD: "gloves", correct: "A" },
      { prompt: "How much ___ this jacket?", optionA: "is", optionB: "are", optionC: "do", optionD: "does", correct: "A" },
      { prompt: "This shirt is ___ sale this week. (indirimde)", optionA: "at", optionB: "on", optionC: "in", optionD: "for", correct: "B" },
      { prompt: "I need to make an ___ with the dentist. (randevu)", optionA: "appointment", optionB: "meeting", optionC: "reservation", optionD: "invitation", correct: "A" },
      { prompt: "We had to ___ the meeting until next week. (ertelemek)", optionA: "cancel", optionB: "postpone", optionC: "start", optionD: "join", correct: "B" },
      { prompt: "Are you ___ this weekend? (müsait)", optionA: "free", optionB: "busy", optionC: "tired", optionD: "bored", correct: "A" },
    ],
  },
  {
    title: "6 Yakın Geçmiş Zaman (Present Perfect) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "Present Perfect yapısı nedir?", optionA: "HAVE/HAS + V3", optionB: "HAD + V3", optionC: "WILL HAVE + V3", optionD: "BE + V-ing", correct: "A" },
      { prompt: "I have ___ my homework.", optionA: "finish", optionB: "finished", optionC: "finishing", optionD: "finishes", correct: "B" },
      { prompt: "She has ___ left.", optionA: "already", optionB: "yet", optionC: "still", optionD: "ago", correct: "A" },
      { prompt: "___ you ever been to London?", optionA: "Do", optionB: "Did", optionC: "Have", optionD: "Has", correct: "C" },
      { prompt: "He ___ called me today.", optionA: "hasn't", optionB: "haven't", optionC: "didn't", optionD: "doesn't", correct: "A" },
      { prompt: "We have visited that museum ___.", optionA: "yesterday", optionB: "twice", optionC: "ago", optionD: "last week", correct: "B" },
      { prompt: "FOR ve SINCE arasındaki fark nedir?", optionA: "FOR süre, SINCE başlangıç noktası", optionB: "İkisi de aynı", optionC: "FOR başlangıç, SINCE süre", optionD: "Fark yok", correct: "A" },
      { prompt: "They have lived here ___ ten years.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "I have known him ___ 2015.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "A" },
      { prompt: "\"GO\" fiilinin 3. hali nedir?", optionA: "went", optionB: "gone", optionC: "going", optionD: "goes", correct: "B" },
      { prompt: "Has she ___ her homework?", optionA: "do", optionB: "did", optionC: "done", optionD: "doing", correct: "C" },
      { prompt: "I have never ___ there before.", optionA: "be", optionB: "being", optionC: "been", optionD: "was", correct: "C" },
      { prompt: "Present Perfect ile hangi zaman ifadesi KULLANILMAZ?", optionA: "already", optionB: "yesterday", optionC: "yet", optionD: "never", correct: "B" },
      { prompt: "He has ___ arrived.", optionA: "just", optionB: "yesterday", optionC: "ago", optionD: "last week", correct: "A" },
      { prompt: "Present Perfect ile Past Simple arasındaki temel fark nedir?", optionA: "Fark yok", optionB: "Past Simple net zaman belirtir, Present Perfect belirtmez", optionC: "İkisi de aynı zamanı anlatır", optionD: "Present Perfect gelecek içindir", correct: "B" },
      { prompt: "Have you finished the report ___?", optionA: "already", optionB: "yet", optionC: "ago", optionD: "since", correct: "B" },
      { prompt: "We have ___ paid the bill.", optionA: "already", optionB: "yet", optionC: "ago", optionD: "last week", correct: "A" },
      { prompt: "\"EAT\" fiilinin 3. hali nedir?", optionA: "ate", optionB: "eaten", optionC: "eating", optionD: "eats", correct: "B" },
      { prompt: "How long have you ___ here?", optionA: "live", optionB: "lives", optionC: "lived", optionD: "living", correct: "C" },
      { prompt: "I have lost my keys ___ in the house.", optionA: "somewhere", optionB: "yesterday", optionC: "ago", optionD: "last night", correct: "A" },
    ],
  },
];

async function main() {
  for (const quiz of quizzes) {
    await publishQuiz(quiz);
  }
}

main().finally(() => prisma.$disconnect());
