import { publishQuiz, prisma, QuizDef } from "./lib/quiz-lib";

const ZAMANLAR = "İngilizce - Zamanlar";
const KELIME = "İngilizce - Kelime ve Kalıplar";

const quizzes: QuizDef[] = [
  {
    title: "3 Şimdiki Zaman (Present Continuous) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "I ___ TV right now.", optionA: "watch", optionB: "watches", optionC: "am watching", optionD: "watched", correct: "C" },
      { prompt: "She ___ a book at the moment.", optionA: "read", optionB: "reads", optionC: "is reading", optionD: "was reading", correct: "C" },
      { prompt: "They ___ football now.", optionA: "play", optionB: "plays", optionC: "are playing", optionD: "played", correct: "C" },
      { prompt: "___ you listening to me?", optionA: "Do", optionB: "Does", optionC: "Are", optionD: "Is", correct: "C" },
      { prompt: "He ___ not sleeping.", optionA: "is", optionB: "am", optionC: "are", optionD: "do", correct: "A" },
      { prompt: "We ___ having dinner right now.", optionA: "is", optionB: "am", optionC: "are", optionD: "be", correct: "C" },
      { prompt: "Present Continuous'un yapısı nedir?", optionA: "V1", optionB: "BE + V-ing", optionC: "BE + V3", optionD: "HAVE + V3", correct: "B" },
      { prompt: "Look! It ___ raining.", optionA: "is", optionB: "am", optionC: "are", optionD: "do", correct: "A" },
      { prompt: "I ___ writing an email at the moment.", optionA: "is", optionB: "am", optionC: "are", optionD: "be", correct: "B" },
      { prompt: "Sessiz -E ile biten fiillerde -ING eklenirken ne olur?", optionA: "E düşer", optionB: "E kalır", optionC: "E ikiye katlanır", optionD: "E'ye Y eklenir", correct: "A" },
      { prompt: "RUN fiiline -ING eklenince nasıl yazılır?", optionA: "runing", optionB: "running", optionC: "runeing", optionD: "runnning", correct: "B" },
      { prompt: "She ___ cooking dinner right now.", optionA: "is", optionB: "am", optionC: "are", optionD: "do", correct: "A" },
      { prompt: "___ they working today?", optionA: "Do", optionB: "Does", optionC: "Are", optionD: "Is", correct: "C" },
      { prompt: "I'm not ___ anything important.", optionA: "do", optionB: "doing", optionC: "does", optionD: "did", correct: "B" },
      { prompt: "He is ___ his homework now.", optionA: "do", optionB: "does", optionC: "doing", optionD: "did", correct: "C" },
      { prompt: "Present Continuous genellikle hangi zarflarla kullanılır?", optionA: "always, usually", optionB: "now, at the moment", optionC: "yesterday, ago", optionD: "next week, tomorrow", correct: "B" },
      { prompt: "We ___ studying for the exam this week.", optionA: "is", optionB: "am", optionC: "are", optionD: "be", correct: "C" },
      { prompt: "Durum (state) fiilleri genelde hangi zamanla kullanılmaz?", optionA: "Present Simple", optionB: "Present Continuous", optionC: "Past Simple", optionD: "Future Simple", correct: "B" },
      { prompt: "___ she wearing a red dress today?", optionA: "Do", optionB: "Does", optionC: "Is", optionD: "Are", correct: "C" },
      { prompt: "The children ___ playing in the garden.", optionA: "is", optionB: "am", optionC: "are", optionD: "be", correct: "C" },
    ],
  },
  {
    title: "4 Günlük Fiiller ve Edatlar - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "I get ___ at seven every morning. (kalkmak)", optionA: "up", optionB: "on", optionC: "in", optionD: "at", correct: "A" },
      { prompt: "She turns ___ the lights before leaving. (kapatmak)", optionA: "on", optionB: "off", optionC: "up", optionD: "down", correct: "B" },
      { prompt: "We arrived ___ the airport early.", optionA: "in", optionB: "on", optionC: "at", optionD: "to", correct: "C" },
      { prompt: "He lives ___ Istanbul.", optionA: "at", optionB: "on", optionC: "in", optionD: "to", correct: "C" },
      { prompt: "The book is ___ the table.", optionA: "in", optionB: "on", optionC: "at", optionD: "under", correct: "B" },
      { prompt: "I'm looking ___ my keys. (aramak)", optionA: "for", optionB: "at", optionC: "after", optionD: "up", correct: "A" },
      { prompt: "She takes care ___ her little brother.", optionA: "of", optionB: "for", optionC: "with", optionD: "about", correct: "A" },
      { prompt: "We arrived ___ Monday morning.", optionA: "in", optionB: "at", optionC: "on", optionD: "to", correct: "C" },
      { prompt: "Wait ___ me, please!", optionA: "for", optionB: "to", optionC: "at", optionD: "on", correct: "A" },
      { prompt: "He depends ___ his parents.", optionA: "at", optionB: "in", optionC: "on", optionD: "to", correct: "C" },
      { prompt: "I'm interested ___ music.", optionA: "at", optionB: "in", optionC: "on", optionD: "to", correct: "B" },
      { prompt: "Get ___ the car, we're leaving!", optionA: "in", optionB: "on", optionC: "at", optionD: "into", correct: "A" },
      { prompt: "She's good ___ math.", optionA: "at", optionB: "in", optionC: "on", optionD: "with", correct: "A" },
      { prompt: "We're afraid ___ spiders.", optionA: "at", optionB: "in", optionC: "of", optionD: "with", correct: "C" },
      { prompt: "He apologized ___ being late.", optionA: "for", optionB: "to", optionC: "about", optionD: "with", correct: "A" },
      { prompt: "I'm proud ___ you.", optionA: "at", optionB: "of", optionC: "with", optionD: "for", correct: "B" },
      { prompt: "She's married ___ a doctor.", optionA: "with", optionB: "to", optionC: "at", optionD: "for", correct: "B" },
      { prompt: "Turn ___ the TV, I want to watch something. (açmak)", optionA: "off", optionB: "on", optionC: "up", optionD: "down", correct: "B" },
      { prompt: "He picked ___ the phone. (telefonu açmak)", optionA: "up", optionB: "on", optionC: "in", optionD: "at", correct: "A" },
      { prompt: "We're looking forward ___ the holidays.", optionA: "for", optionB: "to", optionC: "at", optionD: "with", correct: "B" },
    ],
  },
  {
    title: "5 Sorular ve Dönüşlü Zamirler - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "\"Kendim\" kelimesinin İngilizcesi nedir?", optionA: "myself", optionB: "yourself", optionC: "himself", optionD: "itself", correct: "A" },
      { prompt: "She hurt ___ while cooking.", optionA: "myself", optionB: "herself", optionC: "himself", optionD: "themselves", correct: "B" },
      { prompt: "They did it ___. (kendileri)", optionA: "themselves", optionB: "ourselves", optionC: "yourselves", optionD: "itself", correct: "A" },
      { prompt: "___ is your name?", optionA: "Who", optionB: "What", optionC: "Where", optionD: "When", correct: "B" },
      { prompt: "___ do you live?", optionA: "Who", optionB: "What", optionC: "Where", optionD: "Why", correct: "C" },
      { prompt: "___ are you late?", optionA: "Who", optionB: "What", optionC: "Where", optionD: "Why", correct: "D" },
      { prompt: "___ is coming to the party?", optionA: "Who", optionB: "What", optionC: "Where", optionD: "Why", correct: "A" },
      { prompt: "___ books do you have?", optionA: "How much", optionB: "How many", optionC: "How long", optionD: "How often", correct: "B" },
      { prompt: "___ money do you need?", optionA: "How much", optionB: "How many", optionC: "How long", optionD: "How often", correct: "A" },
      { prompt: "___ do you go to the gym?", optionA: "How much", optionB: "How many", optionC: "How long", optionD: "How often", correct: "D" },
      { prompt: "He looked at ___ in the mirror.", optionA: "himself", optionB: "herself", optionC: "itself", optionD: "themselves", correct: "A" },
      { prompt: "We enjoyed ___ at the party.", optionA: "myself", optionB: "ourselves", optionC: "yourselves", optionD: "themselves", correct: "B" },
      { prompt: "Be careful, don't hurt ___!", optionA: "myself", optionB: "yourself", optionC: "himself", optionD: "itself", correct: "B" },
      { prompt: "The cat cleaned ___.", optionA: "himself", optionB: "herself", optionC: "itself", optionD: "themselves", correct: "C" },
      { prompt: "___ is this bag? (kimin)", optionA: "Who", optionB: "Whose", optionC: "What", optionD: "Which", correct: "B" },
      { prompt: "___ one do you prefer? (hangisi)", optionA: "Who", optionB: "What", optionC: "Which", optionD: "Whose", correct: "C" },
      { prompt: "I made this cake ___. (kendim)", optionA: "myself", optionB: "yourself", optionC: "himself", optionD: "herself", correct: "A" },
      { prompt: "___ time does the movie start?", optionA: "What", optionB: "Which", optionC: "Whose", optionD: "Who", correct: "A" },
      { prompt: "They introduced ___ to the class.", optionA: "myself", optionB: "themselves", optionC: "ourselves", optionD: "itself", correct: "B" },
      { prompt: "___ is the weather today?", optionA: "Who", optionB: "How", optionC: "Whose", optionD: "Which", correct: "B" },
    ],
  },
  {
    title: "4 Di'li Geçmiş Zaman (Past Simple) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "I ___ to the cinema yesterday.", optionA: "go", optionB: "goes", optionC: "went", optionD: "going", correct: "C" },
      { prompt: "She ___ not come to school.", optionA: "don't", optionB: "doesn't", optionC: "didn't", optionD: "isn't", correct: "C" },
      { prompt: "___ you see him yesterday?", optionA: "Do", optionB: "Does", optionC: "Did", optionD: "Are", correct: "C" },
      { prompt: "\"GO\" fiilinin geçmiş hali nedir?", optionA: "goed", optionB: "went", optionC: "gone", optionD: "going", correct: "B" },
      { prompt: "They ___ a movie last night.", optionA: "watch", optionB: "watched", optionC: "watches", optionD: "watching", correct: "B" },
      { prompt: "He ___ his homework yesterday.", optionA: "doesn't", optionB: "didn't do", optionC: "don't did", optionD: "not did", correct: "B" },
      { prompt: "\"WRITE\" fiilinin geçmiş hali nedir?", optionA: "writed", optionB: "wrote", optionC: "written", optionD: "writing", correct: "B" },
      { prompt: "We ___ in Paris last year.", optionA: "are", optionB: "is", optionC: "were", optionD: "was", correct: "C" },
      { prompt: "I ___ very tired last night.", optionA: "am", optionB: "is", optionC: "was", optionD: "were", correct: "C" },
      { prompt: "___ she call you yesterday?", optionA: "Do", optionB: "Does", optionC: "Did", optionD: "Was", correct: "C" },
      { prompt: "He didn't ___ the truth.", optionA: "tell", optionB: "told", optionC: "tells", optionD: "telling", correct: "A" },
      { prompt: "Düzenli fiillerin geçmiş hali nasıl yapılır?", optionA: "-ing eklenir", optionB: "-ed eklenir", optionC: "V3 eklenir", optionD: "değişmez", correct: "B" },
      { prompt: "\"EAT\" fiilinin geçmiş hali nedir?", optionA: "eated", optionB: "ate", optionC: "eaten", optionD: "eating", correct: "B" },
      { prompt: "They ___ here two years ago.", optionA: "live", optionB: "lives", optionC: "lived", optionD: "living", correct: "C" },
      { prompt: "I ___ not know about the meeting.", optionA: "am", optionB: "do", optionC: "did", optionD: "does", correct: "C" },
      { prompt: "She ___ born in 1995.", optionA: "is", optionB: "was", optionC: "were", optionD: "be", correct: "B" },
      { prompt: "We ___ at the party until midnight.", optionA: "stay", optionB: "stayed", optionC: "stays", optionD: "staying", correct: "B" },
      { prompt: "\"BUY\" fiilinin geçmiş hali nedir?", optionA: "buyed", optionB: "bought", optionC: "buyen", optionD: "buying", correct: "B" },
      { prompt: "___ they at home last night?", optionA: "Do", optionB: "Does", optionC: "Did", optionD: "Were", correct: "D" },
      { prompt: "He ___ his keys yesterday.", optionA: "lose", optionB: "loses", optionC: "lost", optionD: "losing", correct: "C" },
    ],
  },
  {
    title: "6 Was - Were ve Farklı Sıfatlar - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "I ___ at home yesterday.", optionA: "am", optionB: "is", optionC: "was", optionD: "were", correct: "C" },
      { prompt: "They ___ at school last week.", optionA: "was", optionB: "were", optionC: "is", optionD: "are", correct: "B" },
      { prompt: "She ___ not happy.", optionA: "wasn't", optionB: "weren't", optionC: "isn't", optionD: "aren't", correct: "A" },
      { prompt: "___ you tired last night?", optionA: "Was", optionB: "Were", optionC: "Is", optionD: "Are", correct: "B" },
      { prompt: "We ___ excited about the trip.", optionA: "was", optionB: "were", optionC: "is", optionD: "am", correct: "B" },
      { prompt: "It ___ cold yesterday.", optionA: "was", optionB: "were", optionC: "is", optionD: "are", correct: "A" },
      { prompt: "\"Muhteşem\" kelimesinin İngilizcesi nedir?", optionA: "awful", optionB: "amazing", optionC: "boring", optionD: "terrible", correct: "B" },
      { prompt: "\"Korkunç\" kelimesinin İngilizcesi nedir?", optionA: "amazing", optionB: "wonderful", optionC: "terrible", optionD: "fantastic", correct: "C" },
      { prompt: "He ___ at the meeting yesterday.", optionA: "was", optionB: "were", optionC: "is", optionD: "are", correct: "A" },
      { prompt: "___ she at work on Monday?", optionA: "Was", optionB: "Were", optionC: "Is", optionD: "Did", correct: "A" },
      { prompt: "\"Şaşırtıcı\" kelimesinin İngilizcesi nedir?", optionA: "boring", optionB: "surprising", optionC: "tired", optionD: "angry", correct: "B" },
      { prompt: "The weather ___ terrible last week.", optionA: "was", optionB: "were", optionC: "is", optionD: "are", correct: "A" },
      { prompt: "My grandparents ___ farmers.", optionA: "was", optionB: "were", optionC: "is", optionD: "am", correct: "B" },
      { prompt: "\"Yorgun\" kelimesinin İngilizcesi nedir?", optionA: "tired", optionB: "excited", optionC: "bored", optionD: "angry", correct: "A" },
      { prompt: "I ___ born in Ankara.", optionA: "am", optionB: "was", optionC: "were", optionD: "be", correct: "B" },
      { prompt: "___ your parents happy with the news?", optionA: "Was", optionB: "Were", optionC: "Is", optionD: "Are", correct: "B" },
      { prompt: "\"Sıkıcı\" kelimesinin İngilizcesi nedir?", optionA: "exciting", optionB: "interesting", optionC: "boring", optionD: "amazing", correct: "C" },
      { prompt: "The movie ___ really interesting.", optionA: "was", optionB: "were", optionC: "is", optionD: "am", correct: "A" },
      { prompt: "We ___ not ready for the exam.", optionA: "wasn't", optionB: "weren't", optionC: "isn't", optionD: "aren't", correct: "B" },
      { prompt: "\"Heyecanlı\" kelimesinin İngilizcesi nedir?", optionA: "bored", optionB: "excited", optionC: "tired", optionD: "sad", correct: "B" },
    ],
  },
];

async function main() {
  for (const quiz of quizzes) {
    await publishQuiz(quiz);
  }
}

main().finally(() => prisma.$disconnect());
