import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "17_Istek_Kaliplari",
    title: "\"-MENİ / -MANI\" İSTEK KALIPLARI",
    blocks: [
      { type: "rule", text: "İngilizcede \"birinin bir şey yapmasını istemek\" anlamı WANT + kişi + TO + fiil kalıbıyla kurulur." },
      { type: "pattern", text: "WANT + KİŞİ + TO + V1" },
      { type: "example", en: "I want to come.", tr: "Gelmek istiyorum." },
      { type: "example", en: "I want you to come.", tr: "Gelmeni istiyorum." },
      { type: "example", en: "They want us to finish this project.", tr: "Bu projeyi bitirmemizi istiyorlar." },
      { type: "example", en: "Do you want him to come here?", tr: "Onun buraya gelmesini istiyor musun?" },
      { type: "example", en: "She wants them to leave.", tr: "O, onların ayrılmasını istiyor." },
      { type: "rule", text: "Bu kalıpta \"istemek\" fiilinden sonra gelen kişi nesne (object) konumundadır ve TO'dan sonra gelen fiil her zaman yalın haldedir (V1); özneye göre bu fiil hiç değişmez." },
      { type: "example", en: "He wants her to call him tonight.", tr: "Onun bu gece kendisini aramasını istiyor." },
      { type: "example", en: "We don't want you to worry about it.", tr: "Bunun için endişelenmeni istemiyoruz." },
      { type: "pattern", text: "WOULD LIKE + KİŞİ + TO + V1 = ...mesini isterim (kibar istek)" },
      { type: "rule", text: "WOULD LIKE, WANT'a göre daha kibar bir istek bildirir ve resmi ortamlarda WANT yerine tercih edilir." },
      { type: "example", en: "I would like you to meet my parents.", tr: "Ailemle tanışmanı isterim." },
      { type: "example", en: "We would like you to arrive a bit earlier.", tr: "Biraz daha erken gelmenizi isteriz." },
      { type: "pattern", text: "WOULD PREFER + KİŞİ + TO + V1 = ...mesini tercih ederim" },
      { type: "example", en: "I would prefer you to pay in cash.", tr: "Nakit ödemeni tercih ederim." },
      { type: "pattern", text: "ASK + KİŞİ + TO + V1 = birinden bir şey yapmasını rica etmek" },
      { type: "example", en: "I asked him to close the door.", tr: "Ondan kapıyı kapatmasını rica ettim." },
      { type: "example", en: "She asked me to help her with the boxes.", tr: "Kutularla ona yardım etmemi rica etti." },
      { type: "pattern", text: "TELL + KİŞİ + TO + V1 = birine bir şey yapmasını söylemek (talimat/emir)" },
      { type: "example", en: "The doctor told him to rest for a week.", tr: "Doktor ona bir hafta dinlenmesini söyledi." },
      { type: "example", en: "My mother told me to be home before ten.", tr: "Annem saat ondan önce evde olmamı söyledi." },
      { type: "rule", text: "ASK kibarca rica etmeyi, TELL ise daha kesin bir talimat ya da emir vermeyi ifade eder." },
      { type: "pattern", text: "ADVISE + KİŞİ + TO + V1 = tavsiye etmek" },
      { type: "example", en: "The dentist advised me to brush my teeth twice a day.", tr: "Diş hekimi dişlerimi günde iki kez fırçalamamı tavsiye etti." },
      { type: "pattern", text: "ALLOW / PERMIT + KİŞİ + TO + V1 = izin vermek" },
      { type: "example", en: "My parents don't allow me to stay out late.", tr: "Ailem geç saatlere kadar dışarıda kalmama izin vermiyor." },
      { type: "example", en: "They permitted us to use the pool.", tr: "Havuzu kullanmamıza izin verdiler." },
      { type: "pattern", text: "ENCOURAGE + KİŞİ + TO + V1 = teşvik etmek, cesaretlendirmek" },
      { type: "example", en: "Our teacher always encourages us to ask questions.", tr: "Öğretmenimiz soru sormamız için bizi her zaman teşvik eder." },
      { type: "pattern", text: "FORCE + KİŞİ + TO + V1 = zorlamak" },
      { type: "example", en: "They forced him to sign the contract.", tr: "Onu sözleşmeyi imzalamaya zorladılar." },
      { type: "pattern", text: "PERSUADE + KİŞİ + TO + V1 = ikna etmek" },
      { type: "example", en: "I finally persuaded her to come with us.", tr: "Sonunda onu bizimle gelmeye ikna ettim." },
      { type: "pattern", text: "ORDER + KİŞİ + TO + V1 = emretmek" },
      { type: "example", en: "The captain ordered the soldiers to stop.", tr: "Yüzbaşı askerlere durmalarını emretti." },
      { type: "pattern", text: "REMIND + KİŞİ + TO + V1 = hatırlatmak" },
      { type: "example", en: "Can you remind me to call the bank tomorrow?", tr: "Yarın bankayı aramamı hatırlatabilir misin?" },
      { type: "pattern", text: "WARN + KİŞİ + (NOT) TO + V1 = uyarmak" },
      { type: "example", en: "I warned him not to be late again.", tr: "Ona bir daha geç kalmaması için uyarıda bulundum." },
      { type: "pattern", text: "INVITE + KİŞİ + TO + V1 = davet etmek" },
      { type: "example", en: "They invited us to join their wedding.", tr: "Bizi düğünlerine katılmaya davet ettiler." },
      { type: "rule", text: "Bu kalıpların olumsuzu için TO'dan hemen önce NOT getirilir: FİİL + KİŞİ + NOT TO + V1." },
      { type: "example", en: "She asked me not to tell anyone.", tr: "Kimseye söylememi istemedi." },
      { type: "example", en: "The teacher warned the students not to cheat.", tr: "Öğretmen öğrencileri kopya çekmemeleri konusunda uyardı." },
      { type: "rule", text: "MAKE ve LET fiillerinden sonra ise TO kullanılmaz, fiil yalın (bare infinitive) haldedir; bu, en sık yapılan hatalardan biridir." },
      { type: "pattern", text: "MAKE + KİŞİ + V1 (TO'suz) = birine bir şey yaptırmak, zorlamak" },
      { type: "example", en: "My boss made me stay late.", tr: "Patronum beni geç saate kadar kalmaya zorladı." },
      { type: "pattern", text: "LET + KİŞİ + V1 (TO'suz) = birine izin vermek, bırakmak" },
      { type: "example", en: "My parents let me go to the concert.", tr: "Ailem konsere gitmeme izin verdi." },
      { type: "example", en: "They made him to wait. (YANLIŞ) — They made him wait. (DOĞRU)", tr: "Yanlış: MAKE'ten sonra TO kullanılmaz. Doğrusu TO'suz kullanılmalıdır." },
      { type: "rule", text: "HELP fiilinden sonra ise hem TO'lu hem TO'suz kullanım kabul edilir, ikisi de doğrudur." },
      { type: "example", en: "Can you help me carry this box? / Can you help me to carry this box?", tr: "Bu kutuyu taşımama yardım edebilir misin?" },
      { type: "pattern", text: "EXPECT = beklemek / EXPECTATION = beklenti" },
      { type: "example", en: "Don't expect me to believe you.", tr: "Sana inanmamı bekleme." },
      { type: "example", en: "I don't expect you to understand.", tr: "Anlamanı beklemiyorum." },
      { type: "pattern", text: "SATISFY = karşılamak, tatmin etmek" },
      { type: "example", en: "This hotel can't satisfy your expectations.", tr: "Bu otel beklentilerini karşılayamaz." },
      { type: "pattern", text: "ACCOMPANY = eşlik etmek" },
      { type: "example", en: "Could you accompany me to the hotel?", tr: "Otele kadar bana eşlik edebilir misin?" },
      { type: "pattern", text: "DEPARTURE = kalkış / ARRIVAL = varış / FLOOR = LEVEL = kat" },
      { type: "example", en: "Where is the arrivals floor?", tr: "Varış katı nerede?" },
      { type: "example", en: "He is waiting for us at the departures level.", tr: "O bizi kalkış katında bekliyor." },
      { type: "pattern", text: "ESTIMATE = tahmin etmek / AMOUNT = miktar / QUANTITY = miktar, nicelik" },
      { type: "example", en: "Do you have any idea about the estimated arrival time?", tr: "Tahmini varış zamanı hakkında bir fikrin var mı?" },
      { type: "example", en: "What is the amount of butter we need?", tr: "İhtiyacımız olan tereyağı miktarı ne kadar?" },
      { type: "pattern", text: "GET RID OF = kurtulmak / NONSENSE = saçmalık / ILLNESS, DISEASE, TROUBLE = hastalık, sıkıntı" },
      { type: "rule", text: "IN ANY WAY / IN NO WAY = bir türlü." },
      { type: "example", en: "He cannot get rid of that disease in any way.", tr: "O bir türlü o hastalıktan kurtulamıyor." },
      { type: "pattern", text: "FINALLY / AT LAST = sonunda" },
      { type: "example", en: "Finally, I got rid of the nonsense.", tr: "Sonunda o saçmalıktan kurtuldum." },
      { type: "example", en: "At last, they reached the hotel.", tr: "Sonunda otele vardılar." },
      { type: "rule", text: "Bu dersteki bütün \"fiil + kişi + TO + V1\" kalıplarını pekiştiren karma bir tekrar bölümü görelim." },
      { type: "example", en: "My father wants me to study medicine, but I want to study law.", tr: "Babam tıp okumamı istiyor ama ben hukuk okumak istiyorum." },
      { type: "example", en: "The manager asked the staff to arrive fifteen minutes early.", tr: "Müdür personelden on beş dakika erken gelmelerini rica etti." },
      { type: "example", en: "I encouraged him to apply for the job.", tr: "Ona işe başvurması için cesaret verdim." },
      { type: "example", en: "They didn't allow us to take photographs inside the museum.", tr: "Müzenin içinde fotoğraf çekmemize izin vermediler." },
      { type: "example", en: "He advised me not to sign the contract without reading it.", tr: "Bana sözleşmeyi okumadan imzalamamamı tavsiye etti." },
      { type: "rule", text: "Son olarak bu kalıpların günlük hayatta nasıl bir araya geldiğini gösteren birkaç mini diyalog görelim." },
      { type: "example", en: "Why did your boss want you to stay late? — He wanted me to finish the report before the deadline.", tr: "Patronun neden geç saate kadar kalmanı istedi? — Son teslim tarihinden önce raporu bitirmemi istedi." },
      { type: "example", en: "Did the doctor advise you to rest? — Yes, she advised me to rest and drink plenty of water.", tr: "Doktor dinlenmeni tavsiye etti mi? — Evet, dinlenmemi ve bol su içmemi tavsiye etti." },
      { type: "example", en: "Did your parents let you go to the party? — No, they didn't let me go, so I asked them to reconsider.", tr: "Ailen partiye gitmene izin verdi mi? — Hayır, izin vermediler, o yüzden yeniden düşünmelerini rica ettim." },
      { type: "rule", text: "RECOMMEND + KİŞİ + TO + V1 kalıbı da tavsiye etmek anlamında kullanılır; RECOMMEND aynı zamanda THAT bağlacıyla da kullanılabilir." },
      { type: "example", en: "My doctor recommended me to see a specialist.", tr: "Doktorum bir uzmana görünmemi tavsiye etti." },
      { type: "pattern", text: "REQUIRE + KİŞİ + TO + V1 = birinden bir şey yapmasını istemek, gerektirmek" },
      { type: "example", en: "The job requires you to travel frequently.", tr: "İş, sık sık seyahat etmeni gerektiriyor." },
      { type: "rule", text: "CAUSE + KİŞİ/ŞEY + TO + V1 kalıbı, bir şeyin başka bir şeye sebep olduğunu anlatır." },
      { type: "example", en: "The heavy rain caused the flight to be delayed.", tr: "Şiddetli yağmur uçuşun gecikmesine sebep oldu." },
      { type: "rule", text: "Bu dersteki fiillerin çoğu iş hayatında, ebeveyn-çocuk ilişkilerinde ve günlük ricalarda sıkça karşımıza çıkar; bu yüzden pratik yapmak önemlidir." },
      { type: "example", en: "The company requires all employees to attend the training.", tr: "Şirket tüm çalışanların eğitime katılmasını gerektiriyor." },
      { type: "example", en: "I recommended him to apply early, before the deadline.", tr: "Ona son tarihten önce erken başvurmasını tavsiye ettim." },
      { type: "example", en: "The loud noise caused the baby to wake up.", tr: "Yüksek ses bebeğin uyanmasına sebep oldu." },
      { type: "example", en: "We persuaded our parents to let us go on the trip.", tr: "Ailemizi geziye gitmemize izin vermeleri için ikna ettik." },
    ],
  },
  {
    fileBase: "18_Present_Perfect_Continuous",
    title: "YAKIN GEÇMİŞİN ŞİMDİKİ HALİ (PRESENT PERFECT CONTINUOUS)",
    blocks: [
      { type: "rule", text: "Bu tense; geçmişte başlayıp hâlâ devam eden bir eylemin sürekliliğini vurgulamak için kullanılır. \"Ne zamandır yapıyorsun\" sorusunun cevabıdır." },
      { type: "rule", text: "Yapı: Özne + HAVE/HAS BEEN + Fiil-ING." },
      { type: "pattern", text: "I / YOU / WE / THEY + HAVE BEEN + V-ing        HE / SHE / IT + HAS BEEN + V-ing" },
      { type: "example", en: "I have been working here for five years.", tr: "Beş yıldır burada çalışıyorum." },
      { type: "example", en: "She has been waiting for you since morning.", tr: "O sabahtan beri seni bekliyor." },
      { type: "example", en: "They have been playing football for two hours.", tr: "İki saattir futbol oynuyorlar." },
      { type: "rule", text: "Olumsuz yapı: Özne + HAVEN'T/HASN'T BEEN + Fiil-ING." },
      { type: "example", en: "They haven't been listening to the teacher.", tr: "Onlar öğretmeni dinlemiyorlardı (ve hâlâ dinlemiyorlar)." },
      { type: "example", en: "He hasn't been feeling well recently.", tr: "O son zamanlarda kendini iyi hissetmiyor." },
      { type: "rule", text: "Soru yapısı: HAVE/HAS + Özne + BEEN + Fiil-ING?" },
      { type: "example", en: "How long have you been studying English?", tr: "Ne zamandır İngilizce çalışıyorsun?" },
      { type: "example", en: "Has she been crying?", tr: "O ağlıyor muydu?" },
      { type: "rule", text: "Present Perfect Continuous, FOR (süre boyunca) ve SINCE (bir andan beri) ile birlikte sıkça kullanılır ve eylemin hâlâ devam ettiğini vurgular." },
      { type: "example", en: "We have been living in this city for ten years.", tr: "On yıldır bu şehirde yaşıyoruz." },
      { type: "example", en: "He has been driving since 6 am.", tr: "Sabah 6'dan beri araba kullanıyor." },
      { type: "rule", text: "Present Perfect (HAVE + V3) genellikle SONUCU, Present Perfect Continuous (HAVE BEEN + V-ing) ise SÜRECİ/SÜREKLİLİĞİ vurgular." },
      { type: "example", en: "I have painted the wall. (bitmiş, sonuç önemli) / I have been painting the wall. (süreç, ne kadar süredir yaptığı önemli)", tr: "Duvarı boyadım. / Duvarı boyuyorum (bir süredir)." },
      { type: "rule", text: "Bu yapı özellikle yorgunluk, kızgınlık gibi durumların sebebini açıklarken de kullanılır." },
      { type: "example", en: "I'm tired because I have been working all day.", tr: "Yorgunum çünkü bütün gün çalışıyordum." },
      { type: "example", en: "Her eyes are red because she has been crying.", tr: "Gözleri kırmızı çünkü ağlıyordu." },
      { type: "rule", text: "-ING eki eklenirken bazı yazım kuralları uygulanır: sessiz E ile biten fiillerde E harfi düşer (WRITE-WRITING, MAKE-MAKING); tek heceli, ünlü+ünsüzle biten fiillerde son ünsüz ikiye katlanır (RUN-RUNNING, SIT-SITTING, GET-GETTING)." },
      { type: "example", en: "I have been writing this essay since lunchtime.", tr: "Öğle yemeğinden beri bu denemeyi yazıyorum." },
      { type: "example", en: "He has been sitting there for hours.", tr: "O saatlerdir orada oturuyor." },
      { type: "rule", text: "KNOW, BELIEVE, LIKE, LOVE, HATE, WANT, NEED, UNDERSTAND, BELONG, OWN gibi durum (stative) fiilleri normalde -ING almaz; bu yüzden bu fiillerle Present Perfect Continuous değil, Present Perfect Simple kullanılır." },
      { type: "example", en: "I have known her for ten years. (DOĞRU) — NOT: I have been knowing her for ten years. (YANLIŞ)", tr: "Onu on yıldır tanıyorum." },
      { type: "example", en: "We have wanted this house for a long time.", tr: "Bu evi uzun süredir istiyoruz." },
      { type: "rule", text: "ALL DAY, ALL WEEK, ALL MONTH, ALL MY LIFE gibi süre ifadeleri de Present Perfect Continuous ile sıkça kullanılır." },
      { type: "example", en: "It has been raining all day.", tr: "Bütün gün yağmur yağıyor." },
      { type: "example", en: "I have been studying all week for this exam.", tr: "Bu sınav için bütün hafta ders çalışıyorum." },
      { type: "example", en: "She has been living abroad all her life.", tr: "O hayatı boyunca yurt dışında yaşıyor." },
      { type: "rule", text: "RECENTLY ve LATELY (son zamanlarda) zarfları da bu tense ile sıkça kullanılır." },
      { type: "example", en: "What have you been doing lately?", tr: "Son zamanlarda ne yapıyordun?" },
      { type: "example", en: "I have been thinking about changing my job recently.", tr: "Son zamanlarda işimi değiştirmeyi düşünüyorum." },
      { type: "rule", text: "Present Perfect Continuous, JUST, ALREADY, YET gibi Present Perfect Simple ile kullanılan zarflarla birlikte kullanılmaz; bu zarflar tamamlanmış bir eylemi vurgular." },
      { type: "example", en: "I have just finished my homework. (Present Perfect Simple, doğru)", tr: "Ödevimi az önce bitirdim." },
      { type: "rule", text: "Bu tense'in soru kalıbında HOW LONG dışında WHAT ve WHY soru kelimeleri de sıkça kullanılır." },
      { type: "example", en: "What have you been doing all morning?", tr: "Bütün sabah ne yapıyordun?" },
      { type: "example", en: "Why have you been avoiding me?", tr: "Neden benden kaçıyorsun?" },
      { type: "rule", text: "Olumsuz sorusu: HAVEN'T/HASN'T + Özne + BEEN + Fiil-ING?" },
      { type: "example", en: "Haven't you been sleeping well?", tr: "İyi uyumuyor musun?" },
      { type: "example", en: "Hasn't he been working on this project?", tr: "O bu proje üzerinde çalışmıyor mu?" },
      { type: "rule", text: "LIVE, WORK, STUDY gibi bazı fiillerde hem Present Perfect Simple hem Present Perfect Continuous kullanılabilir, anlam farkı çok küçüktür." },
      { type: "example", en: "I have lived here for ten years. / I have been living here for ten years.", tr: "On yıldır burada yaşıyorum." },
      { type: "rule", text: "Farklı bir fiille tam çekim örneği görelim: LEARN (öğrenmek) fiili." },
      { type: "pattern", text: "TAM ÇEKİM: LEARN (ÖĞRENMEK) — PRESENT PERFECT CONTINUOUS" },
      { type: "example", en: "I have been learning Spanish for six months.", tr: "Altı aydır İspanyolca öğreniyorum." },
      { type: "example", en: "You have been learning Spanish for six months.", tr: "Sen altı aydır İspanyolca öğreniyorsun." },
      { type: "example", en: "He has been learning Spanish for six months.", tr: "O altı aydır İspanyolca öğreniyor." },
      { type: "example", en: "We have been learning Spanish for six months.", tr: "Biz altı aydır İspanyolca öğreniyoruz." },
      { type: "example", en: "They have been learning Spanish for six months.", tr: "Onlar altı aydır İspanyolca öğreniyor." },
      { type: "rule", text: "Aynı fiilin olumsuz çekimini görelim." },
      { type: "example", en: "I haven't been learning much lately.", tr: "Son zamanlarda pek bir şey öğrenmiyorum." },
      { type: "example", en: "She hasn't been learning the new software properly.", tr: "O yeni yazılımı düzgün öğrenmiyor." },
      { type: "rule", text: "Present Perfect Continuous, spor, iş ve eğitim gibi süregelen aktiviteleri anlatırken çok sık kullanılır." },
      { type: "example", en: "He has been training for the marathon for three months.", tr: "O üç aydır maraton için antrenman yapıyor." },
      { type: "example", en: "We have been renovating our house since spring.", tr: "İlkbahardan beri evimizi yeniliyoruz." },
      { type: "example", en: "She has been working on her thesis for almost a year.", tr: "O neredeyse bir yıldır tezi üzerinde çalışıyor." },
      { type: "rule", text: "Bu tense ayrıca bir eylemin fiziksel kanıtlarını (yorgunluk, terleme, dağınıklık vb.) açıklarken de sıkça kullanılır." },
      { type: "example", en: "You're all sweaty — have you been exercising?", tr: "Terlemişsin — spor mu yapıyordun?" },
      { type: "example", en: "The kitchen is a mess; have you been cooking?", tr: "Mutfak dağınık; yemek mi pişiriyordun?" },
      { type: "rule", text: "Present Perfect Continuous'un olumsuz hâli genellikle bir eylemin uzun süredir gerçekleşmediğini vurgular." },
      { type: "example", en: "I haven't been sleeping well this week.", tr: "Bu hafta iyi uyuyamıyorum." },
      { type: "example", en: "They haven't been talking to each other since the argument.", tr: "Tartışmadan beri birbirleriyle konuşmuyorlar." },
      { type: "rule", text: "Sık yapılan bir hata, FOR ve SINCE'i birbirine karıştırmaktır: FOR bir süre miktarını (for two hours), SINCE ise bir başlangıç noktasını (since Monday) belirtir." },
      { type: "example", en: "I have been waiting for two hours.", tr: "İki saattir bekliyorum." },
      { type: "example", en: "I have been waiting since two o'clock.", tr: "Saat ikiden beri bekliyorum." },
      { type: "rule", text: "Present Perfect Continuous ile Present Continuous arasındaki farkı da netleştirelim: Present Continuous şu anda olan bir eylemi, Present Perfect Continuous ise geçmişten beri süregelen bir eylemi anlatır." },
      { type: "example", en: "I am working now. / I have been working since 9 am.", tr: "Şu anda çalışıyorum. / Sabah 9'dan beri çalışıyorum." },
      { type: "rule", text: "Bu tense, bir alışkanlığın yakın geçmişte tekrar edildiğini anlatırken de kullanılabilir (kesin bir süre belirtmeden)." },
      { type: "example", en: "I have been going to the gym a lot lately.", tr: "Son zamanlarda sık sık spor salonuna gidiyorum." },
      { type: "example", en: "He has been smoking again, even though he promised to quit.", tr: "Bırakacağına söz vermesine rağmen yine sigara içiyor." },
      { type: "rule", text: "Present Perfect Continuous'ta kısa cevap yoktur; HAVE/HAS ile tam bir cevap verilir." },
      { type: "example", en: "Have you been waiting long? Yes, I have been waiting for almost an hour.", tr: "Uzun zamandır mı bekliyorsun? Evet, neredeyse bir saattir bekliyorum." },
      { type: "rule", text: "Son olarak bu dersteki bütün kalıpları içeren karma bir tekrar bölümü görelim." },
      { type: "example", en: "How long have you been working on this project? — I have been working on it since January.", tr: "Bu proje üzerinde ne kadar süredir çalışıyorsun? — Ocak'tan beri çalışıyorum." },
      { type: "example", en: "Have you been feeling okay lately? — Not really, I have been feeling a bit tired.", tr: "Son zamanlarda iyi hissediyor musun? — Pek değil, biraz yorgun hissediyorum." },
      { type: "example", en: "Why is your hair wet? — I have been swimming.", tr: "Saçın neden ıslak? — Yüzüyordum." },
      { type: "example", en: "She has been waiting for the bus for twenty minutes.", tr: "O yirmi dakikadır otobüsü bekliyor." },
      { type: "example", en: "We have been discussing this issue for hours, but we still haven't decided anything.", tr: "Bu konuyu saatlerdir tartışıyoruz ama hâlâ bir karara varamadık." },
      { type: "example", en: "My eyes hurt because I have been staring at the screen all day.", tr: "Gözlerim ağrıyor çünkü bütün gün ekrana bakıyorum." },
      { type: "example", en: "The children have been playing outside since lunch.", tr: "Çocuklar öğle yemeğinden beri dışarıda oynuyor." },
      { type: "example", en: "I have been meaning to call you for days.", tr: "Günlerdir seni aramayı düşünüyordum." },
    ],
  },
  {
    fileBase: "19_Miktar_Belirtecleri",
    title: "MİKTAR BELİRTEÇLERİ VE FARKLI KALIPLAR",
    blocks: [
      { type: "rule", text: "Miktar belirteçleri OF ile birlikte kullanılır: ALL OF (hepsi), MOST OF (çoğu), REST OF (geri kalanı), SOME OF (bazısı), FEW OF (birkaçı), ANY/NONE OF (hiçbiri)." },
      { type: "example", en: "We want to see all of them.", tr: "Onların hepsini görmek istiyoruz." },
      { type: "example", en: "None of them are ready for the meeting.", tr: "Onların hiçbiri toplantıya hazır değil." },
      { type: "example", en: "Most of us wanted to stay home.", tr: "Çoğumuz evde kalmak istedi." },
      { type: "rule", text: "Sayılabilir (countable) isimler tek tek sayılabilen isimlerdir (a book, two books); sayılamaz (uncountable) isimler ise sayılamaz ve genelde çoğul yapılmaz (water, money, information, advice, furniture)." },
      { type: "example", en: "I have three books on my desk.", tr: "Masamda üç kitap var." },
      { type: "example", en: "I need some information about this course.", tr: "Bu kurs hakkında biraz bilgiye ihtiyacım var." },
      { type: "rule", text: "MANY sayılabilir isimlerle, MUCH sayılamaz isimlerle kullanılır; ikisi de genellikle olumsuz ve soru cümlelerinde tercih edilir." },
      { type: "pattern", text: "MANY + sayılabilir çoğul isim        MUCH + sayılamaz isim" },
      { type: "example", en: "There aren't many students in the classroom today.", tr: "Bugün sınıfta çok fazla öğrenci yok." },
      { type: "example", en: "We don't have much time left.", tr: "Fazla zamanımız kalmadı." },
      { type: "example", en: "How many books did you read this year?", tr: "Bu yıl kaç kitap okudun?" },
      { type: "example", en: "How much money do you need?", tr: "Ne kadar paraya ihtiyacın var?" },
      { type: "rule", text: "A LOT OF ve LOTS OF hem sayılabilir hem sayılamaz isimlerle kullanılabilir ve özellikle olumlu cümlelerde MANY/MUCH'a tercih edilir." },
      { type: "example", en: "She has a lot of friends in this city.", tr: "Onun bu şehirde çok arkadaşı var." },
      { type: "example", en: "We have lots of work to do today.", tr: "Bugün yapacak çok işimiz var." },
      { type: "rule", text: "(A) FEW sayılabilir isimlerle, (A) LITTLE sayılamaz isimlerle kullanılır. A FEW/A LITTLE olumlu \"birkaç/biraz\" anlamı taşırken, FEW/LITTLE (A'sız) olumsuz bir azlığı vurgular." },
      { type: "pattern", text: "A FEW = birkaç (yeterli)   FEW = çok az (yetersiz)   A LITTLE = biraz (yeterli)   LITTLE = çok az (yetersiz)" },
      { type: "example", en: "I have a few friends here, so I'm not lonely.", tr: "Burada birkaç arkadaşım var, o yüzden yalnız değilim." },
      { type: "example", en: "I have few friends here, so I feel lonely.", tr: "Burada çok az arkadaşım var, o yüzden yalnız hissediyorum." },
      { type: "example", en: "There is a little sugar left in the jar.", tr: "Kavanozda biraz şeker kaldı." },
      { type: "example", en: "There is little hope of finding survivors.", tr: "Hayatta kalanları bulma umudu çok az." },
      { type: "rule", text: "SEVERAL, \"birkaç\" anlamında sadece sayılabilir isimlerle kullanılır ve genellikle A FEW'den biraz daha fazla bir sayıyı ifade eder." },
      { type: "example", en: "I've called him several times today.", tr: "Bugün onu birkaç kez aradım." },
      { type: "rule", text: "ENOUGH (yeterli), isimden önce, ama sıfat veya zarftan sonra gelir." },
      { type: "pattern", text: "ENOUGH + isim        sıfat/zarf + ENOUGH" },
      { type: "example", en: "We don't have enough chairs for everyone.", tr: "Herkes için yeterli sandalyemiz yok." },
      { type: "example", en: "Is this box big enough for all these books?", tr: "Bu kutu bütün bu kitaplar için yeterince büyük mü?" },
      { type: "example", en: "He isn't old enough to drive.", tr: "O araba kullanmak için yeterince büyük değil." },
      { type: "rule", text: "TOO MUCH / TOO MANY, \"gereğinden fazla\" anlamında olumsuz bir aşırılığı belirtir." },
      { type: "pattern", text: "TOO MANY + sayılabilir isim        TOO MUCH + sayılamaz isim" },
      { type: "example", en: "There are too many people in this room.", tr: "Bu odada gereğinden fazla insan var." },
      { type: "example", en: "You put too much salt in the soup.", tr: "Çorbaya gereğinden fazla tuz koydun." },
      { type: "rule", text: "PLENTY OF, \"bol miktarda, fazlasıyla yeterli\" anlamına gelir ve hem sayılabilir hem sayılamaz isimlerle kullanılır." },
      { type: "example", en: "Don't worry, we have plenty of time.", tr: "Merak etme, bol vaktimiz var." },
      { type: "example", en: "There is plenty of food for everyone.", tr: "Herkes için bol miktarda yemek var." },
      { type: "rule", text: "A NUMBER OF (birçok, birkaç) sayılabilir isimlerle kullanılır ve çoğul fiil alır; THE NUMBER OF ise \"sayısı\" anlamına gelir ve tekil fiil alır." },
      { type: "pattern", text: "A NUMBER OF + çoğul isim + çoğul fiil        THE NUMBER OF + çoğul isim + tekil fiil" },
      { type: "example", en: "A number of students have complained about the exam.", tr: "Birçok öğrenci sınavdan şikayet etti." },
      { type: "example", en: "The number of students in this class is increasing.", tr: "Bu sınıftaki öğrenci sayısı artıyor." },
      { type: "rule", text: "THE MAJORITY OF, \"çoğunluğu\" anlamına gelir ve genellikle çoğul bir isimle birlikte kullanılır." },
      { type: "example", en: "The majority of people agreed with the decision.", tr: "İnsanların çoğunluğu karara katıldı." },
      { type: "pattern", text: "APPLY = uygulamak / APPLICATION = uygulama, başvuru / APPLY FOR = başvurmak" },
      { type: "example", en: "When will you apply for the visa?", tr: "Vize için ne zaman başvuracaksın?" },
      { type: "example", en: "Did you receive the application form?", tr: "Başvuru formunu aldın mı?" },
      { type: "pattern", text: "EXPRESS = ifade etmek / CLEARLY = açıkça" },
      { type: "example", en: "You must clearly express yourself.", tr: "Kendini açıkça ifade etmelisin." },
      { type: "rule", text: "DIFFICULT = zor, DIFFICULTY = zorluk, HAVE DIFFICULTY + IN = zorlanmak. FOR/WITH/WITHOUT/BY/IN/AT/ON edatlarından sonra gelen fiiller -ING alır." },
      { type: "example", en: "He had difficulty in expressing himself.", tr: "O kendini ifade etmekte zorlandı." },
      { type: "example", en: "Do they have difficulty in getting up early?", tr: "Onlar erken kalkmakta zorlanıyor mu?" },
      { type: "pattern", text: "HURT = incitmek / FEELING = his, duygu / EMOTION = duygu" },
      { type: "example", en: "You hurt her feelings by doing like this.", tr: "Böyle yaparak onun duygularını incittin." },
      { type: "pattern", text: "SUGGEST = önermek / SUGGESTION = öneri / PRECIOUS = kıymetli, değerli" },
      { type: "example", en: "Your suggestion is very precious for me.", tr: "Önerin benim için çok değerli." },
      { type: "example", en: "What do you suggest?", tr: "Ne öneriyorsun?" },
      { type: "pattern", text: "KEEP = tutmak, sürdürmek / PROMISE = söz / KEEP PROMISE = sözünü tutmak" },
      { type: "example", en: "You should always keep your promise.", tr: "Her zaman sözünü tutmalısın." },
      { type: "example", en: "He always keeps his promise.", tr: "O her zaman sözünü tutar." },
      { type: "pattern", text: "CORRECT = doğru, düzeltmek / DATA = veri / FAULT = hata, kusur" },
      { type: "example", en: "Who will correct this fault?", tr: "Bu hatayı kim düzeltecek?" },
      { type: "pattern", text: "SOLVE = çözmek / OWN = kendi / ON MY OWN = kendi kendime / HANDLE = halletmek" },
      { type: "example", en: "I can solve this problem on my own.", tr: "Bu problemi kendi kendime çözebilirim." },
      { type: "example", en: "He can handle it on his own.", tr: "O bunu kendi başına halledebilir." },
      { type: "pattern", text: "JEALOUS = kıskanç / BE JEALOUS OF = kıskanmak" },
      { type: "example", en: "I think they aren't jealous of us.", tr: "Sanırım onlar bizi kıskanmıyor." },
      { type: "example", en: "Are you jealous of her?", tr: "Onu kıskanıyor musun?" },
      { type: "pattern", text: "LOOK AFTER = birine bakmak, göz kulak olmak / WHILE = -iken / GO OUT = dışarı çıkmak" },
      { type: "example", en: "Can you look after the kid while I'm out?", tr: "Ben dışarıdayken çocuğa bakabilir misin?" },
      { type: "example", en: "He can't go out today, because he has to look after his grandfather.", tr: "O bugün dışarı çıkamaz çünkü büyükbabasına bakması gerekiyor." },
      { type: "pattern", text: "STRUGGLE = çabalamak / MAKE AN EFFORT = çaba sarfetmek" },
      { type: "example", en: "You should struggle much more.", tr: "Çok daha fazla çabalamalısın." },
      { type: "example", en: "I need to make more effort.", tr: "Daha fazla çaba sarfetmeliyim." },
      { type: "rule", text: "Son olarak bu dersteki miktar belirteçlerini pekiştiren karma bir tekrar bölümü görelim." },
      { type: "example", en: "How much water do we need for the trip? — We need a few bottles, that should be enough.", tr: "Yolculuk için ne kadar suya ihtiyacımız var? — Birkaç şişe yeterli olur." },
      { type: "example", en: "There isn't much time left, so a few of you should hurry.", tr: "Fazla zaman kalmadı, o yüzden bazılarınız acele etmeli." },
      { type: "example", en: "Most of the guests have already left, but a few of them are still here.", tr: "Misafirlerin çoğu çoktan gitti ama birkaçı hâlâ burada." },
      { type: "example", en: "We don't have enough chairs, and too many people are coming to the party.", tr: "Yeterli sandalyemiz yok ve partiye gereğinden fazla insan geliyor." },
      { type: "example", en: "A number of guests haven't arrived yet, but the majority of them are already here.", tr: "Bazı misafirler henüz gelmedi ama çoğunluğu şimdiden burada." },
      { type: "rule", text: "BOTH, EITHER, NEITHER kalıpları da miktar/seçenek belirtirken kullanılır: BOTH (ikisi de), EITHER (ikisinden biri), NEITHER (ikisi de değil)." },
      { type: "pattern", text: "BOTH OF + çoğul isim        EITHER OF / NEITHER OF + tekil isim" },
      { type: "example", en: "Both of my sisters live abroad.", tr: "İki kız kardeşim de yurt dışında yaşıyor." },
      { type: "example", en: "You can choose either of the two options.", tr: "İki seçenekten birini seçebilirsin." },
      { type: "example", en: "Neither of us wanted to leave early.", tr: "İkimiz de erken ayrılmak istemedik." },
      { type: "rule", text: "ALL, EACH ve EVERY arasındaki fark: ALL bir grubun bütününü, EACH grubun her bir üyesini ayrı ayrı, EVERY ise genel bir kuralı vurgular." },
      { type: "example", en: "All the students passed the exam.", tr: "Öğrencilerin hepsi sınavı geçti." },
      { type: "example", en: "Each student received a certificate.", tr: "Her bir öğrenci bir sertifika aldı." },
      { type: "example", en: "Every student must bring their own book.", tr: "Her öğrenci kendi kitabını getirmelidir." },
    ],
  },
  {
    fileBase: "20_That_ve_Soru_Baglaclari",
    title: "THAT VE SORU KELİMESİ BAĞLAÇLARI",
    blocks: [
      { type: "rule", text: "THAT bağlacı \"-ki, -dığını, -diğini\" anlamlarında iki cümleyi birbirine bağlar." },
      { type: "pattern", text: "ÖZNE + FİİL + THAT + CÜMLE" },
      { type: "example", en: "I am sure that he isn't at home.", tr: "Onun evde olmadığına eminim." },
      { type: "example", en: "We know that they aren't determined enough.", tr: "Yeterince kararlı olmadıklarını biliyoruz." },
      { type: "example", en: "She said that she was tired.", tr: "O yorgun olduğunu söyledi." },
      { type: "pattern", text: "ADMIT = itiraf etmek" },
      { type: "example", en: "I'm sure that he'll admit the truth.", tr: "Gerçeği itiraf edeceğine eminim." },
      { type: "rule", text: "THINK, BELIEVE, HOPE, SUPPOSE gibi düşünce/inanç bildiren fiillerden sonra da THAT bağlacı kullanılır." },
      { type: "example", en: "I think that this plan will work.", tr: "Bu planın işe yarayacağını düşünüyorum." },
      { type: "example", en: "We believe that he is telling the truth.", tr: "Onun doğruyu söylediğine inanıyoruz." },
      { type: "example", en: "I hope that everything goes well.", tr: "Umarım her şey yolunda gider." },
      { type: "rule", text: "Günlük konuşma dilinde THAT genellikle düşürülebilir, özellikle THINK, SAY, KNOW, BELIEVE gibi fiillerden sonra; anlam değişmez." },
      { type: "example", en: "I think (that) you're right.", tr: "Sanırım haklısın." },
      { type: "example", en: "She said (that) she would call later.", tr: "Daha sonra arayacağını söyledi." },
      { type: "rule", text: "DISCOVER, REALIZE, NOTICE, EXPLAIN, PROMISE gibi fiiller de THAT ile sıkça kullanılır." },
      { type: "example", en: "We discovered that the door was open.", tr: "Kapının açık olduğunu fark ettik." },
      { type: "example", en: "I didn't realize that it was so late.", tr: "Bu kadar geç olduğunu fark etmemiştim." },
      { type: "example", en: "He promised that he would help us.", tr: "Bize yardım edeceğine söz verdi." },
      { type: "rule", text: "WHERE / WHEN / WHAT / WHO / WHY soru kelimeleri de THAT gibi bağlaç olarak kullanılabilir; cümle içinde soru sırası değil, düz cümle sırası kullanılır." },
      { type: "example", en: "I don't know where they meet.", tr: "Nerede buluşacaklarını bilmiyorum." },
      { type: "example", en: "I don't know who he is.", tr: "Onun kim olduğunu bilmiyorum." },
      { type: "example", en: "Do you know what she wants?", tr: "Onun ne istediğini biliyor musun?" },
      { type: "pattern", text: "FIGURE OUT = anlamak, çözmek" },
      { type: "example", en: "I couldn't figure out why they started.", tr: "Neden başladıklarını anlayamadım." },
      { type: "pattern", text: "MOVE = taşınmak" },
      { type: "example", en: "We aren't sure when we'll move there.", tr: "Oraya ne zaman taşınacağımızdan emin değiliz." },
      { type: "pattern", text: "IDEA = fikir" },
      { type: "example", en: "I have no idea what they want.", tr: "Ne istediklerine dair hiçbir fikrim yok." },
      { type: "example", en: "Can you tell me where the pharmacy is?", tr: "Bana eczanenin nerede olduğunu söyleyebilir misin?" },
      { type: "example", en: "I don't know where I am.", tr: "Nerede olduğumu bilmiyorum." },
      { type: "rule", text: "Sık yapılan bir hata, bu tür bağlı sorularda (embedded questions) soru cümlesi sırasını kullanmaktır; doğrusu düz cümle sırasıdır (özne + fiil)." },
      { type: "example", en: "I don't know where is he. (YANLIŞ) — I don't know where he is. (DOĞRU)", tr: "Nerede olduğunu bilmiyorum." },
      { type: "example", en: "Can you tell me what does she want? (YANLIŞ) — Can you tell me what she wants? (DOĞRU)", tr: "Onun ne istediğini söyleyebilir misin?" },
      { type: "rule", text: "Evet/hayır cevabı gerektiren sorularda soru kelimesi olmadığı için IF veya WHETHER bağlacı kullanılır." },
      { type: "pattern", text: "ÖZNE + FİİL + IF/WHETHER + DÜZ CÜMLE" },
      { type: "example", en: "I don't know if he is coming.", tr: "Onun gelip gelmeyeceğini bilmiyorum." },
      { type: "example", en: "She asked me whether I was hungry.", tr: "Aç olup olmadığımı sordu." },
      { type: "example", en: "Do you know if the shop is open today?", tr: "Bugün dükkanın açık olup olmadığını biliyor musun?" },
      { type: "rule", text: "WHETHER, OR NOT ile birlikte de kullanılabilir ve iki seçenek arasındaki belirsizliği vurgular; IF bu şekilde kullanılamaz." },
      { type: "pattern", text: "WHETHER...OR NOT = ...olsun ya da olmasın" },
      { type: "example", en: "I don't know whether she will come or not.", tr: "Onun gelip gelmeyeceğini bilmiyorum." },
      { type: "example", en: "We have to leave now, whether you're ready or not.", tr: "Sen hazır olsan da olmasan da şimdi gitmemiz gerekiyor." },
      { type: "rule", text: "WONDER (merak etmek) fiili de genellikle IF/WHETHER veya soru kelimeleriyle birlikte kullanılır." },
      { type: "example", en: "I wonder if she'll like this gift.", tr: "Acaba bu hediyeyi sever mi diye merak ediyorum." },
      { type: "example", en: "He wondered why she left so early.", tr: "O neden bu kadar erken ayrıldığını merak etti." },
      { type: "rule", text: "Soru kelimesi + TO + V1 kalıbı, \"ne yapacağını, nereye gideceğini\" gibi anlamlar taşır ve özne tekrarlanmaz." },
      { type: "pattern", text: "SORU KELİMESİ + TO + V1" },
      { type: "example", en: "I don't know what to do.", tr: "Ne yapacağımı bilmiyorum." },
      { type: "example", en: "She didn't know where to go.", tr: "Nereye gideceğini bilmiyordu." },
      { type: "example", en: "Can you tell me how to get to the station?", tr: "İstasyona nasıl gideceğimi söyleyebilir misin?" },
      { type: "example", en: "We couldn't decide which one to choose.", tr: "Hangisini seçeceğimize karar veremedik." },
      { type: "rule", text: "SAY ve TELL arasındaki fark THAT bağlacıyla da görülür: SAY + (THAT) + cümle (kişi nesnesi almadan), TELL + kişi + (THAT) + cümle (mutlaka bir kişi nesne alır)." },
      { type: "example", en: "He said that he was busy.", tr: "O meşgul olduğunu söyledi." },
      { type: "example", en: "He told me that he was busy.", tr: "O bana meşgul olduğunu söyledi." },
      { type: "example", en: "He said me that he was busy. (YANLIŞ) — He told me that he was busy. (DOĞRU)", tr: "Yanlış: SAY kişi nesne almaz, TELL alır." },
      { type: "rule", text: "HEAR, NOTICE, FIND OUT gibi fiiller de THAT bağlacıyla sıkça kullanılır ve bir bilgiyi öğrenme/edinme durumunu anlatır." },
      { type: "example", en: "I heard that they are moving to a new city.", tr: "Yeni bir şehre taşındıklarını duydum." },
      { type: "example", en: "We found out that the flight was cancelled.", tr: "Uçuşun iptal edildiğini öğrendik." },
      { type: "rule", text: "NOT SURE / HAVE NO IDEA gibi kalıplar hem THAT hem soru kelimeleriyle kullanılabilir." },
      { type: "example", en: "I'm not sure that this is the right decision.", tr: "Bunun doğru karar olduğundan emin değilim." },
      { type: "example", en: "I have no idea how this happened.", tr: "Bunun nasıl olduğuna dair hiçbir fikrim yok." },
      { type: "rule", text: "Bu tür bağlı cümleler resmi yazışmalarda, iş ortamında ve günlük konuşmada çok sık karşımıza çıkar." },
      { type: "example", en: "Please let me know if you need anything else.", tr: "Başka bir şeye ihtiyacınız olursa lütfen bana bildirin." },
      { type: "example", en: "I'll let you know when the results arrive.", tr: "Sonuçlar geldiğinde sana haber vereceğim." },
      { type: "pattern", text: "LOOK FORWARD TO = dört gözle beklemek, sabırsızlanmak" },
      { type: "rule", text: "LOOK FORWARD TO'dan sonra gelen fiil -ING alır, çünkü TO burada bir edattır." },
      { type: "example", en: "We look forward to seeing them.", tr: "Onları görmeye sabırsızlanıyoruz." },
      { type: "example", en: "They look forward to starting.", tr: "Başlamaya sabırsızlanıyorlar." },
      { type: "example", en: "I'm looking forward to the vacation.", tr: "Tatile sabırsızlanıyorum." },
      { type: "rule", text: "Son olarak bu dersteki THAT ve soru kelimesi bağlaçlarının bir arada geçtiği daha uzun örnek cümleler görelim." },
      { type: "example", en: "I don't know why he hasn't called yet, but I hope that everything is fine.", tr: "Neden henüz aramadığını bilmiyorum ama umarım her şey yolundadır." },
      { type: "example", en: "She asked me if I knew where the meeting was, but I had no idea.", tr: "Toplantının nerede olduğunu bilip bilmediğimi sordu ama hiçbir fikrim yoktu." },
      { type: "example", en: "Can you tell me whether the train has left or not?", tr: "Trenin gidip gitmediğini söyleyebilir misin?" },
      { type: "example", en: "I'm not sure what to say, but I think that you should apologize.", tr: "Ne diyeceğimden emin değilim ama sanırım özür dilemelisin." },
      { type: "example", en: "Nobody knows why she suddenly decided to quit her job, but everyone believes that she made the right choice.", tr: "Kimse neden aniden işini bırakmaya karar verdiğini bilmiyor ama herkes doğru seçimi yaptığına inanıyor." },
      { type: "example", en: "I wasn't sure whether to tell him the truth, but in the end I decided that honesty was the best option.", tr: "Ona gerçeği söyleyip söylememem konusunda emin değildim ama sonunda dürüstlüğün en iyi seçenek olduğuna karar verdim." },
      { type: "rule", text: "MAKE SURE (THAT) kalıbı, bir şeyin kesinlikle gerçekleşmesini sağlamak anlamında çok sık kullanılır." },
      { type: "example", en: "Make sure that you lock the door before you leave.", tr: "Çıkmadan önce kapıyı kilitlediğinden emin ol." },
      { type: "example", en: "Please make sure everyone has a copy of the report.", tr: "Lütfen herkesin raporun bir kopyasına sahip olduğundan emin ol." },
      { type: "rule", text: "IT IS + sıfat + THAT kalıbı, bir durumu vurgulamak için kullanılır: IT'S CLEAR THAT, IT'S OBVIOUS THAT, IT'S POSSIBLE THAT." },
      { type: "example", en: "It's obvious that she doesn't want to come.", tr: "Onun gelmek istemediği açık." },
      { type: "example", en: "It's possible that the meeting will be postponed.", tr: "Toplantının ertelenmesi mümkün." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
