import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "32_Passive_Voice",
    title: "EDİLGEN ÇATI (PASSIVE VOICE)",
    blocks: [
      { type: "rule", text: "Eylemi gerçekleştirenin belli olmadığı ya da önemli olmadığı cümleler edilgen (passive) çatıyla kurulur." },
      { type: "rule", text: "Yapı: Nesne + BE fiilinin uygun hâli + Fiil (3. hal / V3). Eylemi yapan kişi belirtilmek istenirse \"BY\" edatıyla eklenir." },
      { type: "pattern", text: "NESNE + BE (uygun zaman) + V3 (+ BY + ÖZNE)" },
      { type: "rule", text: "ACCEPT (kabul etmek) fiili üzerinden bütün zamanlardaki edilgen hâlleri inceleyelim." },
      { type: "example", en: "The offer was accepted.", tr: "Teklif kabul edildi." },
      { type: "example", en: "The offer is accepted.", tr: "Teklif kabul edilir." },
      { type: "example", en: "The offer will be accepted.", tr: "Teklif kabul edilecek." },
      { type: "example", en: "The offer can be accepted.", tr: "Teklif kabul edilebilir." },
      { type: "example", en: "The offer should be accepted.", tr: "Teklif kabul edilmeli." },
      { type: "rule", text: "Aynı kural düzensiz fiillerin 3. hâliyle de geçerlidir: SELL-SOLD-SOLD, BUY-BOUGHT-BOUGHT, WRITE-WROTE-WRITTEN, SEND-SENT-SENT, GIVE-GAVE-GIVEN, TAKE-TOOK-TAKEN, FORGIVE-FORGAVE-FORGIVEN, TELL-TOLD-TOLD, FORGET-FORGOT-FORGOTTEN, KEEP-KEPT-KEPT, CHOOSE-CHOSE-CHOSEN." },
      { type: "example", en: "The cars were sold.", tr: "Arabalar satıldı." },
      { type: "example", en: "This house shouldn't be sold now.", tr: "Bu ev şimdi satılmamalı." },
      { type: "example", en: "I think this car can be bought.", tr: "Sanırım bu araba satın alınabilir." },
      { type: "example", en: "Everything will be written by me.", tr: "Her şey benim tarafımdan yazılacak." },
      { type: "example", en: "It was written yesterday morning.", tr: "Dün sabah yazıldı." },
      { type: "example", en: "The payment will be sent in a short time.", tr: "Ödeme kısa süre içinde gönderilecek." },
      { type: "example", en: "The train shouldn't be missed.", tr: "Tren kaçırılmamalı." },
      { type: "example", en: "The bills were paid by him.", tr: "Faturalar onun tarafından ödendi." },
      { type: "example", en: "His debts weren't paid yet.", tr: "Onun borçları henüz ödenmedi." },
      { type: "example", en: "Everything was taken.", tr: "Her şey alındı." },
      { type: "example", en: "I think he will be forgiven.", tr: "Sanırım o affedilecek." },
      { type: "example", en: "Were the truths told?", tr: "Gerçekler söylendi mi?" },
      { type: "example", en: "Nothing was forgotten.", tr: "Hiçbir şey unutulmadı." },
      { type: "example", en: "Were all the promises kept?", tr: "Bütün sözler tutuldu mu?" },
      { type: "example", en: "I was neglected a lot.", tr: "Çok ihmal edildim." },
      { type: "rule", text: "MEETING/EXAM/ORGANIZATION gibi kelimelerle CANCEL (iptal etmek) fiili sık kullanılır." },
      { type: "example", en: "The meeting was cancelled.", tr: "Toplantı iptal edildi." },
      { type: "example", en: "Will the organization be cancelled?", tr: "Organizasyon iptal edilecek mi?" },
      { type: "rule", text: "CHECK (kontrol etmek) ve FIX (tamir etmek) fiilleri de günlük hayatta sık edilgen çatıyla kullanılır." },
      { type: "example", en: "The documents will be checked.", tr: "Belgeler kontrol edilecek." },
      { type: "example", en: "My bike was fixed.", tr: "Bisikletim tamir edildi." },
      { type: "example", en: "Before leaving, everything should be fixed.", tr: "Ayrılmadan önce her şey tamir edilmeli." },
      { type: "rule", text: "Edilgen çatı kurulurken o an gereken fiil hâli önceden öğrenilmemiş olsa bile, öğrenciye 3. hâliyle birlikte verilebilir." },
      { type: "rule", text: "Edilgen çatı sadece basit zamanlarda değil, sürekli (continuous) ve tamamlanmış (perfect) zamanlarda da kurulabilir." },
      { type: "pattern", text: "IS/ARE BEING + V3 (şimdiki zaman)   —   WAS/WERE BEING + V3 (geçmiş zaman)" },
      { type: "example", en: "The house is being painted.", tr: "Ev boyanıyor." },
      { type: "example", en: "The road was being repaired when we passed by.", tr: "Biz oradan geçerken yol tamir ediliyordu." },
      { type: "example", en: "Dinner is being prepared right now.", tr: "Akşam yemeği şu anda hazırlanıyor." },
      { type: "rule", text: "Tamamlanmış (perfect) zamanlarda yapı: Nesne + HAVE/HAS/HAD + BEEN + V3." },
      { type: "pattern", text: "HAVE/HAS BEEN + V3 (yakın geçmiş)   —   HAD BEEN + V3 (geçmişte geçmiş)" },
      { type: "example", en: "The letter has been sent.", tr: "Mektup gönderildi." },
      { type: "example", en: "All the tickets have already been sold.", tr: "Bütün biletler zaten satıldı." },
      { type: "example", en: "The work had been finished before we arrived.", tr: "Biz varmadan önce iş bitirilmişti." },
      { type: "rule", text: "Aktif bir cümleyi edilgene çevirirken izlenecek adımlar: 1) Nesne özne yapılır. 2) Fiil, cümlenin zamanına uygun BE + V3 hâline getirilir. 3) Eski özne BY ile (gerekiyorsa) cümlenin sonuna eklenir." },
      { type: "example", en: "Active: They built this bridge in 1990. / Passive: This bridge was built in 1990.", tr: "Aktif: Bu köprüyü 1990'da inşa ettiler. / Edilgen: Bu köprü 1990'da inşa edildi." },
      { type: "example", en: "Active: Someone stole my bike. / Passive: My bike was stolen.", tr: "Aktif: Birisi bisikletimi çaldı. / Edilgen: Bisikletim çalındı." },
      { type: "rule", text: "Eylemi yapan kişi belli değilse, önemli değilse ya da herkes tarafından biliniyorsa BY ile belirtilmez; bu, edilgen çatının en sık kullanılma sebebidir." },
      { type: "example", en: "English is spoken in many countries.", tr: "İngilizce birçok ülkede konuşulur." },
      { type: "example", en: "This bridge was built in 1990.", tr: "Bu köprü 1990'da inşa edildi." },
      { type: "rule", text: "Modal fiillerle (MUST, MIGHT, COULD, MAY) kurulan edilgen yapı: MODAL + BE + V3." },
      { type: "pattern", text: "MUST BE + V3 = ...edilmelidir   —   MIGHT/MAY BE + V3 = ...edilebilir (olasılık)   —   COULD BE + V3 = ...edilebilir" },
      { type: "example", en: "This problem must be solved immediately.", tr: "Bu sorun hemen çözülmeli." },
      { type: "example", en: "The result might be announced tomorrow.", tr: "Sonuç yarın açıklanabilir." },
      { type: "example", en: "This medicine could be found at any pharmacy.", tr: "Bu ilaç herhangi bir eczanede bulunabilir." },
      { type: "rule", text: "Passive soru cümleleri kurulurken yardımcı fiil (BE, HAVE, modal) başa alınır." },
      { type: "pattern", text: "BE + NESNE + V3 ?" },
      { type: "example", en: "Is this room cleaned every day?", tr: "Bu oda her gün temizleniyor mu?" },
      { type: "example", en: "Was the letter written by him?", tr: "Mektup onun tarafından mı yazıldı?" },
      { type: "example", en: "Has the problem been solved yet?", tr: "Sorun henüz çözüldü mü?" },
      { type: "rule", text: "GET, günlük konuşmada BE yerine edilgen çatı kurmak için de kullanılabilir; özellikle ani, beklenmedik ya da olumsuz durumlarda tercih edilir." },
      { type: "pattern", text: "GET + V3 (informal passive)" },
      { type: "example", en: "He got injured in the accident.", tr: "O kazada yaralandı." },
      { type: "example", en: "My wallet got stolen on the bus.", tr: "Cüzdanım otobüste çalındı." },
      { type: "example", en: "They got married last summer.", tr: "Onlar geçen yaz evlendiler." },
      { type: "rule", text: "Genel bilgi ya da haberler aktarılırken kullanılan \"kişisiz\" (impersonal) edilgen yapı: IT IS SAID/BELIEVED/THOUGHT THAT... veya ÖZNE + IS SAID/BELIEVED TO + fiil." },
      { type: "pattern", text: "IT IS SAID THAT + cümle   =   ÖZNE + IS SAID TO + V1" },
      { type: "example", en: "It is said that he is very rich.", tr: "Onun çok zengin olduğu söyleniyor." },
      { type: "example", en: "He is said to be very rich.", tr: "Onun çok zengin olduğu söyleniyor." },
      { type: "example", en: "It is believed that the company will grow.", tr: "Şirketin büyüyeceğine inanılıyor." },
      { type: "rule", text: "İki nesneli (indirect/direct object) fiillerde (GIVE, SEND, SHOW, OFFER, TELL) edilgen çatı genellikle kişi nesnesi özne yapılarak kurulur." },
      { type: "example", en: "Active: They gave me a present. / Passive: I was given a present.", tr: "Aktif: Bana bir hediye verdiler. / Edilgen: Bana bir hediye verildi." },
      { type: "example", en: "Active: They sent her a letter. / Passive: She was sent a letter.", tr: "Aktif: Ona bir mektup gönderdiler. / Edilgen: Ona bir mektup gönderildi." },
      { type: "rule", text: "Edilgen çatıda sıkça geçen fiiller: MAKE-MADE-MADE, BREAK-BROKE-BROKEN, STEAL-STOLE-STOLEN, DAMAGE-DAMAGED-DAMAGED, INJURE-INJURED-INJURED, DESTROY-DESTROYED-DESTROYED, PRODUCE-PRODUCED-PRODUCED, BUILD-BUILT-BUILT, DESIGN-DESIGNED-DESIGNED, INVENT-INVENTED-INVENTED, DISCOVER-DISCOVERED-DISCOVERED, FOUND-FOUNDED-FOUNDED." },
      { type: "example", en: "This car was made in Germany.", tr: "Bu araba Almanya'da üretildi." },
      { type: "example", en: "The window was broken by the kids.", tr: "Pencere çocuklar tarafından kırıldı." },
      { type: "example", en: "The company was founded in 1998.", tr: "Şirket 1998'de kuruldu." },
      { type: "example", en: "The telephone was invented by Alexander Graham Bell.", tr: "Telefon Alexander Graham Bell tarafından icat edildi." },
      { type: "example", en: "America was discovered by Columbus.", tr: "Amerika Kolomb tarafından keşfedildi." },
      { type: "rule", text: "Sık yapılan hatalar: 1) BE fiilini unutmak (\"The letter written.\" YANLIŞ). 2) Fiili V3 yerine V1/V2 kullanmak (\"was write\" YANLIŞ, doğrusu \"was written\"). 3) Zamanı yanlış BE hâliyle eşleştirmek." },
      { type: "example", en: "The letter was written yesterday. (DOĞRU) — NOT: The letter written yesterday.", tr: "Mektup dün yazıldı. — Yanlış kullanım: BE fiili olmadan \"mektup dün yazılan\" demek." },
      { type: "rule", text: "Bütün zamanlardaki edilgen yapıyı özetleyen bir tablo görelim." },
      { type: "pattern", text: "Geniş zaman: AM/IS/ARE + V3   |   Geçmiş zaman: WAS/WERE + V3   |   Gelecek zaman: WILL BE + V3" },
      { type: "pattern", text: "Sürekli zaman: IS/ARE/WAS/WERE + BEING + V3   |   Yakın geçmiş: HAVE/HAS BEEN + V3   |   Geçmişte geçmiş: HAD BEEN + V3" },
      { type: "rule", text: "Şimdi bu dersteki bütün yapıları pekiştiren kısa bir diyalog görelim." },
      { type: "example", en: "Has the report been finished yet? — Not yet, it is still being checked by the manager.", tr: "Rapor henüz bitirildi mi? — Henüz değil, hâlâ müdür tarafından kontrol ediliyor." },
      { type: "example", en: "When was this building built? — It was built in 1985 and it has been renovated twice since then.", tr: "Bu bina ne zaman inşa edildi? — 1985'te inşa edildi ve o zamandan beri iki kez yenilendi." },
      { type: "rule", text: "Karma alıştırma cümleleriyle bu dersi tamamlayalım." },
      { type: "example", en: "This song was written by a famous singer.", tr: "Bu şarkı ünlü bir şarkıcı tarafından yazıldı." },
      { type: "example", en: "All the seats have been reserved.", tr: "Bütün koltuklar rezerve edildi." },
      { type: "example", en: "The new bridge is being built near the city center.", tr: "Yeni köprü şehir merkezinin yakınında inşa ediliyor." },
      { type: "example", en: "Was the case investigated properly?", tr: "Dava düzgün bir şekilde soruşturuldu mu?" },
      { type: "example", en: "The rules must be followed by everyone.", tr: "Kurallara herkes tarafından uyulmalı." },
      { type: "example", en: "This product wasn't tested before it was sold.", tr: "Bu ürün satılmadan önce test edilmedi." },
    ],
  },
  {
    fileBase: "33_As_Kaliplari",
    title: "AS KALIPLARI VE MEMNUNİYET İFADELERİ",
    blocks: [
      { type: "pattern", text: "AS = gibi, olarak, kadar, iken" },
      { type: "example", en: "As a company, we should pay attention to our expenses.", tr: "Bir şirket olarak, giderlerimize dikkat etmeliyiz." },
      { type: "pattern", text: "AS SOON AS POSSIBLE = mümkün olan en kısa zamanda" },
      { type: "example", en: "He has to call me as soon as possible.", tr: "Beni mümkün olan en kısa zamanda araması gerek." },
      { type: "example", en: "We want to be there as soon as possible.", tr: "Oraya mümkün olan en kısa zamanda ulaşmak istiyoruz." },
      { type: "pattern", text: "AS LONG AS POSSIBLE = olabildiğince uzun" },
      { type: "example", en: "I want to stay there as long as possible.", tr: "Orada olabildiğince uzun kalmak istiyorum." },
      { type: "example", en: "We will talk to them as long as possible.", tr: "Onlarla olabildiğince uzun konuşacağız." },
      { type: "rule", text: "AS...AS = ... kadar. İki şeyin eşit olduğunu anlatmak için kullanılır." },
      { type: "example", en: "This car is as expensive as the other one.", tr: "Bu araba diğeri kadar pahalı." },
      { type: "example", en: "I am as sad as him.", tr: "Onun kadar üzgünüm." },
      { type: "example", en: "He isn't as stubborn as me.", tr: "O benim kadar inatçı değil." },
      { type: "example", en: "You aren't as patient as those people.", tr: "Sen o insanlar kadar sabırlı değilsin." },
      { type: "pattern", text: "BE USED TO = alışmak, alışık olmak" },
      { type: "example", en: "I'm used to the cold.", tr: "Ben soğuğa alışkınım." },
      { type: "example", en: "Unfortunately, they aren't used to the conditions.", tr: "Maalesef şartlara alışık değiller." },
      { type: "pattern", text: "BE IN A GOOD MOOD = iyi modda olmak / BE IN A BAD MOOD = kötü modda olmak" },
      { type: "example", en: "If you are in a good mood, we can go there together.", tr: "İyi modda isen, oraya birlikte gidebiliriz." },
      { type: "example", en: "He doesn't want to come here because he is in a bad mood.", tr: "Buraya gelmek istemiyor çünkü modu kötü." },
      { type: "pattern", text: "DISAPPOINT = hayal kırıklığına uğratmak / ATTITUDE = tavır / DISAPPOINTED = hayal kırıklığına uğramış" },
      { type: "example", en: "You disappointed me by doing like this.", tr: "Böyle yaparak beni hayal kırıklığına uğrattın." },
      { type: "example", en: "Their attitudes disappointed us a lot.", tr: "Onların tavırları bizi çok hayal kırıklığına uğrattı." },
      { type: "example", en: "I don't want to be disappointed because of him.", tr: "Onun yüzünden hayal kırıklığına uğramak istemiyorum." },
      { type: "pattern", text: "HAVE FUN / HAVE A GOOD TIME = eğlenmek, iyi vakit geçirmek" },
      { type: "example", en: "Have fun!", tr: "İyi eğlenceler!" },
      { type: "example", en: "After a long time, we will have a good time together.", tr: "Uzun zaman sonra birlikte iyi vakit geçireceğiz." },
      { type: "pattern", text: "TERMS OF AGREEMENT = anlaşma şartları / SUBJECT = TOPIC = konu" },
      { type: "example", en: "Who will determine the terms of agreement?", tr: "Anlaşma şartlarını kim belirleyecek?" },
      { type: "example", en: "What do they know about this subject?", tr: "Onlar bu konu hakkında ne biliyor?" },
      { type: "pattern", text: "REASONABLE = makul / UNREASONABLE = mantıksız / EXCUSE = bahane / FOR NOTHING = boşuna" },
      { type: "example", en: "I cannot accept the unreasonable excuses.", tr: "Mantıksız bahaneleri kabul edemem." },
      { type: "example", en: "Don't come here for nothing!", tr: "Buraya boşuna gelme!" },
      { type: "pattern", text: "FIRE = kovmak/yangın / HIRE = işe almak" },
      { type: "example", en: "I cannot fire him.", tr: "Onu kovamam." },
      { type: "example", en: "She decided to hire a new assistant.", tr: "Yeni bir asistan işe almaya karar verdi." },
      { type: "pattern", text: "TRY ON = (kıyafet) denemek / MAKE WAIT = bekletmek / COMPARE = kıyaslamak" },
      { type: "example", en: "Do you want to try on this shirt?", tr: "Bu gömleği denemek ister misin?" },
      { type: "example", en: "I don't want you to make me wait.", tr: "Beni bekletmeni istemiyorum." },
      { type: "example", en: "Don't compare this building to the other!", tr: "Bu binayı diğeriyle kıyaslama!" },
      { type: "rule", text: "AS IF / AS THOUGH (-mış gibi) kalıbı, gerçek olmayan bir durumu betimlemek için kullanılır ve genellikle Past Simple ile kurulur." },
      { type: "pattern", text: "AS IF / AS THOUGH + Past Simple = ...mış gibi" },
      { type: "example", en: "He talks as if he knew everything.", tr: "Her şeyi biliyormuş gibi konuşuyor." },
      { type: "example", en: "She looked at me as though she had seen a ghost.", tr: "Bana sanki bir hayalet görmüş gibi baktı." },
      { type: "rule", text: "AS WELL AS (...nin yanı sıra, hem de) iki şeyi birlikte anlatmak için kullanılır." },
      { type: "example", en: "She speaks French as well as English.", tr: "O İngilizce'nin yanı sıra Fransızca da konuşuyor." },
      { type: "rule", text: "AS FAR AS I KNOW (bildiğim kadarıyla), AS A MATTER OF FACT (aslına bakarsan) gibi kalıplar da AS ailesindendir ve konuşma dilinde sık kullanılır." },
      { type: "example", en: "As far as I know, the meeting has been postponed.", tr: "Bildiğim kadarıyla toplantı ertelendi." },
      { type: "example", en: "As a matter of fact, I don't agree with you.", tr: "Aslına bakarsan, seninle aynı fikirde değilim." },
      { type: "rule", text: "Memnuniyet/memnuniyetsizlik ifadelerini pekiştiren ek kalıplar: SATISFACTORY (tatmin edici), UNSATISFACTORY (tatmin edici olmayan), FED UP WITH (bıkmış olmak)." },
      { type: "example", en: "The service was far from satisfactory.", tr: "Hizmet tatmin edicilikten çok uzaktı." },
      { type: "example", en: "I'm fed up with all these excuses.", tr: "Bütün bu bahanelerden bıktım." },
      { type: "rule", text: "Son olarak AS kalıplarını ve memnuniyet ifadelerini içeren bir kapanış paragrafı görelim." },
      { type: "example", en: "As far as I'm concerned, as long as you're happy with the decision, I'm satisfied too.", tr: "Bana kalırsa, sen karardan memnun olduğun sürece ben de memnunum." },
      { type: "rule", text: "AS SOON AS (...er ...mez), iki eylemin ardı sıra gerçekleştiğini anlatır ve genellikle Present Simple ile gelecek zamanı ifade eder." },
      { type: "example", en: "I'll let you know as soon as I hear anything.", tr: "Bir şey duyar duymaz sana haber vereceğim." },
      { type: "rule", text: "AS USUAL (her zamanki gibi) ve AS EXPECTED (beklendiği gibi) günlük konuşmada sık kullanılan AS kalıplarıdır." },
      { type: "example", en: "As usual, he was late for the meeting.", tr: "Her zamanki gibi toplantıya geç kaldı." },
      { type: "example", en: "As expected, the team won the championship.", tr: "Beklendiği gibi takım şampiyonluğu kazandı." },
      { type: "rule", text: "AS + sıfat/zarf + AS POSSIBLE kalıbı, bir şeyin mümkün olan en yüksek/düşük derecesini anlatır." },
      { type: "pattern", text: "AS + sıfat + AS POSSIBLE = mümkün olduğunca ..." },
      { type: "example", en: "Please arrive as early as possible.", tr: "Lütfen mümkün olduğunca erken varın." },
      { type: "example", en: "Try to keep the noise as low as possible.", tr: "Gürültüyü mümkün olduğunca düşük tutmaya çalış." },
      { type: "rule", text: "BE USED TO ile USED TO'yu karıştırmamak gerekir: BE USED TO bir alışkanlığı, USED TO ise eskiden yapılan ama artık yapılmayan bir eylemi anlatır." },
      { type: "example", en: "I used to smoke, but now I'm used to living a healthier life.", tr: "Eskiden sigara içerdim ama şimdi daha sağlıklı bir hayat yaşamaya alıştım." },
      { type: "rule", text: "GET USED TO (alışmak), bir alışkanlığın oluşma sürecini vurgular; BE USED TO ise zaten oluşmuş bir alışkanlığı." },
      { type: "example", en: "It took me months to get used to the new job, but now I'm completely used to it.", tr: "Yeni işe alışmam aylarımı aldı ama şimdi tamamen alıştım." },
      { type: "rule", text: "Duygu durumu ile ilgili ek kalıplar: IN A GOOD/BAD MOOD, FEEL LIKE + V-ing (canı bir şey yapmak istemek)." },
      { type: "example", en: "I don't feel like going out tonight.", tr: "Bu gece dışarı çıkmak canım istemiyor." },
      { type: "example", en: "Do you feel like watching a movie?", tr: "Film izlemek ister misin (canın ister mi)?" },
      { type: "rule", text: "Son olarak bu dersteki bütün AS kalıplarını içeren uzun bir kapanış paragrafı görelim." },
      { type: "example", en: "As soon as she got used to the new schedule, she started finishing her tasks as quickly as possible, and as expected, her performance improved.", tr: "Yeni programa alışır alışmaz, görevlerini mümkün olduğunca hızlı bitirmeye başladı ve beklendiği gibi performansı gelişti." },
      { type: "rule", text: "AS IF NOTHING HAD HAPPENED (hiçbir şey olmamış gibi) gibi kalıplaşmış ifadeler günlük konuşmada sıkça kullanılır." },
      { type: "example", en: "He walked in as if nothing had happened.", tr: "Hiçbir şey olmamış gibi içeri girdi." },
      { type: "rule", text: "AS + kişi/şey + isim kalıbı, bir rolü ya da kimliği belirtmek için kullanılır: AS A TEACHER (öğretmen olarak), AS A FRIEND (arkadaş olarak)." },
      { type: "example", en: "As a friend, I have to tell you the truth.", tr: "Bir arkadaş olarak, sana gerçeği söylemeliyim." },
      { type: "example", en: "As the manager, she has to make difficult decisions.", tr: "Müdür olarak, zor kararlar vermek zorunda." },
      { type: "rule", text: "SUCH AS (gibi, örneğin) örnek verirken kullanılır." },
      { type: "example", en: "I enjoy outdoor activities such as hiking and cycling.", tr: "Yürüyüş ve bisiklet gibi açık hava aktivitelerinden hoşlanırım." },
      { type: "rule", text: "Memnuniyet ölçeğini ifade eden zarflar: EXTREMELY SATISFIED (son derece memnun), FAIRLY SATISFIED (oldukça memnun), NOT AT ALL SATISFIED (hiç memnun değil)." },
      { type: "example", en: "We are extremely satisfied with the results.", tr: "Sonuçlardan son derece memnunuz." },
      { type: "example", en: "I'm not at all satisfied with this outcome.", tr: "Bu sonuçtan hiç memnun değilim." },
      { type: "rule", text: "AS + zarf + AS + POSSIBLE kalıbını pekiştiren birkaç örnek daha görelim; bu kalıp iş ve günlük hayatta çok işlevseldir." },
      { type: "example", en: "Please respond as soon as possible.", tr: "Lütfen mümkün olduğunca çabuk cevap verin." },
      { type: "example", en: "We tried to finish the work as efficiently as possible.", tr: "İşi mümkün olduğunca verimli bir şekilde bitirmeye çalıştık." },
      { type: "rule", text: "Bu dersteki bütün AS kalıplarını içeren son bir diyalog örneği görelim." },
      { type: "example", en: "Are you satisfied with the new manager? — As a matter of fact, yes, he treats everyone fairly, as far as I can tell.", tr: "Yeni müdürden memnun musun? — Aslına bakarsan, evet, benim görebildiğim kadarıyla herkese adil davranıyor." },
    ],
  },
  {
    fileBase: "34_Karma_Kaliplar_1",
    title: "KARMA KALIPLAR - 1",
    blocks: [
      { type: "pattern", text: "IN A SENSE = bir bakıma" },
      { type: "example", en: "You're right in a sense, but I can't defend you.", tr: "Bir bakıma haklısın ama seni savunamam." },
      { type: "pattern", text: "MAKE AN EFFORT = çaba sarfetmek / INSIST + ON = ısrar etmek / INSISTENT = ısrarcı" },
      { type: "example", en: "She insisted on coming with us.", tr: "O bizimle gelmekte ısrar etti." },
      { type: "example", en: "We have to make more effort.", tr: "Daha fazla çaba sarfetmeliyiz." },
      { type: "example", en: "Don't be insistent!", tr: "Israrcı olma!" },
      { type: "pattern", text: "LAST = sürmek / HOW LONG = ne kadar (zamansal)" },
      { type: "example", en: "How long does the concert last?", tr: "Konser ne kadar sürer?" },
      { type: "example", en: "How long does it take?", tr: "Ne kadar sürer?" },
      { type: "pattern", text: "ABOUT / APPROXIMATELY = yaklaşık" },
      { type: "example", en: "It takes approximately 20 minutes.", tr: "Yaklaşık 20 dakika sürer." },
      { type: "pattern", text: "HOW FAR = ne kadar uzak / FROM HERE = buradan" },
      { type: "example", en: "How far is Ankara from here?", tr: "Ankara buradan ne uzaklıktadır?" },
      { type: "pattern", text: "AS A RESULT = sonuç olarak / AT FIRST = FIRSTLY = ilk olarak" },
      { type: "example", en: "As a result, we will not go there this summer.", tr: "Sonuç olarak, bu yaz oraya gitmeyeceğiz." },
      { type: "example", en: "At first, we should inform them, then we will start.", tr: "İlk olarak onları bilgilendirmeliyiz, sonra başlayacağız." },
      { type: "pattern", text: "HESITATE = çekinmek, tereddüt etmek" },
      { type: "example", en: "Please don't hesitate!", tr: "Lütfen çekinmeyin!" },
      { type: "pattern", text: "FACT = gerçek / CONCLUSION = sonuç / FORECAST = tahmin / BROADCAST = yayın" },
      { type: "example", en: "The broadcast suddenly stopped.", tr: "Yayın aniden durdu." },
      { type: "pattern", text: "RECOMMEND = ADVISE = tavsiye etmek" },
      { type: "example", en: "Which hotel do you recommend for me?", tr: "Bana hangi oteli tavsiye edersin?" },
      { type: "pattern", text: "ALTHOUGH = EVEN THOUGH = -e rağmen" },
      { type: "example", en: "Although you were here, you didn't inform me.", tr: "Burada olmana rağmen beni bilgilendirmedin." },
      { type: "pattern", text: "REPRESENT = temsil etmek / SUCCESSFULLY = başarıyla" },
      { type: "example", en: "I think they will successfully represent you.", tr: "Sanırım seni başarıyla temsil edecekler." },
      { type: "pattern", text: "INCREASE = arttırmak / DECREASE = azaltmak" },
      { type: "example", en: "Will they increase the salaries?", tr: "Maaşları arttıracaklar mı?" },
      { type: "example", en: "If you decrease the prices, we can accept your offer.", tr: "Fiyatları düşürürseniz teklifinizi kabul edebiliriz." },
      { type: "pattern", text: "NOWADAYS = bugünlerde, şu sıralar" },
      { type: "example", en: "Nowadays I'm very busy, I can call you later.", tr: "Bugünlerde çok meşgulüm, seni sonra arayabilirim." },
      { type: "pattern", text: "INTERESTING = ilginç / BE INTERESTED IN = ilgilenmek" },
      { type: "example", en: "I am interested in football.", tr: "Futbolla ilgileniyorum." },
      { type: "example", en: "For a long time, he is interested in the stock market.", tr: "Uzun zamandır borsayla ilgileniyor." },
      { type: "pattern", text: "FROM NOW ON = bundan böyle / CELEBRATE = kutlamak / CELEBRATION = kutlama" },
      { type: "example", en: "From now on, we shouldn't make these mistakes.", tr: "Bundan böyle bu hataları yapmamalıyız." },
      { type: "example", en: "Where do they want to celebrate this victory?", tr: "Bu zaferi nerede kutlamak istiyorlar?" },
      { type: "pattern", text: "ACHIEVE = başarmak / ACHIEVEMENT = başarı / SUCCEED = başarılı olmak / FAIL = başarısız olmak" },
      { type: "example", en: "She achieved everything she wanted.", tr: "İstediği her şeyi başardı." },
      { type: "example", en: "They failed to complete the mission.", tr: "Görevi tamamlamayı başaramadılar." },
      { type: "pattern", text: "IN ADDITION (TO) = buna ek olarak / BESIDES = ayrıca, üstelik" },
      { type: "example", en: "In addition to his salary, he receives a bonus.", tr: "Maaşına ek olarak bir prim de alıyor." },
      { type: "example", en: "Besides, we don't have enough time anyway.", tr: "Üstelik zaten yeterli zamanımız yok." },
      { type: "pattern", text: "ON THE OTHER HAND = diğer yandan / IN CONTRAST = buna karşın" },
      { type: "example", en: "On the other hand, this option is cheaper.", tr: "Diğer yandan, bu seçenek daha ucuz." },
      { type: "pattern", text: "MENTION = bahsetmek / BRIEFLY = kısaca" },
      { type: "example", en: "Did he mention anything about the delay?", tr: "Gecikme hakkında bir şey bahsetti mi?" },
      { type: "example", en: "Let me briefly explain the situation.", tr: "Durumu kısaca açıklayayım." },
      { type: "pattern", text: "AVOID = kaçınmak / PREVENT = önlemek" },
      { type: "example", en: "We should avoid making the same mistake.", tr: "Aynı hatayı yapmaktan kaçınmalıyız." },
      { type: "example", en: "This medicine can prevent the disease from spreading.", tr: "Bu ilaç hastalığın yayılmasını önleyebilir." },
      { type: "pattern", text: "IN ORDER TO = -mek için, amacıyla" },
      { type: "example", en: "We left early in order to catch the train.", tr: "Treni yakalamak için erken ayrıldık." },
      { type: "rule", text: "IN SPITE OF ve DESPITE (-e rağmen) ALTHOUGH ile aynı anlama gelir ancak bunlardan sonra bir isim ya da V-ing gelir, cümle gelmez." },
      { type: "pattern", text: "IN SPITE OF / DESPITE + isim/V-ing" },
      { type: "example", en: "In spite of the rain, we went for a walk.", tr: "Yağmura rağmen yürüyüşe çıktık." },
      { type: "example", en: "Despite feeling tired, she finished the marathon.", tr: "Yorgun hissetmesine rağmen maratonu bitirdi." },
      { type: "rule", text: "Son olarak bu dersteki bağlaçları ve kalıpları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "In spite of all the difficulties, we achieved our goal, and in addition, we finished ahead of schedule.", tr: "Bütün zorluklara rağmen hedefimize ulaştık ve buna ek olarak, plandan önce bitirdik." },
      { type: "pattern", text: "CONSEQUENTLY = THEREFORE = bu yüzden, sonuç olarak" },
      { type: "example", en: "The flight was cancelled; consequently, we had to stay another night.", tr: "Uçuş iptal edildi; bu yüzden bir gece daha kalmak zorunda kaldık." },
      { type: "pattern", text: "SIMILARLY = benzer şekilde / LIKEWISE = aynı şekilde" },
      { type: "example", en: "Similarly, the second experiment showed the same results.", tr: "Benzer şekilde, ikinci deney de aynı sonuçları gösterdi." },
      { type: "pattern", text: "EVENTUALLY = sonunda / GRADUALLY = kademeli olarak, giderek" },
      { type: "example", en: "Eventually, they reached an agreement.", tr: "Sonunda bir anlaşmaya vardılar." },
      { type: "example", en: "The situation gradually improved over the months.", tr: "Durum aylar içinde giderek düzeldi." },
      { type: "pattern", text: "PARTICULARLY = ESPECIALLY = özellikle" },
      { type: "example", en: "This dish is particularly popular in the south.", tr: "Bu yemek özellikle güneyde popüler." },
      { type: "pattern", text: "UNLESS = -mediği takdirde, -medikçe" },
      { type: "example", en: "Unless you study harder, you won't pass the exam.", tr: "Daha çok çalışmadıkça sınavı geçemezsin." },
      { type: "example", en: "We won't leave unless everyone is ready.", tr: "Herkes hazır olmadıkça ayrılmayacağız." },
      { type: "pattern", text: "PROVIDED THAT = AS LONG AS = -mesi şartıyla" },
      { type: "example", en: "You can borrow my car, provided that you drive carefully.", tr: "Dikkatli sürmen şartıyla arabamı ödünç alabilirsin." },
      { type: "rule", text: "Son olarak bu dersteki bağlaçları ve zarfları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Unless something unexpected happens, we will eventually finish the project, and consequently, everyone will get a bonus.", tr: "Beklenmedik bir şey olmadıkça, sonunda projeyi bitireceğiz ve bunun sonucunda herkes prim alacak." },
      { type: "pattern", text: "OVERALL = genel olarak / IN GENERAL = genellikle" },
      { type: "example", en: "Overall, the project was a success.", tr: "Genel olarak, proje bir başarıydı." },
      { type: "pattern", text: "REGARDING = WITH REGARD TO = ile ilgili olarak, hususunda" },
      { type: "example", en: "Regarding your request, we will get back to you soon.", tr: "İsteğinizle ilgili olarak, size yakında dönüş yapacağız." },
      { type: "pattern", text: "ACCORDING TO = ...e göre" },
      { type: "example", en: "According to the report, sales increased last quarter.", tr: "Rapora göre, geçen çeyrekte satışlar arttı." },
      { type: "pattern", text: "IN TERMS OF = açısından, bakımından" },
      { type: "example", en: "In terms of quality, this product is much better.", tr: "Kalite açısından, bu ürün çok daha iyi." },
      { type: "pattern", text: "TEND TO = eğiliminde olmak / TENDENCY = eğilim" },
      { type: "example", en: "People tend to make mistakes when they're tired.", tr: "İnsanlar yorgunken hata yapma eğilimindedir." },
      { type: "rule", text: "Son olarak bu dersteki bağlaç ve zarfları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "According to the latest data, and in terms of overall performance, the company has done remarkably well this year.", tr: "En son verilere göre ve genel performans açısından, şirket bu yıl dikkate değer bir başarı gösterdi." },
      { type: "pattern", text: "WHEREAS = oysa, halbuki / WHILE = -iken (karşılaştırma)" },
      { type: "example", en: "He loves the city, whereas his wife prefers the countryside.", tr: "O şehri seviyor, oysa karısı kırsalı tercih ediyor." },
      { type: "pattern", text: "NEVERTHELESS = NONETHELESS = yine de, buna rağmen" },
      { type: "example", en: "The plan was risky; nevertheless, we decided to go ahead with it.", tr: "Plan riskliydi; yine de devam etmeye karar verdik." },
      { type: "rule", text: "Bu bağlaçları pekiştiren son bir örnek görelim." },
      { type: "example", en: "Whereas the first proposal focused on cost, the second one, nevertheless, prioritized quality.", tr: "İlk teklif maliyete odaklanırken, ikincisi yine de kaliteyi önceliklendirdi." },
    ],
  },
  {
    fileBase: "35_Karma_Kaliplar_2",
    title: "KARMA KALIPLAR - 2",
    blocks: [
      { type: "pattern", text: "PREDICT = öngörmek / PREDICTABLE = öngörülebilir / UNPREDICTABLE = öngörülemez" },
      { type: "example", en: "The result was unpredictable, so we didn't take risks.", tr: "Sonuç öngörülemezdi, bu yüzden risk almadık." },
      { type: "pattern", text: "TAKE A RISK = risk almak" },
      { type: "pattern", text: "SHY = utangaç, çekingen" },
      { type: "example", en: "You don't need to be shy.", tr: "Çekingen olmana gerek yok." },
      { type: "pattern", text: "PLEASURE = keyif / PLEASED = memnun / BE PLEASED WITH = memnun olmak" },
      { type: "example", en: "It is our pleasure to welcome them.", tr: "Onları ağırlamak bizim için bir zevk." },
      { type: "example", en: "Are you pleased with that?", tr: "Bundan memnun musun?" },
      { type: "pattern", text: "PROUD = gururlu / BE PROUD OF = gurur duymak" },
      { type: "example", en: "I'm proud of my children.", tr: "Çocuklarımla gurur duyuyorum." },
      { type: "example", en: "You should be proud of them.", tr: "Onlarla gurur duymalısın." },
      { type: "pattern", text: "INTRODUCE = tanıştırmak / BY THE WAY = bu arada" },
      { type: "example", en: "By the way, I want to introduce you my brother.", tr: "Bu arada, sana kardeşimi tanıtmak istiyorum." },
      { type: "pattern", text: "APPEAR = görünmek, ortaya çıkmak / DISAPPEAR = ortadan kaybolmak / LOOK = görünmek (dışarıdan) / APPEARANCE = görünüm" },
      { type: "example", en: "They didn't appear today.", tr: "Onlar bugün görünmedi." },
      { type: "example", en: "He suddenly disappeared, nobody knows where he is.", tr: "Aniden ortadan kayboldu, kimse nerede olduğunu bilmiyor." },
      { type: "pattern", text: "DECEIVE = kandırmak / DECEPTIVE = yanıltıcı" },
      { type: "example", en: "The hotel looks nice, but appearances can be deceptive.", tr: "Otel güzel görünüyor ama görünüş yanıltıcı olabilir." },
      { type: "pattern", text: "WHAT KIND OF = ne tür" },
      { type: "example", en: "What kind of music do you like?", tr: "Ne tür müzik seversin?" },
      { type: "example", en: "What kind of movies do you like?", tr: "Ne tür filmler seversin?" },
      { type: "pattern", text: "PURPOSE = amaç / GOAL = TARGET = hedef / AIM = hedeflemek" },
      { type: "example", en: "What is the purpose of your visit?", tr: "Ziyaretinizin amacı ne?" },
      { type: "example", en: "We aim to be number one.", tr: "Bir numara olmayı hedefliyoruz." },
      { type: "pattern", text: "DURATION = süre / DURING = süresince, boyunca" },
      { type: "example", en: "What is the flight duration?", tr: "Uçuş süresi ne kadar?" },
      { type: "example", en: "I want to rest during the vacation.", tr: "Tatil süresince dinlenmek istiyorum." },
      { type: "pattern", text: "RESCUE = kurtarmak / RESCUE TEAM = kurtarma ekibi" },
      { type: "example", en: "We'll try everything to rescue her.", tr: "Onu kurtarmak için her şeyi deneyeceğiz." },
      { type: "example", en: "The rescue team didn't come yet.", tr: "Kurtarma ekibi henüz gelmedi." },
      { type: "rule", text: "ALL (hepsi) - BOTH (her ikisi) - BOTH...AND (hem...hem de). EITHER...OR (ya...ya da). NEITHER...NOR (ne...ne de)." },
      { type: "example", en: "Did they all come on time?", tr: "Onların hepsi zamanında geldi mi?" },
      { type: "example", en: "We both want to start today.", tr: "Her ikimiz de bugün başlamak istiyoruz." },
      { type: "example", en: "They want to see both you and me.", tr: "Onlar hem seni hem de beni görmek istiyorlar." },
      { type: "example", en: "I will inform either you or him.", tr: "Ya sana ya da ona haber vereceğim." },
      { type: "example", en: "He wants to see neither me nor you.", tr: "O ne beni ne de seni görmek istiyor." },
      { type: "pattern", text: "ADMIT = kabul etmek, içeri almak / ADMISSION = giriş / FREE ADMISSION = ücretsiz giriş / VISITOR = ziyaretçi" },
      { type: "example", en: "Why don't you admit the visitors?", tr: "Siz niye ziyaretçileri kabul etmiyorsunuz?" },
      { type: "example", en: "Is there free admission?", tr: "Ücretsiz giriş mi var?" },
      { type: "pattern", text: "PROVIDE = sağlamak / CITIZEN = vatandaş / CITIZENSHIP = vatandaşlık / DUAL CITIZENSHIP = çifte vatandaşlık" },
      { type: "example", en: "What kind of services do they provide?", tr: "Ne tür hizmetler sağlıyorlar?" },
      { type: "example", en: "Does he have dual citizenship?", tr: "Onun çifte vatandaşlığı mı var?" },
      { type: "pattern", text: "DEPOSIT (MONEY) = para yatırmak / WITHDRAW = para çekmek / SETTLE + IN = yerleşmek" },
      { type: "example", en: "I'll deposit money into my account.", tr: "Hesabıma para yatıracağım." },
      { type: "example", en: "Are you planning to settle in Moscow?", tr: "Moskova'ya yerleşmeyi mi planlıyorsun?" },
      { type: "pattern", text: "GAIN = kazanmak, elde etmek / GAIN PROFIT = kâr elde etmek" },
      { type: "example", en: "My goal is to gain more experience.", tr: "Hedefim daha fazla tecrübe kazanmak." },
      { type: "example", en: "We will gain more profit from this business.", tr: "Bu işten daha fazla kâr elde edeceğiz." },
      { type: "pattern", text: "INNOCENT = masum / GUILTY = suçlu" },
      { type: "example", en: "I am sure that he is more guilty.", tr: "Onun daha suçlu olduğundan eminim." },
      { type: "pattern", text: "CONFIRM = onaylamak, doğrulamak / CONFIRMATION = onay" },
      { type: "example", en: "Could you confirm the reservation?", tr: "Rezervasyonu onaylayabilir misiniz?" },
      { type: "pattern", text: "SUBMIT = teslim etmek, sunmak / APPLICATION FORM = başvuru formu" },
      { type: "example", en: "You need to submit your application form by Friday.", tr: "Başvuru formunu Cuma'ya kadar teslim etmen gerekiyor." },
      { type: "pattern", text: "RENEW = yenilemek / RENEWAL = yenileme / EXPIRE = süresi dolmak" },
      { type: "example", en: "My passport is going to expire next month.", tr: "Pasaportumun süresi gelecek ay dolacak." },
      { type: "example", en: "I need to renew my driving license.", tr: "Ehliyetimi yenilemem gerekiyor." },
      { type: "pattern", text: "GUARANTEE = garanti etmek, garanti / WARRANTY = garanti (ürün)" },
      { type: "example", en: "This product comes with a two-year warranty.", tr: "Bu ürün iki yıllık garanti ile geliyor." },
      { type: "example", en: "I can't guarantee that it will work.", tr: "Çalışacağını garanti edemem." },
      { type: "pattern", text: "ESSENTIAL = temel, gerekli / NECESSARY = gerekli / OPTIONAL = isteğe bağlı" },
      { type: "example", en: "Water is essential for life.", tr: "Su hayat için gerekli." },
      { type: "example", en: "This part of the form is optional.", tr: "Formun bu kısmı isteğe bağlı." },
      { type: "pattern", text: "ACCURATE = doğru, isabetli / ACCURACY = doğruluk / PRECISE = kesin, tam" },
      { type: "example", en: "The information you gave wasn't accurate.", tr: "Verdiğin bilgi doğru değildi." },
      { type: "pattern", text: "ADEQUATE = yeterli / INADEQUATE = yetersiz" },
      { type: "example", en: "The training we received was inadequate.", tr: "Aldığımız eğitim yetersizdi." },
      { type: "pattern", text: "CONSIDER = değerlendirmek, düşünmek / CONSIDERATE = düşünceli / CONSIDERATION = değerlendirme" },
      { type: "example", en: "We should consider all the options before deciding.", tr: "Karar vermeden önce bütün seçenekleri değerlendirmeliyiz." },
      { type: "example", en: "He's always very considerate towards others.", tr: "O her zaman başkalarına karşı çok düşünceli." },
      { type: "rule", text: "Son olarak bu dersteki karma kalıpları içeren birkaç örnek daha görelim." },
      { type: "example", en: "Before you submit the application, make sure all the information is accurate and the required documents are attached.", tr: "Başvuruyu göndermeden önce, bütün bilgilerin doğru olduğundan ve gerekli belgelerin eklendiğinden emin ol." },
      { type: "example", en: "The company guarantees a full refund if you're not satisfied with the product.", tr: "Şirket, üründen memnun kalmazsanız tam para iadesi garanti ediyor." },
      { type: "pattern", text: "VERIFY = doğrulamak / VERIFICATION = doğrulama" },
      { type: "example", en: "We need to verify your identity first.", tr: "Önce kimliğinizi doğrulamamız gerekiyor." },
      { type: "pattern", text: "RELIABLE = güvenilir / TRUSTWORTHY = güvenilir, itimat edilir" },
      { type: "example", en: "We need a reliable source of information.", tr: "Güvenilir bir bilgi kaynağına ihtiyacımız var." },
      { type: "pattern", text: "GENUINE = gerçek, hakiki / AUTHENTIC = otantik, özgün" },
      { type: "example", en: "Is this a genuine leather bag?", tr: "Bu gerçek deri bir çanta mı?" },
      { type: "pattern", text: "VALUABLE = değerli / PRICELESS = paha biçilmez / WORTHLESS = değersiz" },
      { type: "example", en: "This painting is priceless to our family.", tr: "Bu tablo ailemiz için paha biçilmez." },
      { type: "pattern", text: "OBTAIN = elde etmek / ACQUIRE = edinmek, kazanmak" },
      { type: "example", en: "How did you obtain this information?", tr: "Bu bilgiyi nasıl elde ettin?" },
      { type: "example", en: "The company acquired a smaller competitor last year.", tr: "Şirket geçen yıl daha küçük bir rakibi satın aldı." },
      { type: "rule", text: "Son olarak bu dersteki karma kalıpların hepsini içeren uzun bir kapanış paragrafı görelim." },
      { type: "example", en: "In order to obtain a reliable result, we need to consider all the factors, verify our sources, and provide accurate data.", tr: "Güvenilir bir sonuç elde etmek için, bütün faktörleri değerlendirmemiz, kaynaklarımızı doğrulamamız ve doğru veri sağlamamız gerekiyor." },
      { type: "pattern", text: "DISTINGUISH = ayırt etmek / DIFFERENTIATE = farklılaştırmak" },
      { type: "example", en: "It's hard to distinguish between the two versions.", tr: "İki versiyon arasında ayırt etmek zor." },
      { type: "pattern", text: "RESEMBLE = benzemek / RESEMBLANCE = benzerlik" },
      { type: "example", en: "She resembles her mother a lot.", tr: "O annesine çok benziyor." },
      { type: "rule", text: "Son olarak bu dersteki bütün kalıpları içeren bir kapanış cümlesi görelim." },
      { type: "example", en: "Although the two products resemble each other, it's essential to distinguish between them in terms of quality and price.", tr: "İki ürün birbirine benzese de, kalite ve fiyat açısından aralarını ayırt etmek önemli." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
