import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "28_Seyahat_ve_Bilgi",
    title: "SEYAHAT VE BİLGİ ALIŞVERİŞİ KALIPLARI",
    blocks: [
      { type: "pattern", text: "GATE = kapı (havalimanı) / DEPARTURES = kalkışlar / ARRIVALS = varışlar / FLOOR = LEVEL = kat" },
      { type: "example", en: "Excuse me! Can you show me the departures floor?", tr: "Affedersiniz! Bana kalkış katını gösterebilir misiniz?" },
      { type: "pattern", text: "LAND = yere inmek / TAKE OFF = havalanmak / BOARDING = biniş" },
      { type: "example", en: "When did your plane land?", tr: "Uçağınız ne zaman indi?" },
      { type: "example", en: "Boarding completed!", tr: "Biniş tamamlandı!" },
      { type: "pattern", text: "ATTEMPT = girişim, teşebbüs etmek" },
      { type: "example", en: "This is my first attempt.", tr: "Bu benim ilk girişimim." },
      { type: "example", en: "They didn't attempt enough, that's why they're so sad.", tr: "Yeterince girişimde bulunmadılar, bu yüzden çok üzgünler." },
      { type: "pattern", text: "THINK + ABOUT = düşünmek / PLAN = planlamak, plan" },
      { type: "example", en: "You must plan the next trip.", tr: "Bir sonraki geziyi planlamalısın." },
      { type: "example", en: "She always thinks about you.", tr: "O her zaman seni düşünüyor." },
      { type: "pattern", text: "GET INFORMATION = bilgi almak / GIVE INFORMATION = bilgi vermek" },
      { type: "example", en: "Excuse me! Can I get information?", tr: "Affedersiniz! Bilgi alabilir miyim?" },
      { type: "example", en: "Who will give information to you?", tr: "Sana kim bilgi verecek?" },
      { type: "pattern", text: "OBJECT + TO = itiraz etmek, karşı çıkmak / EVALUATE = değerlendirmek" },
      { type: "example", en: "We can't object to his decision.", tr: "Onun kararına itiraz edemeyiz." },
      { type: "example", en: "You should absolutely evaluate their objection.", tr: "Kesinlikle onların itirazını değerlendirmelisin." },
      { type: "pattern", text: "NOTICE = farkına varmak" },
      { type: "rule", text: "Öğün isimleri: BREAKFAST (kahvaltı), LUNCH (öğle yemeği), DINNER (akşam yemeği). HAVE BREAKFAST/LUNCH/DINNER = yemek yemek." },
      { type: "example", en: "Who did you have breakfast with?", tr: "Kahvaltıyı kiminle yaptın?" },
      { type: "rule", text: "Sıklık ifadeleri: ONCE (bir kez), TWICE (iki kez), THREE TIMES (üç kez)... ONCE A WEEK (haftada bir), TWICE A MONTH (ayda iki kere)." },
      { type: "example", en: "I see her once a week.", tr: "Onu haftada bir görürüm." },
      { type: "example", en: "He travels twice a month.", tr: "O ayda iki kere seyahat eder." },
      { type: "example", en: "She calls me three times a day.", tr: "O beni günde üç kez arar." },
      { type: "pattern", text: "TAKE A SHOWER / HAVE A SHOWER = duş almak" },
      { type: "example", en: "I take a shower twice a day.", tr: "Günde iki kez duş alırım." },
      { type: "pattern", text: "NEGOTIATE = görüşmek, müzakere etmek / GO ON = sürmek, devam etmek" },
      { type: "example", en: "The negotiations are going on.", tr: "Müzakereler devam ediyor." },
      { type: "pattern", text: "MAKE A DECISION = karar vermek" },
      { type: "example", en: "When did you make your decision?", tr: "Kararını ne zaman verdin?" },
      { type: "example", en: "I will make my own decision.", tr: "Kendi kararımı vereceğim." },
      { type: "pattern", text: "AFFORD = gücü yetmek / AFFORDABLE = satın alınabilir" },
      { type: "example", en: "She can't afford this car.", tr: "Bu arabayı almaya onun gücü yetmiyor." },
      { type: "example", en: "This house isn't affordable, so we will give up buying it.", tr: "Bu ev satın alınabilir değil, bu yüzden almaktan vazgeçeceğiz." },
      { type: "pattern", text: "INTENTION = niyet / INTEND = niyeti olmak" },
      { type: "example", en: "He has no intention of renting this house.", tr: "Onun bu evi kiralamaya niyeti yok." },
      { type: "example", en: "We intend to get up so early.", tr: "Çok erken kalkmayı planlıyoruz." },
      { type: "pattern", text: "LEARN A LESSON = ders çıkartmak" },
      { type: "example", en: "You should learn a lesson from your mistakes.", tr: "Hatalarından ders çıkarmalısın." },
      { type: "spacer" },
      { type: "rule", text: "Otelde kullanılan temel kalıplar: CHECK IN (giriş yapmak), CHECK OUT (çıkış yapmak), RESERVATION (rezervasyon), BOOK A ROOM (oda ayırtmak), RECEPTION (resepsiyon), VACANCY (boş oda)." },
      { type: "example", en: "I'd like to check in, please.", tr: "Giriş yapmak istiyorum lütfen." },
      { type: "example", en: "What time is check-out?", tr: "Çıkış saati kaçta?" },
      { type: "example", en: "We booked a room for three nights.", tr: "Üç gecelik oda ayırttık." },
      { type: "example", en: "Do you have any vacancies for tonight?", tr: "Bu gece için boş odanız var mı?" },
      { type: "rule", text: "Yön tarifi kalıpları: TURN LEFT/RIGHT (sağa/sola dönmek), GO STRAIGHT ON (düz devam etmek), CROSS THE STREET (caddeyi geçmek), ON THE CORNER (köşede), ROUNDABOUT (kavşak)." },
      { type: "example", en: "Turn left at the traffic lights.", tr: "Trafik ışıklarında sola dön." },
      { type: "example", en: "Go straight on until you see the bank.", tr: "Bankayı görene kadar düz devam et." },
      { type: "example", en: "The hotel is on the corner of this street.", tr: "Otel bu caddenin köşesinde." },
      { type: "pattern", text: "HOW DO I GET TO...? = ...'e nasıl giderim? / IS IT FAR FROM HERE? = buradan uzak mı?" },
      { type: "example", en: "How do I get to the train station?", tr: "Tren istasyonuna nasıl giderim?" },
      { type: "example", en: "Is the museum far from here?", tr: "Müze buradan uzak mı?" },
      { type: "rule", text: "Bilet ve ulaşımla ilgili kalıplar: ONE-WAY TICKET (tek yön bilet), ROUND-TRIP TICKET (gidiş-dönüş bilet), PLATFORM (peron), TIMETABLE (tarife), DELAY (gecikme), CANCEL (iptal etmek)." },
      { type: "example", en: "I'd like a round-trip ticket to Izmir.", tr: "İzmir'e gidiş-dönüş bilet istiyorum." },
      { type: "example", en: "Which platform does the train leave from?", tr: "Tren hangi perondan kalkıyor?" },
      { type: "example", en: "Our flight has been delayed by two hours.", tr: "Uçuşumuz iki saat gecikti." },
      { type: "example", en: "They canceled the last train because of the storm.", tr: "Fırtına yüzünden son treni iptal ettiler." },
      { type: "pattern", text: "EXCHANGE RATE = döviz kuru / CURRENCY = para birimi / EXCHANGE OFFICE = döviz bürosu" },
      { type: "example", en: "What's the exchange rate today?", tr: "Bugün döviz kuru ne?" },
      { type: "example", en: "Where is the nearest exchange office?", tr: "En yakın döviz bürosu nerede?" },
      { type: "rule", text: "Kayıp eşya ve şikayet ile ilgili kalıplar: LOST LUGGAGE (kayıp bagaj), CLAIM (talep etmek), COMPLAINT (şikayet), REFUND (para iadesi)." },
      { type: "example", en: "I need to report my lost luggage.", tr: "Kayıp bagajımı bildirmem gerekiyor." },
      { type: "example", en: "Can I make a complaint about this service?", tr: "Bu hizmet hakkında şikayette bulunabilir miyim?" },
      { type: "example", en: "We asked for a refund because the flight was canceled.", tr: "Uçuş iptal olduğu için para iadesi istedik." },
      { type: "pattern", text: "PASSPORT CONTROL = pasaport kontrolü / CUSTOMS = gümrük / DECLARE = beyan etmek" },
      { type: "example", en: "You need to go through passport control first.", tr: "Önce pasaport kontrolünden geçmen gerekiyor." },
      { type: "example", en: "Do you have anything to declare?", tr: "Beyan edeceğiniz bir şey var mı?" },
      { type: "pattern", text: "TOURIST INFORMATION = turist danışma / GUIDE = rehber / SOUVENIR = hediyelik eşya" },
      { type: "example", en: "Is there a tourist information office near the square?", tr: "Meydanın yakınında turist danışma ofisi var mı?" },
      { type: "example", en: "Our guide showed us the old city.", tr: "Rehberimiz bize eski şehri gösterdi." },
      { type: "example", en: "I want to buy some souvenirs for my family.", tr: "Aileme birkaç hediyelik eşya almak istiyorum." },
      { type: "rule", text: "Bilgi alışverişinde kullanılan diğer fiiller: FIND OUT (öğrenmek), INQUIRE (sormak, bilgi almak), POINT OUT (belirtmek, işaret etmek)." },
      { type: "example", en: "Could you find out what time the museum closes?", tr: "Müzenin saat kaçta kapandığını öğrenebilir misin?" },
      { type: "example", en: "I'd like to inquire about the ferry schedule.", tr: "Feribot tarifesi hakkında bilgi almak istiyorum." },
      { type: "example", en: "The guide pointed out the most important buildings.", tr: "Rehber en önemli binaları işaret etti." },
      { type: "rule", text: "Restoranda bilgi alışverişi: MENU (menü), RECOMMEND A DISH (bir yemek önermek), BE ALLERGIC TO (...'e alerjisi olmak)." },
      { type: "example", en: "Could you recommend a local dish?", tr: "Yerel bir yemek önerebilir misiniz?" },
      { type: "example", en: "I'm allergic to nuts, so I can't eat this.", tr: "Fındığa alerjim var, bu yüzden bunu yiyemem." },
      { type: "example", en: "Can I see the menu, please?", tr: "Menüyü görebilir miyim lütfen?" },
      { type: "rule", text: "Acil durumlarla ilgili kalıplar: EMERGENCY (acil durum), POLICE STATION (karakol), HOSPITAL (hastane), GET LOST (kaybolmak)." },
      { type: "example", en: "Where's the nearest police station?", tr: "En yakın karakol nerede?" },
      { type: "example", en: "We got lost in the old town.", tr: "Eski şehirde kaybolduk." },
      { type: "example", en: "Call an ambulance, it's an emergency!", tr: "Ambulans çağırın, bu acil bir durum!" },
      { type: "rule", text: "Zaman farkı ve yerel saat ile ilgili kalıplar: TIME DIFFERENCE (saat farkı), LOCAL TIME (yerel saat)." },
      { type: "example", en: "What's the time difference between Istanbul and London?", tr: "İstanbul ile Londra arasındaki saat farkı ne kadar?" },
      { type: "example", en: "What's the local time there now?", tr: "Oradaki yerel saat şu an kaç?" },
      { type: "rule", text: "İnternet bağlantısı hakkında bilgi almak için kullanılan kalıplar: IS THERE WIFI HERE? (burada wifi var mı?), WHAT'S THE PASSWORD? (şifre nedir?)." },
      { type: "example", en: "Is there free wifi in this hotel?", tr: "Bu otelde ücretsiz wifi var mı?" },
      { type: "example", en: "What's the wifi password, please?", tr: "Wifi şifresi nedir acaba?" },
      { type: "rule", text: "Sık yapılan hata: GET INFORMATION kalıbında \"informations\" gibi çoğul kullanmak yanlıştır; INFORMATION sayılamayan bir isimdir, her zaman tekil kullanılır." },
      { type: "example", en: "I need some information about the tour. (doğru) — NOT: some informations", tr: "Tur hakkında biraz bilgiye ihtiyacım var. — Yanlış: informations" },
      { type: "rule", text: "Otel resepsiyonunda geçen örnek bir diyalog ile bu dersi tamamlayalım." },
      { type: "example", en: "I have a reservation under the name Aydın. — Let me check... yes, your room is ready.", tr: "Aydın adına rezervasyonum var. — Kontrol edeyim... evet, odanız hazır." },
    ],
  },
  {
    fileBase: "29_Duygular_ve_Kisilik",
    title: "DUYGULAR VE KİŞİLİK SIFATLARI",
    blocks: [
      { type: "pattern", text: "HAPPINESS = mutluluk / SADNESS = üzüntü / AT ALL = hiç / TO THE LAST = sonuna kadar" },
      { type: "example", en: "He didn't deserve the sadness at all.", tr: "O üzüntüyü hiç hak etmedi." },
      { type: "example", en: "We deserve the happiness to the last.", tr: "Sonuna kadar mutluluğu hak ediyoruz." },
      { type: "pattern", text: "TIREDNESS = yorgunluk" },
      { type: "example", en: "I couldn't get rid of the tiredness.", tr: "Yorgunluktan kurtulamadım." },
      { type: "pattern", text: "STUBBORN = inatçı / AMBITIOUS = hırslı" },
      { type: "example", en: "You shouldn't be so stubborn.", tr: "Bu kadar inatçı olmamalısın." },
      { type: "pattern", text: "COURAGE = cesaret / ENCOURAGE = cesaretlendirmek / DISCOURAGE = cesaretini kırmak" },
      { type: "example", en: "We must encourage him in this matter.", tr: "Bu konuda onu teşvik etmeliyiz." },
      { type: "example", en: "Don't try to discourage him!", tr: "Onun cesaretini kırmaya çalışma!" },
      { type: "pattern", text: "MATTER = mesele, önemi olmak / WHAT'S THE MATTER? = sorun ne?" },
      { type: "example", en: "No matter! Nothing else matters.", tr: "Önemi yok! Başka hiçbir şeyin önemi yok." },
      { type: "example", en: "What's the matter with you?", tr: "Senin sorunun ne?" },
      { type: "pattern", text: "ELSE = başka / ANYTHING ELSE? = başka bir şey?" },
      { type: "example", en: "What else do you need?", tr: "Başka neye ihtiyacın var?" },
      { type: "pattern", text: "COOPERATE = işbirliği yapmak" },
      { type: "example", en: "They decided to cooperate with us.", tr: "Bizimle işbirliği yapmaya karar verdiler." },
      { type: "example", en: "Who will you cooperate with?", tr: "Sen kiminle işbirliği yapacaksın?" },
      { type: "pattern", text: "CLASS = sınıf, ders / INVEST = yatırım yapmak / INVESTMENT = yatırım" },
      { type: "example", en: "I have a class today.", tr: "Bugün dersim var." },
      { type: "rule", text: "Yönler: NORTH (kuzey), SOUTH (güney), WEST (batı), EAST (doğu). MIDDLE EAST = orta doğu, FAR EAST = uzak doğu." },
      { type: "example", en: "Do they want to invest in the far east?", tr: "Onlar uzak doğuya yatırım yapmak isterler mi?" },
      { type: "example", en: "Are you satisfied with our investments?", tr: "Yatırımlarımızdan memnun musunuz?" },
      { type: "pattern", text: "ASK = sormak / ASK FOR = istemek, rica etmek / ANSWER = cevap vermek" },
      { type: "pattern", text: "DIE = ölmek / DEAD = ölü / ALIVE = hayatta" },
      { type: "example", en: "Are your parents alive?", tr: "Anne baban hayatta mı?" },
      { type: "example", en: "We don't know when we will die.", tr: "Ne zaman öleceğimizi bilmiyoruz." },
      { type: "pattern", text: "BROKEN = bozuk, kırık / SOMEONE = biri / SAFE = kasa / REPAIR = FIX = tamir etmek" },
      { type: "example", en: "The safe is broken. Can someone fix it?", tr: "Kasa bozuk. Biri tamir edebilir mi?" },
      { type: "pattern", text: "REFUSE = REJECT = reddetmek / PERSUADE = ikna etmek" },
      { type: "example", en: "Why did you reject his offer?", tr: "Neden onun teklifini reddettin?" },
      { type: "example", en: "I'm trying to persuade her.", tr: "Onu ikna etmeye çalışıyorum." },
      { type: "pattern", text: "GIFT = PRESENT = hediye / RECENTLY = son zamanlarda" },
      { type: "example", en: "He recently sold his motorbike.", tr: "O son zamanlarda motosikletini sattı." },
      { type: "example", en: "You deserve this gift to the last.", tr: "Bu hediyeyi sonuna kadar hak ediyorsun." },
      { type: "pattern", text: "SUPPORT = destek, desteklemek / ATTENTION = dikkat, ilgi / ADD = eklemek / CONTRIBUTE = katkı sağlamak" },
      { type: "example", en: "Thank you for your support!", tr: "Desteğin için teşekkürler!" },
      { type: "example", en: "I want you to contribute more.", tr: "Daha fazla katkı sağlamanı istiyorum." },
      { type: "pattern", text: "EXPENSES = masraflar, giderler" },
      { type: "example", en: "Aren't the expenses so high?", tr: "Giderler çok yüksek değil mi?" },
      { type: "rule", text: "Kişilik sıfatları: OUTGOING (dışa dönük), SHY (çekingen), CONFIDENT (özgüvenli), GENEROUS (cömert), SELFISH (bencil), HONEST (dürüst), RELIABLE (güvenilir)." },
      { type: "example", en: "She is very outgoing and makes friends easily.", tr: "O çok dışa dönük ve kolayca arkadaş ediniyor." },
      { type: "example", en: "He is too selfish to share anything.", tr: "O bir şeyi paylaşamayacak kadar bencil." },
      { type: "example", en: "You can always trust her, she's very reliable.", tr: "Ona her zaman güvenebilirsin, o çok güvenilir." },
      { type: "rule", text: "Duygu bildiren sıfatların -ED ve -ING hâlleri: -ED kişinin hissettiği duyguyu, -ING ise duyguya sebep olan şeyi/kişiyi anlatır." },
      { type: "pattern", text: "INTERESTED (ilgilenen) / INTERESTING (ilginç)   |   SURPRISED (şaşıran) / SURPRISING (şaşırtıcı)   |   CONFUSED (kafası karışan) / CONFUSING (kafa karıştırıcı)" },
      { type: "example", en: "I was surprised by the surprising results.", tr: "Şaşırtıcı sonuçlar tarafından şaşırtıldım." },
      { type: "example", en: "This book is really interesting, I'm very interested in it.", tr: "Bu kitap gerçekten ilginç, ona çok ilgi duyuyorum." },
      { type: "example", en: "The instructions were confusing, so everyone was confused.", tr: "Talimatlar kafa karıştırıcıydı, bu yüzden herkesin kafası karıştı." },
      { type: "rule", text: "Duyguları ifade eden fiiller: FEEL (hissetmek), BE IN THE MOOD FOR (canı istemek), CHEER UP (neşelenmek/neşelendirmek), CALM DOWN (sakinleşmek)." },
      { type: "example", en: "I'm not in the mood for talking right now.", tr: "Şu an konuşacak halim yok." },
      { type: "example", en: "Please calm down, everything will be fine.", tr: "Lütfen sakin ol, her şey düzelecek." },
      { type: "example", en: "That song always cheers me up.", tr: "O şarkı beni her zaman neşelendirir." },
      { type: "rule", text: "Kişilik tanımlarken kullanılan diğer sıfatlar: PATIENT (sabırlı), IMPATIENT (sabırsız), OPTIMISTIC (iyimser), PESSIMISTIC (kötümser), CURIOUS (meraklı)." },
      { type: "example", en: "You need to be more patient with children.", tr: "Çocuklara karşı daha sabırlı olman gerekiyor." },
      { type: "example", en: "She's always optimistic, even in difficult times.", tr: "O zor zamanlarda bile her zaman iyimser." },
      { type: "rule", text: "Son olarak duygu ve kişilik sıfatlarını birlikte kullanan bir örnek diyalog görelim." },
      { type: "example", en: "Why does he seem so nervous today? — He's always anxious before exams, but he's actually very confident once he starts.", tr: "Bugün neden bu kadar gergin görünüyor? — Sınavlardan önce hep endişeli oluyor ama başladığında aslında çok özgüvenli oluyor." },
      { type: "rule", text: "Duygu durumu bildiren daha fazla sıfat: EMBARRASSED (utanmış), JEALOUS (kıskanç), PROUD (gururlu), ASHAMED (utanç duyan), GRATEFUL (minnettar)." },
      { type: "example", en: "I felt embarrassed when I forgot his name.", tr: "Adını unuttuğumda utandım." },
      { type: "example", en: "We are very proud of your achievements.", tr: "Başarılarınla çok gurur duyuyoruz." },
      { type: "example", en: "I'm grateful for everything you've done for me.", tr: "Benim için yaptığın her şey için minnettarım." },
      { type: "rule", text: "Kişilik olumsuz sıfatları: RUDE (kaba), ARROGANT (kibirli), DISHONEST (dürüst olmayan), CARELESS (dikkatsiz), MOODY (huysuz, değişken ruh hali)." },
      { type: "example", en: "Don't be so rude to your sister.", tr: "Kardeşine karşı bu kadar kaba olma." },
      { type: "example", en: "He can be quite moody sometimes.", tr: "O bazen oldukça huysuz olabiliyor." },
      { type: "rule", text: "Duyguları vücut dili ile anlatan ifadeler: BURST INTO TEARS (gözyaşlarına boğulmak), BLUSH (kızarmak, mahcup olmak), FROWN (kaşlarını çatmak)." },
      { type: "example", en: "She burst into tears when she heard the news.", tr: "Haberi duyunca gözyaşlarına boğuldu." },
      { type: "example", en: "He frowned when he read the letter.", tr: "Mektubu okuduğunda kaşlarını çattı." },
      { type: "rule", text: "GET + sıfat kalıbı bir duygu değişimini anlatır: GET ANGRY (kızmak), GET UPSET (üzülmek), GET EXCITED (heyecanlanmak)." },
      { type: "example", en: "Please don't get upset about this.", tr: "Lütfen bu konuda üzülme." },
      { type: "example", en: "The kids got so excited when they saw the presents.", tr: "Çocuklar hediyeleri görünce çok heyecanlandı." },
      { type: "rule", text: "Son olarak duygu ve kişilik sıfatlarını içeren karma bir tekrar bölümü görelim." },
      { type: "example", en: "Even though he's usually confident, he got really nervous before the interview.", tr: "Genelde özgüvenli olmasına rağmen, mülakattan önce gerçekten gerildi." },
      { type: "example", en: "She's not selfish at all; she's actually one of the most generous people I know.", tr: "O hiç bencil değil; aslında tanıdığım en cömert insanlardan biri." },
      { type: "rule", text: "Kişilik özelliklerini FEEL/BE + sıfat + PREPOSITION kalıplarıyla pekiştirelim: BE GOOD AT (iyi olmak), BE AFRAID OF (korkmak), BE FOND OF (sevmek, düşkün olmak)." },
      { type: "example", en: "She's really good at solving problems.", tr: "O sorun çözmede gerçekten iyi." },
      { type: "example", en: "I'm afraid of spiders.", tr: "Örümceklerden korkarım." },
      { type: "example", en: "He's very fond of his grandchildren.", tr: "O torunlarına çok düşkün." },
      { type: "rule", text: "Son olarak duygu ve kişilik sıfatlarını birleştiren uzun bir kapanış paragrafı görelim." },
      { type: "example", en: "Although she seemed calm and confident during the presentation, she later admitted that she had been extremely nervous the whole time.", tr: "Sunum sırasında sakin ve özgüvenli görünse de, daha sonra bütün zaman boyunca aşırı gergin olduğunu itiraf etti." },
      { type: "rule", text: "İnsanları tanımlarken kullanılan ek sıfatlar: DETERMINED (kararlı), FLEXIBLE (esnek), STUBBORN (inatçı), INDEPENDENT (bağımsız), SENSITIVE (hassas)." },
      { type: "example", en: "She's very determined to reach her goals.", tr: "O hedeflerine ulaşmak konusunda çok kararlı." },
      { type: "example", en: "Try to be more flexible about the schedule.", tr: "Program konusunda daha esnek olmaya çalış." },
      { type: "example", en: "He's quite sensitive about criticism.", tr: "O eleştiriler konusunda oldukça hassas." },
      { type: "rule", text: "Duygusal tepki bildiren fiiller: APPRECIATE (takdir etmek, değer vermek), MISS (özlemek), REGRET (pişman olmak)." },
      { type: "example", en: "I really appreciate your help.", tr: "Yardımın için gerçekten minnettarım." },
      { type: "example", en: "I miss my hometown so much.", tr: "Memleketimi çok özlüyorum." },
      { type: "example", en: "He regrets not studying harder in school.", tr: "Okulda daha çok çalışmadığına pişman." },
    ],
  },
  {
    fileBase: "30_Future_Perfect",
    title: "GELECEK ZAMANDAKİ GEÇMİŞ (FUTURE PERFECT)",
    blocks: [
      { type: "rule", text: "Bu tense; gelecekte belirli bir zamana kadar tamamlanmış olacak eylemleri anlatmak için kullanılır." },
      { type: "rule", text: "Yapı: Özne + WILL HAVE + Fiil (3. hal / V3). WILL HAVE bütün öznelerde aynı kalır." },
      { type: "pattern", text: "ÖZNE + WILL HAVE + V3" },
      { type: "example", en: "By next year, I will have finished my studies.", tr: "Gelecek yıla kadar eğitimimi bitirmiş olacağım." },
      { type: "example", en: "She will have left before you arrive.", tr: "Sen varmadan önce o gitmiş olacak." },
      { type: "example", en: "We will have moved to the new house by summer.", tr: "Yaza kadar yeni eve taşınmış olacağız." },
      { type: "rule", text: "Olumsuz yapı: Özne + WON'T HAVE + V3." },
      { type: "example", en: "They won't have finished the project by Friday.", tr: "Cuma gününe kadar projeyi bitirmemiş olacaklar." },
      { type: "example", en: "He won't have arrived by 6 pm.", tr: "Akşam 6'ya kadar varmamış olacak." },
      { type: "rule", text: "Soru yapısı: WILL + Özne + HAVE + V3?" },
      { type: "example", en: "Will you have completed the report by tomorrow?", tr: "Yarına kadar raporu tamamlamış olacak mısın?" },
      { type: "example", en: "Will they have decided by next week?", tr: "Gelecek haftaya kadar karar vermiş olacaklar mı?" },
      { type: "rule", text: "Future Perfect genellikle BY (kadar) ile birlikte belirli bir gelecek zaman noktası verilerek kullanılır: BY TOMORROW, BY NEXT WEEK, BY 2030." },
      { type: "example", en: "By 2030, they will have built the new bridge.", tr: "2030'a kadar yeni köprüyü inşa etmiş olacaklar." },
      { type: "rule", text: "Bu tense, gelecekteki bir olaydan ÖNCE başka bir şeyin tamamlanmış olacağını vurgular; yani \"gelecekteki geçmiş\" gibi düşünülebilir." },
      { type: "example", en: "When you call me, I will have already left.", tr: "Beni aradığında ben çoktan gitmiş olacağım." },
      { type: "example", en: "By the time you wake up, I will have made breakfast.", tr: "Sen uyandığında ben kahvaltı hazırlamış olacağım." },
      { type: "rule", text: "Future Perfect ile Future Simple arasındaki fark: Future Simple bir eylemin gelecekte yapılacağını, Future Perfect ise o eylemin belirli bir zamana kadar TAMAMLANMIŞ olacağını anlatır." },
      { type: "example", en: "I will finish the report tomorrow. (Future Simple) / I will have finished the report by tomorrow. (Future Perfect)", tr: "Raporu yarın bitireceğim. / Yarına kadar raporu bitirmiş olacağım." },
      { type: "rule", text: "Bu tense genellikle iş, eğitim ve proje planlamasında belirli bir teslim tarihine (deadline) atıfta bulunmak için kullanılır." },
      { type: "example", en: "The workers will have completed the building by next spring.", tr: "İşçiler gelecek bahara kadar binayı tamamlamış olacaklar." },
      { type: "example", en: "By the time she is thirty, she will have earned her doctorate.", tr: "Otuz yaşına geldiğinde, doktorasını almış olacak." },
      { type: "rule", text: "Kısaltma: konuşma dilinde WILL HAVE genellikle 'LL HAVE olarak kısaltılır." },
      { type: "example", en: "We'll have moved out by the end of the month.", tr: "Ay sonuna kadar taşınmış olacağız." },
      { type: "rule", text: "\"BUILD\" fiili üzerinden tam çekim tablosunu görelim." },
      { type: "pattern", text: "TAM ÇEKİM: BUILD (İNŞA ETMEK)" },
      { type: "example", en: "I will have built my own house by the time I'm forty.", tr: "Kırk yaşıma geldiğimde kendi evimi inşa etmiş olacağım." },
      { type: "example", en: "You will have built a strong reputation by then.", tr: "O zamana kadar güçlü bir itibar inşa etmiş olacaksın." },
      { type: "example", en: "She will have built her own company within five years.", tr: "Beş yıl içinde kendi şirketini kurmuş olacak." },
      { type: "rule", text: "Olumsuz ve soru çekimlerini görelim." },
      { type: "example", en: "We won't have built the new office by then.", tr: "O zamana kadar yeni ofisi inşa etmemiş olacağız." },
      { type: "example", en: "Will they have built the bridge by 2027?", tr: "2027'ye kadar köprüyü inşa etmiş olacaklar mı?" },
      { type: "rule", text: "Future Perfect, hayattaki dönüm noktalarına atıfta bulunurken sıkça kullanılır: belirli bir yaşa gelene kadar neyin başarılmış olacağı gibi." },
      { type: "example", en: "By the time I retire, I will have worked here for thirty years.", tr: "Emekli olduğumda burada otuz yıl çalışmış olacağım." },
      { type: "example", en: "By 2030, scientists will have found a cure for many diseases.", tr: "2030'a kadar bilim insanları birçok hastalığa çare bulmuş olacak." },
      { type: "rule", text: "ALREADY, Future Perfect ile birlikte bir eylemin belirtilen zamandan önce bile tamamlanmış olacağını vurgular." },
      { type: "example", en: "By the time you get here, I will have already left for the airport.", tr: "Sen buraya geldiğinde ben havaalanına gitmek için çoktan ayrılmış olacağım." },
      { type: "rule", text: "Sık yapılan bir hata, Future Perfect yerine sadece Future Simple kullanmaktır; bu, \"belirli bir zamana kadar tamamlanmış olma\" anlamını kaybettirir." },
      { type: "example", en: "By next month, I will have finished this course. (DOĞRU) — NOT: By next month, I will finish this course. (eksik anlam)", tr: "Gelecek aya kadar bu kursu bitirmiş olacağım." },
      { type: "rule", text: "Son olarak Future Perfect'i pekiştiren bir soru-cevap alıştırması ve kapanış cümlesi görelim." },
      { type: "example", en: "Will you have graduated by next summer? — Yes, I will have graduated by then, and I'll be looking for a job.", tr: "Gelecek yaza kadar mezun olmuş olacak mısın? — Evet, o zamana kadar mezun olmuş olacağım ve iş arıyor olacağım." },
      { type: "example", en: "By the end of this decade, technology will have changed our daily lives in ways we can't even imagine today.", tr: "Bu on yılın sonuna kadar teknoloji günlük hayatlarımızı bugün hayal bile edemeyeceğimiz şekillerde değiştirmiş olacak." },
      { type: "rule", text: "Future Perfect, bir eylemin belirli bir sayıya/miktara ulaşacağını belirtirken de kullanılır: sayılar, tekrarlar, deneyimler." },
      { type: "example", en: "By the end of this year, I will have read twenty books.", tr: "Bu yılın sonuna kadar yirmi kitap okumuş olacağım." },
      { type: "example", en: "By the time she turns eighteen, she will have visited ten countries.", tr: "On sekiz yaşına geldiğinde on ülke ziyaret etmiş olacak." },
      { type: "rule", text: "HOW LONG WILL YOU HAVE + V3 kalıbı, gelecekteki bir noktaya kadar geçecek toplam süreyi sormak için kullanılır." },
      { type: "example", en: "How long will you have worked here by the end of this year?", tr: "Bu yılın sonuna kadar burada ne kadar süre çalışmış olacaksın?" },
      { type: "example", en: "By December, I will have worked here for exactly five years.", tr: "Aralık'a kadar burada tam olarak beş yıl çalışmış olacağım." },
      { type: "rule", text: "Future Perfect, bir tahmin ya da varsayımı geçmişe dönük olarak ifade etmek için de kullanılabilir (MUST HAVE'e benzer bir mantıkla, ama gelecek için)." },
      { type: "example", en: "She will have heard the news by now, I'm sure.", tr: "Eminim şimdiye kadar haberi duymuştur." },
      { type: "rule", text: "Son olarak Future Perfect'i pekiştiren uzun bir kapanış örneği görelim." },
      { type: "example", en: "By the time this project is finished, we will have spent almost a year planning, building, and testing every single feature.", tr: "Bu proje bittiğinde, her bir özelliği planlamak, geliştirmek ve test etmek için neredeyse bir yıl harcamış olacağız." },
      { type: "rule", text: "Future Perfect, geçmişten bugüne kadar ve bugünden geleceğe kadar olan iki dönemi karşılaştırırken de kullanılır." },
      { type: "example", en: "I have lived here for five years, and by next year I will have lived here for six.", tr: "Burada beş yıldır yaşıyorum ve gelecek yıla kadar altı yıl yaşamış olacağım." },
      { type: "rule", text: "Future Perfect'in olumsuz sorusu, birinin bir şeyi tamamlayıp tamamlamayacağından şüphe duyulduğunda kullanılabilir." },
      { type: "example", en: "Won't they have finished the renovation by the wedding?", tr: "Düğüne kadar tadilatı bitirmemiş olacaklar mı?" },
      { type: "rule", text: "Bu tense, uzun vadeli hedefleri ve kariyer planlarını anlatırken çok kullanışlıdır." },
      { type: "example", en: "By the time I'm thirty-five, I will have opened my own business.", tr: "Otuz beş yaşıma geldiğimde kendi işimi açmış olacağım." },
      { type: "example", en: "By next semester, she will have completed all her required courses.", tr: "Gelecek döneme kadar bütün zorunlu derslerini tamamlamış olacak." },
      { type: "rule", text: "\"SAVE\" fiili üzerinden ek bir çekim örneği daha görelim, para biriktirme hedefleriyle." },
      { type: "pattern", text: "TAM ÇEKİM: SAVE (BİRİKTİRMEK)" },
      { type: "example", en: "I will have saved enough money by next summer to buy a car.", tr: "Gelecek yaza kadar araba almak için yeterli para biriktirmiş olacağım." },
      { type: "example", en: "They will have saved a lot by cutting unnecessary expenses.", tr: "Gereksiz giderleri keserek çok tasarruf etmiş olacaklar." },
      { type: "rule", text: "Future Perfect'i pekiştiren son bir soru-cevap alıştırması görelim." },
      { type: "example", en: "Will you have paid off your debt by the end of the year? — Yes, I will have paid it all off by December.", tr: "Yıl sonuna kadar borcunu ödemiş olacak mısın? — Evet, Aralık'a kadar hepsini ödemiş olacağım." },
      { type: "example", en: "By the time we celebrate our anniversary, we will have been married for exactly ten years.", tr: "Yıl dönümümüzü kutladığımızda, tam olarak on yıldır evli olmuş olacağız." },
      { type: "rule", text: "Future Perfect, iddialı hedefler ve büyük projeler hakkında konuşurken sıklıkla WILL HAVE + V3 + BY THE TIME/BY THEN kalıplarıyla kurulur." },
      { type: "example", en: "By the time the conference starts, we will have set up all the equipment.", tr: "Konferans başladığında bütün ekipmanı kurmuş olacağız." },
      { type: "example", en: "By next week, the whole team will have reviewed the final draft.", tr: "Gelecek haftaya kadar bütün ekip son taslağı incelemiş olacak." },
      { type: "rule", text: "Future Perfect, bir eylemin tamamlanma yüzdesini ya da aşamasını belirtirken de kullanılabilir." },
      { type: "example", en: "By the end of the week, we will have completed eighty percent of the work.", tr: "Hafta sonuna kadar işin yüzde seksenini tamamlamış olacağız." },
      { type: "rule", text: "Son olarak Future Perfect'in gerçek hayattaki kullanımını gösteren uzun bir örnek görelim." },
      { type: "example", en: "By the time she finishes university, she will have studied abroad twice, completed three internships, and learned two foreign languages.", tr: "Üniversiteyi bitirdiğinde, iki kez yurt dışında okumuş, üç staj tamamlamış ve iki yabancı dil öğrenmiş olacak." },
      { type: "rule", text: "BY THE TIME + Present Simple kalıbı gelecekteki bir noktayı belirtirken, ana cümlede Future Perfect kullanılır; BY THE TIME + Past Simple kullanıldığında ise ana cümlede Past Perfect kullanılır." },
      { type: "example", en: "By the time we finish this course, we will have covered all twelve tenses.", tr: "Bu kursu bitirdiğimizde on iki zamanın hepsini işlemiş olacağız." },
      { type: "example", en: "By the time you read this message, I will have already boarded the plane.", tr: "Bu mesajı okuduğunda ben uçağa çoktan binmiş olacağım." },
      { type: "rule", text: "Future Perfect, bir dizi olayın gelecekteki sırasını netleştirmek için de kullanılır: hangi eylem hangi eylemden önce tamamlanmış olacak." },
      { type: "example", en: "By the time the sun rises, the bakers will have already baked hundreds of loaves of bread.", tr: "Güneş doğduğunda, fırıncılar çoktan yüzlerce ekmek pişirmiş olacak." },
      { type: "rule", text: "Future Perfect, garanti ya da kesinlik ifade eden BY ALL MEANS, DEFINITELY, CERTAINLY gibi zarflarla güçlendirilebilir." },
      { type: "example", en: "By next year, they will definitely have finished the construction.", tr: "Gelecek yıla kadar inşaatı kesinlikle bitirmiş olacaklar." },
      { type: "rule", text: "Future Perfect'in olumsuz hâli, bir eylemin belirtilen zamana kadar tamamlanmayacağını vurgulayarak bir tür uyarı ya da endişe ifade edebilir." },
      { type: "example", en: "If we don't hurry, we won't have finished by the deadline.", tr: "Acele etmezsek, son teslim tarihine kadar bitirmemiş olacağız." },
      { type: "rule", text: "Bu tense, akademik ve bilimsel metinlerde de gelecekteki araştırma sonuçlarını öngörmek için kullanılır." },
      { type: "example", en: "By 2050, researchers will have developed new treatments for many currently incurable diseases.", tr: "2050'ye kadar araştırmacılar şu anda tedavisi olmayan birçok hastalık için yeni tedaviler geliştirmiş olacak." },
    ],
  },
  {
    fileBase: "31_Is_ve_Gunluk_Yasam",
    title: "İŞ VE GÜNLÜK YAŞAM KALIPLARI",
    blocks: [
      { type: "pattern", text: "HARDWORKING = çalışkan / LAZY = tembel / BUSY = meşgul / AVAILABLE = müsait" },
      { type: "example", en: "If you aren't available, we will not come today.", tr: "Müsait değilsen, bugün gelmeyeceğiz." },
      { type: "example", en: "We must be more hardworking.", tr: "Daha çalışkan olmalıyız." },
      { type: "pattern", text: "UNTIL = -e kadar" },
      { type: "example", en: "We are going to be busy until tomorrow.", tr: "Yarına kadar meşgul olacağız." },
      { type: "pattern", text: "DRIVE = araba kullanmak / CAREFULLY = dikkatlice / ENTER = GET IN = COME IN = girmek" },
      { type: "example", en: "Don't worry, he drives carefully.", tr: "Merak etme, o dikkatli sürer." },
      { type: "example", en: "Inform me when you get in.", tr: "İçeri girdiğinde bana haber ver." },
      { type: "pattern", text: "ENTERPRISE = VENTURE = girişim / JOINT VENTURE = ortak girişim / ENTREPRENEUR = girişimci / GATHER = toplanmak" },
      { type: "example", en: "The entrepreneurs gathered for a new project.", tr: "Girişimciler yeni proje için toplandı." },
      { type: "example", en: "That enterprise is very important for them.", tr: "O girişim onlar için çok önemli." },
      { type: "pattern", text: "PREPARE = hazırlamak / GET READY = hazırlanmak / PREPARED = hazır" },
      { type: "example", en: "The dinner is prepared by him.", tr: "Yemek onun tarafından hazırlanıyor." },
      { type: "example", en: "When should we get ready?", tr: "Ne zaman hazırlanmalıyız?" },
      { type: "pattern", text: "SIMILAR = benzer / REALLY = gerçekten" },
      { type: "example", en: "We made similar mistakes.", tr: "Benzer hatalar yaptık." },
      { type: "example", en: "Do you really want to talk to me?", tr: "Gerçekten benimle konuşmak istiyor musun?" },
      { type: "pattern", text: "RAISE = zam, arttırmak / ELECT = seçmek / ELECTIONS = seçimler / PRESIDENT = cumhurbaşkanı / GOVERNMENT = hükümet" },
      { type: "example", en: "People prepare to elect the president.", tr: "Halk cumhurbaşkanını seçmeye hazırlanıyor." },
      { type: "example", en: "I don't think that he deserves the raise.", tr: "Zammı hak ettiğini düşünmüyorum." },
      { type: "pattern", text: "QUALITY = kalite / SMOKE = sigara içmek / SHARE = paylaşmak, hisse" },
      { type: "example", en: "I have no doubt of the quality of goods.", tr: "Malların kalitesinden şüphem yok." },
      { type: "example", en: "I can't share it with anyone.", tr: "Bunu kimseyle paylaşamam." },
      { type: "rule", text: "ON (açık, çalışmakta) / OFF (kapalı) yalın hâlde. TURN ON / SWITCH ON (açmak), TURN OFF / SWITCH OFF (kapatmak) fiil hâlleridir." },
      { type: "example", en: "Is the tv on?", tr: "Televizyon açık mı?" },
      { type: "example", en: "Why don't you turn off the lights when you leave the house?", tr: "Evden çıkarken ışıkları neden kapatmıyorsun?" },
      { type: "example", en: "He forgot to switch on his phone.", tr: "O telefonunu açmayı unuttu." },
      { type: "pattern", text: "HURRY UP = acele etmek / OTHERWISE = aksi takdirde, yoksa" },
      { type: "example", en: "Hurry up! Otherwise, we will miss the plane.", tr: "Acele et! Yoksa uçağı kaçıracağız." },
      { type: "example", en: "Work hard! Otherwise, you may regret it.", tr: "Sıkı çalış! Yoksa pişman olabilirsin." },
      { type: "pattern", text: "MIND = akıl, aldırış etmek / CHANGE MIND = fikir değiştirmek / NEVER MIND! = boşver!" },
      { type: "example", en: "Why don't you change your mind?", tr: "Neden fikrini değiştirmiyorsun?" },
      { type: "pattern", text: "IT DOESN'T MAKE SENSE! = mantıklı değil, saçma / SENSE = duyu, anlam" },
      { type: "pattern", text: "SAFE AND SOUND = sağ salim / MAKE A LIVING = geçinmek" },
      { type: "example", en: "Did you arrive at home safe and sound?", tr: "Eve sağ salim vardın mı?" },
      { type: "example", en: "Can you make a living in London?", tr: "Londra'da geçinebilir misin?" },
      { type: "pattern", text: "COME BACK = BE BACK = RETURN = dönmek / OWE = borçlu olmak" },
      { type: "example", en: "How much does he owe you?", tr: "Sana ne kadar borcu var?" },
      { type: "example", en: "He returned because he couldn't make a living in Paris.", tr: "Paris'te geçinemediği için döndü." },
      { type: "pattern", text: "EACH OTHER = birbiri / FOR A LONG TIME = uzun zamandır" },
      { type: "example", en: "We didn't see each other for a long time.", tr: "Uzun zamandır birbirimizi görmedik." },
      { type: "example", en: "Don't they know each other?", tr: "Onlar birbirini tanımıyor mu?" },
      { type: "rule", text: "İş yerinde kullanılan kalıplar: MEET A DEADLINE (son teslim tarihine yetişmek), TAKE ON A PROJECT (bir proje üstlenmek), GET PROMOTED (terfi almak)." },
      { type: "example", en: "We need to meet this deadline no matter what.", tr: "Ne olursa olsun bu son teslim tarihine yetişmemiz gerekiyor." },
      { type: "example", en: "She got promoted after only one year at the company.", tr: "Şirkette sadece bir yıl sonra terfi aldı." },
      { type: "example", en: "He decided to take on a new project this month.", tr: "Bu ay yeni bir proje üstlenmeye karar verdi." },
      { type: "rule", text: "Toplantı ve iletişimle ilgili kalıplar: SCHEDULE A MEETING (toplantı planlamak), TAKE MINUTES (tutanak tutmak), BRING UP A TOPIC (bir konuyu gündeme getirmek)." },
      { type: "example", en: "Can you schedule a meeting for Thursday?", tr: "Perşembe için bir toplantı planlayabilir misin?" },
      { type: "example", en: "Who is going to take the minutes today?", tr: "Bugün tutanağı kim tutacak?" },
      { type: "example", en: "I'd like to bring up a different topic.", tr: "Farklı bir konuyu gündeme getirmek istiyorum." },
      { type: "rule", text: "Günlük yaşamda ev ve alışkanlık ile ilgili kalıplar: GET USED TO (alışmak), BE USED TO (alışkın olmak), USED TO (eskiden yapardı)." },
      { type: "pattern", text: "USED TO + V1 = eskiden ...irdi   |   BE USED TO + V-ing/isim = ...e alışkın olmak   |   GET USED TO + V-ing/isim = ...e alışmak" },
      { type: "example", en: "I used to live in a small village.", tr: "Eskiden küçük bir köyde yaşardım." },
      { type: "example", en: "She is used to working long hours.", tr: "O uzun saatler çalışmaya alışkın." },
      { type: "example", en: "It took me a while to get used to the new schedule.", tr: "Yeni programa alışmam biraz zaman aldı." },
      { type: "rule", text: "İş görüşmesi ve kariyer ile ilgili kalıplar: APPLY FOR A JOB (işe başvurmak), JOB INTERVIEW (iş görüşmesi), RESUME/CV (özgeçmiş), QUALIFICATIONS (nitelikler)." },
      { type: "example", en: "I applied for three jobs this week.", tr: "Bu hafta üç işe başvurdum." },
      { type: "example", en: "Don't forget to bring your resume to the interview.", tr: "Görüşmeye özgeçmişini getirmeyi unutma." },
      { type: "example", en: "Do you have the qualifications for this position?", tr: "Bu pozisyon için gerekli niteliklere sahip misin?" },
      { type: "rule", text: "Zaman yönetimi ile ilgili kalıplar: PRIORITIZE (önceliklendirmek), PROCRASTINATE (ertelemek), MULTITASK (birden fazla iş yapmak)." },
      { type: "example", en: "You need to prioritize your tasks better.", tr: "Görevlerini daha iyi önceliklendirmen gerekiyor." },
      { type: "example", en: "Stop procrastinating and start working!", tr: "Ertelemeyi bırak ve çalışmaya başla!" },
      { type: "example", en: "I can't multitask when I'm this tired.", tr: "Bu kadar yorgunken birden fazla iş yapamıyorum." },
      { type: "rule", text: "Günlük yaşamda sıkça karşılaşılan diğer kalıplar: RUN ERRANDS (işleri halletmek), BE ON A TIGHT BUDGET (dar bütçeyle yaşamak), TREAT YOURSELF (kendine iyi bakmak, kendine bir şey ısmarlamak)." },
      { type: "example", en: "I have to run some errands this afternoon.", tr: "Bu öğleden sonra bazı işlerimi halletmem gerekiyor." },
      { type: "example", en: "We're on a tight budget this month.", tr: "Bu ay dar bir bütçeyle yaşıyoruz." },
      { type: "example", en: "You've worked so hard, treat yourself to something nice.", tr: "Çok çalıştın, kendine güzel bir şey ısmarla." },
      { type: "rule", text: "Son olarak bu dersteki iş ve günlük yaşam kalıplarını içeren bir kapanış diyaloğu görelim." },
      { type: "example", en: "How's your new job going? — Pretty well, although I'm still getting used to the early mornings and tight deadlines.", tr: "Yeni işin nasıl gidiyor? — Oldukça iyi, gerçi hâlâ erken sabahlara ve sıkı son teslim tarihlerine alışmaya çalışıyorum." },
      { type: "example", en: "Are you free this weekend? — Not really, I need to run some errands and prepare for Monday's meeting.", tr: "Bu hafta sonu müsait misin? — Pek değil, bazı işlerimi halletmem ve Pazartesi toplantısına hazırlanmam gerekiyor." },
      { type: "rule", text: "İş-yaşam dengesi ile ilgili kalıplar: WORK-LIFE BALANCE (iş-yaşam dengesi), BURN OUT (tükenmek), TAKE A DAY OFF (izin almak)." },
      { type: "example", en: "It's important to maintain a good work-life balance.", tr: "İyi bir iş-yaşam dengesi sürdürmek önemli." },
      { type: "example", en: "I need to take a day off this week, I'm exhausted.", tr: "Bu hafta bir gün izin almam gerekiyor, bitkinim." },
      { type: "example", en: "Ever since I started prioritizing my tasks, I've been able to maintain a much better work-life balance.", tr: "Görevlerimi önceliklendirmeye başladığımdan beri, çok daha iyi bir iş-yaşam dengesi sürdürebiliyorum." },
      { type: "rule", text: "İş yerinde performans ve geri bildirimle ilgili kalıplar: GIVE FEEDBACK (geri bildirim vermek), PERFORMANCE REVIEW (performans değerlendirmesi), IMPROVE (gelişmek)." },
      { type: "example", en: "My manager gave me some useful feedback yesterday.", tr: "Müdürüm dün bana faydalı bir geri bildirim verdi." },
      { type: "example", en: "I have a performance review next month.", tr: "Gelecek ay performans değerlendirmem var." },
      { type: "example", en: "You've really improved over the past few months.", tr: "Son birkaç ayda gerçekten geliştin." },
      { type: "rule", text: "Ekip çalışması ile ilgili kalıplar: TEAMWORK (ekip çalışması), COLLABORATE (iş birliği yapmak), SUPPORT EACH OTHER (birbirini desteklemek)." },
      { type: "example", en: "Good teamwork made this project a success.", tr: "İyi ekip çalışması bu projeyi başarılı kıldı." },
      { type: "example", en: "We need to collaborate more closely with the design team.", tr: "Tasarım ekibiyle daha yakın işbirliği yapmamız gerekiyor." },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
