import { publishQuiz, prisma, QuizDef } from "./lib/quiz-lib";

const ZAMANLAR = "İngilizce - Zamanlar";
const KELIME = "İngilizce - Kelime ve Kalıplar";

const quizzes: QuizDef[] = [
  {
    title: "24 Karma Kalıplar - 3 - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "CHEER UP ne anlama gelir?", optionA: "Üzmek", optionB: "Neşelendirmek", optionC: "Kızdırmak", optionD: "Korkutmak", correct: "B" },
      { prompt: "KEEP IN TOUCH ne anlama gelir?", optionA: "İletişimi kesmek", optionB: "İletişimde kalmak", optionC: "Unutmak", optionD: "Kaçmak", correct: "B" },
      { prompt: "BE GOOD AT ne anlama gelir?", optionA: "-de iyi olmak", optionB: "-den korkmak", optionC: "-e alışkın olmak", optionD: "-i sevmemek", correct: "A" },
      { prompt: "OUT OF ORDER ne anlama gelir?", optionA: "Çalışıyor", optionB: "Bozuk, arızalı", optionC: "Yeni", optionD: "Temiz", correct: "B" },
      { prompt: "LET fiili ne anlama gelir?", optionA: "Yasaklamak", optionB: "İzin vermek", optionC: "Zorlamak", optionD: "Reddetmek", correct: "B" },
      { prompt: "DEPEND ON ne anlama gelir?", optionA: "Bağlı olmak", optionB: "Bağımsız olmak", optionC: "Reddetmek", optionD: "Kabul etmek", correct: "A" },
      { prompt: "CALM DOWN ne anlama gelir?", optionA: "Sinirlenmek", optionB: "Sakinleşmek", optionC: "Heyecanlanmak", optionD: "Korkmak", correct: "B" },
      { prompt: "TAKE AFTER ne anlama gelir?", optionA: "Benzemek", optionB: "Farklı olmak", optionC: "Takip etmek", optionD: "Kaçmak", correct: "A" },
      { prompt: "FALL ASLEEP ne anlama gelir?", optionA: "Uyanmak", optionB: "Uyuyakalmak", optionC: "Kalkmak", optionD: "Yorulmak", correct: "B" },
      { prompt: "FALL IN LOVE WITH ne anlama gelir?", optionA: "Nefret etmek", optionB: "Aşık olmak", optionC: "Unutmak", optionD: "Kızmak", correct: "B" },
      { prompt: "HARMFUL ne anlama gelir?", optionA: "Zararsız", optionB: "Zararlı", optionC: "Faydalı", optionD: "Güvenli", correct: "B" },
      { prompt: "BE ABOUT TO ne anlama gelir?", optionA: "-meyi bitirmiş olmak", optionB: "-mek üzere olmak", optionC: "-meyi düşünmek", optionD: "-meyi istememek", correct: "B" },
      { prompt: "SET OUT / HIT THE ROAD ne anlama gelir?", optionA: "Yola çıkmak", optionB: "Eve dönmek", optionC: "Durmak", optionD: "Beklemek", correct: "A" },
      { prompt: "OVERCOME ne anlama gelir?", optionA: "Kaçmak", optionB: "Üstesinden gelmek", optionC: "Vazgeçmek", optionD: "Kaybetmek", correct: "B" },
      { prompt: "CARRY OUT ne anlama gelir?", optionA: "Gerçekleştirmek", optionB: "İptal etmek", optionC: "Ertelemek", optionD: "Unutmak", correct: "A" },
      { prompt: "GET PROMOTED ne anlama gelir?", optionA: "Kovulmak", optionB: "Terfi etmek", optionC: "İşe girmek", optionD: "İstifa etmek", correct: "B" },
      { prompt: "SET UP ne anlama gelir?", optionA: "Kapatmak", optionB: "Kurmak", optionC: "Yıkmak", optionD: "Satmak", correct: "B" },
      { prompt: "GIVE UP ne anlama gelir?", optionA: "Devam etmek", optionB: "Vazgeçmek", optionC: "Başlamak", optionD: "Kazanmak", correct: "B" },
      { prompt: "LOOK INTO ne anlama gelir?", optionA: "Görmezden gelmek", optionB: "Araştırmak, incelemek", optionC: "Unutmak", optionD: "Reddetmek", correct: "B" },
      { prompt: "PUT OFF ne anlama gelir?", optionA: "Hemen yapmak", optionB: "Ertelemek", optionC: "Bitirmek", optionD: "Başlamak", correct: "B" },
    ],
  },
  {
    title: "25 Karma Kalıplar - 4 - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "BLAME ne anlama gelir?", optionA: "Övmek", optionB: "Suçlamak", optionC: "Affetmek", optionD: "Desteklemek", correct: "B" },
      { prompt: "PRODUCE ne anlama gelir?", optionA: "Tüketmek", optionB: "Üretmek", optionC: "Satmak", optionD: "Almak", correct: "B" },
      { prompt: "CONSUME ne anlama gelir?", optionA: "Üretmek", optionB: "Tüketmek", optionC: "Saklamak", optionD: "Satmak", correct: "B" },
      { prompt: "DUE TO ne anlama gelir?", optionA: "-e rağmen", optionB: "-den dolayı, nedeniyle", optionC: "-e kadar", optionD: "-den önce", correct: "B" },
      { prompt: "GRATEFUL ne anlama gelir?", optionA: "Nankör", optionB: "Minnettar", optionC: "Kızgın", optionD: "Şaşkın", correct: "B" },
      { prompt: "QUIT SMOKING ne anlama gelir?", optionA: "Sigaraya başlamak", optionB: "Sigarayı bırakmak", optionC: "Sigara içmek", optionD: "Sigara almak", correct: "B" },
      { prompt: "TEMPORARY ne anlama gelir?", optionA: "Kalıcı", optionB: "Geçici", optionC: "Sonsuz", optionD: "Ani", correct: "B" },
      { prompt: "PERMANENT ne anlama gelir?", optionA: "Geçici", optionB: "Kalıcı", optionC: "Ani", optionD: "Kısa süreli", correct: "B" },
      { prompt: "PROVIDING THAT ne anlama gelir?", optionA: "-mesi şartıyla", optionB: "-mesine rağmen", optionC: "-meden önce", optionD: "-dığı için", correct: "A" },
      { prompt: "BE OBSESSED WITH ne anlama gelir?", optionA: "Nefret etmek", optionB: "Takıntılı olmak", optionC: "Sıkılmak", optionD: "Korkmak", correct: "B" },
      { prompt: "INTERRUPT ne anlama gelir?", optionA: "Dinlemek", optionB: "Sözünü kesmek", optionC: "Devam etmek", optionD: "Sessiz kalmak", correct: "B" },
      { prompt: "EXHAUSTED ne anlama gelir?", optionA: "Dinlenmiş", optionB: "Bitkin, aşırı yorgun", optionC: "Heyecanlı", optionD: "Mutlu", correct: "B" },
      { prompt: "WILLING ne anlama gelir?", optionA: "İsteksiz", optionB: "İstekli", optionC: "Kararsız", optionD: "Yorgun", correct: "B" },
      { prompt: "RELUCTANT ne anlama gelir?", optionA: "İstekli", optionB: "İsteksiz", optionC: "Emin", optionD: "Meraklı", correct: "B" },
      { prompt: "DILIGENT ne anlama gelir?", optionA: "Tembel", optionB: "Çalışkan", optionC: "Yavaş", optionD: "Dikkatsiz", correct: "B" },
      { prompt: "PERSEVERANCE ne anlama gelir?", optionA: "Vazgeçme", optionB: "Azim, sebat", optionC: "Tembellik", optionD: "Korku", correct: "B" },
      { prompt: "APPOINT ne anlama gelir?", optionA: "Kovmak", optionB: "Atamak, görevlendirmek", optionC: "İşten çıkarmak", optionD: "Reddetmek", correct: "B" },
      { prompt: "IMMEDIATELY ne anlama gelir?", optionA: "Sonra", optionB: "Hemen, derhal", optionC: "Asla", optionD: "Bazen", correct: "B" },
      { prompt: "INTERFERE WITH ne anlama gelir?", optionA: "Yardım etmek", optionB: "Karışmak, müdahale etmek", optionC: "Desteklemek", optionD: "Kabul etmek", correct: "B" },
      { prompt: "CANDIDATE ne anlama gelir?", optionA: "Aday", optionB: "Kazanan", optionC: "Kaybeden", optionD: "Yönetici", correct: "A" },
    ],
  },
  {
    title: "26 Karma Kalıplar - 5 - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "OWNER ne anlama gelir?", optionA: "Çalışan", optionB: "Sahip", optionC: "Müşteri", optionD: "Misafir", correct: "B" },
      { prompt: "LOYAL ne anlama gelir?", optionA: "Sadık", optionB: "Hain", optionC: "Bencil", optionD: "Kararsız", correct: "A" },
      { prompt: "DEDICATE ne anlama gelir?", optionA: "Adamak", optionB: "Terk etmek", optionC: "Unutmak", optionD: "Reddetmek", correct: "A" },
      { prompt: "BEYOND ne anlama gelir?", optionA: "Önünde", optionB: "Ötesinde", optionC: "İçinde", optionD: "Altında", correct: "B" },
      { prompt: "ANNOUNCE ne anlama gelir?", optionA: "Gizlemek", optionB: "Duyurmak, açıklamak", optionC: "Unutmak", optionD: "Reddetmek", correct: "B" },
      { prompt: "ARREST ne anlama gelir?", optionA: "Serbest bırakmak", optionB: "Tutuklamak", optionC: "Affetmek", optionD: "Ödüllendirmek", correct: "B" },
      { prompt: "RETAIN ne anlama gelir?", optionA: "Kaybetmek", optionB: "Tutmak, kaybetmemek", optionC: "Vermek", optionD: "Satmak", correct: "B" },
      { prompt: "BENEFICIAL ne anlama gelir?", optionA: "Zararlı", optionB: "Yararlı", optionC: "Gereksiz", optionD: "Pahalı", correct: "B" },
      { prompt: "TAKE ADVANTAGE OF ne anlama gelir?", optionA: "Faydalanmak/istismar etmek", optionB: "Zarar vermek", optionC: "Yardım etmek", optionD: "Unutmak", correct: "A" },
      { prompt: "IN PRINCIPLE ne anlama gelir?", optionA: "Prensipte", optionB: "Asla", optionC: "Kesinlikle", optionD: "Hiçbir zaman", correct: "A" },
      { prompt: "BREATHE ne anlama gelir?", optionA: "Koşmak", optionB: "Nefes almak", optionC: "Uyumak", optionD: "Yemek", correct: "B" },
      { prompt: "OUT OF BREATH ne anlama gelir?", optionA: "Rahat", optionB: "Nefes nefese", optionC: "Sakin", optionD: "Yorgun değil", correct: "B" },
      { prompt: "PROS AND CONS ne anlama gelir?", optionA: "Artılar ve eksiler", optionB: "Sorular ve cevaplar", optionC: "Başlangıç ve son", optionD: "Sebep ve sonuç", correct: "A" },
      { prompt: "MAKE A HABIT OF ne anlama gelir?", optionA: "Alışkanlık haline getirmek", optionB: "Alışkanlığı bırakmak", optionC: "Unutmak", optionD: "Reddetmek", correct: "A" },
      { prompt: "FULFILL ne anlama gelir?", optionA: "İptal etmek", optionB: "Yerine getirmek", optionC: "Ertelemek", optionD: "Reddetmek", correct: "B" },
      { prompt: "ON BEHALF OF ne anlama gelir?", optionA: "-e karşı", optionB: "-in adına", optionC: "-den önce", optionD: "-e rağmen", correct: "B" },
      { prompt: "CONFIDENT ne anlama gelir?", optionA: "Kararsız", optionB: "Kendinden emin", optionC: "Korkak", optionD: "Şüpheli", correct: "B" },
      { prompt: "CAUTIOUS ne anlama gelir?", optionA: "Dikkatsiz", optionB: "Tedbirli, dikkatli", optionC: "Cesur", optionD: "Aceleci", correct: "B" },
      { prompt: "USE UP ne anlama gelir?", optionA: "Biriktirmek", optionB: "Tüketmek, bitirmek", optionC: "Saklamak", optionD: "Paylaşmak", correct: "B" },
      { prompt: "WHETHER ne anlama gelir?", optionA: "-olup olmadığı", optionB: "-dığı için", optionC: "-meden önce", optionD: "-dığı sürece", correct: "A" },
    ],
  },
  {
    title: "27 Karma Kalıplar - 6 - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "RUN INTO ne anlama gelir?", optionA: "Kaçmak", optionB: "Tesadüfen karşılaşmak", optionC: "Aramak", optionD: "Kaybolmak", correct: "B" },
      { prompt: "SOLD-OUT ne anlama gelir?", optionA: "Yeni gelmiş", optionB: "Tükenmiş", optionC: "İndirimde", optionD: "Ücretsiz", correct: "B" },
      { prompt: "TURN DOWN ne anlama gelir?", optionA: "Kabul etmek", optionB: "Reddetmek", optionC: "Açmak", optionD: "Yükseltmek", correct: "B" },
      { prompt: "MAY-1'in kullanımı nedir?", optionA: "Kibar rica", optionB: "İzin, olasılık", optionC: "Geçmiş yetenek", optionD: "Zorunluluk", correct: "B" },
      { prompt: "MAY-2'nin kullanımı nedir?", optionA: "Kibar soru/izin", optionB: "Geçmiş yetenek", optionC: "Zorunluluk", optionD: "Tavsiye", correct: "A" },
      { prompt: "VIOLATE ne anlama gelir?", optionA: "Uymak", optionB: "İhlal etmek", optionC: "Desteklemek", optionD: "Onaylamak", correct: "B" },
      { prompt: "FORBID ne anlama gelir?", optionA: "İzin vermek", optionB: "Yasaklamak", optionC: "Tavsiye etmek", optionD: "Önermek", correct: "B" },
      { prompt: "SUSTAINABLE ne anlama gelir?", optionA: "Sürdürülemez", optionB: "Sürdürülebilir", optionC: "Geçici", optionD: "Ani", correct: "B" },
      { prompt: "COLLEAGUE ne anlama gelir?", optionA: "Patron", optionB: "İş arkadaşı", optionC: "Müşteri", optionD: "Rakip", correct: "B" },
      { prompt: "THRIFTY ne anlama gelir?", optionA: "Savurgan", optionB: "Tutumlu", optionC: "Cömert", optionD: "Bencil", correct: "B" },
      { prompt: "PUBLISH ne anlama gelir?", optionA: "Yazmak", optionB: "Yayınlamak, basmak", optionC: "Okumak", optionD: "Silmek", correct: "B" },
      { prompt: "VARIETY ne anlama gelir?", optionA: "Tek tip", optionB: "Çeşitlilik", optionC: "Azlık", optionD: "Benzerlik", correct: "B" },
      { prompt: "DISCRIMINATE BETWEEN ne anlama gelir?", optionA: "Ayrım yapmak", optionB: "Birleştirmek", optionC: "Karıştırmak", optionD: "Kabul etmek", correct: "A" },
      { prompt: "ABUSE ne anlama gelir?", optionA: "Doğru kullanmak", optionB: "Suistimal etmek, kötüye kullanmak", optionC: "Paylaşmak", optionD: "Saklamak", correct: "B" },
      { prompt: "SEE OFF ne anlama gelir?", optionA: "Karşılamak", optionB: "Uğurlamak", optionC: "Beklemek", optionD: "Aramak", correct: "B" },
      { prompt: "COINCIDENCE ne anlama gelir?", optionA: "Plan", optionB: "Tesadüf", optionC: "Kural", optionD: "Zorunluluk", correct: "B" },
      { prompt: "PROPERLY ne anlama gelir?", optionA: "Yanlış şekilde", optionB: "Doğru düzgün", optionC: "Asla", optionD: "Bazen", correct: "B" },
      { prompt: "VARIOUS ne anlama gelir?", optionA: "Aynı", optionB: "Çeşitli, farklı", optionC: "Tek", optionD: "Basit", correct: "B" },
      { prompt: "GET ALONG WITH ne anlama gelir?", optionA: "Kavga etmek", optionB: "İyi geçinmek", optionC: "Kaçmak", optionD: "Unutmak", correct: "B" },
      { prompt: "GET OVER ne anlama gelir?", optionA: "Başlamak", optionB: "Atlatmak (hastalık, üzüntü)", optionC: "Unutmak", optionD: "Kaybetmek", correct: "B" },
    ],
  },
  {
    title: "13 Gelecek Zamandaki Geçmişin Şimdiki Hali (Future Perfect Continuous) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "Future Perfect Continuous yapısı nedir?", optionA: "WILL HAVE BEEN + V-ing", optionB: "WILL HAVE + V3", optionC: "WILL BE + V-ing", optionD: "HAD BEEN + V-ing", correct: "A" },
      { prompt: "Bu tense hangi tense ailesinin son üyesidir?", optionA: "Present", optionB: "Past", optionC: "Future", optionD: "Conditional", correct: "C" },
      { prompt: "By next year, I will have been working here for ___ years.", optionA: "five", optionB: "fives", optionC: "fifth", optionD: "fiving", correct: "A" },
      { prompt: "Future Perfect Continuous neyi vurgular?", optionA: "Anlık kararı", optionB: "Belirli bir gelecek noktasına kadar süregelen eylemi", optionC: "Geçmişi", optionD: "Emri", correct: "B" },
      { prompt: "Future Perfect Continuous'un olumsuzu nasıl yapılır?", optionA: "WON'T HAVE BEEN + V-ing", optionB: "WON'T HAVE + V3", optionC: "WON'T BE + V-ing", optionD: "HAVEN'T BEEN + V-ing", correct: "A" },
      { prompt: "By the time she retires, she will have been teaching for thirty ___.", optionA: "year", optionB: "years", optionC: "yearly", optionD: "yearing", correct: "B" },
      { prompt: "Bu tense ile Future Perfect arasındaki fark nedir?", optionA: "Fark yok", optionB: "Future Perfect sonuç, bu tense süreç vurgular", optionC: "Bu tense sonuç, Future Perfect süreç vurgular", optionD: "İkisi de aynı", correct: "B" },
      { prompt: "KNOW, BELIEVE gibi fiillerle hangi tense tercih edilir?", optionA: "Future Perfect Continuous", optionB: "Future Perfect Simple", optionC: "Future Continuous", optionD: "Present Perfect", correct: "B" },
      { prompt: "How long will you have been ___ by the time you finish your PhD?", optionA: "study", optionB: "studying", optionC: "studied", optionD: "studies", correct: "B" },
      { prompt: "By 2040, farmers will have been using this method for nearly twenty ___.", optionA: "year", optionB: "years", optionC: "yearly", optionD: "yearing", correct: "B" },
      { prompt: "Future Perfect Continuous en çok hangi soru kalıbıyla kullanılır?", optionA: "WHAT", optionB: "HOW LONG WILL YOU HAVE BEEN", optionC: "WHERE", optionD: "WHO", correct: "B" },
      { prompt: "Bu tense'in kısaltması nedir?", optionA: "'LL HAVE BEEN", optionB: "'LL BE", optionC: "'VE BEEN", optionD: "'D BEEN", correct: "A" },
      { prompt: "By the time the project is delivered, the team will have been working on it for over a ___.", optionA: "year", optionB: "years", optionC: "yearly", optionD: "yearing", correct: "A" },
      { prompt: "Future Perfect Continuous, akademik metinlerde genellikle ne anlatmak için kullanılır?", optionA: "Kısa anlık olaylar", optionB: "Uzun vadeli gelecek süreçler", optionC: "Geçmiş olaylar", optionD: "Emirler", correct: "B" },
      { prompt: "İngilizcede toplam kaç temel tense (zaman) vardır?", optionA: "8", optionB: "10", optionC: "12", optionD: "14", correct: "C" },
      { prompt: "By the deadline, we won't have been testing the software long ___.", optionA: "enough", optionB: "too", optionC: "so", optionD: "very", correct: "A" },
      { prompt: "Bu, kursun kaçıncı ve son tense'idir?", optionA: "10.", optionB: "11.", optionC: "12.", optionD: "13.", correct: "C" },
      { prompt: "Future Perfect Continuous, Present Perfect Continuous'a göre nasıl bir zaman noktasına atıf yapar?", optionA: "Şimdiye kadar", optionB: "Gelecekteki bir noktaya kadar", optionC: "Geçmişteki bir noktaya kadar", optionD: "Hiçbir zamana", correct: "B" },
      { prompt: "By the time this course ends, you will have been learning English tenses for several ___.", optionA: "month", optionB: "months", optionC: "monthly", optionD: "monthing", correct: "B" },
      { prompt: "Bu tense'i pekiştirmenin en iyi yolu nedir?", optionA: "Sadece ezberlemek", optionB: "Örnek cümlelerle bağlam içinde pratik yapmak", optionC: "Hiç kullanmamak", optionD: "Sadece yazılı sınavlarda kullanmak", correct: "B" },
    ],
  },
];

async function main() {
  for (const quiz of quizzes) {
    await publishQuiz(quiz);
  }
}

main().finally(() => prisma.$disconnect());
