import { publishQuiz, prisma, QuizDef } from "./lib/quiz-lib";

const ZAMANLAR = "İngilizce - Zamanlar";
const KELIME = "İngilizce - Kelime ve Kalıplar";

const quizzes: QuizDef[] = [
  {
    title: "1 Geniş Zaman (Present Simple) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "She ___ to school every day.", optionA: "go", optionB: "goes", optionC: "going", optionD: "went", correct: "B" },
      { prompt: "Do you ___ coffee in the morning?", optionA: "drinks", optionB: "drink", optionC: "drinking", optionD: "drank", correct: "B" },
      { prompt: "He doesn't ___ fish.", optionA: "eat", optionB: "eats", optionC: "eating", optionD: "ate", correct: "A" },
      { prompt: "They ___ in London.", optionA: "lives", optionB: "live", optionC: "living", optionD: "lived", correct: "B" },
      { prompt: "My father ___ a doctor.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "B" },
      { prompt: "___ she speak French?", optionA: "Do", optionB: "Does", optionC: "Is", optionD: "Are", correct: "B" },
      { prompt: "Water ___ at 100 degrees Celsius.", optionA: "boil", optionB: "boils", optionC: "boiling", optionD: "boiled", correct: "B" },
      { prompt: "I usually ___ up at seven.", optionA: "get", optionB: "gets", optionC: "getting", optionD: "got", correct: "A" },
      { prompt: "He ___ never late for work.", optionA: "do", optionB: "does", optionC: "is", optionD: "are", correct: "C" },
      { prompt: "My sister ___ TV every evening.", optionA: "watch", optionB: "watches", optionC: "watching", optionD: "watched", correct: "B" },
      { prompt: "We don't ___ meat.", optionA: "eat", optionB: "eats", optionC: "ate", optionD: "eating", correct: "A" },
      { prompt: "___ your parents live nearby?", optionA: "Do", optionB: "Does", optionC: "Is", optionD: "Are", correct: "A" },
      { prompt: "The sun ___ in the east.", optionA: "rise", optionB: "rises", optionC: "rising", optionD: "rose", correct: "B" },
      { prompt: "She always ___ her homework before dinner.", optionA: "finish", optionB: "finishes", optionC: "finishing", optionD: "finished", correct: "B" },
      { prompt: "I ___ not like spicy food.", optionA: "do", optionB: "does", optionC: "am", optionD: "is", correct: "A" },
      { prompt: "He ___ to the gym three times a week.", optionA: "go", optionB: "goes", optionC: "going", optionD: "went", correct: "B" },
      { prompt: "___ it rain a lot here in winter?", optionA: "Do", optionB: "Does", optionC: "Is", optionD: "Are", correct: "B" },
      { prompt: "My brothers ___ football on Saturdays.", optionA: "play", optionB: "plays", optionC: "playing", optionD: "played", correct: "A" },
      { prompt: "She ___ speak Spanish.", optionA: "doesn't", optionB: "don't", optionC: "isn't", optionD: "aren't", correct: "A" },
      { prompt: "Cats ___ mice.", optionA: "chase", optionB: "chases", optionC: "chasing", optionD: "chased", correct: "A" },
    ],
  },
  {
    title: "1 Temel Fiiller ve Sıklık Zarfları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "Sıklık zarfları genellikle nerede kullanılır (BE fiili dışında)?", optionA: "Cümle başında", optionB: "Ana fiilden önce", optionC: "Cümle sonunda", optionD: "Özneden önce", correct: "B" },
      { prompt: "She ___ goes to the cinema. (bazen)", optionA: "always", optionB: "sometimes", optionC: "never", optionD: "usually", correct: "B" },
      { prompt: "He is ___ late. (asla)", optionA: "always", optionB: "usually", optionC: "never", optionD: "often", correct: "C" },
      { prompt: "We ___ eat out on weekends. (genellikle)", optionA: "usually", optionB: "usual", optionC: "use to", optionD: "used", correct: "A" },
      { prompt: "I have ___ been to Japan. (hiç)", optionA: "always", optionB: "never", optionC: "sometimes", optionD: "often", correct: "B" },
      { prompt: "\"Do\" ve \"Does\" hangi zamanla kullanılır?", optionA: "Present Continuous", optionB: "Present Simple", optionC: "Past Simple", optionD: "Future Simple", correct: "B" },
      { prompt: "___ she like tea?", optionA: "Do", optionB: "Does", optionC: "Is", optionD: "Are", correct: "B" },
      { prompt: "He ___ likes pizza. (gerçekten)", optionA: "real", optionB: "really", optionC: "realy", optionD: "reall", correct: "B" },
      { prompt: "\"TAKE\" fiilinin 3. hali nedir?", optionA: "took", optionB: "taken", optionC: "taking", optionD: "takes", correct: "B" },
      { prompt: "\"GO\" fiilinin geçmiş zaman hali nedir?", optionA: "goed", optionB: "gone", optionC: "went", optionD: "going", correct: "C" },
      { prompt: "She never ___ breakfast.", optionA: "skip", optionB: "skips", optionC: "skipping", optionD: "skipped", correct: "B" },
      { prompt: "They ___ visit their grandparents every month. (sık sık)", optionA: "often", optionB: "oftenly", optionC: "offen", optionD: "ofter", correct: "A" },
      { prompt: "I usually ___ to bed at eleven.", optionA: "go", optionB: "goes", optionC: "going", optionD: "went", correct: "A" },
      { prompt: "My father hardly ever ___ angry.", optionA: "get", optionB: "gets", optionC: "getting", optionD: "got", correct: "B" },
      { prompt: "\"FIND\" fiilinin geçmiş hali nedir?", optionA: "finded", optionB: "found", optionC: "find", optionD: "founded", correct: "B" },
      { prompt: "She is ___ on time. (her zaman)", optionA: "always", optionB: "alway", optionC: "allways", optionD: "allway", correct: "A" },
      { prompt: "We ___ go to the theatre. (nadiren)", optionA: "rare", optionB: "rarely", optionC: "rarity", optionD: "rarest", correct: "B" },
      { prompt: "\"GIVE\" fiilinin 3. hali nedir?", optionA: "gave", optionB: "given", optionC: "give", optionD: "giving", correct: "B" },
      { prompt: "He usually ___ his room on Sundays.", optionA: "clean", optionB: "cleans", optionC: "cleaning", optionD: "cleaned", correct: "B" },
      { prompt: "My sister is ___ helpful. (her zaman)", optionA: "always", optionB: "alway", optionC: "allways", optionD: "allwais", correct: "A" },
    ],
  },
  {
    title: "2 Gelecek Zaman (Future Simple - Will) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "I think it ___ tomorrow.", optionA: "is raining", optionB: "will rain", optionC: "rains", optionD: "rained", correct: "B" },
      { prompt: "She ___ not come to the party.", optionA: "wills", optionB: "don't will", optionC: "will", optionD: "isn't will", correct: "C" },
      { prompt: "___ you help me tomorrow?", optionA: "Do", optionB: "Are", optionC: "Will", optionD: "Is", correct: "C" },
      { prompt: "WILL'den sonra fiil hangi halde kullanılır?", optionA: "V-ing", optionB: "V3", optionC: "V2", optionD: "V1 (yalın)", correct: "D" },
      { prompt: "I promise I ___ call you tonight.", optionA: "am", optionB: "do", optionC: "can", optionD: "will", correct: "D" },
      { prompt: "They ___ arrive at 6 pm.", optionA: "is will", optionB: "are will", optionC: "will", optionD: "wills", correct: "C" },
      { prompt: "\"I'll\" neyin kısaltmasıdır?", optionA: "I want", optionB: "I am", optionC: "I will", optionD: "I shall only", correct: "C" },
      { prompt: "We ___ not be late, I promise.", optionA: "don't will", optionB: "will", optionC: "isn't will", optionD: "wills", correct: "B" },
      { prompt: "___ she pass the exam?", optionA: "Does", optionB: "Is", optionC: "Are", optionD: "Will", correct: "D" },
      { prompt: "He thinks he ___ win the match.", optionA: "is will", optionB: "does will", optionC: "will", optionD: "wills", correct: "C" },
      { prompt: "I'm sure they ___ like the gift.", optionA: "are will", optionB: "do will", optionC: "wills", optionD: "will", correct: "D" },
      { prompt: "Gelecekle ilgili anlık kararlar için hangi yapı kullanılır?", optionA: "Present Continuous", optionB: "Going to", optionC: "Present Simple", optionD: "WILL", correct: "D" },
      { prompt: "She ___ probably be here soon.", optionA: "is", optionB: "does", optionC: "will", optionD: "can will", correct: "C" },
      { prompt: "\"WON'T\" neyin kısaltmasıdır?", optionA: "was not", optionB: "will not", optionC: "want not", optionD: "were not", correct: "B" },
      { prompt: "I ___ never forget this day.", optionA: "am", optionB: "do", optionC: "will", optionD: "can", correct: "C" },
      { prompt: "___ it be cold tomorrow?", optionA: "Does", optionB: "Is", optionC: "Do", optionD: "Will", correct: "D" },
      { prompt: "We ___ meet again someday.", optionA: "are", optionB: "do", optionC: "wills", optionD: "will", correct: "D" },
      { prompt: "He ___ not be able to come.", optionA: "don't will", optionB: "wills", optionC: "will", optionD: "isn't will", correct: "C" },
      { prompt: "I hope you ___ enjoy the trip.", optionA: "are", optionB: "can will", optionC: "will", optionD: "do", correct: "C" },
      { prompt: "They ___ celebrate their anniversary next week.", optionA: "wills", optionB: "are will", optionC: "do will", optionD: "will", correct: "D" },
    ],
  },
  {
    title: "2 Modallar ve İhtiyaç Kalıpları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "You ___ swim very well. (yetenek)", optionA: "must", optionB: "should", optionC: "need", optionD: "can", correct: "D" },
      { prompt: "___ I open the window? (izin)", optionA: "Must", optionB: "Should", optionC: "Can", optionD: "Need", correct: "C" },
      { prompt: "You ___ see a doctor. (tavsiye)", optionA: "can", optionB: "should", optionC: "need", optionD: "must", correct: "B" },
      { prompt: "We ___ finish this today. (kendi hissettiğimiz zorunluluk)", optionA: "can", optionB: "should", optionC: "must", optionD: "may", correct: "C" },
      { prompt: "I ___ to buy some milk. (ihtiyacım var)", optionA: "must", optionB: "need", optionC: "can", optionD: "should", correct: "B" },
      { prompt: "You ___ smoke here. (yasak)", optionA: "don't have to", optionB: "mustn't", optionC: "needn't", optionD: "shouldn't", correct: "B" },
      { prompt: "You ___ worry, everything is fine. (gerek yok)", optionA: "mustn't", optionB: "can't", optionC: "don't need to", optionD: "shouldn't", correct: "C" },
      { prompt: "\"DON'T HAVE TO\" ne anlama gelir?", optionA: "Yasak", optionB: "Gerek yok", optionC: "İzin yok", optionD: "Tavsiye edilmez", correct: "B" },
      { prompt: "She ___ speak three languages. (yetenek)", optionA: "must", optionB: "should", optionC: "can", optionD: "need", correct: "C" },
      { prompt: "___ you help me, please? (rica)", optionA: "Must", optionB: "Could", optionC: "Need", optionD: "Should", correct: "B" },
      { prompt: "We ___ wear a uniform at school. (kural)", optionA: "can", optionB: "may", optionC: "could", optionD: "have to", correct: "D" },
      { prompt: "You ___ eat so much sugar. (olumsuz tavsiye)", optionA: "mustn't", optionB: "shouldn't", optionC: "can't", optionD: "needn't", correct: "B" },
      { prompt: "He ___ drive, he doesn't have a license. (yetenek yok)", optionA: "mustn't", optionB: "shouldn't", optionC: "can't", optionD: "needn't", correct: "C" },
      { prompt: "MUST genellikle hangi tür zorunluluğu ifade eder?", optionA: "Dışarıdan gelen kural", optionB: "Konuşmacının kendi hissettiği zorunluluk", optionC: "Tavsiye", optionD: "İzin", correct: "B" },
      { prompt: "HAVE TO genellikle hangi tür zorunluluğu ifade eder?", optionA: "Dışarıdan gelen kural", optionB: "Konuşmacının kendi hissettiği zorunluluk", optionC: "Yasak", optionD: "İzin", correct: "A" },
      { prompt: "You ___ be quiet in the library. (kural, zorunluluk)", optionA: "can", optionB: "may", optionC: "have to", optionD: "could", correct: "C" },
      { prompt: "___ I borrow your pen? (rica/izin)", optionA: "Must", optionB: "Should", optionC: "May", optionD: "Need", correct: "C" },
      { prompt: "We ___ pay for parking here, it's free. (gerek yok)", optionA: "mustn't", optionB: "don't have to", optionC: "shouldn't", optionD: "can't", correct: "B" },
      { prompt: "You ___ study harder if you want to pass. (tavsiye)", optionA: "must", optionB: "should", optionC: "can", optionD: "may", correct: "B" },
      { prompt: "NEED TO ile HAVE TO arasındaki temel benzerlik nedir?", optionA: "İkisi de izin bildirir", optionB: "İkisi de ihtiyaç/zorunluluk bildirir", optionC: "İkisi de yasak bildirir", optionD: "İkisi de tavsiye bildirir", correct: "B" },
    ],
  },
  {
    title: "3 Am - Is - Are ve Duygu Sıfatları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "I ___ happy today.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "A" },
      { prompt: "She ___ tired.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "B" },
      { prompt: "They ___ excited about the trip.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "C" },
      { prompt: "We ___ hungry.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "C" },
      { prompt: "He ___ angry with me.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "B" },
      { prompt: "___ you scared of spiders?", optionA: "Am", optionB: "Is", optionC: "Are", optionD: "Be", correct: "C" },
      { prompt: "I ___ not bored.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "A" },
      { prompt: "My parents ___ proud of me.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "C" },
      { prompt: "The movie ___ boring.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "B" },
      { prompt: "___ he nervous about the exam?", optionA: "Am", optionB: "Is", optionC: "Are", optionD: "Be", correct: "B" },
      { prompt: "I ___ surprised by the news.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "A" },
      { prompt: "She ___ sad because of the rain.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "B" },
      { prompt: "We ___ confused about the instructions.", optionA: "am", optionB: "is", optionC: "are", optionD: "be", correct: "C" },
      { prompt: "___ they interested in music?", optionA: "Am", optionB: "Is", optionC: "Are", optionD: "Be", correct: "C" },
      { prompt: "\"Kıskanç\" kelimesinin İngilizcesi nedir?", optionA: "angry", optionB: "jealous", optionC: "nervous", optionD: "proud", correct: "B" },
      { prompt: "\"Utanmış\" kelimesinin İngilizcesi nedir?", optionA: "excited", optionB: "confused", optionC: "embarrassed", optionD: "bored", correct: "C" },
      { prompt: "\"Şaşırmış\" kelimesinin İngilizcesi nedir?", optionA: "surprised", optionB: "worried", optionC: "scared", optionD: "sad", correct: "A" },
      { prompt: "\"Gururlu\" kelimesinin İngilizcesi nedir?", optionA: "proud", optionB: "bored", optionC: "angry", optionD: "tired", correct: "A" },
      { prompt: "\"Endişeli\" kelimesinin İngilizcesi nedir?", optionA: "happy", optionB: "worried", optionC: "excited", optionD: "jealous", correct: "B" },
      { prompt: "\"Sıkılmış\" kelimesinin İngilizcesi nedir?", optionA: "bored", optionB: "scared", optionC: "nervous", optionD: "confused", correct: "A" },
    ],
  },
];

async function main() {
  for (const quiz of quizzes) {
    await publishQuiz(quiz);
  }
}

main().finally(() => prisma.$disconnect());
