import { publishQuiz, prisma, QuizDef } from "./lib/quiz-lib";

const ZAMANLAR = "İngilizce - Zamanlar";
const KELIME = "İngilizce - Kelime ve Kalıplar";

const quizzes: QuizDef[] = [
  {
    title: "14 Yer Edatları, There Is-Are ve Hava Durumu - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "\"Üstünde\" edatı hangisidir?", optionA: "ON", optionB: "UNDER", optionC: "IN", optionD: "AT", correct: "A" },
      { prompt: "\"Altında\" edatı hangisidir?", optionA: "ON", optionB: "UNDER", optionC: "BEHIND", optionD: "NEXT TO", correct: "B" },
      { prompt: "\"Önünde\" edatı hangisidir?", optionA: "BEHIND", optionB: "IN FRONT OF", optionC: "UNDER", optionD: "NEXT TO", correct: "B" },
      { prompt: "\"Arkasında\" edatı hangisidir?", optionA: "BEHIND", optionB: "IN FRONT OF", optionC: "UNDER", optionD: "BETWEEN", correct: "A" },
      { prompt: "\"Yanında\" edatı hangisidir?", optionA: "NEXT TO", optionB: "UNDER", optionC: "BEHIND", optionD: "ACROSS", correct: "A" },
      { prompt: "THERE IS hangi isimlerle kullanılır?", optionA: "Tekil/sayılamayan", optionB: "Çoğul", optionC: "Her ikisi", optionD: "Hiçbiri", correct: "A" },
      { prompt: "THERE ARE hangi isimlerle kullanılır?", optionA: "Tekil", optionB: "Çoğul", optionC: "Sayılamaz", optionD: "Hiçbiri", correct: "B" },
      { prompt: "There ___ a man in front of the door.", optionA: "is", optionB: "are", optionC: "am", optionD: "be", correct: "A" },
      { prompt: "There ___ some people across the building.", optionA: "is", optionB: "are", optionC: "am", optionD: "be", correct: "B" },
      { prompt: "Hava durumu için hangi öznenin kullanılması gerekir?", optionA: "I", optionB: "It", optionC: "They", optionD: "We", correct: "B" },
      { prompt: "It ___ raining right now.", optionA: "is", optionB: "am", optionC: "are", optionD: "do", correct: "A" },
      { prompt: "\"Bulutlu\" kelimesinin İngilizcesi nedir?", optionA: "sunny", optionB: "cloudy", optionC: "windy", optionD: "foggy", correct: "B" },
      { prompt: "\"Rüzgarlı\" kelimesinin İngilizcesi nedir?", optionA: "sunny", optionB: "cloudy", optionC: "windy", optionD: "foggy", correct: "C" },
      { prompt: "\"Sisli\" kelimesinin İngilizcesi nedir?", optionA: "sunny", optionB: "cloudy", optionC: "windy", optionD: "foggy", correct: "D" },
      { prompt: "\"HOW IS THE WEATHER?\" ne anlama gelir?", optionA: "Saat kaç?", optionB: "Hava nasıl?", optionC: "Nerelisin?", optionD: "Ne yapıyorsun?", correct: "B" },
      { prompt: "There ___ enough time. (yeterli değil)", optionA: "isn't", optionB: "aren't", optionC: "doesn't", optionD: "don't", correct: "A" },
      { prompt: "Is there an ATM ___ the mall?", optionA: "in", optionB: "on", optionC: "at", optionD: "under", correct: "A" },
      { prompt: "The bank is ___ the pharmacy and the bookstore.", optionA: "between", optionB: "among", optionC: "behind", optionD: "under", correct: "A" },
      { prompt: "\"Güneşli\" kelimesinin İngilizcesi nedir?", optionA: "sunny", optionB: "rainy", optionC: "snowy", optionD: "stormy", correct: "A" },
      { prompt: "It was very ___ last night. (rüzgarlı)", optionA: "sun", optionB: "windy", optionC: "wind", optionD: "winding", correct: "B" },
    ],
  },
  {
    title: "15 Sıra Sayıları ve Zaman İfadeleri - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "\"İlk\" kelimesinin İngilizcesi nedir?", optionA: "one", optionB: "first", optionC: "once", optionD: "firstly", correct: "B" },
      { prompt: "\"Üçüncü\" kelimesinin İngilizcesi nedir?", optionA: "three", optionB: "third", optionC: "threeth", optionD: "thirdly", correct: "B" },
      { prompt: "\"FOR THE FIRST TIME\" ne anlama gelir?", optionA: "İlk defa", optionB: "Son defa", optionC: "Bazen", optionD: "Her zaman", correct: "A" },
      { prompt: "STILL hangi cümlelerde kullanılır?", optionA: "Olumsuz/soru", optionB: "Olumlu/soru", optionC: "Sadece olumsuz", optionD: "Sadece emir", correct: "B" },
      { prompt: "YET hangi cümlelerde kullanılır?", optionA: "Olumlu", optionB: "Olumsuz/soru", optionC: "Emir", optionD: "Ünlem", correct: "B" },
      { prompt: "He didn't call me ___. (henüz)", optionA: "still", optionB: "yet", optionC: "already", optionD: "ago", correct: "B" },
      { prompt: "Are you ___ working? (hâlâ)", optionA: "still", optionB: "yet", optionC: "already", optionD: "never", correct: "A" },
      { prompt: "WHEN bağlacı ne anlama gelir?", optionA: "-dığında", optionB: "-mesine rağmen", optionC: "-meden önce", optionD: "-diği için", correct: "A" },
      { prompt: "He will call us ___ he arrives.", optionA: "when", optionB: "although", optionC: "despite", optionD: "unless", correct: "A" },
      { prompt: "\"AT WHAT TIME\" ne anlama gelir?", optionA: "Ne zamandan beri", optionB: "Saat kaçta", optionC: "Ne kadar süre", optionD: "Hangi gün", correct: "B" },
      { prompt: "Sıra sayısı yazarken hangi ek çoğunlukla kullanılır?", optionA: "-TH", optionB: "-ST", optionC: "-ER", optionD: "-ING", correct: "A" },
      { prompt: "\"Yirmi birinci\" nasıl yazılır?", optionA: "twenty-first", optionB: "twenty-oneth", optionC: "twentyth-one", optionD: "twenty-onest", correct: "A" },
      { prompt: "DURING hangi kelime türünden sonra kullanılır?", optionA: "İsim", optionB: "Cümle (özne+fiil)", optionC: "Sıfat", optionD: "Zarf", correct: "A" },
      { prompt: "WHILE hangi yapıdan sonra kullanılır?", optionA: "İsim", optionB: "Cümle (özne+fiil)", optionC: "Sıfat", optionD: "Zarf", correct: "B" },
      { prompt: "UNTIL ne anlama gelir?", optionA: "-e kadar (süreklilik)", optionB: "En geç -e kadar", optionC: "-den önce", optionD: "-den sonra", correct: "A" },
      { prompt: "BY ne anlama gelir?", optionA: "-e kadar (süreklilik)", optionB: "En geç -e kadar (tamamlanma)", optionC: "-den önce", optionD: "-den sonra", correct: "B" },
      { prompt: "AT THE BEGINNING OF ne anlama gelir?", optionA: "Sonunda", optionB: "Başında", optionC: "Ortasında", optionD: "Boyunca", correct: "B" },
      { prompt: "NOWADAYS ne anlama gelir?", optionA: "Eskiden", optionB: "Günümüzde", optionC: "Yakında", optionD: "Asla", correct: "B" },
      { prompt: "\"Geçen hafta\" kelimesinin İngilizcesi nedir?", optionA: "next week", optionB: "last week", optionC: "this week", optionD: "every week", correct: "B" },
      { prompt: "\"Öbür gün\" kelimesinin İngilizcesi nedir?", optionA: "yesterday", optionB: "the day after tomorrow", optionC: "tomorrow", optionD: "today", correct: "B" },
    ],
  },
  {
    title: "8 Geçmişten Önceki Geçmiş Zaman (Past Perfect) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "Past Perfect yapısı nedir?", optionA: "HAD + V3", optionB: "HAVE/HAS + V3", optionC: "WAS/WERE + V-ing", optionD: "WILL HAVE + V3", correct: "A" },
      { prompt: "Past Perfect ne zaman kullanılır?", optionA: "Gelecekteki bir olay için", optionB: "Geçmişteki iki olaydan önce olanı belirtmek için", optionC: "Şu anki durum için", optionD: "Emir vermek için", correct: "B" },
      { prompt: "The train had already ___ when we arrived.", optionA: "leave", optionB: "left", optionC: "leaving", optionD: "leaves", correct: "B" },
      { prompt: "She had ___ her homework before dinner.", optionA: "finish", optionB: "finished", optionC: "finishing", optionD: "finishes", correct: "B" },
      { prompt: "I hadn't ___ him before that day.", optionA: "see", optionB: "saw", optionC: "seen", optionD: "seeing", correct: "C" },
      { prompt: "___ they left before you called?", optionA: "Do", optionB: "Did", optionC: "Had", optionD: "Have", correct: "C" },
      { prompt: "Past Perfect en çok hangi bağlaçlarla kullanılır?", optionA: "AND, OR", optionB: "BEFORE, AFTER", optionC: "SO, BUT", optionD: "WHILE, WHEN", correct: "B" },
      { prompt: "By the time we got there, the movie ___ already started.", optionA: "has", optionB: "had", optionC: "have", optionD: "was", correct: "B" },
      { prompt: "Past Perfect'in kısaltması nedir?", optionA: "'D", optionB: "'S", optionC: "'RE", optionD: "'VE", correct: "A" },
      { prompt: "He said that he ___ already paid the bill.", optionA: "has", optionB: "have", optionC: "had", optionD: "was", correct: "C" },
      { prompt: "NO SOONER...THAN kalıbı ne anlama gelir?", optionA: "-ar -maz", optionB: "-mesine rağmen", optionC: "-diği sürece", optionD: "-meden önce", correct: "A" },
      { prompt: "IF + Past Perfect kalıbı hangi şart cümlesinde kullanılır?", optionA: "Birinci tip", optionB: "İkinci tip", optionC: "Üçüncü tip", optionD: "Sıfırıncı tip", correct: "C" },
      { prompt: "I wish I ___ told her the truth. (keşke)", optionA: "have", optionB: "had", optionC: "has", optionD: "will have", correct: "B" },
      { prompt: "By the time the police arrived, the thief ___ escaped.", optionA: "has", optionB: "have", optionC: "had already", optionD: "will have", correct: "C" },
      { prompt: "Past Perfect'in olumsuzu nasıl yapılır?", optionA: "HADN'T + V3", optionB: "HAVEN'T + V3", optionC: "WASN'T + V-ing", optionD: "DIDN'T + V1", correct: "A" },
      { prompt: "She realized she ___ left her passport at home.", optionA: "has", optionB: "have", optionC: "had", optionD: "was", correct: "C" },
      { prompt: "We had never ___ before that party.", optionA: "meet", optionB: "met", optionC: "meeting", optionD: "meets", correct: "B" },
      { prompt: "AFTER we ___ dinner, we watched a movie.", optionA: "have had", optionB: "had had", optionC: "has had", optionD: "having", correct: "B" },
      { prompt: "Past Perfect, hangi zamanla birlikte sıkça kullanılır?", optionA: "Present Simple", optionB: "Past Simple", optionC: "Future Simple", optionD: "Present Continuous", correct: "B" },
      { prompt: "He told me he ___ never eaten sushi before.", optionA: "has", optionB: "have", optionC: "had", optionD: "was", correct: "C" },
    ],
  },
  {
    title: "9 Geçmişten Önceki Geçmişin Şimdiki Hali (Past Perfect Continuous) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "Past Perfect Continuous yapısı nedir?", optionA: "HAD BEEN + V-ing", optionB: "HAD + V3", optionC: "HAVE BEEN + V-ing", optionD: "WAS + V-ing", correct: "A" },
      { prompt: "Past Perfect Continuous ne vurgular?", optionA: "Sonuç", optionB: "Süreç/süreklilik", optionC: "Ani karar", optionD: "Gelecek", correct: "B" },
      { prompt: "He had been working there ___ ten years before he retired.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "They had been waiting ___ two hours when the bus came.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "Past Perfect Continuous'un olumsuzu nasıl yapılır?", optionA: "HADN'T BEEN + V-ing", optionB: "HAVEN'T BEEN + V-ing", optionC: "WASN'T + V-ing", optionD: "DIDN'T + V1", correct: "A" },
      { prompt: "Her clothes were wet because she had been ___.", optionA: "swim", optionB: "swimming", optionC: "swam", optionD: "swims", correct: "B" },
      { prompt: "How long had you been ___ there before you moved?", optionA: "live", optionB: "living", optionC: "lived", optionD: "lives", correct: "B" },
      { prompt: "Past Perfect Continuous, Past Perfect'ten farklı olarak neyi vurgular?", optionA: "Sonucu", optionB: "Süreci", optionC: "Geleceği", optionD: "Emri", correct: "B" },
      { prompt: "By the time the police arrived, they had been fighting ___ twenty minutes.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "His hands were dirty because he had been ___ in the garden.", optionA: "work", optionB: "working", optionC: "worked", optionD: "works", correct: "B" },
      { prompt: "KNOW, BELIEVE gibi fiillerle bu tense kullanılır mı?", optionA: "Evet", optionB: "Hayır, Past Perfect kullanılır", optionC: "Bazen", optionD: "Sadece olumsuzda", correct: "B" },
      { prompt: "I had been reading for two hours when the power ___ out.", optionA: "go", optionB: "went", optionC: "goes", optionD: "going", correct: "B" },
      { prompt: "Past Perfect Continuous en çok hangi soru kelimesiyle kullanılır?", optionA: "HOW LONG", optionB: "WHAT", optionC: "WHERE", optionD: "WHO", correct: "A" },
      { prompt: "She had been crying all night before he finally ___ her.", optionA: "call", optionB: "called", optionC: "calls", optionD: "calling", correct: "B" },
      { prompt: "We had been driving all day, so we were ___. (bitkin)", optionA: "excited", optionB: "exhausted", optionC: "bored", optionD: "surprised", correct: "B" },
      { prompt: "He had never been working so hard ___ that project.", optionA: "after", optionB: "before", optionC: "during", optionD: "since", correct: "B" },
      { prompt: "Past Perfect Continuous ile Past Continuous arasındaki fark nedir?", optionA: "Fark yok", optionB: "Past Continuous belirli anı, Past Perfect Continuous bir noktaya kadar süreni anlatır", optionC: "İkisi de gelecek içindir", optionD: "Past Continuous daha resmi", correct: "B" },
      { prompt: "They had been arguing for months before they decided to ___.", optionA: "marry", optionB: "separate", optionC: "celebrate", optionD: "travel", correct: "B" },
      { prompt: "I hadn't been sleeping well, so I felt ___ all week.", optionA: "happy", optionB: "dizzy", optionC: "excited", optionD: "proud", correct: "B" },
      { prompt: "We had been planning the trip for months before we finally ___.", optionA: "left", optionB: "leave", optionC: "leaving", optionD: "leaves", correct: "A" },
    ],
  },
  {
    title: "16 Before - After ve Sorumluluk Kalıpları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "BEFORE ve AFTER'dan sonra özneler aynıysa fiil hangi hale getirilebilir?", optionA: "V1", optionB: "V-ing", optionC: "V2", optionD: "V3", correct: "B" },
      { prompt: "I will call you before I ___. (finish)", optionA: "finish", optionB: "finishing", optionC: "finished", optionD: "to finish", correct: "B" },
      { prompt: "She will cook the meal after ___ home. (kısaltılmış hâli)", optionA: "arrive", optionB: "arrives", optionC: "arriving", optionD: "arrived", correct: "C" },
      { prompt: "AS SOON AS ne anlama gelir?", optionA: "-ar -maz", optionB: "-mesine rağmen", optionC: "-meden önce", optionD: "-dığı sürece", correct: "A" },
      { prompt: "BE RESPONSIBLE FOR ne anlama gelir?", optionA: "-den sorumlu olmak", optionB: "-den korkmak", optionC: "-e güvenmek", optionD: "-i sevmek", correct: "A" },
      { prompt: "Who is responsible ___ accounting?", optionA: "of", optionB: "for", optionC: "with", optionD: "at", correct: "B" },
      { prompt: "\"Sabır\" kelimesinin İngilizcesi nedir?", optionA: "patience", optionB: "courage", optionC: "confidence", optionD: "attitude", correct: "A" },
      { prompt: "\"Cesaret\" kelimesinin İngilizcesi nedir?", optionA: "patience", optionB: "courage", optionC: "attitude", optionD: "requirement", correct: "B" },
      { prompt: "This job requires more ___. (sabır)", optionA: "patience", optionB: "courage", optionC: "process", optionD: "account", correct: "A" },
      { prompt: "IN CHARGE OF ne anlama gelir?", optionA: "-den sorumlu, başında", optionB: "-e karşı", optionC: "-den önce", optionD: "-e rağmen", correct: "A" },
      { prompt: "TAKE RESPONSIBILITY FOR ne anlama gelir?", optionA: "Sorumluluk almak", optionB: "Sorumluluktan kaçmak", optionC: "Suçlamak", optionD: "Affetmek", correct: "A" },
      { prompt: "DEAL WITH ne anlama gelir?", optionA: "Uğraşmak, başa çıkmak", optionB: "Kaçmak", optionC: "Unutmak", optionD: "Beklemek", correct: "A" },
      { prompt: "PRIOR TO ne anlama gelir?", optionA: "-den sonra", optionB: "-den önce", optionC: "-e rağmen", optionD: "-dığı sürece", correct: "B" },
      { prompt: "FOLLOWING ne anlama gelir?", optionA: "-den önce", optionB: "-in ardından", optionC: "-e rağmen", optionD: "-meden önce", correct: "B" },
      { prompt: "OWE ne anlama gelir?", optionA: "Borçlu olmak", optionB: "Ödemek", optionC: "Kazanmak", optionD: "Harcamak", correct: "A" },
      { prompt: "APOLOGIZE FOR ne anlama gelir?", optionA: "Teşekkür etmek", optionB: "Özür dilemek", optionC: "Şikayet etmek", optionD: "Kutlamak", correct: "B" },
      { prompt: "BLAME ne anlama gelir?", optionA: "Övmek", optionB: "Suçlamak", optionC: "Affetmek", optionD: "Desteklemek", correct: "B" },
      { prompt: "TAKE OVER ne anlama gelir?", optionA: "Devralmak", optionB: "Devretmek", optionC: "Reddetmek", optionD: "Kabul etmek", correct: "A" },
      { prompt: "HAND OVER ne anlama gelir?", optionA: "Devralmak", optionB: "Devretmek", optionC: "Saklamak", optionD: "Kaybetmek", correct: "B" },
      { prompt: "RELY ON ne anlama gelir?", optionA: "Güvenmek", optionB: "Şüphelenmek", optionC: "Korkmak", optionD: "Kızmak", correct: "A" },
    ],
  },
];

async function main() {
  for (const quiz of quizzes) {
    await publishQuiz(quiz);
  }
}

main().finally(() => prisma.$disconnect());
