import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const OUT_DIR = "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons";

const lessons: LessonDef[] = [
  {
    fileBase: "02_Temel_Fiiller",
    title: "TEMEL FİİLLER VE SIKLIK ZARFLARI",
    blocks: [
      { type: "rule", text: "Bu derste geniş zamanla birlikte en sık kullanılan temel fiilleri örnek cümlelerle pekiştireceğiz." },
      { type: "pattern", text: "GO = gitmek / WHERE = nereye / THERE = oraya / TO = -e, -a" },
      { type: "example", en: "Where do you go every summer?", tr: "Her yaz nereye gidersin?" },
      { type: "example", en: "I go to London every year.", tr: "Her yıl Londra'ya giderim." },
      { type: "example", en: "They don't go there anymore.", tr: "Onlar artık oraya gitmiyorlar." },
      { type: "pattern", text: "COME = gelmek / HERE = buraya / WHEN = ne zaman / HOME = eve" },
      { type: "example", en: "When do you come home?", tr: "Eve ne zaman gelirsin?" },
      { type: "example", en: "She comes here every Monday.", tr: "O buraya her pazartesi gelir." },
      { type: "rule", text: "\"Do you come or not?\" gibi soru kalıplarında DO/DOES yardımcı fiili cümlenin başına gelir." },
      { type: "pattern", text: "WORK = çalışmak / DAY = gün / EVERYDAY = her gün" },
      { type: "example", en: "I work every day.", tr: "Ben her gün çalışırım." },
      { type: "example", en: "He doesn't work on Sundays.", tr: "O pazar günleri çalışmaz." },
      { type: "pattern", text: "VISIT = ziyaret etmek / ME-YOU-HIM-HER-US-YOU-THEM = beni-seni-onu(erkek)-onu(kız)-bizi-sizi-onları" },
      { type: "example", en: "Does he visit you often?", tr: "O seni sık ziyaret eder mi?" },
      { type: "example", en: "We visit them every summer.", tr: "Biz onları her yaz ziyaret ederiz." },
      { type: "pattern", text: "SPEAK = konuşmak (bir dili konuşmak) / ENGLISH - GERMAN - SPANISH - TURKISH - FRENCH" },
      { type: "example", en: "She speaks English, German and Spanish.", tr: "O İngilizce, Almanca ve İspanyolca konuşur." },
      { type: "example", en: "I don't speak French.", tr: "Ben Fransızca konuşmam." },
      { type: "pattern", text: "UNDERSTAND = anlamak" },
      { type: "example", en: "Do you understand me?", tr: "Beni anlıyor musun?" },
      { type: "rule", text: "SEE ve WANT fiilleri iki fiil yan yana geldiğinde ikinci fiil \"to + V1\" (mastar) hâlinde kullanılır." },
      { type: "example", en: "I want to see him.", tr: "Onu görmek istiyorum." },
      { type: "example", en: "Who do you want to see?", tr: "Kimi görmek istiyorsun?" },
      { type: "pattern", text: "KNOW = bilmek / ANYTHING = hiçbir şey / UNFORTUNATELY = maalesef" },
      { type: "example", en: "Unfortunately, I don't know anything.", tr: "Maalesef hiçbir şey bilmiyorum." },
      { type: "example", en: "Do you know everything about him?", tr: "Onun hakkında her şeyi biliyor musun?" },
      { type: "pattern", text: "BELIEVE = inanmak / START = başlamak / FINISH = bitirmek / JOB, PROJECT = iş, proje" },
      { type: "example", en: "I believe you.", tr: "Sana inanıyorum." },
      { type: "example", en: "When do they start the project?", tr: "Onlar projeye ne zaman başlıyor?" },
      { type: "rule", text: "Sıklık zarfları: ALWAYS (her zaman), USUALLY (genellikle), OFTEN (sık sık), SOMETIMES (bazen), RARELY (nadiren), NEVER (asla)." },
      { type: "example", en: "They rarely invite us to their parties.", tr: "Onlar bizi partilerine nadiren davet ederler." },
      { type: "pattern", text: "INVITE = davet etmek / ORGANIZATION, PARTY = organizasyon, parti" },
      { type: "example", en: "Do you always invite them to your organizations?", tr: "Onları her zaman organizasyonlarına davet eder misin?" },
      { type: "pattern", text: "SLEEP = uyumak / GET UP = kalkmak / EARLY = erken / LATE = geç" },
      { type: "example", en: "He always sleeps early and gets up early.", tr: "O her zaman erken uyur ve erken kalkar." },
      { type: "example", en: "I don't sleep late on weekdays.", tr: "Hafta içi geç uyumam." },
      { type: "pattern", text: "EAT = yemek / DRINK = içmek / SOMETHING = bir şey / TEA, COFFEE = çay, kahve" },
      { type: "example", en: "Do you want something to eat or drink?", tr: "Yiyecek ya da içecek bir şey ister misin?" },
      { type: "example", en: "She drinks tea every morning.", tr: "O her sabah çay içer." },
      { type: "pattern", text: "PROMISE = söz vermek / ACCEPT = kabul etmek / OFFER, PRICE = teklif, fiyat" },
      { type: "example", en: "He always accepts the offer, but he never promises anything.", tr: "O teklifi her zaman kabul eder ama asla söz vermez." },
      { type: "pattern", text: "USE = kullanmak / PHONE, COMPUTER = telefon, bilgisayar" },
      { type: "example", en: "I use my phone and computer every day.", tr: "Telefonumu ve bilgisayarımı her gün kullanırım." },
      { type: "example", en: "Does she use a computer at work?", tr: "O işte bilgisayar kullanıyor mu?" },
      { type: "rule", text: "\"GO\" fiilinin bütün özneler için tam çekimini inceleyerek pekiştirelim." },
      { type: "pattern", text: "GO (OLUMLU)" },
      { type: "example", en: "I go to the gym on Mondays.", tr: "Pazartesileri spor salonuna giderim." },
      { type: "example", en: "You go to the gym on Mondays.", tr: "Sen pazartesileri spor salonuna gidersin." },
      { type: "example", en: "He goes to the gym on Mondays.", tr: "O pazartesileri spor salonuna gider." },
      { type: "example", en: "She goes to the gym on Mondays.", tr: "O (kadın) pazartesileri spor salonuna gider." },
      { type: "example", en: "We go to the gym on Mondays.", tr: "Biz pazartesileri spor salonuna gideriz." },
      { type: "example", en: "They go to the gym on Mondays.", tr: "Onlar pazartesileri spor salonuna giderler." },
      { type: "pattern", text: "GO (OLUMSUZ)" },
      { type: "example", en: "I don't go to the gym on weekends.", tr: "Hafta sonları spor salonuna gitmem." },
      { type: "example", en: "He doesn't go to the gym on weekends.", tr: "O hafta sonları spor salonuna gitmez." },
      { type: "example", en: "They don't go to the gym on weekends.", tr: "Onlar hafta sonları spor salonuna gitmezler." },
      { type: "pattern", text: "GO (SORU)" },
      { type: "example", en: "Do you go to the gym every day?", tr: "Her gün spor salonuna gider misin?" },
      { type: "example", en: "Does she go to the gym every day?", tr: "O her gün spor salonuna gider mi?" },
      { type: "example", en: "Do they go to the gym every day?", tr: "Onlar her gün spor salonuna gider mi?" },
      { type: "rule", text: "Bu derste geçen fiilleri farklı öznelerle daha fazla pekiştirelim." },
      { type: "example", en: "My parents visit us every weekend.", tr: "Ailem her hafta sonu bizi ziyaret eder." },
      { type: "example", en: "My colleague speaks four languages.", tr: "Meslektaşım dört dil konuşur." },
      { type: "example", en: "The students don't understand this topic.", tr: "Öğrenciler bu konuyu anlamıyorlar." },
      { type: "example", en: "Nobody knows the answer.", tr: "Kimse cevabı bilmiyor." },
      { type: "example", en: "I believe in hard work.", tr: "Çok çalışmaya inanırım." },
      { type: "example", en: "We never sleep before midnight.", tr: "Gece yarısından önce asla uyumayız." },
      { type: "example", en: "She eats vegetables every day.", tr: "O her gün sebze yer." },
      { type: "example", en: "He promises to help us.", tr: "O bize yardım edeceğine söz veriyor." },
      { type: "rule", text: "Karışık alıştırma cümleleriyle bu dersi pekiştirelim." },
      { type: "example", en: "Do you visit your grandparents often?", tr: "Büyükanne ve büyükbabanı sık ziyaret eder misin?" },
      { type: "example", en: "He always uses his phone at work.", tr: "O işte her zaman telefonunu kullanır." },
      { type: "example", en: "They don't believe his excuse.", tr: "Onlar onun mazeretine inanmıyorlar." },
      { type: "example", en: "Does your sister speak Spanish?", tr: "Kız kardeşin İspanyolca konuşuyor mu?" },
      { type: "example", en: "I sometimes forget to lock the door.", tr: "Bazen kapıyı kilitlemeyi unuturum." },
      { type: "rule", text: "\"COME\" fiilinin tam çekimini de inceleyelim." },
      { type: "pattern", text: "COME (OLUMLU / OLUMSUZ / SORU)" },
      { type: "example", en: "I come here every summer.", tr: "Her yaz buraya gelirim." },
      { type: "example", en: "He comes to work by train.", tr: "O işe trenle gelir." },
      { type: "example", en: "She doesn't come to class on time.", tr: "O derse vaktinde gelmez." },
      { type: "example", en: "We don't come here often.", tr: "Buraya sık gelmeyiz." },
      { type: "example", en: "Do you come from Turkey?", tr: "Sen Türkiye'den mi geliyorsun?" },
      { type: "example", en: "Does he come to the meetings?", tr: "O toplantılara geliyor mu?" },
      { type: "rule", text: "Bu fiillerle kurulmuş birkaç günlük hayat cümlesi daha görelim." },
      { type: "example", en: "My neighbor speaks very loudly.", tr: "Komşum çok yüksek sesle konuşur." },
      { type: "example", en: "The manager doesn't understand the problem.", tr: "Müdür problemi anlamıyor." },
      { type: "example", en: "Do your parents know about this?", tr: "Ailen bunu biliyor mu?" },
      { type: "example", en: "I don't believe everything I read.", tr: "Okuduğum her şeye inanmam." },
      { type: "example", en: "They always invite the whole family.", tr: "Onlar her zaman bütün aileyi davet eder." },
      { type: "example", en: "He never promises anything he can't do.", tr: "O yapamayacağı hiçbir şeye söz vermez." },
      { type: "example", en: "Do you use social media a lot?", tr: "Sosyal medyayı çok mu kullanırsın?" },
      { type: "example", en: "She doesn't drink alcohol.", tr: "O alkol içmez." },
      { type: "example", en: "We eat out once a week.", tr: "Haftada bir dışarıda yemek yeriz." },
      { type: "example", en: "Does your father go to work by bus?", tr: "Baban işe otobüsle mi gider?" },
    ],
  },
  {
    fileBase: "03_Gelecek_Zaman",
    title: "GELECEK ZAMAN (FUTURE SIMPLE - WILL)",
    blocks: [
      { type: "rule", text: "Gelecek zaman; anlık kararları, tahminleri, sözleri ve gelecekte olacak olayları anlatmak için kullanılır." },
      { type: "rule", text: "Yapı: Özne + WILL + Fiil (yalın hal). WILL bütün öznelerde aynı kalır, hiçbir özneye göre değişmez." },
      { type: "pattern", text: "I / YOU / HE / SHE / IT / WE / THEY + WILL + V1" },
      { type: "example", en: "I will rest.", tr: "Dinleneceğim." },
      { type: "example", en: "She will call you tomorrow.", tr: "O sana yarın telefon edecek." },
      { type: "example", en: "We will travel to Italy next year.", tr: "Gelecek yıl İtalya'ya seyahat edeceğiz." },
      { type: "rule", text: "Konuşma dilinde WILL genellikle kısaltılarak \"'LL\" olarak kullanılır." },
      { type: "example", en: "I'll do my best.", tr: "Elimden gelenin en iyisini yapacağım." },
      { type: "example", en: "She'll be here soon.", tr: "O yakında burada olacak." },
      { type: "rule", text: "Olumsuz yapı: Özne + WON'T (WILL NOT) + Fiil (yalın hal)." },
      { type: "pattern", text: "ÖZNE + WON'T + V1" },
      { type: "example", en: "They won't accept this offer.", tr: "Onlar bu teklifi kabul etmeyecekler." },
      { type: "example", en: "He won't be late again.", tr: "O bir daha geç kalmayacak." },
      { type: "rule", text: "Soru yapısı: WILL + Özne + Fiil (yalın hal)?" },
      { type: "pattern", text: "WILL + ÖZNE + V1 ?" },
      { type: "example", en: "Will you come to the party?", tr: "Partiye gelecek misin?" },
      { type: "example", en: "Will he finish the project on time?", tr: "O projeyi zamanında bitirecek mi?" },
      { type: "example", en: "Won't they join us?", tr: "Onlar bize katılmayacaklar mı?" },
      { type: "rule", text: "WILL ayrıca konuşma anında verilen sözlerde ve gönüllü tekliflerde de sıkça kullanılır." },
      { type: "example", en: "Don't worry, I'll help you.", tr: "Merak etme, sana yardım edeceğim." },
      { type: "example", en: "I'll carry that bag for you.", tr: "O çantayı senin için taşıyacağım." },
      { type: "rule", text: "Gelecekle ilgili tahminlerde WILL kullanılır; genellikle I THINK, I GUESS gibi ifadelerle birlikte gelir." },
      { type: "example", en: "I guess it will rain tomorrow.", tr: "Sanırım yarın yağmur yağacak." },
      { type: "example", en: "I think she will like this gift.", tr: "Sanırım o bu hediyeyi sevecek." },
      { type: "rule", text: "WILL, gelecek zaman zarflarıyla (tomorrow, next week, next year, soon) birlikte sıkça kullanılır." },
      { type: "example", en: "We will see you soon.", tr: "Seni yakında göreceğiz." },
      { type: "example", en: "He will arrive next Monday.", tr: "O gelecek pazartesi varacak." },
      { type: "rule", text: "SHALL kelimesi de bazen I/WE özneleriyle birlikte WILL yerine kullanılabilir, fakat günlük konuşmada oldukça nadirdir ve daha çok teklif sorularında görülür (Shall we go?)." },
      { type: "example", en: "Shall we start now?", tr: "Şimdi başlayalım mı?" },
      { type: "rule", text: "Bundan sonraki derslerde göreceğimiz birçok örnek cümlede WILL kullanılacağından bu yapı çok iyi öğrenilmelidir." },
      { type: "rule", text: "\"CALL\" fiili üzerinden bütün öznelerle tam çekim tablosunu inceleyelim." },
      { type: "pattern", text: "CALL (OLUMLU)" },
      { type: "example", en: "I will call the office tomorrow.", tr: "Yarın ofisi arayacağım." },
      { type: "example", en: "You will call the office tomorrow.", tr: "Yarın ofisi arayacaksın." },
      { type: "example", en: "He will call the office tomorrow.", tr: "O yarın ofisi arayacak." },
      { type: "example", en: "She will call the office tomorrow.", tr: "O (kadın) yarın ofisi arayacak." },
      { type: "example", en: "We will call the office tomorrow.", tr: "Yarın ofisi arayacağız." },
      { type: "example", en: "They will call the office tomorrow.", tr: "Onlar yarın ofisi arayacaklar." },
      { type: "pattern", text: "CALL (OLUMSUZ)" },
      { type: "example", en: "I won't call him again.", tr: "Onu bir daha aramayacağım." },
      { type: "example", en: "She won't call you today.", tr: "O bugün seni aramayacak." },
      { type: "example", en: "We won't call them without a reason.", tr: "Onları sebepsiz aramayacağız." },
      { type: "pattern", text: "CALL (SORU)" },
      { type: "example", en: "Will you call me later?", tr: "Beni sonra arayacak mısın?" },
      { type: "example", en: "Will she call the client today?", tr: "O bugün müşteriyi arayacak mı?" },
      { type: "example", en: "Will they call before they arrive?", tr: "Onlar varmadan önce arayacaklar mı?" },
      { type: "rule", text: "WILL kullanılan daha fazla günlük örnekle bu dersi pekiştirelim." },
      { type: "example", en: "The economy will grow next year.", tr: "Ekonomi gelecek yıl büyüyecek." },
      { type: "example", en: "It won't be easy, but we will manage.", tr: "Kolay olmayacak ama başaracağız." },
      { type: "example", en: "I promise I will pay you back.", tr: "Sana geri ödeyeceğime söz veriyorum." },
      { type: "example", en: "She will probably be late.", tr: "O muhtemelen geç kalacak." },
      { type: "example", en: "We will let you know as soon as possible.", tr: "Sana mümkün olan en kısa zamanda haber vereceğiz." },
      { type: "example", en: "Will there be enough food for everyone?", tr: "Herkese yetecek kadar yemek olacak mı?" },
      { type: "example", en: "He will definitely pass the exam.", tr: "O kesinlikle sınavı geçecek." },
      { type: "example", en: "I won't forget your birthday.", tr: "Doğum gününü unutmayacağım." },
      { type: "rule", text: "WILL ile GOING TO arasındaki fark: WILL genellikle anlık kararlarda, GOING TO ise önceden planlanmış niyetlerde kullanılır. Bu kitapta GOING TO yapısı ayrıntılı işlenmez, ama farkının bilinmesi faydalıdır." },
      { type: "example", en: "I'm hungry, I will make a sandwich. (anlık karar)", tr: "Açım, bir sandviç yapacağım." },
      { type: "example", en: "We are going to visit Paris next month. (önceden plan)", tr: "Gelecek ay Paris'i ziyaret edeceğiz." },
      { type: "rule", text: "WILL ile kurulmuş daha fazla soru-cevap alıştırması yapalım." },
      { type: "example", en: "What will you do this weekend? I will visit my parents.", tr: "Bu hafta sonu ne yapacaksın? Ailemi ziyaret edeceğim." },
      { type: "example", en: "Where will they stay? They will stay at a hotel.", tr: "Onlar nerede kalacaklar? Bir otelde kalacaklar." },
      { type: "example", en: "How will you get there? I will take a taxi.", tr: "Oraya nasıl gideceksin? Taksiye bineceğim." },
      { type: "example", en: "Who will pick up the kids? I will.", tr: "Çocukları kim alacak? Ben alacağım." },
      { type: "rule", text: "WILL'in NEVER, ALWAYS gibi zarflarla birlikte kullanımını görelim." },
      { type: "example", en: "I will never give up.", tr: "Asla vazgeçmeyeceğim." },
      { type: "example", en: "She will always remember this day.", tr: "O bu günü her zaman hatırlayacak." },
      { type: "example", en: "We will definitely come next time.", tr: "Bir dahaki sefere kesinlikle geleceğiz." },
      { type: "rule", text: "\"START\" fiili üzerinden bir tam çekim tablosu daha görelim." },
      { type: "pattern", text: "START (OLUMLU / OLUMSUZ / SORU)" },
      { type: "example", en: "I will start my new job on Monday.", tr: "Yeni işime pazartesi başlayacağım." },
      { type: "example", en: "You will start the course next week.", tr: "Kursa gelecek hafta başlayacaksın." },
      { type: "example", en: "He will start cooking soon.", tr: "O yakında yemek yapmaya başlayacak." },
      { type: "example", en: "She won't start until everyone arrives.", tr: "Herkes gelene kadar başlamayacak." },
      { type: "example", en: "We won't start the meeting without him.", tr: "O olmadan toplantıya başlamayacağız." },
      { type: "example", en: "Will they start the project this month?", tr: "Onlar bu ay projeye başlayacak mı?" },
      { type: "example", en: "Will you start early tomorrow?", tr: "Yarın erken mi başlayacaksın?" },
      { type: "rule", text: "Günlük hayattan daha fazla WILL cümlesi ile bu dersi tamamlayalım." },
      { type: "example", en: "The prices will increase next month.", tr: "Fiyatlar gelecek ay artacak." },
      { type: "example", en: "I won't be able to attend the party.", tr: "Partiye katılamayacağım." },
      { type: "example", en: "She will graduate next year.", tr: "O gelecek yıl mezun olacak." },
      { type: "example", en: "We will need more time.", tr: "Daha fazla zamana ihtiyacımız olacak." },
      { type: "rule", text: "Son olarak WILL ile kurulmuş birkaç örnek daha ekleyerek bu dersi tamamlayalım." },
      { type: "example", en: "The weather will be nice this weekend.", tr: "Bu hafta sonu hava güzel olacak." },
      { type: "example", en: "I will text you when I get there.", tr: "Oraya vardığımda sana mesaj atacağım." },
      { type: "example", en: "They will probably cancel the flight.", tr: "Muhtemelen uçuşu iptal edecekler." },
      { type: "example", en: "Will the store be open on Sunday?", tr: "Mağaza pazar günü açık olacak mı?" },
      { type: "example", en: "She won't change her mind easily.", tr: "O fikrini kolayca değiştirmeyecek." },
      { type: "example", en: "We will find a solution together.", tr: "Birlikte bir çözüm bulacağız." },
    ],
  },
  {
    fileBase: "04_Modallar_ve_Ihtiyac",
    title: "MODALLAR VE İHTİYAÇ KALIPLARI",
    blocks: [
      { type: "pattern", text: "CAN = yapabilmek (yetenek, izin) / SHOULD = yapmalı (öneri, tavsiye)" },
      { type: "example", en: "He can speak three languages.", tr: "O üç dil konuşabilir." },
      { type: "example", en: "You should sleep early.", tr: "Erken uyumalısın." },
      { type: "example", en: "Can I open the window?", tr: "Pencereyi açabilir miyim?" },
      { type: "example", en: "You shouldn't smoke.", tr: "Sigara içmemelisin." },
      { type: "rule", text: "CAN ve SHOULD'dan sonra fiil her zaman yalın halde kullanılır; hiçbir özneye göre değişmez." },
      { type: "pattern", text: "İyelik sıfatları: MY (benim) / YOUR (senin) / HIS (onun-erkek) / HER (onun-kız) / OUR (bizim) / YOUR (sizin) / THEIR (onların)" },
      { type: "example", en: "This is my book, that is your pen.", tr: "Bu benim kitabım, o senin kalemin." },
      { type: "example", en: "Their house is bigger than our house.", tr: "Onların evi bizim evimizden daha büyük." },
      { type: "example", en: "Is this her bag or his bag?", tr: "Bu onun (kız) çantası mı yoksa onun (erkek) çantası mı?" },
      { type: "rule", text: "NEED (ihtiyaç duymak) fiilinden sonra gelen tekil sayılabilir isimlerde A/AN kullanılır. A ünsüzle başlayan kelimelerde, AN ise ünlüyle başlayan kelimelerde kullanılır." },
      { type: "example", en: "I need a book and a pen.", tr: "Bir kitaba ve bir kaleme ihtiyacım var." },
      { type: "example", en: "Do you need more money or more time?", tr: "Daha fazla paraya mı yoksa daha fazla zamana mı ihtiyacın var?" },
      { type: "example", en: "She needs a desk for her room.", tr: "Onun odası için bir masaya ihtiyacı var." },
      { type: "rule", text: "WHICH (hangi) sorusu belirli bir seçenek grubu içinden seçim yapıldığında kullanılır." },
      { type: "example", en: "Which book do you need?", tr: "Hangi kitaba ihtiyacın var?" },
      { type: "example", en: "Which one do you like more?", tr: "Hangisini daha çok beğeniyorsun?" },
      { type: "pattern", text: "READ = okumak / WRITE = yazmak / BOOK, NEWSPAPER, MAGAZINE, LETTER = kitap, gazete, dergi, mektup" },
      { type: "example", en: "I read the newspaper and write letters every morning.", tr: "Her sabah gazete okur ve mektup yazarım." },
      { type: "example", en: "Does he read magazines?", tr: "O dergi okur mu?" },
      { type: "pattern", text: "BUY = satın almak / SELL = satmak" },
      { type: "example", en: "He wants to sell his car and buy a new one.", tr: "O arabasını satmak ve yeni bir tane satın almak istiyor." },
      { type: "example", en: "They don't sell this product anymore.", tr: "Onlar bu ürünü artık satmıyor." },
      { type: "rule", text: "Bu derste geçen kalıpları bir sonraki dersteki AM-IS-ARE konusuyla birlikte cümlelerde daha çok kullanacağız." },
      { type: "rule", text: "CAN modalının bütün özneler için kullanımını daha fazla örnekle pekiştirelim." },
      { type: "pattern", text: "CAN (OLUMLU / OLUMSUZ / SORU)" },
      { type: "example", en: "I can drive a car.", tr: "Araba kullanabilirim." },
      { type: "example", en: "You can drive a car.", tr: "Araba kullanabilirsin." },
      { type: "example", en: "He can drive a car.", tr: "O araba kullanabilir." },
      { type: "example", en: "She can't drive a car.", tr: "O araba kullanamaz." },
      { type: "example", en: "We can't drive a car.", tr: "Araba kullanamayız." },
      { type: "example", en: "Can they drive a car?", tr: "Onlar araba kullanabilir mi?" },
      { type: "example", en: "Can you help me with this?", tr: "Bununla bana yardım edebilir misin?" },
      { type: "rule", text: "SHOULD modalının bütün özneler için kullanımını daha fazla örnekle pekiştirelim." },
      { type: "pattern", text: "SHOULD (OLUMLU / OLUMSUZ / SORU)" },
      { type: "example", en: "I should study more.", tr: "Daha fazla ders çalışmalıyım." },
      { type: "example", en: "You should study more.", tr: "Daha fazla ders çalışmalısın." },
      { type: "example", en: "He should study more.", tr: "O daha fazla ders çalışmalı." },
      { type: "example", en: "She shouldn't eat too much sugar.", tr: "O çok fazla şeker yememeli." },
      { type: "example", en: "We should leave now.", tr: "Şimdi ayrılmalıyız." },
      { type: "example", en: "Should they apologize?", tr: "Onlar özür dilemeli mi?" },
      { type: "example", en: "Should I tell him the truth?", tr: "Ona gerçeği söylemeli miyim?" },
      { type: "rule", text: "İyelik sıfatlarıyla daha fazla örnek cümle kuralım." },
      { type: "example", en: "My favorite color is blue.", tr: "En sevdiğim renk mavi." },
      { type: "example", en: "Your idea is very good.", tr: "Fikrin çok iyi." },
      { type: "example", en: "His office is on the third floor.", tr: "Onun (erkek) ofisi üçüncü katta." },
      { type: "example", en: "Her presentation was excellent.", tr: "Onun (kadın) sunumu mükemmeldi." },
      { type: "example", en: "Our company is growing fast.", tr: "Şirketimiz hızla büyüyor." },
      { type: "example", en: "Their plan didn't work.", tr: "Onların planı işe yaramadı." },
      { type: "rule", text: "NEED, WHICH ve BUY-SELL kalıplarıyla karışık alıştırma cümleleri kuralım." },
      { type: "example", en: "We need an umbrella, it's raining.", tr: "Bir şemsiyeye ihtiyacımız var, yağmur yağıyor." },
      { type: "example", en: "Which restaurant do you recommend?", tr: "Hangi restoranı tavsiye edersin?" },
      { type: "example", en: "Which of these two do you prefer?", tr: "Bu ikisinden hangisini tercih edersin?" },
      { type: "example", en: "I need to buy new shoes.", tr: "Yeni ayakkabılara ihtiyacım var." },
      { type: "example", en: "Do you need a hand with the boxes?", tr: "Kutularla yardıma ihtiyacın var mı?" },
      { type: "example", en: "He sells vegetables at the market.", tr: "O pazarda sebze satar." },
      { type: "example", en: "We don't need any more chairs.", tr: "Daha fazla sandalyeye ihtiyacımız yok." },
      { type: "example", en: "She reads a book every week.", tr: "O her hafta bir kitap okur." },
      { type: "rule", text: "CAN'in izin anlamındaki kullanımına ve MUST/HAVE TO'ya kısaca değinelim (bu yapılar ileride ayrıntılı işlenecektir)." },
      { type: "example", en: "You can leave early today.", tr: "Bugün erken çıkabilirsin." },
      { type: "example", en: "Can I use your phone for a minute?", tr: "Telefonunu bir dakikalığına kullanabilir miyim?" },
      { type: "rule", text: "SHOULD ile tavsiye veren daha fazla günlük hayat cümlesi kuralım." },
      { type: "example", en: "You should see a doctor.", tr: "Bir doktora görünmelisin." },
      { type: "example", en: "We should book the tickets now.", tr: "Biletleri şimdi almalıyız." },
      { type: "example", en: "They shouldn't waste their money.", tr: "Onlar paralarını boşa harcamamalı." },
      { type: "rule", text: "İyelik sıfatları ve NEED kalıbı ile daha fazla karışık örnek görelim." },
      { type: "example", en: "My keys are on the table.", tr: "Anahtarlarım masanın üstünde." },
      { type: "example", en: "Your answer is correct.", tr: "Cevabın doğru." },
      { type: "example", en: "We need your help with this project.", tr: "Bu projede senin yardımına ihtiyacımız var." },
      { type: "example", en: "Do they need a bigger house?", tr: "Onların daha büyük bir eve ihtiyacı var mı?" },
      { type: "example", en: "I don't need your permission.", tr: "İznine ihtiyacım yok." },
      { type: "rule", text: "Bu dersteki bütün kalıpları içeren karışık bir alıştırma bölümüyle konuyu tamamlayalım." },
      { type: "example", en: "Can she speak in front of a large audience?", tr: "O büyük bir topluluğun önünde konuşabilir mi?" },
      { type: "example", en: "You shouldn't compare yourself to others.", tr: "Kendini başkalarıyla kıyaslamamalısın." },
      { type: "example", en: "His new car is very expensive.", tr: "Onun yeni arabası çok pahalı." },
      { type: "example", en: "Which of these options is better?", tr: "Bu seçeneklerden hangisi daha iyi?" },
      { type: "example", en: "I need an answer as soon as possible.", tr: "Mümkün olan en kısa zamanda bir cevaba ihtiyacım var." },
      { type: "example", en: "Can you buy some bread on your way home?", tr: "Eve gelirken biraz ekmek alabilir misin?" },
      { type: "rule", text: "Bu dersteki modal ve ihtiyaç kalıplarını içeren birkaç günlük diyalog cümlesiyle konuyu tamamlayalım." },
      { type: "example", en: "Can you pass me the salt, please?", tr: "Bana tuzu uzatabilir misin lütfen?" },
      { type: "example", en: "You should apologize to her.", tr: "Ondan özür dilemelisin." },
      { type: "example", en: "My brother needs a new laptop.", tr: "Kardeşimin yeni bir dizüstü bilgisayara ihtiyacı var." },
      { type: "example", en: "Which subject do you find most difficult?", tr: "Hangi dersi en zor buluyorsun?" },
      { type: "example", en: "We should thank them for their help.", tr: "Yardımları için onlara teşekkür etmeliyiz." },
      { type: "example", en: "Can birds see colors?", tr: "Kuşlar renkleri görebilir mi?" },
    ],
  },
];

async function main() {
  for (const lesson of lessons) {
    const p = await writeLessonDocx(OUT_DIR, lesson);
    console.log("Yazıldı:", p);
  }
}

main();
