import { publishQuiz, prisma, QuizDef } from "./lib/quiz-lib";

const ZAMANLAR = "İngilizce - Zamanlar";
const KELIME = "İngilizce - Kelime ve Kalıplar";

const quizzes: QuizDef[] = [
  {
    title: "10 Could Kalıpları ve Anlaşma-Memnuniyet İfadeleri - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "COULD-1'in kullanımı nedir?", optionA: "Kibar rica", optionB: "Geçmişteki yetenek", optionC: "Gelecek olasılık", optionD: "Zorunluluk", correct: "B" },
      { prompt: "COULD-2'nin kullanımı nedir?", optionA: "Kibar rica", optionB: "Geçmişteki yetenek", optionC: "Zorunluluk", optionD: "İzin yok", correct: "A" },
      { prompt: "___ you open the window? (kibarca rica)", optionA: "Must", optionB: "Should", optionC: "Could", optionD: "Need", correct: "C" },
      { prompt: "I ___ swim when I was five. (geçmişteki yetenek)", optionA: "can", optionB: "could", optionC: "will", optionD: "should", correct: "B" },
      { prompt: "We couldn't ___ an agreement.", optionA: "reach", optionB: "reaches", optionC: "reaching", optionD: "reached", correct: "A" },
      { prompt: "Are you satisfied ___ the service?", optionA: "of", optionB: "with", optionC: "at", optionD: "for", correct: "B" },
      { prompt: "\"Hizmet\" kelimesinin İngilizcesi nedir?", optionA: "service", optionB: "accommodation", optionC: "product", optionD: "quality", correct: "A" },
      { prompt: "\"Konaklama\" kelimesinin İngilizcesi nedir?", optionA: "service", optionB: "accommodation", optionC: "reservation", optionD: "hotel", correct: "B" },
      { prompt: "Could you please ___ the bill?", optionA: "pay", optionB: "pays", optionC: "paying", optionD: "paid", correct: "A" },
      { prompt: "COULD HAVE + V3 kalıbı ne anlatır?", optionA: "Şimdiki yetenek", optionB: "Geçmişte yapılabilecek ama yapılmamış eylem", optionC: "Gelecek zorunluluk", optionD: "Şu anki izin", correct: "B" },
      { prompt: "You ___ have told me earlier! (pişmanlık)", optionA: "could", optionB: "can", optionC: "must", optionD: "should has", correct: "A" },
      { prompt: "We are trying to reach an ___ with them.", optionA: "agreement", optionB: "argument", optionC: "disagreement", optionD: "discussion", correct: "A" },
      { prompt: "I am ___ with your work. (memnun)", optionA: "satisfy", optionB: "satisfied", optionC: "satisfying", optionD: "satisfaction", correct: "B" },
      { prompt: "Could I ___ you a question?", optionA: "ask", optionB: "asks", optionC: "asking", optionD: "asked", correct: "A" },
      { prompt: "Would you ___ closing the door? (sakıncası var mı)", optionA: "mind", optionB: "minds", optionC: "minding", optionD: "minded", correct: "A" },
      { prompt: "COULD, CAN'e göre nasıldır?", optionA: "Daha az kibar", optionB: "Daha kibar", optionC: "Aynı anlamda", optionD: "Sadece geçmiş için kullanılır", correct: "B" },
      { prompt: "They finally came to a decision after a long ___. (tartışma)", optionA: "discussion", optionB: "agreement", optionC: "service", optionD: "accommodation", correct: "A" },
      { prompt: "The hotel ___ wasn't satisfying at all.", optionA: "service", optionB: "accommodation", optionC: "reservation", optionD: "quality", correct: "A" },
      { prompt: "___ they speak English when they were children?", optionA: "Did", optionB: "Could", optionC: "Do", optionD: "Can", correct: "B" },
      { prompt: "We couldn't finish it ___ time. (zamanında)", optionA: "at", optionB: "on", optionC: "in", optionD: "for", correct: "B" },
    ],
  },
  {
    title: "11 \"-Meni / -Manı\" İstek Kalıpları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "WANT + kişi + TO + V1 kalıbında istenilen kişi nasıl konumlanır?", optionA: "Özne", optionB: "Nesne", optionC: "Zarf", optionD: "Sıfat", correct: "B" },
      { prompt: "I want you ___ come. (gelmeni istiyorum)", optionA: "come", optionB: "to come", optionC: "coming", optionD: "came", correct: "B" },
      { prompt: "She wants them ___ leave.", optionA: "leave", optionB: "to leave", optionC: "leaving", optionD: "left", correct: "B" },
      { prompt: "WOULD LIKE, WANT'a göre nasıldır?", optionA: "Daha kaba", optionB: "Daha kibar", optionC: "Aynı", optionD: "Kullanılmaz", correct: "B" },
      { prompt: "I asked him ___ close the door. (rica)", optionA: "close", optionB: "to close", optionC: "closing", optionD: "closed", correct: "B" },
      { prompt: "The doctor told him ___ rest. (talimat)", optionA: "rest", optionB: "to rest", optionC: "resting", optionD: "rested", correct: "B" },
      { prompt: "ASK ile TELL arasındaki fark nedir?", optionA: "Fark yok", optionB: "ASK rica, TELL talimat/emir", optionC: "ASK emir, TELL rica", optionD: "İkisi de aynı anlamda", correct: "B" },
      { prompt: "My parents don't allow me ___ stay out late.", optionA: "stay", optionB: "to stay", optionC: "staying", optionD: "stayed", correct: "B" },
      { prompt: "MAKE fiilinden sonra TO kullanılır mı?", optionA: "Evet her zaman", optionB: "Hayır, kullanılmaz", optionC: "Bazen", optionD: "Sadece olumsuzda", correct: "B" },
      { prompt: "My boss made me ___ late. (TO'suz)", optionA: "stay", optionB: "to stay", optionC: "staying", optionD: "stayed", correct: "A" },
      { prompt: "LET fiilinden sonra TO kullanılır mı?", optionA: "Evet", optionB: "Hayır", optionC: "Bazen", optionD: "Sadece soruda", correct: "B" },
      { prompt: "My parents let me ___ to the concert.", optionA: "go", optionB: "to go", optionC: "going", optionD: "went", correct: "A" },
      { prompt: "HELP fiilinden sonra hangi kullanım(lar) doğrudur?", optionA: "Sadece TO'lu", optionB: "Sadece TO'suz", optionC: "Her ikisi de doğru", optionD: "Hiçbiri", correct: "C" },
      { prompt: "I don't expect you ___ understand.", optionA: "understand", optionB: "to understand", optionC: "understanding", optionD: "understood", correct: "B" },
      { prompt: "\"Beklenti\" kelimesinin İngilizcesi nedir?", optionA: "expect", optionB: "expectation", optionC: "expected", optionD: "expecting", correct: "B" },
      { prompt: "She asked me ___ tell anyone. (olumsuz istek)", optionA: "not to", optionB: "to not", optionC: "don't", optionD: "no to", correct: "A" },
      { prompt: "The teacher warned the students ___ cheat.", optionA: "not to", optionB: "to not", optionC: "don't", optionD: "no", correct: "A" },
      { prompt: "I encouraged him ___ apply for the job.", optionA: "apply", optionB: "to apply", optionC: "applying", optionD: "applied", correct: "B" },
      { prompt: "\"Eşlik etmek\" kelimesinin İngilizcesi nedir?", optionA: "accompany", optionB: "accomplish", optionC: "accommodate", optionD: "company", correct: "A" },
      { prompt: "They invited us ___ join their wedding.", optionA: "join", optionB: "to join", optionC: "joining", optionD: "joined", correct: "B" },
    ],
  },
  {
    title: "7 Yakın Geçmişin Şimdiki Hali (Present Perfect Continuous) - Test",
    subject: ZAMANLAR,
    creditCost: 1,
    questions: [
      { prompt: "Present Perfect Continuous yapısı nedir?", optionA: "HAVE/HAS BEEN + V-ing", optionB: "HAVE/HAS + V3", optionC: "HAD BEEN + V-ing", optionD: "WILL BE + V-ing", correct: "A" },
      { prompt: "I have been working here ___ five years.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "She has been waiting ___ morning.", optionA: "for", optionB: "since", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "Present Perfect ile Present Perfect Continuous arasındaki fark nedir?", optionA: "Fark yok", optionB: "Biri sonuç, diğeri süreç vurgular", optionC: "İkisi de aynı", optionD: "Biri gelecek içindir", correct: "B" },
      { prompt: "I'm tired because I have been ___ all day.", optionA: "work", optionB: "working", optionC: "worked", optionD: "works", correct: "B" },
      { prompt: "How long have you been ___ English?", optionA: "study", optionB: "studying", optionC: "studied", optionD: "studies", correct: "B" },
      { prompt: "KNOW, BELIEVE gibi durum fiilleriyle hangi tense tercih edilir?", optionA: "Present Perfect Continuous", optionB: "Present Perfect Simple", optionC: "Present Continuous", optionD: "Past Continuous", correct: "B" },
      { prompt: "It has been raining ___ day.", optionA: "all", optionB: "since", optionC: "for", optionD: "ago", correct: "A" },
      { prompt: "They haven't been talking ___ each other.", optionA: "with", optionB: "to", optionC: "at", optionD: "for", correct: "B" },
      { prompt: "Her eyes are red because she has been ___.", optionA: "cry", optionB: "crying", optionC: "cried", optionD: "cries", correct: "B" },
      { prompt: "FOR ile SINCE arasındaki fark nedir?", optionA: "FOR süre miktarı, SINCE başlangıç noktası", optionB: "Fark yok", optionC: "FOR başlangıç, SINCE süre", optionD: "İkisi de süre bildirir", correct: "A" },
      { prompt: "What have you been ___ lately?", optionA: "do", optionB: "doing", optionC: "did", optionD: "does", correct: "B" },
      { prompt: "Present Perfect Continuous'un olumsuz yapısı nedir?", optionA: "HAVEN'T/HASN'T BEEN + V-ing", optionB: "DIDN'T + V1", optionC: "ISN'T + V-ing", optionD: "WON'T BE + V-ing", correct: "A" },
      { prompt: "I have been learning Spanish ___ six months.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "You're all sweaty, have you been ___?", optionA: "exercise", optionB: "exercising", optionC: "exercised", optionD: "exercises", correct: "B" },
      { prompt: "He has been smoking ___ ten years.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "Present Perfect Continuous en çok hangi soru kelimesiyle kullanılır?", optionA: "WHAT", optionB: "HOW LONG", optionC: "WHERE", optionD: "WHO", correct: "B" },
      { prompt: "I have been trying to reach him ___ days.", optionA: "since", optionB: "for", optionC: "ago", optionD: "at", correct: "B" },
      { prompt: "Tek heceli, ünlü+ünsüzle biten fiillere -ING eklenirken ne olur?", optionA: "Son ünsüz ikiye katlanır", optionB: "Değişmez", optionC: "E düşer", optionD: "Y eklenir", correct: "A" },
      { prompt: "She has been living abroad ___ her life.", optionA: "all", optionB: "since", optionC: "for", optionD: "ago", correct: "A" },
    ],
  },
  {
    title: "12 Miktar Belirteçleri ve Farklı Kalıplar - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "MANY hangi isimlerle kullanılır?", optionA: "Sayılabilir çoğul", optionB: "Sayılamaz", optionC: "Tekil", optionD: "Özel isim", correct: "A" },
      { prompt: "MUCH hangi isimlerle kullanılır?", optionA: "Sayılabilir çoğul", optionB: "Sayılamaz", optionC: "Tekil", optionD: "Özel isim", correct: "B" },
      { prompt: "How ___ books did you read?", optionA: "much", optionB: "many", optionC: "few", optionD: "little", correct: "B" },
      { prompt: "How ___ money do you need?", optionA: "much", optionB: "many", optionC: "few", optionD: "little", correct: "A" },
      { prompt: "A LOT OF hangi isimlerle kullanılabilir?", optionA: "Sadece sayılabilir", optionB: "Sadece sayılamaz", optionC: "Her ikisiyle de", optionD: "Hiçbiriyle", correct: "C" },
      { prompt: "A FEW hangi isimlerle kullanılır?", optionA: "Sayılabilir", optionB: "Sayılamaz", optionC: "Her ikisi", optionD: "Hiçbiri", correct: "A" },
      { prompt: "A LITTLE hangi isimlerle kullanılır?", optionA: "Sayılabilir", optionB: "Sayılamaz", optionC: "Her ikisi", optionD: "Hiçbiri", correct: "B" },
      { prompt: "I have a few friends, so I'm not ___.", optionA: "lonely", optionB: "hungry", optionC: "tired", optionD: "busy", correct: "A" },
      { prompt: "There is a little sugar ___ in the jar.", optionA: "left", optionB: "leave", optionC: "leaving", optionD: "leaves", correct: "A" },
      { prompt: "SEVERAL kelimesi ne anlama gelir?", optionA: "Hiç", optionB: "Birkaç", optionC: "Çok az", optionD: "Hepsi", correct: "B" },
      { prompt: "ENOUGH isimden önce mi sonra mı gelir?", optionA: "Önce", optionB: "Sonra", optionC: "Ortasında", optionD: "Fark etmez", correct: "A" },
      { prompt: "Is this box big ___ for all these books?", optionA: "enough", optionB: "too", optionC: "very", optionD: "so", correct: "A" },
      { prompt: "There are ___ many people in this room.", optionA: "too", optionB: "enough", optionC: "so", optionD: "very", correct: "A" },
      { prompt: "PLENTY OF ne anlama gelir?", optionA: "Çok az", optionB: "Bol miktarda", optionC: "Hiç yok", optionD: "Biraz", correct: "B" },
      { prompt: "A NUMBER OF hangi fiil ile kullanılır?", optionA: "Tekil", optionB: "Çoğul", optionC: "Fark etmez", optionD: "Hiçbiri", correct: "B" },
      { prompt: "THE NUMBER OF hangi fiil ile kullanılır?", optionA: "Tekil", optionB: "Çoğul", optionC: "Fark etmez", optionD: "Hiçbiri", correct: "A" },
      { prompt: "BOTH...AND ne anlama gelir?", optionA: "Ya...ya da", optionB: "Hem...hem de", optionC: "Ne...ne de", optionD: "Sadece bir tanesi", correct: "B" },
      { prompt: "NEITHER...NOR ne anlama gelir?", optionA: "Hem...hem de", optionB: "Ya...ya da", optionC: "Ne...ne de", optionD: "Hepsi", correct: "C" },
      { prompt: "EITHER...OR ne anlama gelir?", optionA: "Hem...hem de", optionB: "Ya...ya da", optionC: "Ne...ne de", optionD: "Hiçbiri", correct: "B" },
      { prompt: "THE MAJORITY OF ne anlama gelir?", optionA: "Azınlık", optionB: "Çoğunluk", optionC: "Yarısı", optionD: "Hiçbiri", correct: "B" },
    ],
  },
  {
    title: "13 That ve Soru Kelimesi Bağlaçları - Test",
    subject: KELIME,
    creditCost: 1,
    questions: [
      { prompt: "THAT bağlacı ne anlama gelir?", optionA: "-ki, -dığını", optionB: "Ve", optionC: "Ama", optionD: "Veya", correct: "A" },
      { prompt: "I am sure ___ he isn't at home.", optionA: "that", optionB: "what", optionC: "who", optionD: "where", correct: "A" },
      { prompt: "Günlük konuşmada THAT genellikle ne yapılır?", optionA: "Zorunlu kullanılır", optionB: "Düşürülebilir", optionC: "İkiye katlanır", optionD: "Yerine WHAT kullanılır", correct: "B" },
      { prompt: "I don't know ___ they meet. (nerede)", optionA: "that", optionB: "where", optionC: "who", optionD: "what", correct: "B" },
      { prompt: "Bağlı sorularda (embedded questions) cümle sırası nasıldır?", optionA: "Soru sırası", optionB: "Düz cümle sırası", optionC: "Ters çevrilir", optionD: "Fark etmez", correct: "B" },
      { prompt: "I don't know where ___ is. (doğru kullanım)", optionA: "is he", optionB: "he is", optionC: "does he", optionD: "he does", correct: "B" },
      { prompt: "IF/WHETHER hangi tür sorularda kullanılır?", optionA: "Evet/hayır soruları", optionB: "Soru kelimeli sorular", optionC: "Emir cümleleri", optionD: "Ünlem cümleleri", correct: "A" },
      { prompt: "I don't know ___ he is coming. (olup olmadığını)", optionA: "that", optionB: "if", optionC: "who", optionD: "which", correct: "B" },
      { prompt: "WHETHER...OR NOT ne anlama gelir?", optionA: "-olsun ya da olmasın", optionB: "-mediği sürece", optionC: "-dığı zaman", optionD: "-meden önce", correct: "A" },
      { prompt: "SORU KELİMESİ + TO + V1 kalıbında özne tekrarlanır mı?", optionA: "Evet", optionB: "Hayır", optionC: "Bazen", optionD: "Sadece soruda", correct: "B" },
      { prompt: "I don't know what ___. (ne yapacağımı)", optionA: "to do", optionB: "do", optionC: "doing", optionD: "did", correct: "A" },
      { prompt: "SAY fiili kişi nesnesi alır mı?", optionA: "Evet, her zaman", optionB: "Hayır, almaz", optionC: "Bazen", optionD: "Sadece olumsuzda", correct: "B" },
      { prompt: "TELL fiili kişi nesnesi alır mı?", optionA: "Evet, mutlaka alır", optionB: "Hayır", optionC: "Bazen", optionD: "Asla", correct: "A" },
      { prompt: "He ___ me that he was busy. (doğru fiil)", optionA: "said", optionB: "told", optionC: "says", optionD: "tells", correct: "B" },
      { prompt: "WONDER fiili genellikle hangi bağlaçlarla kullanılır?", optionA: "AND, BUT", optionB: "IF/WHETHER, soru kelimeleri", optionC: "BECAUSE", optionD: "ALTHOUGH", correct: "B" },
      { prompt: "LOOK FORWARD TO'dan sonra fiil hangi halde olur?", optionA: "V1", optionB: "V-ing", optionC: "V3", optionD: "V2", correct: "B" },
      { prompt: "We look forward to ___ you.", optionA: "see", optionB: "seeing", optionC: "saw", optionD: "seen", correct: "B" },
      { prompt: "I'm not sure ___ this is the right decision.", optionA: "that", optionB: "who", optionC: "whose", optionD: "which", correct: "A" },
      { prompt: "HEAR, NOTICE, FIND OUT fiilleri genellikle hangi bağlaçla kullanılır?", optionA: "THAT", optionB: "BUT", optionC: "OR", optionD: "SO", correct: "A" },
      { prompt: "Please let me know ___ you need anything. (eğer)", optionA: "that", optionB: "if", optionC: "who", optionD: "which", correct: "B" },
    ],
  },
];

async function main() {
  for (const quiz of quizzes) {
    await publishQuiz(quiz);
  }
}

main().finally(() => prisma.$disconnect());
