import { writeLessonDocx, LessonDef } from "./lib/lesson-docx";

const lesson: LessonDef = {
  fileBase: "01_Genis_Zaman",
  title: "GENİŞ ZAMAN (PRESENT SIMPLE)",
  blocks: [
    { type: "rule", text: "Geniş zaman; alışkanlıkları, günlük rutinleri, genel doğruları ve sürekli geçerli olan durumları anlatmak için kullanılır." },
    { type: "example", en: "The sun rises in the east.", tr: "Güneş doğudan doğar." },
    { type: "example", en: "Water boils at 100 degrees.", tr: "Su 100 derecede kaynar." },
    { type: "rule", text: "Yapı: Özne + Fiil (yalın hal). Fakat özne HE / SHE / IT olduğunda fiile -S veya -ES eklenir." },
    { type: "pattern", text: "I / YOU / WE / THEY + V1        HE / SHE / IT + V1(-s/-es)" },
    { type: "example", en: "I work every day.", tr: "Ben her gün çalışırım." },
    { type: "example", en: "She works every day.", tr: "O her gün çalışır." },
    { type: "example", en: "We live in Istanbul.", tr: "Biz İstanbul'da yaşarız." },
    { type: "example", en: "It rains a lot here.", tr: "Burada çok yağmur yağar." },
    { type: "rule", text: "-S / -ES eki kuralları: Fiil O, CH, SH, SS, X, Z ile bitiyorsa -ES eklenir (go-goes, watch-watches, wash-washes, miss-misses). Fiil sessiz harf + Y ile bitiyorsa Y, I'ya dönüşüp -ES eklenir (study-studies, carry-carries)." },
    { type: "example", en: "He goes to work by bus.", tr: "O işe otobüsle gider." },
    { type: "example", en: "She studies English every evening.", tr: "O her akşam İngilizce çalışır." },
    { type: "example", en: "He watches TV after dinner.", tr: "O akşam yemeğinden sonra televizyon izler." },
    { type: "example", en: "She carries a heavy bag every morning.", tr: "O her sabah ağır bir çanta taşır." },
    { type: "rule", text: "Fiil sessiz harf + Y ile değil de ünlü harf + Y ile bitiyorsa kural değişmez, sadece -S eklenir (play-plays, buy-buys)." },
    { type: "example", en: "He plays football on Saturdays.", tr: "O cumartesileri futbol oynar." },
    { type: "rule", text: "Olumsuz yapı: Özne + DON'T / DOESN'T + Fiil (yalın hal). HE / SHE / IT için DOESN'T kullanılır ve fiile -s/-es eklenmez." },
    { type: "pattern", text: "I / YOU / WE / THEY + DON'T + V1        HE / SHE / IT + DOESN'T + V1" },
    { type: "example", en: "I don't come here every day.", tr: "Ben buraya her gün gelmem." },
    { type: "example", en: "He doesn't speak French.", tr: "O Fransızca konuşmaz." },
    { type: "example", en: "We don't eat meat.", tr: "Biz et yemeyiz." },
    { type: "example", en: "She doesn't drink coffee in the evening.", tr: "O akşamları kahve içmez." },
    { type: "rule", text: "Soru yapısı: DO / DOES + Özne + Fiil (yalın hal)? HE / SHE / IT için DOES kullanılır." },
    { type: "pattern", text: "DO + I / YOU / WE / THEY + V1 ?        DOES + HE / SHE / IT + V1 ?" },
    { type: "example", en: "Do you understand me?", tr: "Beni anlıyor musun?" },
    { type: "example", en: "Does he visit his family every month?", tr: "O ailesini her ay ziyaret ediyor mu?" },
    { type: "example", en: "Do they live near here?", tr: "Onlar buraya yakın mı yaşıyorlar?" },
    { type: "rule", text: "Kısa cevaplar: YES, I DO. / NO, I DON'T. / YES, HE DOES. / NO, HE DOESN'T. Soruya tam cümleyle değil, kısa cevapla yanıt vermek İngilizcede çok yaygındır." },
    { type: "example", en: "Do you like tea? Yes, I do.", tr: "Çay sever misin? Evet, severim." },
    { type: "example", en: "Does she work here? No, she doesn't.", tr: "O burada mı çalışıyor? Hayır, çalışmıyor." },
    { type: "rule", text: "Geniş zamanla sıkça kullanılan sıklık zarfları: ALWAYS (her zaman), USUALLY (genellikle), OFTEN (sık sık), SOMETIMES (bazen), RARELY (nadiren), NEVER (asla), EVERY DAY (her gün)." },
    { type: "rule", text: "Sıklık zarfları genellikle özne ile fiil arasına yerleştirilir; fakat özne AM/IS/ARE fiiliyse zarf bu fiilden sonra gelir." },
    { type: "example", en: "I always believe him.", tr: "Ben ona her zaman inanırım." },
    { type: "example", en: "They sometimes invite us to their parties.", tr: "Onlar bazen bizi partilerine davet ederler." },
    { type: "example", en: "She is never late.", tr: "O asla geç kalmaz." },
    { type: "example", en: "We usually eat breakfast at 8.", tr: "Biz genellikle saat 8'de kahvaltı ederiz." },
    { type: "example", en: "He rarely watches TV.", tr: "O nadiren televizyon izler." },
    { type: "example", en: "You are often right.", tr: "Sen sık sık haklısın." },
    { type: "rule", text: "Geniş zaman ayrıca CAN ve SHOULD gibi yardımcı fiillerle (modal) birlikte de kullanılabilir; bu durumda ana fiil her özne için yalın halde kalır." },
    { type: "example", en: "He can speak three languages.", tr: "O üç dil konuşabilir." },
    { type: "example", en: "You should sleep early.", tr: "Erken uyumalısın." },
    { type: "example", en: "She can play the piano.", tr: "O piyano çalabilir." },
    { type: "rule", text: "Sık yapılan hata: HE/SHE/IT ile fiile -s/-es eklemeyi unutmak. \"He go\" yanlıştır, doğrusu \"He goes\" olmalıdır. Bir diğer hata: DOESN'T ile birlikte fiile yine de -s eklemek. \"He doesn't goes\" yanlıştır, doğrusu \"He doesn't go\" olmalıdır." },
    { type: "rule", text: "\"WORK\" (çalışmak) fiili üzerinden bütün öznelerle tam çekim tablosunu inceleyelim." },
    { type: "pattern", text: "TAM ÇEKİM: WORK (ÇALIŞMAK)" },
    { type: "example", en: "I work in a bank.", tr: "Ben bir bankada çalışırım." },
    { type: "example", en: "You work in a bank.", tr: "Sen bir bankada çalışırsın." },
    { type: "example", en: "He works in a bank.", tr: "O (erkek) bir bankada çalışır." },
    { type: "example", en: "She works in a bank.", tr: "O (kadın) bir bankada çalışır." },
    { type: "example", en: "It works well.", tr: "O (nesne) iyi çalışır." },
    { type: "example", en: "We work in a bank.", tr: "Biz bir bankada çalışırız." },
    { type: "example", en: "They work in a bank.", tr: "Onlar bir bankada çalışırlar." },
    { type: "rule", text: "Aynı fiilin olumsuz çekimi." },
    { type: "example", en: "I don't work on Sundays.", tr: "Ben pazar günleri çalışmam." },
    { type: "example", en: "You don't work on Sundays.", tr: "Sen pazar günleri çalışmazsın." },
    { type: "example", en: "He doesn't work on Sundays.", tr: "O pazar günleri çalışmaz." },
    { type: "example", en: "We don't work on Sundays.", tr: "Biz pazar günleri çalışmayız." },
    { type: "example", en: "They don't work on Sundays.", tr: "Onlar pazar günleri çalışmazlar." },
    { type: "rule", text: "Aynı fiilin soru çekimi." },
    { type: "example", en: "Do I work too much?", tr: "Ben çok mu çalışıyorum?" },
    { type: "example", en: "Do you work here?", tr: "Sen burada mı çalışıyorsun?" },
    { type: "example", en: "Does he work here?", tr: "O burada mı çalışıyor?" },
    { type: "example", en: "Do we work together?", tr: "Biz birlikte mi çalışıyoruz?" },
    { type: "example", en: "Do they work together?", tr: "Onlar birlikte mi çalışıyorlar?" },
    { type: "rule", text: "Sıklık zarflarının EVERY WEEK (her hafta), EVERY MONTH (her ay), EVERY YEAR (her yıl) gibi zaman ifadeleriyle kullanımını da inceleyelim." },
    { type: "example", en: "We visit our grandparents every week.", tr: "Büyükanne ve büyükbabamızı her hafta ziyaret ederiz." },
    { type: "example", en: "He travels abroad every year.", tr: "O her yıl yurt dışına seyahat eder." },
    { type: "example", en: "They clean the house every month.", tr: "Onlar evi her ay temizler." },
    { type: "rule", text: "Geniş zamanda genel doğrular ve bilimsel gerçekler de anlatılır." },
    { type: "example", en: "Birds fly.", tr: "Kuşlar uçar." },
    { type: "example", en: "Fish live in water.", tr: "Balıklar suda yaşar." },
    { type: "example", en: "The earth goes around the sun.", tr: "Dünya güneşin etrafında döner." },
    { type: "rule", text: "Karışık alıştırma cümleleriyle bu dersi pekiştirelim." },
    { type: "example", en: "My father drives to work every day.", tr: "Babam her gün arabayla işe gider." },
    { type: "example", en: "My mother doesn't like spicy food.", tr: "Annem baharatlı yemeği sevmez." },
    { type: "example", en: "Does your brother play any instruments?", tr: "Kardeşin herhangi bir enstrüman çalıyor mu?" },
    { type: "example", en: "Our teacher explains everything clearly.", tr: "Öğretmenimiz her şeyi açıkça anlatır." },
    { type: "example", en: "The shop opens at nine and closes at seven.", tr: "Dükkan dokuzda açılır ve yedide kapanır." },
    { type: "example", en: "I don't understand this question.", tr: "Bu soruyu anlamıyorum." },
    { type: "example", en: "Do you usually walk or drive to school?", tr: "Genellikle okula yürüyerek mi yoksa araba ile mi gidersin?" },
    { type: "rule", text: "Geniş zamanda sıkça kullanılan bazı fiillerin HE/SHE/IT çekimlerini ayrıca inceleyelim." },
    { type: "pattern", text: "DO = yapmak (DOES)" },
    { type: "example", en: "He does his homework every evening.", tr: "O her akşam ödevini yapar." },
    { type: "pattern", text: "HAVE = sahip olmak (HAS)" },
    { type: "example", en: "She has a beautiful garden.", tr: "Onun güzel bir bahçesi var." },
    { type: "pattern", text: "LIKE = sevmek, hoşlanmak" },
    { type: "example", en: "He likes classical music.", tr: "O klasik müzik sever." },
    { type: "pattern", text: "WANT = istemek" },
    { type: "example", en: "She wants a new phone.", tr: "O yeni bir telefon istiyor." },
    { type: "pattern", text: "LOVE = çok sevmek / HATE = nefret etmek" },
    { type: "example", en: "He loves his job, but he hates waking up early.", tr: "O işini seviyor ama erken kalkmaktan nefret ediyor." },
    { type: "pattern", text: "WATCH = izlemek" },
    { type: "example", en: "She watches the news every night.", tr: "O her gece haberleri izler." },
    { type: "pattern", text: "LISTEN + TO = dinlemek" },
    { type: "example", en: "He listens to music while driving.", tr: "O araba kullanırken müzik dinler." },
    { type: "pattern", text: "TRAVEL = seyahat etmek" },
    { type: "example", en: "She travels a lot for work.", tr: "O iş için çok seyahat eder." },
    { type: "rule", text: "Geniş zamanda özne olarak kullanılan sözcüklere göre bazı örnek soru-cevap alıştırmaları yapalım." },
    { type: "example", en: "What time does the shop open? It opens at 9.", tr: "Dükkan saat kaçta açılıyor? Saat 9'da açılıyor." },
    { type: "example", en: "Where does she live? She lives in Ankara.", tr: "O nerede yaşıyor? O Ankara'da yaşıyor." },
    { type: "example", en: "Why don't you eat breakfast? I don't have time.", tr: "Neden kahvaltı yapmıyorsun? Vaktim yok." },
    { type: "example", en: "How often do you exercise? I exercise three times a week.", tr: "Ne sıklıkta spor yaparsın? Haftada üç kez spor yaparım." },
    { type: "rule", text: "Bu dersteki bütün örnekler geniş zamanın günlük hayatta ne kadar sık kullanıldığını göstermektedir; bir sonraki derste bu yapıyı yeni fiillerle pekiştirmeye devam edeceğiz." },
    { type: "rule", text: "Genel olarak bu derste geçen fiil ve kalıpları (go, come, work, visit, speak, understand, see, know, believe, invite, sleep, eat, promise, use, need, read, write, buy, sell) bir sonraki derste örnek cümlelerle pekiştireceğiz." },
  ],
};

writeLessonDocx(
  "C:\\Users\\Kemal_Tahir\\Desktop\\ARDEMY PROJEM\\scratchpad\\english-lessons",
  lesson
).then((p) => console.log("Yazıldı:", p));
